### ISSUE TITLE
Implement support for horizontally-shifted data updates

### ISSUE THREAD

**Issue by t-mullen** [carbon-design-system/carbon-charts#100]
#### I am submitting a...

- [x] Feature request

### Issue description
When we update data, the point elements are animated vertically from their old data value to their new one. When the updated data is a horizontal translation of the previous (such as a sliding window of realtime data), this causes large and confusing changes in the graph during the animation.

We should add the option to specify the data is a translation and match point elements to their translated values.

For example, we have the data:
```
{
   labels: [0, 1, 2, 3, 4, 5],
   data: [200, 100, 800, 900, 100, 5]
}
```

We can update the data, specifying that it is a translation of the previous data.

```javascript
chart.setData([100, 800, 900, 100, 99], { translation: -1 })
```

This will probably be difficult to implement given the current codebase, but it's necessary if we want to support real-time data.

**Comment by theiliad** [comment]
This is relevant to our continuous x-scale requirement. Would be great if we can add this functionality once those scale are added.
