### ISSUE TITLE
Line chart value issue

### ISSUE THREAD

**Issue by bkarolyi** [carbon-design-system/carbon-charts#1001]
#### I am submitting a...

- [x] Other - bug

#### charts version:

0.41.2 and above

### Issue description

Line charts with a customized domain doesn't grow on vertical axis. The chart is displayes as a constant row.
In this reported issue the chart was empty. 
#885 
It was fixed, but still does not represent the correct line.
See the sandboxed example:

#### Steps to produce the issue

Open this sandboxed example app:

With 0.38.0 version in the package.json the the value displayed in the line graph.
✅ - https://codesandbox.io/s/charts-v0380-6emt5?file=/package.json

If you change the version to 0.41.0 the line disappears
❌ - https://codesandbox.io/s/charts-v0411-u554l?file=/package.json

Since 0.41.2 the line is a constant row
Current version: 
❌ - https://codesandbox.io/s/charts-v04157-3xyk7?file=/package.json

In an attached screenshot the bug can be seen with more points.
![Screenshot 2021-04-21 at 12 17 58](https://user-images.githubusercontent.com/797503/115538612-5d5e6f80-a29c-11eb-99b6-4ac6447891cf.jpg)

#### Current behavior

The y dimension of the chart is constant.

#### Expected behavior

The chart grows in y dimension.

**Comment by theiliad** [comment]
Hi, please always use JS-dates rather than date strings. Unfortunately storybook shows all of our JS-date values as strings, I'm working on fixing that https://codesandbox.io/s/charts-v04157-forked-3swo4?file=/src/index.js

**Comment by bkarolyi** [comment]
Thanks!
