### ISSUE TITLE
Proper way to theme svelte charts

### ISSUE THREAD

**Issue by amit777** [carbon-design-system/carbon-charts#1002]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x] Other

#### charts version:
"svelte": "^3.23.2"
 "carbon-components-svelte": "^0.32.1",
  "@carbon/charts": "^0.41.57",
 "@carbon/charts-svelte": "^0.41.57",

### Issue description
In your screen shot, it looks like the charts have a dark theme to them.  What is the correct way to make our chart components automatically pick up our current active carbon theme?  For example if I have Gray-90, the background of the chart remains white.  Here is my chart component definition:
```svelte
                  <BarChartSimple
  data={[
  {
    "group": "Qty",
    "value": 65000
  },
  {
    "group": "More",
    "value": 29123
  },
  {
    "group": "Sold",
    "value": 35213
  },
  {
    "group": "Restocking",
    "value": 51213
  },
  {
    "group": "Misc",
    "value": 16932
  }
]}
  options={{
  "title": "Simple bar (discrete)",
  "axes": {
    "left": {
      "mapsTo": "value"
    },
    "bottom": {
      "mapsTo": "group",
      "scaleType": "labels"
    }
  },
  "height": "400px"
}}
  />
```

### Screenshot or recording
![Screen Shot 2021-04-22 at 7 06 58 AM](https://user-images.githubusercontent.com/2703309/115728438-5e91aa00-a339-11eb-8e7b-6942b112e535.png)

**Comment by theiliad** [comment]
Hi, please read this doc https://carbon-design-system.github.io/carbon-charts/?path=/story/docs-tutorials--themes
