### ISSUE TITLE
Incorrect chart resize

### ISSUE THREAD

**Issue by Jeerihon** [carbon-design-system/carbon-charts#1008]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
```
    "@carbon/charts": "^0.41.48",
    "carbon-components": "^10.32.0",
```

### Issue description

After page resizes, legend items that moved to the next line fall out from the container.

#### Steps to produce the issue

Resize window

#### Current behavior

Items fall out from the container.

#### Expected behavior

Container change Its height, items still inside him

### Screenshot or recording

![Screenshot 2021-04-29 at 17 36 56](https://user-images.githubusercontent.com/34735229/116568980-a2744880-a911-11eb-8dd0-521e838c12c9.png)
![Screenshot 2021-04-29 at 17 30 37](https://user-images.githubusercontent.com/34735229/116568972-a1431b80-a911-11eb-8ff5-b8f9124f30d7.png)

**Comment by theiliad** [comment]
Hi, pls update to the latest version, this was fixed a few versions ago
