### ISSUE TITLE
Threshold tooltip doesn't match with the Design toolkit sketch version and not well contrasted

### ISSUE THREAD

**Issue by bkarolyi** [carbon-design-system/carbon-charts#1012]
#### I am submitting a...

- [x] Design defect

#### charts version:

0.41.62.

### Issue description
Threshold tooltip doesn't match with the Design toolkit sketch version and not well contrasted.

#### Current behavior
In the threshold component the entire tooltip's background is filled with the colour we set in prop, as can be seen here:
https://carbon-design-system.github.io/carbon-charts/?path=/story/utility-thresholds--thresholds-line 
![Screenshot 2021-05-04 at 9 38 58](https://user-images.githubusercontent.com/797503/116973331-a6f78300-acbc-11eb-9a59-1fdd7d85c5c6.jpg)

#### Expected behavior
In the Design toolkit the tooltip has a coloured strip on the left side only:
![Screenshot 2021-05-04 at 9 29 15](https://user-images.githubusercontent.com/797503/116973176-6ef04000-acbc-11eb-910a-2e74a1474b45.jpg)

**Comment by theiliad** [comment]
Hi,
The design that's present in the library reflects the final threshold specs. In the specs, the threshold tooltip is different than datapoint tooltips
