### ISSUE TITLE
long x coordinate labels cover x-axis label on data change

### ISSUE THREAD

**Issue by t-mullen** [carbon-design-system/carbon-charts#102]
#### I am submitting a...

- [x] Source code defect

#### charts version:
core@0.7.4

### Issue description
When changing data from data with short x-labels to to data with long x-labels, the x-axis label does not move downwards to accompany them.

#### Current behavior
1. Create an axis chart.
2. Provide a data set with labels ['0', '1', '2']
3. Change data to one with labels ['20000000000000','20000000000000','10000000000000',]

#### Expected behavior
x-axis label moves downwards, out of the way of the x-labels.

### Screenshot or recording
<img width="455" alt="screen shot 2018-11-19 at 5 27 56 pm" src="https://user-images.githubusercontent.com/14932492/48739029-b8e62800-ec20-11e8-8e19-dc2f696825e1.png">

**Comment by licarijd** [comment]
Looks like this has been fixed
![Screen Shot 2019-04-19 at 11 33 41 PM](https://user-images.githubusercontent.com/12204023/56451821-9ead9480-62fb-11e9-9eed-4fa754d7db92.png)
