### ISSUE TITLE
Error loading complex circle pack for vanilla mode

### ISSUE THREAD

**Issue by fredotieno** [carbon-design-system/carbon-charts#1025]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
https://carbon-design-system.github.io/carbon-charts/?path=/story/complex-charts-circle-pack--one-level-hierachy

### Issue description
When I try to view the complex circle pack type of chart, I get a stacktrace on the viewer. Got error when loading in Carbon Charts - Vanilla mode
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/5555876/118861281-9eb65f00-b8dc-11eb-9097-9a09b101e4be.png">

#### Steps to produce the issue
Load this page for carbon charts vanilla

#### Current behavior
Getting error when I load the page attached screenshot

#### Expected behavior
Should show complex circle pack.

**Comment by natashadecoste** [comment]
@fredotieno 
I dont see this on mine/the live storybook/codesandbox seems to load okay too
Can you give me more informationand ill take a look ? browser/provide a sandbox
