### ISSUE TITLE
IBM Accessibility issues while rendering graphs

### ISSUE THREAD

**Issue by mak009** [carbon-design-system/carbon-charts#1027]
After implementing Carbon charts, I checked with IBM Accessibility chrome extension tool and found below accessibility errors.!

#### charts version: 

   "@carbon/charts": "^0.41.64",
    "@carbon/charts-angular": "^0.41.64",
    "@carbon/icons": "^10.32.0",
    "carbon-components": "^10.35.0",
    "carbon-components-angular": "^4.49.0",
    "d3": "^5.16.0",

### Issue description

- Content is not within a landmark element 
- ViolationContent is not within a landmark element 
- ViolationContent is not within a landmark element 

#### Steps to produce the issue

-  Install carbon graphs and rendered in DOM,
- Install IBM accessibility extension
- Inspect and go to element, Run Accessibility checker

#### Current behaviour
- violations

#### Expected behaviour
- No violations

### Screenshot 

![image](https://user-images.githubusercontent.com/6003347/119090730-9ae42300-ba29-11eb-8367-0e0f6f828ebc.png)

**Comment by theiliad** [comment]
Hi, please reopen with proper directions in terms of what chart type you used and which elements these violations relate to. If you could create a sandbox that'd be great, thank you.
