### ISSUE TITLE
Color scale and getFillColor don't work with circle pack chart

### ISSUE THREAD

**Issue by dilignt** [carbon-design-system/carbon-charts#1030]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.65
### Issue description
Adding a color scale definition or a getFillColor function to a circle pack chart options definition don't change the colors of the circles
#### Steps to produce the issue
Go to https://codesandbox.io/s/604le?file=/App.svelte and add a getFillColor function or a color scale definition to the circle pack chart
#### Current behavior
Legend colors change to scale but circle colors don't
#### Expected behavior
getFillColor and color scale definitions should change circle colors
### Screenshot or recording
![image](https://user-images.githubusercontent.com/5586296/119630309-bb83f280-be06-11eb-8366-db0006f8c364.png)
![image](https://user-images.githubusercontent.com/5586296/119630868-42d16600-be07-11eb-9fc0-2464a84d75ec.png)

**Comment by theiliad** [comment]
@Akshat55 circle pack is missing this line https://github.com/carbon-design-system/carbon-charts/blob/f0c60025629f74199f3e5fc1efa2049efcf76ac2/packages/core/src/components/graphs/bar-simple.ts#L72
