### ISSUE TITLE
Problems dynamically changing data in circle pack chart

### ISSUE THREAD

**Issue by dilignt** [carbon-design-system/carbon-charts#1031]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.65
### Issue description
I love carbon charts because you can dynamically update the data within a svelte app and the app will animate and update to reflect the new data.  But with the new circle pack chart there is an issue that when you change the data to just have a single circle, subsequent data changes don't update correctly and the chart is broken from then on.
#### Steps to produce the issue
Best to illustrate the issue with a sandbox - see the issue here https://codesandbox.io/s/friendly-cherry-4kfmp?file=/App.svelte  

This app sets the initial data to the same as the example circle pack sandbox, moved to a separate file.  2 seconds later it changes the data to a subset of the initial data - the chart animates correctly.  2 seconds later it sets the data to the initial data set - the chart animates correctly.  2 seconds later it changes the data to a single parent with a single child - only one circle is shown - there should be a double circle reflecting a parent containing a single child.  2 seconds later it sets the data to the initial data set - you can see that the initial data set doesn't show correctly.  Every subsequent data change will also show incorrectly - somehow the single data point breaks the chart for subsequent updates.

i have a data vis presentation in a few weeks and I would love to be able to include this circle pack chart, but I can't at the moment because this issue occurs with my data - hopefully this isn't too difficult to fix.

many thanks
Mike

**Comment by theiliad** [comment]
👍🏻
