### ISSUE TITLE
getFillColor colors are being ignored when thresholds are in use

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#1032]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.60

### Issue description
Another weird one with thresholds.  We have a custom fill color (of red) we’re using for our line points and it works well on the first render, however, for datapoints over the threshold, when we mouse over the chart the first time, our custom fill colors disappear and are replaced by the default fill color for any point above or below the thresholds.  I think when the graph repaints when there are thresholds it’s not using the customFillColor callback function

first render
![image](https://user-images.githubusercontent.com/6663002/119677558-0e0be180-bdfc-11eb-9ce6-5e29fa30db14.png)
(notice the points are fully red)

second render after we mouse over the graph
![image](https://user-images.githubusercontent.com/6663002/119677617-1c59fd80-bdfc-11eb-94db-388d6e2d284a.png)

notice the points now have a filled section that’s the default purple on the line

**Comment by theiliad** [comment]
@Akshat55 here's the `getFillColor` method in model https://github.com/carbon-design-system/carbon-charts/blob/f0c60025629f74199f3e5fc1efa2049efcf76ac2/packages/core/src/model.ts#L456-L465
