### ISSUE TITLE
Unpin `@carbon/charts`'s version of `@carbon/colors`

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-charts#1045]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

`@carbon/charts@0.41.68`

### Issue description

It looks as if `@carbon/charts` has a fixed production dependency on `@carbon/colors@10.15.0`. Meanwhile, `@carbon/themes` and `@carbon/elements` depend on `@carbon/colors@^10.26.0`. This means that any Carbon application using `@carbon/charts` ends up pulling in multiple copies of those colours.

#### Steps to produce the issue

```sh
npm install @carbon/charts
npm list @carbon/colors
```

#### Current behavior

```
`-- @carbon/charts@0.41.68
  `-- @carbon/colors@10.15.0
```

#### Expected behavior

```
`-- @carbon/charts@0.41.68
  `-- @carbon/colors@10.26.0
```

**Comment by theiliad** [comment]
Since colors work a bit differently in the 2 libraries, I think we'll have to keep the pin for now.

According to NPM, the unpacked size of `@carbon/colors` is `75.8 kB`, should be fine pulling multiple versions for now.

Sorry! 🙂
