### ISSUE TITLE
Random showing and page alignment problem with Tooltip on Stack chart when high density of data points is passed as props

### ISSUE THREAD

**Issue by KushChibber** [carbon-design-system/carbon-charts#1051]
#### I am submitting a design defect for the stack chart. 

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
The nature of the issue is that when more than 250 data points are supplied to the stack chart, the grid initially shows tooltip as designed, but when the mouse is dragged out from the view pane, a random tooltip appears at the edge of the chart. this makes anything besides the chart unreadable. Also, if the tooltip is displayed at the edge of the screen the tooltip overflows from the page. 
The following screenshot will show the exact illustration of the problem:

#### Expected behaviour
1. When the mouse drags out of the view pane, no random tooltip is displayed.
2. Tooltip does not overflow on page.

### Screenshot or recording
1. Random Tooltip popup.
<img width="974" alt="Screenshot 2021-06-25 at 9 01 26 a m" src="https://user-images.githubusercontent.com/84724362/123391432-f018d480-d593-11eb-9844-aa478a2bd554.png">

2. Tooltip overflow.
<img width="1010" alt="Screenshot 2021-06-25 at 8 57 35 a m" src="https://user-images.githubusercontent.com/84724362/123390984-6c5ee800-d593-11eb-8a45-87c355abc4c5.png">

**Comment by theiliad** [comment]
Hi, please try again by using the latest version (v0.41.79) & lmk to re-open if the issue persists

**Comment by KushChibber** [comment]
@theiliad this issue hasn't been resolved in v0.41.79

**Comment by kush-singh-chb** [comment]
@theiliad this hasn't been resolved. Kindly re-open
