### ISSUE TITLE
'ibm-stacked-bar-chart' is not a known element:

### ISSUE THREAD

**Issue by lakinkintu** [carbon-design-system/carbon-charts#1058]
#### I am submitting a...
- [ ] Design defect
- [ ] Source code defect

#### charts version:
    "@carbon/charts": "0.41.77",
    "@carbon/charts-angular": "0.41.77",
     "d3": "5.16.0",
    "carbon-components": "10.21.0",
    "carbon-icons": "7.0.7",
#### Current behavior
- error NG8001: 'ibm-stacked-bar-chart' is not a known element:
1. If 'ibm-stacked-bar-chart' is an Angular component, then verify that it is part of this module.
2. If 'ibm-stacked-bar-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

####app-module.ts
import{ChartsModule} from'@carbon/charts-angular'
  imports: [
    ChartsModule,

#### Expected behavior
How to resolve this error.

**Comment by theiliad** [comment]
Hi, we have code samples available for angular apps here https://carbon-design-system.github.io/carbon-charts/angular/?path=/story/simple-charts-bar-stacked--vertical-stacked-bar-discrete

Pls let us know if you run into further issues
