### ISSUE TITLE
 Line Chart is not starting from 0

### ISSUE THREAD

**Issue by manik39654** [carbon-design-system/carbon-charts#1059]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### Steps to produce the issue
![image](https://user-images.githubusercontent.com/86999228/124546857-deafb200-de48-11eb-8145-129dc4605a29.png)

#### Current behavior
![image](https://user-images.githubusercontent.com/86999228/124546873-e4a59300-de48-11eb-947e-66605288c058.png)

#### Expected behavior
It should start from 0 after using includeZero : true

### Screenshot or recording
![image](https://user-images.githubusercontent.com/86999228/124546948-030b8e80-de49-11eb-92cf-41ffdb55a278.png)

**Comment by theiliad** [comment]
Hi, `axes.left.includeZero` would include a zero in the left axis, not in the line graph itself.

To include a zero in the line graph, you'd just add a datapoint with a value of 0
