### ISSUE TITLE
Boxplot graph is not working properly

### ISSUE THREAD

**Issue by manik39654** [carbon-design-system/carbon-charts#1063]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

We were trying to plot the values using carbon boxplot graph but after integration it is not showing its default behaviour by showing the calculated middle values from the array object. Tooltip is also not working when we plot the values.
Below is the sample array - 
**[11788.105347347737,8909.459170784427,11282.836153626178,8532.235156293129,11251.040805606683,7042.189192661856]**

Default behaviour of boxplot is to calculate the middle values from the array after sorting i.e. 
middle value will be 10,080 approx.

How ? - **(8909.459170784427 + 11251.040805606683)/2 = 10,080**

<img width="555" alt="Carbon_Feature" src="https://user-images.githubusercontent.com/86999228/125056174-951fcb00-e0c5-11eb-89d5-243579ca2e70.PNG">

If we are plotting these values in chart.js library, it works fine. Below is the screenshot for the same - 

![ChartJS_Feature](https://user-images.githubusercontent.com/86999228/125058093-8cc88f80-e0c7-11eb-9c9b-9e8a1bdad24e.PNG)

#### Current behavior

<img width="555" alt="Carbon_Feature" src="https://user-images.githubusercontent.com/86999228/125058270-be415b00-e0c7-11eb-8815-ffba7bfffafb.PNG">

#### Expected behavior

![ChartJS_Feature](https://user-images.githubusercontent.com/86999228/125058295-c26d7880-e0c7-11eb-81e7-ac289d017d7c.PNG)

**Comment by theiliad** [comment]
![image](https://user-images.githubusercontent.com/14989804/125099134-b40e6500-e0a5-11eb-9f3e-a5494165bc8e.png)

Hi,
I just opened our codesandbox demo for the boxplot and entered some of your data into it, and it looks fine.

Did you use that demo as a starting place?

Could you pls share a sandbox of when the chart breaks?
