### ISSUE TITLE
Known vulnerability in d3-colour: Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by gmc77** [carbon-design-system/carbon-charts#1069]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.68

### Issue description
As flagged by Snyk when we use Carbon in our product.

```
Issues to fix by upgrading:
  Upgrade d3@5.16.0 to d3@7.0.0 to fix
  ✗ Regular Expression Denial of Service (ReDoS) (new) [Medium Severity][https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592] in d3-color@1.4.1
    introduced by d3@5.16.0 > d3-color@1.4.1 
```

See https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592 for details. It can be fixed by upgrading to later versions of d3

#### Steps to produce the issue
Run Snyk against a Carbon charts application

**Comment by abbeyhrt** [comment]
Hi! Are there any updates on this? This vulnerability has also been reported over in Cloud PAL and it would be great to either know if it's not relevant and is a false positive or if there is a path to getitng it resolved, thank you!

**Comment by theiliad** [comment]
> Hi! Are there any updates on this? This vulnerability has also been reported over in Cloud PAL and it would be great to either know if it's not relevant and is a false positive or if there is a path to getitng it resolved, thank you!

Got the #1093 PR, which should be merged soon.

In the meantime, give this a read pls https://overreacted.io/npm-audit-broken-by-design/

**Comment by theiliad** [comment]
Not looked into this specific vulnerability, but a really good point here

![image](https://user-images.githubusercontent.com/14989804/128045754-0c3e8ec5-8648-4d53-baaf-68bf3a05a4c0.png)

**Comment by abbeyhrt** [comment]
Yeah! I've already read it, It's a great read! I've been using it to calm down to some of our users about the vulnerabilities they are seeing. That's why I made sure to add the "if it's not relevant and is a false positive" part!

**Comment by gcatalog** [comment]
@theiliad if this is going to be considered a False positive, it should be more formally declared so, as many service teams are on the hook to resolve all vulnerabilities, and this vulnerability is at this point overdue, and could cause a failure in Audits...

**Comment by theiliad** [comment]
> @theiliad if this is going to be considered a False positive, it should be more formally declared so, as many service teams are on the hook to resolve all vulnerabilities, and this vulnerability is at this point overdue, and could cause a failure in Audits...

Hi, I believe this was addressed ~26 days ago...

We migrated to d3v7 which uses updated versions of d3's sub-packages...

Again, **d3 is only a peer & dev-dependency** in Carbon Charts... users have to manually install it in their apps, and they can choose the version of d3 that they install, and it seems like d3v7 depends on d3-color v3...

**Comment by theiliad** [comment]
https://unpkg.com/browse/d3@7.0.0/package.json
