### ISSUE TITLE
Issue importing @carbon/charts-svelte when using SvelteKit (possibly due to SSR)

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1070]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Getting error this error when trying to import any type of chart into a SvelteKit page (.svelte file representing a route):
> Importing binding name 'default' cannot be resolved by star export entries.
> moduleDeclarationInstantiation@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> link@[native code]
> linkAndEvaluateModule@[native code]
> [native code]
> promiseReactionJobWithoutPromise@[native code]
> promiseReactionJob@[native code]

The error occurs whether I use **DonutChart** in the template or not...
```
<svelte:head>
  <link rel="stylesheet" href="https://unpkg.com/@carbon/charts/styles.min.css" />
</svelte:head>

<script lang="ts">
  import { DonutChart } from '@carbon/charts-svelte'
</script>

<template>
  <DonutChart
        data={[
        {
          "group": "2V2N 9KYPM version 1",
          "value": 20000
        },
        {
          "group": "L22I P66EP L22I P66EP L22I P66EP",
          "value": 65000
        },
        {
          "group": "JQAI 2M4L1",
          "value": 75000
        },
        {
          "group": "J9DZ F37AP",
          "value": 1200
        },
        {
          "group": "YEL48 Q6XK YEL48",
          "value": 10000
        },
        {
          "group": "Misc",
          "value": 25000
        }
      ]}
        options={{
        "title": "Donut",
        "resizable": true,
        "donut": {
          "center": {
            "label": "Browsers"
          }
        },
        "height": "400px"
      }}
  />
</template>
```

#### Steps to produce the issue

1. npm init svelte@next my-app (pick SvelteKit demo app, TypeScript)
2. cd my-app
3. npm install --saveDev @carbon/charts@0.41.84 @carbon/charts-svelte@0.41.84 d3@5.14.2
4. Add `import { DonutChart } from '@carbon/charts-svelte';` to the script tag in /src/routes/todos/index.svelte (note: not the script tag with context="module"). Note: you don't even have to have DonutChart in the template.
5. npm run dev -- --open
6. Click TODOS at the top of the page

#### Current behavior
Error appears

#### Expected behavior
No error

### Screenshot or recording
Following the steps will reproduce this issue

I suspect @carbon.charts may not be compatible with server-side rendering in its present state.

**Comment by theiliad** [comment]
@metonym just caught an important bug which I think is causing this, I'll push a fix

**Comment by metonym** [comment]
I also receive an error in a SvelteKit set-up, although the error is different: `ReferenceError: document is not defined`.

## Workarounds

There are two workaround methods.

First, ensure that you instruct vite to optimize `@carbon/charts` (related #1024):

```js
// svelte.config.js
const config = {
  kit: {
    target: "#svelte",
    vite: {
      optimizeDeps: { include: ["@carbon/charts"] },
    },
  },
};

export default config;

``` 

### 1) Dynamic import

Avoid the SSR error by dynamically importing a chart after a component has mounted.

```svelte
<script>
    import { onMount } from "svelte";
  
    let chart;
  
    onMount(async () => {
      const charts = await import("@carbon/charts-svelte");
      chart = charts.BarChartSimple;
    });
  </script>
  
  <svelte:head>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@carbon/charts/styles.min.css"
    />
  </svelte:head>
  
  <svelte:component
    this={chart}
    data={[
      { group: "Qty", value: 65000 },
      { group: "More", value: 29123 },
      { group: "Sold", value: 35213 },
      { group: "Restocking", value: 51213 },
      { group: "Misc", value: 16932 },
    ]}
    options={{
      title: "Simple bar (discrete)",
      axes: {
        left: { mapsTo: "value" },
        bottom: { mapsTo: "group", scaleType: "labels" },
      },
      height: "400px",
    }}
  />
  
```

### 2) Disable SSR

Set `ssr` to `false` in `svelte.config.js`.

```js
// svelte.config.js
const config = {
  kit: {
    target: "#svelte",
	ssr: false,
    vite: {
      optimizeDeps: { include: ["@carbon/charts"] },
    },
  },
};

export default config;

```

**Comment by mikerussellnz** [comment]
I am experiencing the following, I have an empty svelte project and follow the instructions on this github to show BarChartSimple but always get this browser error and page not loading:

Uncaught ReferenceError: process is not defined
(anonymous) @ browser.js:21
(anonymous) @ main.js:8

I am not sure if it is related to this issue or not or whether there is a workaround for this, I had charts working in another project a while ago, but no matter what I can't seem to get it working now.

**Comment by mikerussellnz** [comment]
In my case, downgrading the package version to 0.41.80 and the page loads fine. :-/

**Comment by metonym** [comment]
@mikerussellnz What set-up are you using? Rollup?

**Comment by metonym** [comment]
Upgrading to `@carbon/charts` version 0.41.86 fixes the SSR issue for me.

**Comment by nstuyvesant** [comment]
Confirmed on my end as well. Thanks for the amazingly fast response!

**Comment by mikerussellnz** [comment]
> @mikerussellnz What set-up are you using? Rollup?
Yes, tried again this morning, still happens on 0.41.87

here are instructions that reproduce the issue I am seeing:

```
npx degit sveltejs/template svelte-app
cd svelte-app
npm install
npm install -S @carbon/charts @carbon/charts-svelte d3@5.x
modify app.svelte with demo chart
npm run dev
localhost:5000 - error Uncaught ReferenceError: process is not defined - browser.js
```

**Comment by metonym** [comment]
@mikerussellnz The `ReferenceError: process is not defined` is unrelated to the SSR bug.

Since you are using Rollup, try the following:

Install `@rollup/plugin-replace`:

```bash
npm i -D @rollup/plugin-replace
```

Import it in rollup.config.js:

```diff
// rollup.config.js
+ import replace from "@rollup/plugin-replace";
```

Invoke it in your list of plugins to re-write "process.env.NODE_ENV" before the code is evaluated:

```
plugins: [
  replace({
      preventAssignment: true,
      "process.env.NODE_ENV": JSON.stringify("production"),
    }),
]
```

**Comment by theiliad** [comment]
v0.41.88 fixes the `ReferenceError: process is not defined` issue in UMD bundles

**Comment by ErraticFox** [comment]
I am getting this with 0.50.7 `<DonutChart> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

**Comment by theiliad** [comment]
You may need to use `optimizeDeps`

https://github.com/carbon-design-system/carbon-charts/tree/master/packages/svelte#sveltekit

**Comment by metonym** [comment]
@ErraticFox I was unable to reproduce it using Yarn and a [SvelteKit set-up](https://github.com/metonym/carbon-charts-svelte-examples/tree/master/sveltekit). Please create a repro.
