### ISSUE TITLE
Give the ability to set precision on pie label percentages

### ISSUE THREAD

**Issue by mRamzii** [carbon-design-system/carbon-charts#1094]
Hello,

I would like to thank the team first of all, for all the amazing work they have done on this library.

#### I am submitting a...
- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.90
### Issue description
When using a Pie Chart, if we have a value with a precision of 0.01, The percentage will show as 0% (0.05% becomes 0%)

#### Steps to produce the issue
Just create a pieChart with values with a precision of 0.01 (example : [0.00020831164147239178, 0.00020831164147239178, 0.806061863899231, 0.19352151453495026]
#### Current behavior
The percentage values are automatically rounded, with no parameters to control this.

I have done some digging around, it seems like the function **convertValueToPercentage(item, fullData)** returns the percentage in the form of a number (1 significant digit if necessary).

I have tried a manual fix by manually setting the Integer passed over to  "toFixed" function, everything works as expected. 

#### Expected behavior
Maybe have a parameter in the piechart options to specify the number of decimals wanted for the percentages in **convertValueToPercentage**. 

### Screenshot or recording
![image](https://user-images.githubusercontent.com/54007844/127638162-35f2fdbb-6204-4aa2-b914-111be966ceb1.png)

**Becomes**

![image](https://user-images.githubusercontent.com/54007844/127638270-297abac6-9ecb-433a-8095-daad44ff2516.png)

Thank you!

**Comment by theiliad** [comment]
Hi,

`pie.labels.formatter` should be able to address this issue https://carbon-design-system.github.io/carbon-charts/documentation/interfaces/_interfaces_charts_.piechartoptions.html#pie
