### ISSUE TITLE
Pulls in redundant, clashing `carbon-components` CSS

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-charts#1115]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

`@carbon/charts@0.41.103` or thereabouts (precise version not known, sorry)

### Issue description

It looks as if `@carbon/charts` has a [pinned dependency](https://github.com/carbon-design-system/carbon-charts/blob/d524616d3db8d0fe7e3cce71c6f08ab04d7e7050/packages/core/package.json#L54) on an old version of Carbon, `carbon-components@10.40.0`. This clashes with the most recent version of Carbon, which is `10.41.x` or thereabouts.

Under normal circumstances, having two versions of the same dependency library in play at once wouldn't cause too much trouble. However, in this case `carbon-components` is a UI library with its own associated CSS. These two sets of CSS both apply to the same CSS classes and so they (1) create a great deal of redundancy in our output CSS bundle and (2) clash with one another because they disagree slightly about the structure of the UI components they're trying to style.

#### Steps to produce the issue

I have a basic webpack build with an `index.js` which simply loads an `index.css`, which reads as follows:

```scss
@import '~carbon-components/scss/globals/scss/styles';
@import '~@carbon/charts/styles/styles';
```

When I run the build and inspect the output CSS bundle...

#### Current behavior

...I see two distinct blocks of CSS which, for example, alter the rendering of `.bx--modal-container`, which is part of Carbon's `<Modal>` component. One of these blocks comes from our application's version of `carbon-components`, and one comes from `@carbon/charts`'s version of `carbon-components`.

#### Expected behavior

* I would expect `@carbon/charts` to allow a more flexible range of versions of `carbon-components`, `^10.40.0` for example.
* I would also not expect `@carbon/charts`'s CSS to contain redundant copies of some of `carbon-components`'s CSS. I would expect to be required to load that CSS once, myself. Imagine if multiple different Carbon-related UI libraries did the same thing... we would end up with two or three or four full copies of Carbon's CSS. In fact, that is exactly the issue we are having right now! `@carbon/charts` is just one of several UI libraries where I am trying to get this issue fixed!

### Screenshot or recording

Because of this clashing CSS, we see puzzling rendering errors like this:

![image](https://user-images.githubusercontent.com/9932290/129048743-8aadca09-59d9-4474-9369-23e1a268f8de.png)

See how the margins on the modal are too narrow.

**Comment by s100** [comment]
On closer inspection, it looks like `@carbon/charts` has [a complete redundant copy of `carbon-components@10.40.0` checked in to source control](https://github.com/carbon-design-system/carbon-charts/tree/09f9c0eff52ce3e4272646249b01818b917cd890/packages/core/src/styles/vendor/carbon-components)? Why is this?

**Comment by theiliad** [comment]
> On closer inspection, it looks like `@carbon/charts` has [a complete redundant copy of `carbon-components@10.40.0` checked in to source control](https://github.com/carbon-design-system/carbon-charts/tree/09f9c0eff52ce3e4272646249b01818b917cd890/packages/core/src/styles/vendor/carbon-components)? Why is this?

Hi, we pull in `vendor` packages for easier bundling and development. other carbon repos do the same. Clashing issues should be resolved in the latest versions. If you're using d3@5.x pls install `0.41.98`, if d3@7.x `0.41.103`

**Comment by s100** [comment]
In fact I think what was probably happening was that `@carbon/charts` was [pinned to the very old `carbon-components@10.5.0`](https://github.com/carbon-design-system/carbon-charts/blob/b1903bab53554c3afd4f1536d28e1734a098ca1f/packages/core/package.json#L54) up until #1087 was merged and you brought things back up to date. Pinning to old versions of other Carbon libraries has previously caused issues under #1045. I think this is something you should look into fixing in general - it's causing problems for those of us who consume `@carbon/charts` downstream.

**Comment by s100** [comment]
@theiliad You haven't addressed this issue fully. What happens six months from now when `carbon-components` drifts ahead of your `10.40.0` pin and all the styles start clashing again? And what are you going to do about this issue of redundant CSS bloating our bundles?

**Comment by theiliad** [comment]
> @theiliad You haven't addressed this issue fully. What happens six months from now when `carbon-components` drifts ahead of your `10.40.0` pin and all the styles start clashing again? And what are you going to do about this issue of redundant CSS bloating our bundles?

it's a bit of a gray area, we can definitely discuss options here if you'd like.

If the styles aren't included, then there's a true dependency on `carbon-components` for styles, so the same reverse thing can happen where you're only using charts and you're getting all of `carbon-components` styles added in.

Also if the styles aren't included and there are changes in the tooltip DOM structure in the newer versions, you'd also run into issues, so I thought it'd be safer it charts include those styles by default.

We can look at adding some flags in the charting styles that'd exclude the carbon-components styles?

**Comment by s100** [comment]
My preferred model for consuming `@carbon/charts` would be something like this:

* First, change the `carbon-components` dependency to `^10.40.0` or something like that. The way you have it currently, we end up needing to pin to `10.40.0` just like you have, which is problematic when other UI component libraries we depend on have moved forward and require more recent Carbon versions. In general Carbon's DOM structure and CSS can be relied upon not to change too much, so this should not cause problems. And, it shouldn't be necessary to rely on that exact structure anyway. If there are other concerns here which I'm not aware of, I'd be interested to hear them.

* Second, figure out this duplication issue.
  * Make it so that `@carbon/charts`'s CSS stops incorporating `carbon-components`'s CSS. `@carbon/charts` can still *rely* on `carbon-components`'s CSS to have been loaded, but will no longer actually include any of it as part of its distribution.
  * In the `@carbon/charts` README, document exactly how to load Carbon's CSS first, and which specific parts are required (if not the entirety of Carbon's CSS). This documentation would probably recommend doing the following:

```scss
@import '~carbon-components/scss/globals/scss/styles';
@import '~@carbon/charts/styles/styles';
```

As this would be a breaking change, bumping the minor version of `@carbon/charts` would also be required.

**Comment by DakotaWray2** [comment]
Do you have a recommendation for components that use charts and carbon components? I believe this is a common use case.

**Comment by theiliad** [comment]
There's no "win" here. I originally added these styles because the vanilla carbon-components aren't really maintained.

If down the road the DOM architecture of modal or overflow-menu changes, then the styles that you manually will import will still break, since we'd have to update the modal & overflow-menu HTML that we use

**Comment by s100** [comment]
As far as I've ever seen, the main [Carbon repo](https://github.com/carbon-design-system/carbon), which includes `carbon-components` and `carbon-components-react`, is very well-maintained. They have a large team of people working full-time on the Carbon system, and whenever I've opened issues against that repo they've responded pretty swiftly and been quite helpful. Carbon is used everywhere in IBM. They shouldn't be making breaking changes without a major version bump. If they accidentally make a change which breaks someone downstream, like `@carbon/charts` or `@carbon/charts-react`, you can raise that with them and get it fixed.

On the topic of DOM architecture... note that the specific DOM and CSS structure of the Carbon components is not part of Carbon's contract with downstream consumers like you and me. What matters is the rendering, which is fixed. Carbon is free to alter their DOM and CSS at will and this shouldn't affect us, provided rendering doesn't break. We've never had a problem with this.

Are you applying significant CSS overrides to the Carbon modal or overflow-menu, and you're worried about your overrides breaking? Does `@carbon/charts` contain a copy of one or more of Carbon's components, which you modify for your own ends? Are you trying to use Carbon's (internal) CSS classes for your own purposes? I would like to know what the issue is with doing what I've suggested, unpinning Carbon and unbundling its CSS. Have you tried it before and seen problems?

**Comment by theiliad** [comment]
Not exactly, what I'm specifically talking about is that at Carbon we more-so focus on the React implementation as the active source of truth.

Carbon Charts can't use the react modal or overflow menus obviously since we support a variety of frameworks, so rather the modal & overflow menu components are used as HTML code + CSS from carbon-components + JS logic from charts.

Now if in the future Carbon's modals ship a different DOM structure for these components, we'd have to update our HTML code as well

**Comment by s100** [comment]
Are you saying that you've copied Carbon's HTML source for their modal and overflow menu components into `@carbon/charts`'s source? And because you've copied some of the HTML from that specific version of Carbon, you also need to bundle the CSS from that specific version of Carbon? I have been looking in the code to try to see for myself and [this](https://github.com/carbon-design-system/carbon-charts/blob/78363325dd37b6ceb4eae953d72e74cd3834509b/packages/core/src/components/essentials/modal.ts#L133) certainly looks like what I'm describing... If so, then all I can say is that I'm fairly sure `carbon-components` isn't intended to be consumed in this way, for all of the reasons that I've been describing. At this point, the modal is essentially your own original component which just happens to closely resemble Carbon's. Unfortunately, as developers, you have the worst of both worlds - all the hassle of maintaining your own UI component instead of relying on a third party to do it for you, but none of the freedom in markup/rendering/styling which would come with that choice.

I don't know what it's like maintaining a package which supports many different UI frameworks at once, we use React only... But surely there has to be a way to do this where you don't end up pinned to a specific patch of Carbon, and bundling that specific patch's CSS along with the package.

(Incidentally, isn't [this](https://github.com/carbon-design-system/carbon-charts/blob/78363325dd37b6ceb4eae953d72e74cd3834509b/packages/core/src/components/essentials/modal.ts#L150) kind of thing vulnerable to XSS attacks?)

**Comment by lkraav** [comment]
Thanks, I discovered this when upgrading 10.10 -> towards 10.40+, and fortunately indeed @carbon/charts@^0.58 seems to have solved this specific issue🙏
