### ISSUE TITLE
D3 dependency errors installing Carbon Charts for React

### ISSUE THREAD

**Issue by John30013** [carbon-design-system/carbon-charts#1123]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version: 
0.44.0

### Issue description
I am following the instructions on the [React Getting Started page](https://github.com/carbon-design-system/carbon-charts/tree/master/packages/react), but I get the following error when installing the packages using the specified command:
```
% npm install -S @carbon/charts @carbon/charts-react d3@5.x
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: call-home-connect-cloud@1.3.0
npm ERR! Found: d3@5.16.0
npm ERR! node_modules/d3
npm ERR!   d3@"5.x" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer d3@"7.x" from @carbon/charts@0.44.0
npm ERR! node_modules/@carbon/charts
npm ERR!   @carbon/charts@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/jpisellous.ibm.com/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
```

Since the error lists a peer dependency from `@carbon/charts@0.44.0` of `d3@"7.x"`, I tried the following two other commands:
`npm install -S @carbon/charts @carbon/charts-react d3@7.x` and `npm install -S @carbon/charts @carbon/charts-react d3`, both of which complete the installation. However, when I then try to build my application, I get the following error:
```
Failed to compile.

./node_modules/@carbon/charts/tools.js
Attempted import error: 'pointer' is not exported from 'd3-selection'.
```

If, instead of the latest version of d3, I specify d3@5.x as the current Getting Started instructions indicate, and install it with the `--force` option, the installation succeeds but I get the same error when building my application:
```
Failed to compile.

./node_modules/@carbon/charts/tools.js
Attempted import error: 'pointer' is not exported from 'd3-selection'.
```

In each of these cases I have deleted my `node_modules` directory and my `package-lock.json` and done a fresh `npm install`. What is strange is that my application was working earlier this morning and the charts were displaying. But I made some updates to my application (not to the charts themselves, but to other components on the page), and at the next build (via the React dev proxy) I got this error.

**Comment by theiliad** [comment]
Hi, sorry about all of that, it seems like I'd updated our getting started guides on the storybook site but missed updating the READMEs in the repo...

Pls install the latest version of d3, and READMEs should also be updated now.

**Comment by John30013** [comment]
@theiliad Thanks! That fixed it for me.
