### ISSUE TITLE
Time/Date scales for X-axis

### ISSUE THREAD

**Issue by surbhibhattar** [carbon-design-system/carbon-charts#113]
#### I am submitting a...

- [x] Feature request
To allow time and date scales on X axis

#### charts version:
0.7.4

### Screenshot or recording
<img width="709" alt="screen shot 2018-11-26 at 2 20 02 pm" src="https://user-images.githubusercontent.com/6988577/49060647-74681700-f234-11e8-9776-8c73f0355b50.png">
<img width="706" alt="screen shot 2018-11-26 at 2 20 16 pm" src="https://user-images.githubusercontent.com/6988577/49060651-78943480-f234-11e8-8335-ef02d62fe9fd.png">

**Comment by PatrickDuncan** [comment]
My team is also seeking the same functionality #277
