### ISSUE TITLE
[Bug]: Failed to resolve entry for package "@carbon/charts-svelte > @carbon/telemetry"

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1130]
### Contact Details

nstuyvesant@gmail.com

### What happened?

@carbon/telemetry has the following package.json
```json
{
  "name": "@carbon/telemetry",
  "description": "Collect telemetry data for projects at IBM using Carbon",
  "version": "0.0.0-alpha.6",
  "license": "Apache-2.0",
  "bin": {
    "carbon-telemetry": "./bin/carbon-telemetry.js"
  },
  "repository": "https://github.com/carbon-design-system/carbon",
  "bugs": "https://github.ibm.com/carbon-design-system/carbon/issues",
  "keywords": [
    "carbon",
    "carbon design system"
  ],
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@babel/parser": "^7.12.5",
    "@babel/traverse": "^7.12.5",
    "ci-info": "^2.0.0",
    "configstore": "^5.0.1",
    "fast-glob": "^3.2.4",
    "fs-extra": "^9.0.1",
    "got": "^11.8.0",
    "semver": "^7.3.2",
    "winston": "^3.3.3",
    "yargs": "^16.1.1"
  }
}
```

When a SvelteKit 1.0.0-next.162 project uses @carbon/charts-svelte that includes @carbon/telemetry in its dependencies, you will get an error like this whenever you start the SvelteKit dev server `npm run dev -- --host --open`...

> > Failed to resolve entry for package "@carbon/charts-svelte > @carbon/telemetry". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@carbon/charts-svelte > @carbon/telemetry". The package may have incorrect main/module/exports specified in its package.json.
> Error: Failed to resolve entry for package "@carbon/charts-svelte > @carbon/telemetry". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@carbon/charts-svelte > @carbon/telemetry". The package may have incorrect main/module/exports specified in its package.json.
>     at packageEntryFailure (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43739:11)
>     at resolvePackageEntry (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43735:9)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43511:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async /Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:76764:27
>     at async optimizeDeps (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:71535:31)
>     at async runOptimize (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75389:48)
>     at async Object.createServer (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75418:9)
> file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/dist/chunks/index.js:3371
> 			throw new Error('Cannot close server before it is initialized');
> 			      ^
> 
> Error: Cannot close server before it is initialized
>     at Watcher.close (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/dist/chunks/index.js:3371:10)
>     at process.<anonymous> (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/dist/chunks/index.js:3198:9)
>     at process.emit (node:events:394:28)
>     at process.emit (node:domain:475:12)
>     at process.exit (node:internal/process/per_thread:184:15)
>     at handle_error (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/dist/cli.js:958:10)
>     at file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/dist/cli.js:1010:4
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**To fix it**, add this line to node_modules/@carbon/telemetry/package.json:
```
  "main": "./bin/carbon-telemetry.js",
```

### Version

@carbon/charts@0.46.4
@carbon/charts-svelte@0.46.4

@sveltejs/kit@1.0.0-next.162

### Data & options used

```
<script>
  import { DonutChart } from '@carbon/charts-svelte'
  import '@carbon/charts/styles.min.css'
</script>
```

**Comment by kevin192291** [comment]
I am getting this in a clean project.

**Comment by nstuyvesant** [comment]
Yeah - it's very easy to see the problem if you examine @carbon/telemetry's package.json. If your project uses a @carbon package that includes telemetry (most) and you use SvelteKit, you'll get the error when you fire up the dev server.

I'd do a pull request for telemetry but I'm not finding its repo (perhaps not public).

**Comment by kevin192291** [comment]
Quick google found this: https://www.npmjs.com/package/@carbon/telemetry
However, installing it doesn't seem to help.

**Comment by nstuyvesant** [comment]
Try manually adding the line `"main": "./bin/carbon-telemetry.js",` to your installed @carbon/telemetry package in node_modules.

**Comment by kevin192291** [comment]
> "main": "./bin/carbon-telemetry.js",

Yep, That did the trick, however that is too much of a workaround for me! I may have to go check into different libs for my charts :(

**Comment by nstuyvesant** [comment]
For the maintainers of **@carbon/telemetry**....
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main - "If main is not set it defaults to index.js in the packages root folder."

That package has no index.js nor a main entry in package.json. This should be an easy fix. I would not give up on @carbon/charts just because of one missing line in one of their dependencies. Hopefully, will be corrected.

**Comment by dominikg** [comment]
relevant issue on vite repo (sveltekit uses vite under the hood) https://github.com/vitejs/vite/issues/4837

Root cause is a recent change in vite-plugin-svelte that doesn't work for "hybrid" svelte packages that declare node dependencies that are not compatible with vite's optimizer.

To fix this you can either add `@carbon/telemetry` to `optimizeDeps.exclude`, or add `@carbon/charts-svelte` to vite-plugin-svelte's [disableDependencyReinclusion](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#disabledependencyreinclusion) option.


In this case i think charts-svelte should drop the dependency on @carbon/telemetry though until that package is a lot less bloaty and opt-in. 
Reasons:
* It is not clear how to opt-out, that magic `CARBON_TELEMETRY_DISABLED` isn't documented/logged anywhere when installing. 
* Disabling telemetry via env won't prevent downloading large dependencies that are not needed
* The telemetry repo itself is private, code is only available through npm, LICENSE isn't included in the package: https://registry.npmjs.org/@carbon/telemetry/-/telemetry-0.0.0-alpha.6.tgz
* post-install scripts are a liability


cc @joshblack 

ps.: @nstuyvesant  please mention issues in other repositories when cross-posting.

**Comment by nstuyvesant** [comment]
@dominikg - thanks. optimizeDeps.exclude approach solved my issue.

I agree the forced inclusion of a private package with no licensing specifically designed for tracking like **@carbon/telemetry** with the other @carbon packages makes them less appealing to use.

I hope **@carbon/telemetry** can become more transparent in the near future.

**Comment by joshblack** [comment]
Hi all! 👋  Chiming in on the `@carbon/telemetry` side. This package provides a CLI which is why there is no `main`, `module`, `exports`, etc field in the `package.json` for a bundler to hook into. It should not be included in any output of a build.

Definitely agreed on the license and visibility issue, the code is available on NPM but we'll bring it over into the monorepo for it to be public.

**Comment by nstuyvesant** [comment]
For those using SvelteKit, here's my svelte.config.js for working with @carbon/charts...
```javascript
import adapter from '@sveltejs/adapter-node'
import preprocess from 'svelte-preprocess'

const production = process.env.NODE_ENV === 'production'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),
	kit: {
		adapter: adapter({
			out: 'build'
		}),
		target: '#svelte',
		vite: {
			ssr: {
        noExternal: [production && "@carbon/charts"].filter(Boolean),
      },
			optimizeDeps: {
				include: ['@carbon/charts'],
				exclude: ['@carbon/telemetry']
			},
			server: {
				fs: {
					// Allow serving files from one level up to the project root
					allow: [
						'..',
						'/api/file/'
					]
				}
			}
		}
	}
}

export default config
```

Hope this helps others.

**Comment by theiliad** [comment]
> For those using SvelteKit, here's my svelte.config.js for working with @carbon/charts...

Yes I think the `optimizeDeps.exclude` is the best way to solve this for now. I'll look into updating our docs for SvelteKit

**Comment by dominikg** [comment]
@theiliad: 
vite-plugin-svelte has added automatic detection for binary only packages like telemetry, it should no longer be needed to explicitly exclude it.

I'd also like to repeat my sentiment against using telemetry the way you are doing right now. This is smelly at best and downright invasive at worst (it includes babel so you may even be scanning the users codebase?! wtf)

**Comment by joshblack** [comment]
@dominikg for telemetry, the process only runs in CI and will print out a notice that points folks to: https://www.carbondesignsystem.com/help/faq/#telemetry

We only collect information from code that is hosted on IBM's GitHub Enterprise host. The only exceptions are the IBM and carbon-design-system orgs on public GitHub. All other code/projects are excluded from this.

Let me know if you have any questions or suggestions for what we can do to make this more apparent or make you feel more comfortable with this work. It is not our intent to collect information about individuals or teams outside of IBM.

**Comment by dominikg** [comment]
If that is not your intent, then you should not add @carbon/telemetry to the dependencies of your public open source libraries. Instead add it directly to the internal projects at ibm you want to analyze as a devDependency. You can even keep it closed source then and noone will blink an eye.

Right now you are forcing down megabytes of useless-at-best dangerous-at-worst dependencies onto every user.
