### ISSUE TITLE
[Enhancement]: Handle events on group changing in the DonutChart.

### ISSUE THREAD

**Issue by RadekKpc** [carbon-design-system/carbon-charts#1144]
### Summary

There is no option to handle events from legend in a donut chart, I would like to call callback function each time I change a group. 
![obraz](https://user-images.githubusercontent.com/48159370/132845700-5426016a-fc15-4999-9ee7-9ee0224bdb3b.png)

### Justification

It allows us to control outside components basing on the legend.

### Desired UX and success metrics

There are no UX matters, we only need additional parameter in the component.

### "Must have" functionality

- Additional parameter in a donut chart that allows us to handle legend event (when changing a group).

### Specific timeline issues / requests

I would appreciate to make it as soon as possible.

### Available extra resources

I have no extra resources.

**Comment by theiliad** [comment]
Hi, pls check out https://carbon-design-system.github.io/carbon-charts/?path=/story/docs-tutorials--event-listeners

&

https://carbon-design-system.github.io/carbon-charts/documentation/enums/_interfaces_events_.legend.html#items_update

the `legend-items-update` event is dispatched with `detail.dataGroups`
