### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GaspardC** [carbon-design-system/carbon-charts#1185]
### What happened?

I updated to React 18 API to use concurrent mode but it breaks the style of carbon charts.

### Version

    "@carbon/charts": "0.50.6",
    "@carbon/charts-react": "0.50.6",

**Comment by nstuyvesant** [comment]
Hi @GaspardC - can you please update to `@carbon/charts-react@latest` and close this if your issue was resolved?

**Comment by GaspardC** [comment]
Hello, I'm not working anymore on this project so you I can close so the issues if you confirm it's working now 🙌
