### ISSUE TITLE
Chart and legend colors not mapped

### ISSUE THREAD

**Issue by arnajdas92** [carbon-design-system/carbon-charts#119]
#### I am submitting a...

- [x] Design defect

#### charts version:
0.7.11

### Issue description
The chart color and the legend color are not mapped properly. In the screenshot given below, the magenta color or the 83% sector is the conformed part, whereas the legend says it is the green section and also there are 4 sectors in the chart, the legend shows only 2
### Screenshot or recording
<img width="353" alt="screenshot 2018-12-31 at 2 52 06 pm" src="https://user-images.githubusercontent.com/7128486/50557487-9e1cce00-0d0b-11e9-90bf-1eb07ed06471.png">

**Comment by theiliad** [comment]
Hi @arnajdas92, is this a bug in the React package?

**Comment by theiliad** [comment]
**Update:** The color mapping issue is fixed in the new version pushed today
