### ISSUE TITLE
[Bug]: Threshold-Lines in line charts are rendered outside the chart and raise javascript error

### ISSUE THREAD

**Issue by usefool** [carbon-design-system/carbon-charts#1214]
### What happened?

I'm accessing carbon chart via the svelte wrapper:
When using threshold lines in line-chart, they are rendered outside the chart. The corresponding tooltip is shown in the right place.
<img width="856" alt="Screen Shot 2021-11-09 at 16 32 42" src="https://user-images.githubusercontent.com/11616064/140964788-f7cb9311-612b-424d-ac05-645240a7fdf4.png">

Additionally, I get this javascript error message:

<img width="530" alt="Screen Shot 2021-11-09 at 16 43 05" src="https://user-images.githubusercontent.com/11616064/140964885-5996d642-f6b6-4691-bdc9-a9f868a41227.png">

### Version

0.51.3 

### Data & options used

```js
Here is the corresponding axis configuration:
axes: {
left: { mapsTo: "value",
thresholds: [
{
value: 20,
label: "My theshold"
},
],
},
bottom: {
mapsTo: "date",
scaleType: "time",

  },
},
```

**Comment by theiliad** [comment]
Hi @usefool 
Have you tried this example? https://charts.carbondesignsystem.com/svelte/?path=/story/utility-thresholds--thresholds-line

works fine on storybook and codesandbox. If you're still having issues, could you pls create a sandbox for us to debug?

**Comment by usefool** [comment]
My mistake. It's working now.

**Comment by Kate-te** [comment]
Having the same problem, @usefool would you share how you fixed it?

**Comment by Kate-te** [comment]
Had the same issue, seems to be caused by the chart data points being rendered after the threshold itself
Solved by adding the threshold when  chart data is already loaded
