### ISSUE TITLE
[Bug]: Combo with Floating bar does not work

### ISSUE THREAD

**Issue by xplodeart** [carbon-design-system/carbon-charts#1215]
### What happened?

On Svelte, when using combo with simple bar, if we change values to an array in order to show a floating bar, nothing gets shown on the axis.

Options and data copied from the storybook demo: https://charts.carbondesignsystem.com/react/?path=/story/simple-charts-combo--combo-line-simple-bar-custom-configs

Options:
`{
  "title": "Combo (Line + Simple bar) - custom configs",
  "axes": {
    "left": {
      "mapsTo": "value",
      "scaleType": "linear",
      "title": "USA Summer School Attendance"
    },
    "right": {
      "mapsTo": "temp",
      "scaleType": "linear",
      "title": "Temperature (°F)",
      "correspondingDatasets": [
        "Temperature"
      ]
    },
    "bottom": {
      "title": "Day of the Week",
      "mapsTo": "date",
      "scaleType": "labels"
    }
  },
  "comboChartTypes": [
    {
      "type": "simple-bar",
      "correspondingDatasets": [
        "School A"
      ]
    },
    {
      "type": "line",
      "options": {
        "points": {
          "radius": 5
        }
      },
      "correspondingDatasets": [
        "Temperature"
      ]
    }
  ],
  "height": "400px"
}`

Data:
`[
  {
    "group": "School A",
    "date": "Monday",
    "value": [10000, 11000]
  },
  {
    "group": "School A",
    "date": "Tuesday",
    "value": [65000, 67000]
  },
  {
    "group": "School A",
    "date": "Wednesday",
    "value": [30000, 33000]
  },
  {
    "group": "School A",
    "date": "Thursday",
    "value": [49213, 51000]
  },
  {
    "group": "School A",
    "date": "Friday",
    "value": [49213, 50500]
  },
  {
    "group": "Temperature",
    "date": "Monday",
    "temp": 70
  },
  {
    "group": "Temperature",
    "date": "Tuesday",
    "temp": 75
  },
  {
    "group": "Temperature",
    "date": "Wednesday",
    "temp": 31
  },
  {
    "group": "Temperature",
    "date": "Thursday",
    "temp": 31
  },
  {
    "group": "Temperature",
    "date": "Friday",
    "temp": 43
  }
]`

### Version

0.51.3

### Data & options used

```js
Options copied from the storybook demo
```

### Relevant log output

```js
Error: <path> attribute d: Expected number, "M221.9828125,undefinedL221.98…".
```

**Comment by Akshat55** [comment]
Hi @xplodeart,

Please have a look at this code sandbox example for creating a combo chart with bar simple (floating) chart. 
https://codesandbox.io/s/lucid-butterfly-rjdek?file=/src/index.js

In short, you do not add ``"scaleType": "linear"`` for floating bar graphs.

**Comment by xplodeart** [comment]
@Akshat55 Thank you.
