### ISSUE TITLE
[Enhancements]: Add support for multiple datasets in bounded area chart

### ISSUE THREAD

**Issue by anbnyc** [carbon-design-system/carbon-charts#1216]
### What happened?

When I create a bounded area chart with one group, I have lines for `min`, `value`, and `max` and I can apply the option `includeZero: false` (works as expected). When I add a second group, two things break: now the lines only show value, not `min` and `max`, and `includeZero` no longer works, which means that the areas appear below the X axis:

![image](https://user-images.githubusercontent.com/2243944/141654255-bfb12cdb-a5a3-4293-b747-a2c6cd3753d1.png)

My most preferred fix would be to show `min`, `value`, and `max` lines and bounded areas for both groups. An OK alternative would be to show the `value` lines for both groups, keep the Y axis the same, and hide the area under the curve. My least preferred fix would be to show the `value` lines and areas and change the axis to include 0.

Thank you.

### Version

@carbon/charts@0.51.3

### Codesandbox example

https://codesandbox.io/s/pedantic-ptolemy-zs0h9?file=/src/components/chart.vue

**Comment by Akshat55** [comment]
Hi @anbnyc,

Currently we only support 1 data group for bounded area chart hence the console warning, 
`Bounds can only be shown when having 1 single datagroup...`

**Comment by Akshat55** [comment]
Issue #1248 fixes the include zero bug, we are still waiting for design approvals for enabling multiple datasets in bounded area chart.

**Comment by theiliad** [comment]
I'll close for now. Feel free to respond with additional info or feedback 🙂
