### ISSUE TITLE
[Enhancement]: Add support for specifying a custom class name on CardNode

### ISSUE THREAD

**Issue by AlanGreene** [carbon-design-system/carbon-charts#1221]
### Summary

Add support for specifying a custom class name on the CardNode react component which can then be used to control the colour of the border or other styles as needed.

### Justification

The CardNode react component has a `color` prop which can be used to specify the colour of the border applied on the outer node. However, this requires the consuming code to be aware of the active theme, handle dark mode, etc. to select an appropriate colour in some cases.

For component libraries this can be problematic as now both the components and their consumers need to be aware of theme rather than relying on this being handled entirely in (S)CSS.

### Desired UX and success metrics

Consumers of the CardNode component can add a custom class to the outer node and use this to style the card and its children.

### "Must have" functionality

n/a

### Specific timeline issues / requests

n/a

### Available extra resources

I can implement this if it's an acceptable change.

**Comment by theiliad** [comment]
> I can implement this if it's an acceptable change.

Sure! Feel free to make a PR 🙂

**Comment by AlanGreene** [comment]
Thanks for the quick response. PR here https://github.com/carbon-design-system/carbon-charts/pull/1222

There were a number of formatting  changes in unrelated files (including changelogs for other packages) after running `yarn run commit` that I didn't include. Let me know if I should and I'll update the PR.
