### ISSUE TITLE
[Bug]: Missing group name causes crash

### ISSUE THREAD

**Issue by tlindener** [carbon-design-system/carbon-charts#1231]
### Contact Details

mail@lindener.it

### What happened?

When using an area chart (or any that behave similarly, e.g. scatter or line chart) without providing a "group" data field rendering the chart crashes at https://github.com/carbon-design-system/carbon-charts/blob/b11873b24c3ca19ef07381b1647be70be33b4baf/packages/core/src/components/essentials/legend.ts#L418 because d.name is undefined

### Version

latest

### Data & options used

```js
See codesandbox
```

### Relevant log output

```js
324 | // truncate the legend label if it's too long
  325 | if (truncationType !== TruncationTypes.NONE) {
  326 |     addedLegendItemsText.html(function (d) {
> 327 |         if (d.name.length > truncationThreshold) {
      | ^  328 |             return Tools.truncateLabel(d.name, truncationType, truncationNumCharacter);
  329 |         }
  330 |         else {

Line numbers are wrong though.
```

### Codesandbox example

https://codesandbox.io/s/nnw91?file=/src/index.js

**Comment by Akshat55** [comment]
@tlindener, `group` is required for organizing the data points and other features like legend and tooltips. If you’d like one group of data or want to fill in the missing group values, you can map through your data array and add the group field to each JSON object.

**Comment by theiliad** [comment]
@tlindener feel free to reopen with additional comments, but yes as @Akshat55 mentioned groups are needed for the library to distinguish datagroups and to perform other operations

**Comment by tlindener** [comment]
Sorry for responding so late. I agree that the group field is important for many parts of the chart. Yet, I feel like in the sense of failing gracefully, the library should rather behave as if group is an empty string.
As you can see in this example:
https://codesandbox.io/s/nice-kowalevski-d38ey?file=/src/index.js
It does not work completely (e.g. selecting/deselecting the dataset is not working) but it does not take down the whole application.
