### ISSUE TITLE
[Enhancement]: Go to version 1.0.0?

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-charts#1234]
### Summary

I propose that `@carbon/charts`, `@carbon/charts-react` *etc.* should bump their versions to `1.0.0` in the next release, indicating that they are now production-ready packages with stable, reliable APIs.

### Justification

At present `@carbon/charts` and `@carbon/charts-react` are at version `0.53.0`. [According to semantic versioning, when the major version is 0, this indicates initial development. Anything may change at any time and the public API of the package is not considered stable.](https://semver.org/#spec-item-4) This means that every time a new version is released (most recently upgrading from `0.52.4`), we have to manually examine the [change log](https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/CHANGELOG.md#0530-2021-12-01) to determine what the breaking changes to the API are and how we need to modify our own code to consume it.

* This is quite disruptive to us as there is a new version of Carbon Charts every week or two on average.
* It looks like the API of Carbon Charts seems to be very stable right now and is not changing significantly or at all from release to release - so invariably we find that there were no breaking changes at all.
  * In a large number of cases the reason for new version is simply given as ["Version bump only for package @carbon/charts"](https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/CHANGELOG.md#0495-2021-09-23) - indicating no changes whatsoever to the Carbon Charts code. (I don't know why you even release new versions in this case?)
* Regardless of whether you consider Carbon Charts to be still under "initial development", we are using it in production right now and have been for over a year. I imagine many other projects are doing the same.

With all of this in mind, I propose that you should bump your version numbers to `1.0.0` and proceed from there. This change...

* would acknowledge to consumers that Carbon Charts is now production-ready - currently it implicitly is not
* would represent a commitment on the part of Carbon Charts' developers to not making breaking changes to the package's public API (except with major version bumps, [as per semver](https://semver.org/#spec-item-8))
* would not affect the cadence of new releases, but make consuming them easier
* would not be disruptive to downstream consumers

### Desired UX and success metrics

No changes to the UX would be required.

### "Must have" functionality

No changes to functionality would be required.

### Specific timeline issues / requests

N/A, but as soon as possible would be desirable.

### Available extra resources

I can theoretically open a PR which bumps all of your version numbers to 1.0.0 manually, but I expect your release process is a little more sophisticated than this, so I will refrain for now.

**Comment by s100** [comment]
Bumping this again due to yet another version bump (`0.54`) with no significant changes...

**Comment by s100** [comment]
@theiliad Any thoughts on this? Version 0.56, again, had no breaking changes.

**Comment by s100** [comment]
@theiliad That is not what I'm talking about. If you're introducing breaking changes, it's okay to bump the most significant version number. However, once again, version 0.57 has no breaking changes. Every time you do this it wastes our time because we get prompted to manually upgrade to the latest version.

Let me ask you a question. Are `@carbon/charts` and `@carbon/charts-react` considered ready for production use or not?

**Comment by theiliad** [comment]
Closing as we're now on 1.x
