### ISSUE TITLE
Positioning not proper of the tooltip and legend list

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#125]
#### I am submitting a...

- [ ] Design defect

#### charts version:
0.7.16

### Issue description
The tooltip positioning is not proper. Also the legend list which appears when clicked on the `+` button is also not in the proper position.

### Screenshot or recording
<img width="478" alt="screenshot 2019-01-04 at 10 23 03 am" src="https://user-images.githubusercontent.com/46365045/50674350-75e2e700-100b-11e9-90a5-a372b3f8847d.png">
<img width="389" alt="screenshot 2019-01-04 at 10 23 10 am" src="https://user-images.githubusercontent.com/46365045/50674351-767b7d80-100b-11e9-94f8-3f8d23dbb72d.png">

**Comment by theiliad** [comment]
Hi @arnajdas1992. Could you please provide a demo link or some code where this can be reproduced?

**Comment by arnajdas1992** [comment]
@theiliad  - This is the similar to the code used
 `import React from 'react';
import { defaultColors } from '@carbon/charts';
import { DonutChart } from '@carbon/charts-react';
import styles from './Demostyles.scss';

const demoPieOptions = {
  accessibility: false,
  legendClickable: true,
  containerResizable: true,
  defaultColors,
};

const demoPieData = {
  labels: ['2V2N-9KYPM version 1', 'L22I-P66EP-L22I-P66EP-L22I-P66EP', 'JQAI-2M4L1', 'J9DZ-F37AP',
    'YEL48-Q6XK-YEL48', 'P66EP-L22I-L22I', 'Q6XK-YEL48', 'XKB5-L6EP', 'YEL48-Q6XK', 'L22I-P66EP-L22I'],
  datasets: [
    {
      label: 'Dataset 1',
      backgroundColors: defaultColors,
      data: [100000, 200000, 600000, 100000, 400000, 450000, 300000, 70000, 20000, 120000],
    },
  ],
};

export const DemoDonutChart = () => (
  <div className={styles.graph}>
    <DonutChart
      data={demoPieData}
      options={demoPieOptions}
    />
  </div>
);

export default DemoDonutChart;
`
This is is the style used

`.graph {
    width: 350px;
    height: 250px;
    border: solid 1px;
}
`
<img width="435" alt="screenshot 2019-01-04 at 11 51 10 am" src="https://user-images.githubusercontent.com/46365045/50675893-0e329900-1017-11e9-8848-89b363c4c20b.png">

Unable to see both the list and tooltip in this case

**Comment by theiliad** [comment]
@arnajdas1992 I'm suspecting that some of the charting CSS classes are interfering with your app's CSS code. Which is why I asked for a demo of this issue.

Can you confirm please that this is what's happening?

**Comment by theiliad** [comment]
@asahlin
