### ISSUE TITLE
[Bug]: packaging improvements

### ISSUE THREAD

**Issue by benmccann** [carbon-design-system/carbon-charts#1256]
### What happened?

The `package.json` has:
```
  "main": "./bundle.js",
  "module": "./index.js",
```

The `module` field is only recognized by bundlers, but not by Node.js itself. In order to supply multiple builds to Node.js it's required to have an `exports` map (and I believe it would also need an `.mjs` extension). Alternatively, if you want to use this package only as ESM in Node.js directly you could add `"type": "module"` and update the `main` field to point at the ESM build

### Version

@carbon/charts@0.54.0

**Comment by nstuyvesant** [comment]
Hi @benmccann - This has been overhauled in `@carbon/charts@latest` and `@carbon/charts-svelte@latest`.

Could you please close this one?

**Comment by theiliad** [comment]
I will close for now, pls let us know @benmccann

**Comment by benmccann** [comment]
Yep, looks good now! There's a new awesome publint tool that will check packages and it's showing both as all good. Thank you!

https://publint.dev/@carbon/charts@1.11.13
https://publint.dev/@carbon/charts-svelte@1.11.13
