### ISSUE TITLE
Unit test cases fail which include carbon-charts

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#126]
#### I am submitting a...

- [ ] Design defect

#### charts version:
0.7.16

### Issue description
The unit test cases for the files which include carbon-charts all fail with undefined import error as in the screenshot.

### Screenshot or recording
<img width="992" alt="screenshot 2019-01-09 at 1 41 48 pm" src="https://user-images.githubusercontent.com/46365045/50891148-aa96da00-1421-11e9-9ebf-89e74bf5bc23.png">

**Comment by theiliad** [comment]
@arnajdas1992 This is not a **carbon charts** issue, and rather an issue with your JEST configurations including `node-modules`. You would need to exclude `node-modules` from your testing configurations.
