### ISSUE TITLE
[Histogram]: How can histogram build with datetime data?

### ISSUE THREAD

**Issue by VitoriaTangHeng** [carbon-design-system/carbon-charts#1272]
### Contact Details

tangheng@cn.ibm.com

### Question

I want to build a histogram chart based on following data:
      [ {"group":"lastupdated","lastupdated":"2019-11-23 03:13:20.000"},
        {"group":"lastupdated","lastupdated":"2019-11-23 03:13:20.000"},
        {"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
        {"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
        {"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
        {"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
        {"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
	{"group":"lastupdated","lastupdated":"2019-11-24 01:26:40.000"},
	{"group":"lastupdated","lastupdated":"2019-11-24 01:26:40.000"},
	{"group":"lastupdated","lastupdated":"2019-11-24 04:13:20.000"},
	{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
	{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
	{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
	{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
	{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"}
   ]
It cannot show histogram, is there any setting let that data can be shown as a histogram?
<img width="834" alt="Screen Shot 2022-01-17 at 5 40 38 PM" src="https://user-images.githubusercontent.com/20531142/149745451-1d286b8e-4974-435d-b8b2-0e845f019dcb.png">

Full test codes see following:

import "@carbon/charts/styles.css";
import { HistogramChart } from "@carbon/charts";

const data = [ {"group":"lastupdated","lastupdated":"2019-11-23 03:13:20.000"},
{"group":"lastupdated","lastupdated":"2019-11-23 03:13:20.000"},
{"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
{"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
{"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
{"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
{"group":"lastupdated","lastupdated":"2019-11-23 06:00:00.000"},
{"group":"lastupdated","lastupdated":"2019-11-24 01:26:40.000"},
{"group":"lastupdated","lastupdated":"2019-11-24 01:26:40.000"},
{"group":"lastupdated","lastupdated":"2019-11-24 04:13:20.000"},
{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"},
{"group":"lastupdated","lastupdated":"2019-11-25 02:26:40.000"}
];

const options = {
	"title": "Histogram (date)",
	"axes": {
		"bottom": {
			"title": "Age",
			"mapsTo": "lastupdated",
			"bins": 20,
			"limitDomainToBins": true,
			"scaleType": "time",
		},
		"left": {
			"title": "No. of participants",
			"scaleType": "linear",
			"stacked": true,
			"binned": true
		}
	},
	"height": "400px"
};

// Grab chart holder HTML element and initialize the chart
const chartHolder = document.getElementById("app");
new HistogramChart(chartHolder, {
	data,
	options
});

**Comment by theiliad** [comment]
Hi 👋🏻 
Our histogram chart has been designed to work mostly with numbered values.

Creating bins from a timeseries axis/scale has lots of downsides IMO (both from a technical perspective & from a UX/readability point-of-view)

When doing the research for this component I also didn't see too many timeseries examples. Bins ideally are very clear ranges & boundaries within your data. (e.g. ages 10-20, 20-30 rather than Jan 9th 18:30:00 - Jan 12th 21:00:00 and so on...)

I will close for now, but feel free to respond with additional comments, feedback or reasoning 🙂
