### ISSUE TITLE
[Enhancement]: how can i prevent zero from being included at line chart ?

### ISSUE THREAD

**Issue by mrtsrdm** [carbon-design-system/carbon-charts#1275]
### Contact Details

murat.suerdem@gmail.com

### Question

There are so many gaps at start and end of the line(first image) chart, even if ı set [includeZero: false]. 
I think it should be like in the second image. How can i handle this ?

![image](https://user-images.githubusercontent.com/65854951/149894197-28eff0c4-2e0d-4861-8576-0fd23482c955.png)

![image](https://user-images.githubusercontent.com/65854951/149894219-2dae49ad-3002-4850-81a1-20fbc66adbb6.png)

**Comment by SteffenBaumann** [comment]
Check this comment on a closed issue: https://github.com/carbon-design-system/carbon-charts/issues/1246#issuecomment-997299812

**Comment by mrtsrdm** [comment]
thank you @SteffenBaumann

**Comment by mrtsrdm** [comment]
it is okay
