### ISSUE TITLE
[Enhancement]: Ability to customize the spacing factor in bar charts

### ISSUE THREAD

**Issue by piotr-kotara-ibm** [carbon-design-system/carbon-charts#1280]
### Contact Details

piotr.kotara@ibm.com

### Summary

Currently width of the bar is calculated as follows:
https://github.com/carbon-design-system/carbon-charts/blob/73613a6c2e0fe88a73645c3edb4778abbc391540/packages/core/src/components/graphs/bar.ts#L19-L24

The width of stacked bar chart is calculated analogously
https://github.com/carbon-design-system/carbon-charts/blob/73613a6c2e0fe88a73645c3edb4778abbc391540/packages/core/src/components/graphs/bar-stacked.ts#L308-L313

As we see we the spacing factor is used in the process, but currently it is fixed to `0.25` value.

Suggestion is to enable developer to customize it's value by chart.

### Justification

In certain scenarios charts with less padding between bars can display data more quickly. For example when we have day-by-day data by default we receive such results:
![obraz](https://user-images.githubusercontent.com/92912677/150775788-40ffb06a-1f44-4bc2-b369-e242c27593af.png)

But when I change spacing factor to `0.75` by changing library code we receive:
![obraz](https://user-images.githubusercontent.com/92912677/150775945-2943f3fd-5b8d-40d7-8d73-3e177d4b901e.png)

As we can see the latter one data is more clear to read as data in which one bar reflects one whole day.

### Desired UX and success metrics

User will be able to more easily read data from chart when low padding between bars is beneficial for readability (for example when data is displayed in time domain and its aggregated by some length of time (like by day, hour, week) rather than correlated with certain point in time (like noon of some day). 

Example visible under *Justification* section.

### "Must have" functionality

Ability to customize the spacing factor by properties of `SimpleBarChart` and `StackedBarChart` React components

### Specific timeline issues / requests

It would be great if this feature could be delivered by the end of February. 

### Available extra resources

I think that the feature could be added just by extending `BarOptions` and `StackedBarOptions` by adding next field to control the spacing factor

**Comment by Thuhaa** [comment]
@theiliad how do i use this in ComboCharts that have bars. This option doesn't seem to exists in the ComboChartOptions
