### ISSUE TITLE
Is there an option that allows bar widths to automatically expand or shrink based on the number of bars and the width of the graphic?

### ISSUE THREAD

**Issue by mrtsrdm** [carbon-design-system/carbon-charts#1293]
### Contact Details

murat.suerdem@gmail.com

### Question

Is there an option that allows bar widths to automatically expand or shrink based on the number of bars and the width of the graphic?

![image](https://user-images.githubusercontent.com/65854951/151727994-4843d7cf-a3a8-432a-81b2-633d637a5531.png)
For the first(# 1) chart, the bars have the appropriate widths.

___________________________________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/65854951/151728151-e7a5a08c-f882-46a6-8f79-d1464bfc6416.png)
but when a different data is used, the bar(# 2) widths can be very narrow.

**Comment by SteffenBaumann** [comment]
This is literally the last issue closed: https://github.com/carbon-design-system/carbon-charts/issues/1290
Please consider reviewing closed items as well. There might be valuable information, too.

**Comment by mrtsrdm** [comment]
thank you @SteffenBaumann , is there any thought to include this improvement in the version "0.41.98-d3v5-latest-0.1" ?

**Comment by SteffenBaumann** [comment]
I am non of the DEVs, however I highly doubt that ... bump up your version instead. That's the recommended approach.
