### ISSUE TITLE
[Bug]: GaugeChart with width 100% but constrained by height aligns left within its SVG

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1318]
### What happened?

My GaugeChart (Angular) has a width of 100% but displays aligned left and uncentered because of height constraint.
<img width="239" alt="image" src="https://user-images.githubusercontent.com/5770938/155460909-89eca681-cb48-4bdf-80c4-f37a0fa3f8db.png">

I expected the Gauge to be centered instead of aligned left.

### Version

@carbon/charts-angular@0.54.12

### Data & options used

```js
  data = [
    {
      group: 'value',
      value: 100
    }
  ]

  options = {
    color: {
      scale: {
        value: this.color
      }
    },
    resizable: true,
    height: '3.75rem',
    width: '100%',
    gauge: {
      type: 'semi',
      showPercentageSymbol: false,
    },
    toolbar: {
      enabled: false
    }
  }
```

```html
<div class="row">
  <div class="col-xl-4 col-lg-6 text-center">
    <ibm-gauge-chart [data]="data" [options]="options"></ibm-gauge-chart>
    <span>{{name}}</span>
   </div>
</div>
```

Testing for the Bootstrap md breakpoint.
```


### Relevant log output

_No response_

### Codesandbox example

_No response_

**Comment by Akshat55** [comment]
Based on the provided options you're using, you seem to be missing the alignments attribute. Please try adding the following to options:

```JSON
"gauge": {
    "type": "semi",
    "showPercentageSymbol": false,
    "alignment": "center"
  }
```
Let us know if that solves the issue :)

**Comment by nstuyvesant** [comment]
Ah... missed that. Thanks - that did it.
