### ISSUE TITLE
Add support for horizontal bar chart

### ISSUE THREAD

**Issue by asahlin** [carbon-design-system/carbon-charts#133]
I am submitting a...

- [x ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

charts version:
0.8.1

Issue description
We have a design to show bar charts horizontally. 

![image](https://user-images.githubusercontent.com/13006634/51137367-3cc52680-1804-11e9-8e95-35fb662c610f.png)

**Comment by theiliad** [comment]
This is not in plan currently. What would help putting this in our roadmap would be if you have an immediate need for this in your project(s). Thanks!

**Comment by theiliad** [comment]
Although a great idea, we don't have any plans for this type of chart right now.

What would help putting this in our roadmap would be if you have an immediate need for this in your project(s). Thanks!

**Comment by asahlin** [comment]
We do have a need for this in our current project.  This design is for the 1st quarter deliverable for Gen1 / PUP device details page.

**Comment by theiliad** [comment]
Thanks @asahlin, any deadlines you can provide?

**Comment by asahlin** [comment]
March 31st is when it is suppose to GA.  So needs to before then ;-)

**Comment by theiliad** [comment]
Sounds good, I'll get back to you

**Comment by asahlin** [comment]
@theiliad Any update on this?

**Comment by theiliad** [comment]
Hi @asahlin. I'm currently in the process of planning this. It is likely that we can get this done in time for you to incorporate & debug, I will get back soon with a confirmation. Are there any changes on your end in terms of deadline, requirements etc?

**Comment by asahlin** [comment]
Ok great, no changes in our requirements/deadline.   Would be nice to get https://github.com/carbon-design-system/carbon-charts/issues/136 as well.   Our designers don't like using background colors they want the bar color itself to indicate threshold level.
  
There was discussion of investigating and using a 3rd party graphing package.    Which we don't want to do.

**Comment by theiliad** [comment]
I see, well thank you for going forward with Carbon Charts 🙂.

We will do our best to satisfy our users.

**Comment by theiliad** [comment]
Hi @asahlin, we've started to work on this. You'll see a PR soon

**Comment by asahlin** [comment]
@theiliad That's awesome, thanks for the heads up.

**Comment by asahlin** [comment]
@theiliad Is this still on the radar?   Any update?

**Comment by lisalukenbill** [comment]
Following this as well. I have a need for horizontal bar charts and would like updates as to when the plan is to make these available.  Thank you!

**Comment by theiliad** [comment]
@shixiedesign @cameroncalder Do you anticipate any major differences between a horizontal and a vertical bar chart design wise?

**Comment by shixiedesign** [comment]
No major differences. Just axis swap. Keep in mind the grid lines in the back should turn vertical in horizontal bar chart to help with reading the length instead of height of bars. 

![image](https://user-images.githubusercontent.com/15144993/61890016-34912680-aecc-11e9-9482-e1a780a052d5.png)

**Comment by theiliad** [comment]
🙌

**Comment by asahlin** [comment]
@theiliad  Is this work planned?

**Comment by theiliad** [comment]
Yes. We're looking at end of sept. max

**Comment by JoannaJanusz** [comment]
@theiliad Hi Eliad. How is it going - is the horizontal chart around? We have a design needing this chart in Watson Knowledge Catalog.

**Comment by theiliad** [comment]
Completed in #415

**Comment by theiliad** [comment]
Sorry for the delay here. Horizontal bar charts are complex when you think of all the design decisions that come with both the implementation and the visual design of the components.

Thankfully both of those concerns have been addressed now.
