### ISSUE TITLE
[Enhancement]: Could @carbon/charts-angular add Angular 13 as a peer dependency?

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1336]
### Summary

Most of my development is using Angular 13.3. Whenever I use Carbon Charts with a project, I have to do an `npm install --force` because the peer dependencies for @carbon/charts-angular only goes up to Angular 12.

Carbon Charts seems to work well with Angular 13.3.0.

### Justification

Angular 13 was released in November 2021. While there are a lot of Angular releases, major releases are about 6 months apart.

### Desired UX and success metrics

Being able to do `npm install` for my Angular projects that include @carbon/charts-angular without having to specify `--force`.

### "Must have" functionality

Modification to the package.json.

### Specific timeline issues / requests

As soon as possible.

### Available extra resources

I can create a pull request for this.

**Comment by nstuyvesant** [comment]
Added https://github.com/carbon-design-system/carbon-charts/pull/1337

**Comment by nstuyvesant** [comment]
Any update on support for Angular 13.3.x?

**Comment by theiliad** [comment]
This was done a while ago, we probably closed a duplicate issue and missed closing this one
