### ISSUE TITLE
[Bug]: Form control with "checkbox" role has no associated label 

### ISSUE THREAD

**Issue by darunya-b-c** [carbon-design-system/carbon-charts#1339]
### What happened?

<img width="1278" alt="图片" src="https://media.github.ibm.com/user/42629/files/76faa080-e0ae-11eb-9252-b7e22ff90649">

<img width="1365" alt="image" src="https://media.github.ibm.com/user/42629/files/9674d400-f55b-11eb-81a7-2889e4e4bd22">

### Version

 "@carbon/charts": "0.41.99",
 "@carbon/charts-react": "0.41.99",

### Data & options used

```js
color: {
    gradient: { enabled: true },
    scale: { value: '#0F62FE' },
  },
  gauge: {
    status: 'danger',
    type: 'semi',
  },
  height: '150px',
  resizable: true,
  title: '',
  width: '80%',
});
```

**Comment by wlinacdl** [comment]
Hi, can I know when this issue could resolved? Thanks.

**Comment by theiliad** [comment]
Hi @wlinacdl,
Just like #1340 

I think you might be on a much older version. Could you pls update to latest and let us if that fixes things?
