### ISSUE TITLE
When hovering over threshold on chart, console error is thrown.

### ISSUE THREAD

**Issue by asahlin** [carbon-design-system/carbon-charts#134]
I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

charts version:
0.8.1

Issue description
When adding thresholds to bar chart, when you hover over threshold area you get console error.
index.js:1 Uncaught TypeError: t.colorScale[n.datasetLabel] is not a function
    at SVGRectElement.eval (index.js:1)
    at SVGRectElement.eval (index.js:1)
If I change the code to pass in a function for dataset label, this error goes away but the then the chart legend label for the dataset is undefined.

Steps to produce the issue:
Pass the threshold property in the options parm.
https://codesandbox.io/s/4j1vz4ly19

![image](https://user-images.githubusercontent.com/13006634/51212646-a7e32b80-18de-11e9-8e88-c6fd25c5fda8.png)

**Comment by theiliad** [comment]
Checked with the **codesandbox** link above, after updating to latest version the issue is resolved
