### ISSUE TITLE
[Bug]: Element with "graphics-symbol" graphics role has no label or an empty label

### ISSUE THREAD

**Issue by darunya-b-c** [carbon-design-system/carbon-charts#1340]
### What happened?

<img width="1254" alt="图片" src="https://media.github.ibm.com/user/42629/files/ec1aa580-e0af-11eb-8750-3e029091c043">

### Version

@carbon/charts": "0.41.99",
"@carbon/charts-react": "0.41.99",

### Data & options used

{
  "title": "Line (skeleton)",
  "axes": {
    "bottom": {
      "title": "2019 Annual Sales Figures",
      "mapsTo": "date",
      "scaleType": "time"
    },
    "left": {
      "mapsTo": "value",
      "title": "Conversion rate",
      "scaleType": "linear"
    }
  },
  "curve": "curveMonotoneX",
  "data": {
    "loading": true
  },
  "height": "400px"
}

**Comment by theiliad** [comment]
Hi,
Building out a line chart in codesandbox with the options that you've provided, I was **unable** to see the error.

Could you pls reproduce this issue and provide a link where I'd be able to see the error inside the checker?

You can use the `Edit on Codesandbox` button on our demos
https://charts.carbondesignsystem.com/?path=/story/simple-charts-line--line-discrete

Pls feel free to reopen with additional comments

**Comment by wlinacdl** [comment]
Hi @theiliad Here is reproduce steps:
1. Go to https://dev.console.test.cloud.ibm.com/
2. Open a CIS service.
3. Go to 'Metrics' page
4. Go to 'Domain' tab

Also could you please let me know your Carbon version? We will use your version to try it again. Thanks.

**Comment by theiliad** [comment]
Hi again @wlinacdl I think you might be on a much older version. Could you pls update to latest and let us if that fixes things?
