### ISSUE TITLE
[Bug]: Data on bar chart unnaturaly cramped when sufficient data given

### ISSUE THREAD

**Issue by piotr-kotara-ibm** [carbon-design-system/carbon-charts#1343]
### Contact Details

piotr.kotara@ibm.com

### What happened?

We use the stacked bar chart to display time-based data - here we have properly displayed range from 9/30/2021 to 11/30/2021:
<img width="1162" alt="obraz" src="https://user-images.githubusercontent.com/92912677/161531997-9e8be64d-8a3c-4c6c-b7fd-6ee873a5d6e6.png">
However when we increase range by one day or more, data starts to be cramped on the chart
<img width="1162" alt="obraz" src="https://user-images.githubusercontent.com/92912677/161532342-2ac21e07-8483-41da-b167-880915501ae8.png">

I had manage to isolate and reproduce the bug on codesandbox environment on the simple bar chart:
<img width="734" alt="obraz" src="https://user-images.githubusercontent.com/92912677/161532649-8d3bc507-3b5e-4f6a-bcb3-8593af769b91.png">
<img width="734" alt="obraz" src="https://user-images.githubusercontent.com/92912677/161532715-bbc8c356-52ba-4ebd-9d43-399e4b282a48.png">

### Version

`@carbon/charts-react@0.53.0`

### Data & options used

```js
options: {
      title: "Vertical simple bar (time series)",
      axes: {
        left: {
          mapsTo: "value"
        },
        bottom: {
          mapsTo: "date",
          scaleType: "time"
        }
      },
      height: "400px"
    }

Data is generated - more info in codesandbox
```

### Codesandbox example

https://codesandbox.io/s/pedantic-keldysh-llx57m?file=/src/index.js

**Comment by piotr-kotara-ibm** [comment]
Issue can be addressed by using 
```
timeScale:{
  addSpaceOnEdges: 0
}
``` 
property.

**Comment by mthaak** [comment]
With `timeScale: {addSpaceOnEdges: 0}` there is no space between the bars and the left and right side of the chart area which doesn't look nice:
![image](https://user-images.githubusercontent.com/6129322/209105065-f3530c53-1fce-4b0e-ae03-e42cf24b9add.png)

So I've opened a new bug report: https://github.com/carbon-design-system/carbon-charts/issues/1480
