### ISSUE TITLE
Is it possible to get CDN version of the Vue Package that I can use via the <script> tag?

### ISSUE THREAD

**Issue by Mashiane** [carbon-design-system/carbon-charts#1344]
### Contact Details

mbanga.anele@gmail.com

### Question

Is it possible to get CDN version of the Vue Package that I can use via the <script> tag? Thanks

**Comment by theiliad** [comment]
Hi,
This is what's currently available on JSdelivr https://www.jsdelivr.com/package/npm/@carbon/charts-vue

I haven't used vue libraries through CDNs but I imagine the UMD package would work for that.

Feel free to reopen with additional comments

**Comment by Mashiane** [comment]
Thank you so much, I will give it a try.
