### ISSUE TITLE
There should be an option to supply a custom color function

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-charts#136]
So colors for lines/bars/pie/etc can be determined based on the data or any other metric.

A potential signature could be:
```typescript
function(data: any, chart: any): string
```

Where `data` is the current data being displayed, and `chart` is either a reference to the chart instance, or a reference to the config (whichever is sufficiently powerful).

**Comment by asahlin** [comment]
This is something we need.   Here is the design for a 1st quarter deliverable to gen1 details page.

![image](https://user-images.githubusercontent.com/13006634/51695977-f6bd4f00-1fc9-11e9-8977-ddc131e0ca8e.png)
