### ISSUE TITLE
[Bug]: I can't import interface of chart options from @carbon/charts-angular

### ISSUE THREAD

**Issue by dkhrunov** [carbon-design-system/carbon-charts#1367]
### What happened?

I'm trying to import intreface `DonutChartOptions` for char, but it not exist in npm package **@carbon/charts-angular**. How I can import `DonutChartOptions` intreface  ?

### Version

"@carbon/charts-angular": "^0.58.1",

### Data & options used

```js
import { DonutChartOptions } from '@carbon/charts-angular'
```

### Relevant log output

```js
Module '"@carbon/charts-angular"' has no exported member 'DonutChartOptions'.
```

**Comment by theiliad** [comment]
Hi, you would import those from `@carbon/charts` 🙂

**Comment by dkhrunov** [comment]
> Hi, you would import those from `@carbon/charts` 🙂

Thanks, but this means, that I also should install `@carbon/charts` with `@carbon/charts-angualr`, because `@carbon/charts` does not installed with @carbon/charts-angualr` package as peer dependency

**Comment by theiliad** [comment]
@dkhrunov `@carbon/charts-angular` has a dependency on `@carbon/charts`, so it should already be installed
https://github.com/carbon-design-system/carbon-charts/blob/master/packages/angular/package.json#L44

**Comment by dkhrunov** [comment]
@theiliad hm, this is my package.json look like, after `npm install @carbon/charts-angular`
![image](https://user-images.githubusercontent.com/25565058/169534885-f92f58e8-c1b1-482b-aec7-7de3fd54d4f9.png)

**Comment by dkhrunov** [comment]
> @dkhrunov yes, internally within `@carbon/charts-angular`, `@carbon/charts` is a dep. That wouldn't make it show up in **your** package.json

Got it, thank you!
