### ISSUE TITLE
[Bug]: @carbon/charts/styles-g90.css seems to be gone in @carbon/charts@1.0.3

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1378]
### Contact Details

nstuyvesant@gmail.com

### What happened?

Just tried out @carbon/charts@1.0.3 and @carbon/charts-angular@1.0.3 and it looks like styles-90.css is gone from the @carbon/charts package.

Is there a different way I should be setting the theme for the new version?

### Version

@carbon/charts@1.0.3
@carbon/charts-angular@1.0.3

**Comment by Akshat55** [comment]
You'll be able to specify the theme via `options` going forward
