### ISSUE TITLE
[Feature Request]: Add Blazor support

### ISSUE THREAD

**Issue by vgb1993** [carbon-design-system/carbon-charts#1384]
### Summary

As a developer I would like to use carbon charts inside a Blazor application.

### Justification

Blazor is the new Microsoft web SPA framework, it has been gaining traction among .NET developers. The framework is still young but it is promissing. Specially since .NET Maui now offers a way to create Hybrid Blazor apps that can run natively on any platform. 

Having a wraper of this amazing chating library would be very very usefull fo us, as we plan to migrate from Angular to Blazor.

### Desired UX and success metrics

None

### "Must have" functionality

None

### Specific timeline issues / requests

None

### Available extra resources

https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor

https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0

**Comment by vgb1993** [comment]
hello any plans to support blazor?

**Comment by theiliad** [comment]
Hi 🙂 

Unfortunately I don't have any experience or expertise in Blazor.
Additionally we currently don't have the bandwidth to look into this.
