### ISSUE TITLE
[Enhancement]: "g80" theme support

### ISSUE THREAD

**Issue by ZodiacWind** [carbon-design-system/carbon-charts#1388]
### Summary

Add "g80" option to carbon chart themes.

### Justification

As mentioned in the tutorial, Carbon Charts support four themes (white, g10, g90 & g100), while Carbon Componets support filve themes  (white, g10, g90, g100 and **g80**). Therefore, I could not sync my components and charts, if "g80" is chosen. 

### Desired UX and success metrics

"g80" style is added to @carbon/charts/styles.css, and it could be selected like the existing four themes.

### "Must have" functionality

"g80" style CSS

### Specific timeline issues / requests

No.

### Available extra resources

We can refer to Carbon Components. And I'd like to do something like syncing the sytle between Components as well as Charts.

**Comment by ZodiacWind** [comment]
I'm sorry but I just noticed that "g80" was removed in v11. Maybe I should not use this theme in carbon-components-svelt?

If so, the issue could be closed.

**Comment by theiliad** [comment]
I've never heard of g80 🙂

And as far as I know it's not included in carbon.

I will close for now and feel free to ask up to reopen with additional comments 🙂

**Comment by ZodiacWind** [comment]
> I've never heard of g80 🙂
> 
> And as far as I know it's not included in carbon.
> 
> I will close for now and feel free to ask up to reopen with additional comments 🙂


Thank you. I came here from `carbon-components-svelte`, which is also based on Carbon library.   `carbon-components-svelte` has "g80" and so does Carbon v10.

**Comment by ZodiacWind** [comment]
@theiliad I noticed that in the earlier version, for example, 0.5.1, `@carbon/charts/styles.css` is enough. But it has changed.
