### ISSUE TITLE
Bar chart - Responsive mode

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#139]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3
### Issue description
**Expected:**  In responsive mode chart weight is expected to adjust to a widget width (expand along with the widget).  Expected to be aligned within the widget.
**Observed:** Component has fixed size and won't adjust as widget expands. Not aligned within widget.
![1](https://media.github.ibm.com/user/45002/files/a927c0c6-1043-11e9-8e8f-403998fe9b5b)

--------------------------------------------------------------------------------------

**2.  Single bar width**
**Expected:** On the Neutrino site there are examples where charts have different bar width (consistent within the same chart).  Below is the example used as a reference for UI design.
**Observed:**  OMSI bars appear thicker than on the mockup. Single bar width changes in responsive mode (becomes even thicker). Our developer team says that bar appearance has to do with the component.
![2](https://media.github.ibm.com/user/45002/files/eb850f14-1043-11e9-9868-25ea25c6c42e)

**Comment by cal-smith** [comment]
The second half of this issue seems to just #140 repeated, maybe edit it out?

From your screenshots it appears the component is resizing properly? It's not clear what the issue is.

**Comment by assiroud** [comment]
@cal-smith In the first comment the issue is that the chart won't align in the centre of the widget in responsive mode: in tends to stick to the left side of the widget. It might have to do with the missing y-axis name that has been added to the component by our devs.

**Comment by cal-smith** [comment]
Possibly ... I think I see the vertical alignment changing in the pictures now. This will definitely need some fine-tuning.
