### ISSUE TITLE
[Bug]: [UI] Carbon Charts Issue for Donut Chart with Latest Carbon Version

### ISSUE THREAD

**Issue by ab20145034** [carbon-design-system/carbon-charts#1399]
### What happened?

With Latest Carbon Version update Donut Chart  is behaving weird in showing data as its showing the unnecessary dots along with the data in few scenarios in Donut Chart and Legand

### Version

"@carbon/charts": "^1.2.1"
"@carbon/charts-react": "^1.2.1",

**Comment by theiliad** [comment]
Hi, pls include **screenshots and details** such as what version of charts you migrated from and what differences exactly you're noticing.

I'm going to close for now as our codesandbox & storybook demos seem to be working fine, however feel free to respond with additional comments and we could re-open 🙂
