### ISSUE TITLE
Bar chart - Single bar width

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#140]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3

### Issue description
**Expected:** On the Neutrino site there are examples where charts have different bar width (consistent within the same chart).  Below is the example used as a reference for UI design.
**Observed:**  OMSI bars appear thicker than on the mockup. Single bar width changes in responsive mode (becomes even thicker). Our developer team says that bar appearance has to do with the component.
![2](https://media.github.ibm.com/user/45002/files/eb850f14-1043-11e9-9868-25ea25c6c42e)

**Comment by cal-smith** [comment]
So you want to constrain the bar width to some maximum width? 

The current behavior preserves spacing between the bars, at the expense of increasing and decreasing the bar width as the screen resizes. We may want to make sure design understands the trade offs of each approach.

**Comment by theiliad** [comment]
Yes, not sure if we want to automatically make that choice for the developer. What would your proposed breakpoints be @EddieLi?

Also, @cal-smith @zvonimirfras opinions on automatically adjusting the gap?

**Comment by assiroud** [comment]
Is single bar width calculated in proportion to the total chart width? 
We are considering defining max width for a bar since all our charts expand horizontally only.

**Comment by cal-smith** [comment]
From what I can see yes, a single bar is calculated based on the total chart width + gap between the bars.

Automatically adjusting the gap to preserve a maximum bar width makes sense to me - I wouldn't change our current defaults, since they're probably what most people want most of the time (keeps the chart from looking too sparse on wider screens).

**Comment by nicoleroppel** [comment]
@theiliad @cal-smith Hi! Not sure if this is helpful or not, but we're hoping that if a chart is the same size, with the same amount of data (same number of bars), the width of the bars will be the same. 

For example, this one is correct (bar width is the exact same in both of the charts).

<img width="543" alt="screen shot 2019-01-28 at 11 47 07 pm" src="https://user-images.githubusercontent.com/43546639/51884899-21efc780-2357-11e9-8fea-7c73cb48435d.png">

However, this one is incorrect. The bottom chart bars are wider, even though it's the same number of bars and the size of the widget + chart is the exact same.

<img width="555" alt="screen shot 2019-01-28 at 11 47 13 pm" src="https://user-images.githubusercontent.com/43546639/51884926-4b105800-2357-11e9-8db7-35c974b38299.png">

It looks like we have the second screenshot happening in our component.

<img width="801" alt="screen shot 2019-01-28 at 11 50 23 pm" src="https://user-images.githubusercontent.com/43546639/51884982-8f035d00-2357-11e9-991a-f287581d59d5.png">

(bad screenshot, I know. I just wanted to get the comparison...)

Unless there's a specific dev reason for the difference, is it possible to get this updated?

Thanks!
