### ISSUE TITLE
Bar chart - Bar legend layout

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#141]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3

### Issue description
**Observed:** OMSI Bar legend is too close to x- axis. Looks ok on the component. According to OMS developers the spacing cannot be maintained because the chart is drawing dynamically. 
![4](https://media.github.ibm.com/user/45002/files/fdd7e092-1043-11e9-882a-b06829b8bfb2)

**Comment by theiliad** [comment]
@EddieLi @assiroud I'm not sure I understand the issue. Please explain more

**Comment by assiroud** [comment]
@theiliad I want to make sure that x- axis legend does not overlap x- axis like we observed it in Neutrino charts in responsive mode. Please let me know if you need more details.

**Comment by theiliad** [comment]
not sure if this is relevant anymore as the use cases apply to an older design language version

**Comment by assiroud** [comment]
agreed, not relevant. we are using the new charts now and these are looking good. great job guys!
