### ISSUE TITLE
[Bug]: BoxplotChart does not render outlier to the proper x coordinate

### ISSUE THREAD

**Issue by theoshu** [carbon-design-system/carbon-charts#1410]
### Contact Details

tshu@us.ibm.com

### What happened?

The BoxplotChart renders the outlier circle at x: 0 instead of the proper x coordinate.

![image](https://user-images.githubusercontent.com/4643524/179068619-5941e4fd-3aed-472e-905e-1f210d16c8e2.png)

### Version

@carbon/charts@0.58.2
@carbon/charts-react@.58.2

I also tested this in the >= 1.0 version and the bug is also there

### Data & options used

```js
Please see the linked codesandbox: https://codesandbox.io/s/trusting-brattain-sbj1y4?file=/src/index.js
```

### Codesandbox example

https://codesandbox.io/s/trusting-brattain-sbj1y4

**Comment by falsepopsky** [comment]
@theoshu I never used BoxPlot chart before, I rewrite your [demo](https://codesandbox.io/s/busy-danny-vjv7z4) with every dep to `latest` and looks like it's fixed (I guess?).

**Comment by theiliad** [comment]
Thank you @falsepopsky 🙂 
@theoshu pls let us know if this resolves your issues.
