### ISSUE TITLE
[Enhancement]: Support for Angular 14+ for @carbon/charts-angular

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1415]
### Contact Details

nstuyvesant@gmail.com

### Summary

Saw that a recent release of @carbon/charts-angular added support for Angular 13. Would it be possible to adjust it to support Angular 14 (now 14.1.0)? In my experience, there are very few breaking changes moving from Angular 13 to 14. I have been using Carbon Charts with Angular 14 for some time with no changes.

### Justification

Would like to be able to use `npm install`. Carbon Charts Angular is the only package that forces us to use `npm install --force`. 

### Desired UX and success metrics

No changes to UX - just an improvement around tooling.

### "Must have" functionality

Be able to run `npm install` when my project has a dependency on @carbon/charts-angular.

### Specific timeline issues / requests

Should be possible without changes so I recommend this going into a minor release.

### Available extra resources

I don't foresee any changes other than to the package.json.

**Comment by nstuyvesant** [comment]
I know the Storybook was the holdup for Angular 13 support. Hopefully, the changes that were made to it to support Angular 13 will work fine with Angular 14.1.0.

**Comment by theiliad** [comment]
Hi @nstuyvesant, unfortunately still having issues with angular 😞 

Curious, would you like to help out with this work? We can setup a contribution model for this specific piece if you'd like?

**Comment by nstuyvesant** [comment]
Sure - is the problem still in the Storybooks or elsewhere?

**Comment by theiliad** [comment]
> Sure - is the problem still in the Storybooks or elsewhere?

Yes, mainly storybook. If there's a PR on your end to add support here, we should ideally have
- Storybook working
- Build process updated (another benefit here would be getting `node-sass` removed
- ng build packages updated

**Comment by nstuyvesant** [comment]
OK - will take a look tomorrow to see what I can do. Thanks for this info.

**Comment by nstuyvesant** [comment]
@theiliad  - Is there a document that describes the overall approach for contributing (and testing)? Just cloned the repo and am running build for all of carbon-charts 1.5.1. Mainly, I'd like to focus on the Angular stuff a bit to see if we can get it to support Angular 14.1.x.

**Comment by nstuyvesant** [comment]
Solved in `@carbon/charts-angular@next` which now supports Angular 16.

**Comment by CsarChvz** [comment]
Does it anyone know how to implement carbon charts-angular for angular 14?

**Comment by nstuyvesant** [comment]
You have to use `@carbon/charts-angular@latest` instead of next but the approach is pretty much the same otherwise.

**Comment by davidhunt135** [comment]
@CsarChvz did you get this working? I'm having issues with Angular 14 too. None of the components are recognised

**Comment by nstuyvesant** [comment]
@davidhunt135 - what version of `@carbon/charts-angular` are you using?

**Comment by davidhunt135** [comment]
@nstuyvesant using latest which I think is 1.8.1. Managed to resolve the issue though, was project configuration
