### ISSUE TITLE
[Bug]: Carbon Charts Angular changes theme on the fly

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1416]
### Contact Details

nstuyvesant@gmail.com

### What happened?

Each instance of a Carbon Charts Angular component is changing its data-carbon-theme at runtime to "white" even though I hard-coded it to "g90".

Code sample below.

### Version

@carbon/charts-angular@1.4.0

### Data & options used

```js
This...

<ibm-stacked-bar-chart data-carbon-theme="g90"
  [data]="barData[barGraphSelection]"
  [options]="bar.options"
></ibm-stacked-bar-chart>

at run time looks like this...
```html
<ibm-stacked-bar-chart _ngcontent-vay-c282="" data-carbon-theme="white" ng-reflect-data="[object Object],[object Object" ng-reflect-options="[object Object]" class="cds--chart-holder" style="height: 400px;">
... <!-- This part looks correct -->
</ibm-stacked-bar-chart>
```

Note the data-carbon-theme value change to white. This is happening with two other Chart Types I use: Donuts and Gauges.
```


### Relevant log output

_No response_

### Codesandbox example

_No response_

**Comment by nstuyvesant** [comment]
Have not been able to find a workaround. Temporarily rolling back to previous version.

**Comment by theiliad** [comment]
Hi, pls use `theme` inside your options instead https://charts.carbondesignsystem.com/?path=/story/docs-tutorials--themes 🙂

**Comment by nstuyvesant** [comment]
Thanks! That did it. Is the use of the data-carbon-theme attribute deprecated?

**Comment by theiliad** [comment]
this API uses data-carbon-theme itself.

I think what's going on on your end is that you might be adding the attribute on the component rather than the chart holder.

Pls use the new `theme` configurable in options
