### ISSUE TITLE
[Enhancement]: Geospatial Charts

### ISSUE THREAD

**Issue by murphye** [carbon-design-system/carbon-charts#1418]
### Summary

Geospatial Charts are shown here:
https://carbondesignsystem.com/data-visualization/complex-charts/#geospatial-charts

Are these a roadmap item? They look great!

### Justification

Geospatial designs are available on carbondesignsystem.com

### Desired UX and success metrics

See https://carbondesignsystem.com/data-visualization/complex-charts/#geospatial-charts

### "Must have" functionality

N/A

### Specific timeline issues / requests

N/A

### Available extra resources

N/A

**Comment by theiliad** [comment]
Hi, unfortunately not yet on the roadmap.
These are really large pieces that need to be thought through (frameworks/libraries/providers to be used, supported use cases etc.)

Also, please use https://github.com/carbon-design-system/carbon-charts/discussions for general questions 🙂
