### ISSUE TITLE
[Bug]: doc for Vue bubble chart makes browser non-responsive

### ISSUE THREAD

**Issue by brunnjf** [carbon-design-system/carbon-charts#1425]
### What happened?

I think the Vue bubble chart causes the browser tab to be non-responsive? Not sure if its the bubble chart in general or just the doc? Visit this URL and the browser will become non-responsive:
https://charts.carbondesignsystem.com/vue/?path=/story/simple-charts-bubble--bubble-linear

Occurs both on FF and Chrome.

### Version

`@carbon/charts@1.50` and many other versions prior

**Comment by nstuyvesant** [comment]
Hi @brunnjf - I am not able to reproduce this issue. Here's a StackBlitz example... https://stackblitz.com/edit/6rnraj?file=src%2FApp.vue

I tried Chrome 115 and Firefox 115 with the example above.

I am using a newer version of `@carbon/charts-vue` than you are with Vue 3.

There was no 1.50 version so I'm guessing you must be on 1.5.0. Are things any different if you move up to 1.11.0 (if you are on Vue 2)?

**Comment by theiliad** [comment]
I will close for now, pls let us know @brunnjf
