### ISSUE TITLE
Vue 3 usage?

### ISSUE THREAD

**Issue by JensvdHeydt** [carbon-design-system/carbon-charts#1428]
Is there a way to use this wonderful chart system with vue 3?

**Comment by theiliad** [comment]
Hi @JensvdHeydt, I'm not familiar with Vue 3 yet.

Does it include breaking changes that'd stop someone from using this library with it?

Also if you're interested, we can look at a contribution model for adding vue 3 support 🙂

**Comment by JensvdHeydt** [comment]
Hi @theiliad, I think that's the case. The syntax to include a plugin in vue 3 has slightly changed, but that's not a big problem. I tried to include a simple line chart but the component doesn't show and I receive a warning "[Vue warn]: Component is missing template or render function." in browser console. I'm not very familiar with the breaking changes between vue v2 and v3 but I think the component registration in plugins has changed. Also things like "this.$el" don't work anymore and one has to use refs instead.

On another note: I'm usually using typescript and when I try to import the the plugin I get a compiler error about types not exported.

**Comment by JensvdHeydt** [comment]
@theiliad I've analyzed this some more and I got it to work ( kind of).

When I try to use the plugin the "vue 3" way this is what I get:

<img width="670" alt="Bildschirmfoto 2022-08-11 um 11 57 54" src="https://user-images.githubusercontent.com/19750185/184110015-9664b4c6-f4ae-48b5-9ecc-26f165c6b27a.png">

But what worked for me was this:
I copied ccv-line-chart.vue and ccv-base-chart.vue into my project and used these components. That's actually working so I guess there's "just" problem with the vue plugin and how the components are registered.

**Comment by nstuyvesant** [comment]
Hi @JensvdHeydt. Try out `@carbon/charts-vue@next`. This version supports Vue.js 3.3.0+. If everything looks good to you, please close this issue.

**Comment by nstuyvesant** [comment]
@theiliad - please close - no reply.

**Comment by theiliad** [comment]
I will close for now, pls let us know @JensvdHeydt
