### ISSUE TITLE
Bar chart - Chart grid

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#143]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3

### Issue description
Expected:** In small versions of charts lower grid density is expected. In some cases grid can be removed.
**Observed:**  In small versions of charts grid is very dense.  Since legend can’t be scaled accordingly, the grid appearance doesn't contribute to data visualization
![5](https://media.github.ibm.com/user/45002/files/24667d40-1044-11e9-832e-5dafc7f58158)

**Comment by nicoleroppel** [comment]
@theiliad Design agrees with this! For the y axis, we'd like to only have a grid line if there's a number.

To using Assia's example:

What we have currently...

<img width="874" alt="screen shot 2019-01-28 at 11 56 30 pm" src="https://user-images.githubusercontent.com/43546639/51885184-6d56a580-2358-11e9-888b-1356a5f3643f.png">

What we'd like:

<img width="624" alt="screen shot 2019-01-28 at 11 56 37 pm" src="https://user-images.githubusercontent.com/43546639/51885198-7ba4c180-2358-11e9-9c3a-99cc8d6fca83.png">

Thanks!

**Comment by theiliad** [comment]
not sure if this is relevant anymore as the use cases apply to an older design language version
