### ISSUE TITLE
[Bug]: Svelte "Sourcemap for '...@carbon/charts/styles.css' points to missing source files"

### ISSUE THREAD

**Issue by josefaidt** [carbon-design-system/carbon-charts#1433]
### Contact Details

reply here

### What happened?

We began receiving an odd issue where SvelteKit is looking for a sourcemap file that is seemingly not surfaced to Vite's dev server, 

```
Sourcemap for "/Users/josef/Documents/projects/aws-amplify/amplify-discord-bots/node_modules/.pnpm/@carbon+charts@1.5.2_d3@7.6.1/node_modules/@carbon/charts/styles.css" points to missing source files
```

From the file in question we can see it points to a `styles.css.map` file, which does in fact exist as a sibling to the `styles.css` file in question.

```
/*# sourceMappingURL=styles.css.map */
```

SvelteKit is looking for 

```
/styles.css.map
```

### Version

"@carbon/charts": "^1.5.2",
"@carbon/charts-svelte": "^1.5.2",

### Relevant log output

```js
DevTools failed to load source map: Could not load content for https://codesandbox.io/s/styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Codesandbox example

https://codesandbox.io/s/qvcofj

**Comment by cloudlena** [comment]
Possibly because of https://github.com/carbon-design-system/carbon-charts/pull/1421#issuecomment-1263886702

**Comment by nstuyvesant** [comment]
Hi @josefaidt - Can you try `@carbon/charts@1.11.8` and `@carbon/charts-svelte@1.11.8` to see if this is resolved? If so, can you close this issue?

**Comment by nstuyvesant** [comment]
@theiliad - please close - no reply.

**Comment by theiliad** [comment]
I will close for now, pls let us know @josefaidt
