### ISSUE TITLE
[Bug]: Rendering issue of line chart and combo charts in Chrome

### ISSUE THREAD

**Issue by JuhiSharma2** [carbon-design-system/carbon-charts#1437]
### Contact Details

JUHI.Sharma2@ibm.com

### What happened?

A bug happened! The Line chart should be coming proper with the data .The line chart has elongated line which does not render data properly and it gets rendered properly after second refresh..This issues is only faced in Chrome and no other browsers are affected .
The line chart, Area chart and combo charts are being affected by this.
<img width="830" alt="Screenshot 2022-08-23 at 10 02 55 AM" src="https://user-images.githubusercontent.com/111729812/186655912-d1f8fc9a-0506-4e2b-b641-f3de6a628209.png"> : Bug image.

correct image : 
<img width="815" alt="Correct image" src="https://user-images.githubusercontent.com/111729812/186655981-a34cdac2-b444-439f-b6f7-d6598d0a6f58.png">

### Version

Package version
1.5.0

React version
17.0.2

### Codesandbox example

https://codesandbox.io/s/wlbj6s

**Comment by Akshat55** [comment]
@JuhiSharma2 I ran the code sandbox and I don't see the bug happening. Could you make sure your chrome is up to date & you're using the latest version of @carbon/charts? Please let me know if you're still seeing this error!

**Comment by theiliad** [comment]
Hi @JuhiSharma2, pls lmk if this is still relevant, and whether Akshat's comment has helped, and we can re-open 🙂
