### ISSUE TITLE
[Bug]: Svelte Carbon charts have upstream `sass` peerDep

### ISSUE THREAD

**Issue by josefaidt** [carbon-design-system/carbon-charts#1440]
### Contact Details

n/a

### What happened?

When using the Svelte distribution of carbon charts, we receive missing peer dependency issues with `sass` when using package managers such as `pnpm` due to the upstream peer dep on [@carbon/styles](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/package.json#L32). From what I can tell this appears to be optional, and I can disable the missing peer deps errors by providing the following `.npmrc` file

```
strict-peer-dependencies=false
```

However is it possible to include the following modifications to the `@carbon/chart`'s package.json to account for when developers opt to use the built CSS stylesheet?

```json
"peerDependenciesMeta": {
  "sass": {
    "optional": true
  }
}
```

### Version

```json
"@carbon/charts": "^1.5.2",
"@carbon/charts-svelte": "^1.5.2",
```

### Data & options used

```js
n/a
```

**Comment by nstuyvesant** [comment]
@josefaidt - This modification (making sass an optional peerDependency) has been added to `@carbon/styles`. Would it be ok for you to close this issue?

**Comment by theiliad** [comment]
I will close for now, pls let us know @josefaidt
