### ISSUE TITLE
Donut chart: Values on the Y-axis are showing as a decimal instead of a whole number

### ISSUE THREAD

**Issue by gentryb** [carbon-design-system/carbon-charts#1444]
#Description

> Problem: Values on the Y-axis are showing as a decimal, e.g. 0.2, instead of a whole number.

Screenshot
![image](https://user-images.githubusercontent.com/74424722/189195156-63081667-ae82-4753-a62e-47b87be4fab8.png)

> I have been informed by development using this component, that this is a bug within the donut chart component and can't be resolved on their end. Let me know what additional info you need, code snippet, etc. or the best next steps.
> [Related issue](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53657)

**Comment by theiliad** [comment]
Hi, the decimals can now be removed by doing

```js
  "axes": {
    "left": {
      "mapsTo": "value",
      "ticks": {
        "values": [0, 1]
      }
    }
  }
```

https://stackblitz.com/edit/so38eu?file=data.json,options.json
