### ISSUE TITLE
Donut chart: Legend displaying in the wrong order

### ISSUE THREAD

**Issue by gentryb** [carbon-design-system/carbon-charts#1446]
Description
> Story priority legends are not displayed in the correct order.
> Expected behavior: P1, P2, **P3**, P4

Screenshot
![image](https://user-images.githubusercontent.com/74424722/189193835-bffd2df6-050b-41c1-84c3-b0ba47829fa1.png)

> What browser are you working in? Google Chrome
> [Related issue](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54408)

**Comment by theiliad** [comment]
Hi 👋🏻 , thank you for reaching out 🙂 

This is a design decision made at the time, it is expected to match the order that you see on the donut itself.
