### ISSUE TITLE
Pie chart - legend

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#145]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3

### Issue description
Once the percentage values turned off on a pie chart can these appear next to legends on the right side of the chart?
￼<img width="526" alt="image" src="https://media.github.ibm.com/user/45002/files/dddf504c-1410-11e9-9c3b-6b6091c2a161">

**Comment by cal-smith** [comment]
related to #144

**Comment by assiroud** [comment]
@cal-smith Here the example of what we are trying to achieve

![image](https://user-images.githubusercontent.com/24441071/51340252-67a9b780-1a5c-11e9-8bd2-21ab30310d99.png)

**Comment by theiliad** [comment]
@nicoleroppel @dianatran18

**Comment by nicoleroppel** [comment]
@theiliad Thank you! I was trying to find this issue again.

So we're not going to remove the percentages from the chart. We want to keep that in to be consistent with our other graphs, and make comparisons very easy. 

Instead, we'd like to have these lines come out from the pie and donut chart like the screenshot below so we avoid percentage overlap when the slices are quite small.

Can you take a look and let me know if you think we could do something like this?

<img width="809" alt="screen shot 2019-01-24 at 3 04 06 pm" src="https://user-images.githubusercontent.com/43546639/51705717-562b5700-1fea-11e9-9b42-0b585d3754be.png">

Thanks!

**Comment by assiroud** [comment]
@nicoleroppel Thanks for updating the design.
@theiliad Do you think the design would work for small charts (around 150-200px)?

**Comment by nicoleroppel** [comment]
@assiroud ah sorry, I should have mentioned it in the thing above...what I showed on the design call on Monday (and the screenshot above) is for a donut chart that's 150px. So I think we should be good!

**Comment by cal-smith** [comment]
So we implemented a few changes to how the % around the pies are rendered, they shouldn't overlap in most reasonable situations (only if there are a number of very small slices side by side) ... adding the lines is something we want to look into, but we'll need a more advanced placement algorithm to accomplish.

We talked to @EddieLi in person, and agreed we could push out the addition of the lines to a later date.

**Comment by assiroud** [comment]
@cal-smith Can you drop a link to what's the updated version look like? Thanks!

**Comment by cal-smith** [comment]
Same demo link as always: https://carbon-design-system.github.io/carbon-charts/

Here it is resized quite small:
![image](https://user-images.githubusercontent.com/1744185/53265665-cd690f00-36ac-11e9-9f89-1bac0f8c23ba.png)

**Comment by assiroud** [comment]
Looks good @cal-smith. We are ok with pushing line to a later day. Question: In some cases our charts display small values side by side, for example 1,2,4,6. Could you create a test with these values for us to check on label appearance? Thanks.

**Comment by dianatran18** [comment]
Leaving an interim design solution here until we do further research, testing, and collaboration within the broader IBM data viz guild. 

Examples of having up to 6 small values in a donut chart: 
<img width="1338" alt="screen shot 2019-03-04 at 3 11 59 pm" src="https://user-images.githubusercontent.com/43549567/53760156-0fa20580-3e90-11e9-9268-ce0e570cc979.png">

Specs:
<img width="558" alt="screen shot 2019-03-04 at 3 12 27 pm" src="https://user-images.githubusercontent.com/43549567/53760175-16307d00-3e90-11e9-932e-0dd66a611482.png">

**Comment by theiliad** [comment]
I think we need a better solution here that's also optimized for the dev side of things. Keep in mind that as the stack of percentages get taller, the donut will have to become smaller to still fit within it's container...

**Comment by dianatran18** [comment]
@theiliad, yes I know we need a better solution, as I mentioned this is a short term design solution until further research and collaboration across teams. This was continuing off the path of the design Nicole had above to answer a few questions that have come up, and not to be the final implementation. 

Also, this is just a solution for the use case of having a max of **7** values in the donut chart. So this will not grow much larger than that.

**Comment by shixiedesign** [comment]
@theiliad @dianatran18 sorry jumping in with a suggestion if I may...since you guys are talking about interim solutions, what if we cap the number of small value "call out" lines to just 2 max (to avoid high stacking labels squashing the donut), and simply skip rendering labels / hide labels for others when labels are starting to overlap  – similar to what is already happening with x-axis labels on charts using axis. 

There should still be hover tooltip anyway – hard to target if slice is too small i know – but I think figuring out small value "call-out" line for 2 or 1 instance is a worth-while investment for this chart type.

**Comment by shixiedesign** [comment]
My very quick exploration. Also I notice if you put the label at the end of the call-out line instead of on top of it, it saves us a few more pixels! 

![image](https://user-images.githubusercontent.com/15144993/59971090-0cb04b00-953b-11e9-8e08-162369d8f650.png)

**Comment by theiliad** [comment]
Addressed in #275.
