### ISSUE TITLE
Two charts are rendered instead of one in React ? [Bug]: 

### ISSUE THREAD

**Issue by lynclet** [carbon-design-system/carbon-charts#1455]
### Contact Details

lynclet1@gmail.com

### Question

Hello,  why is it that two charts are rendered instead of one in React.js

I use the sandbox precisely as it is here: https://codesandbox.io/s/wrpoyz?file=/package.json
"@carbon/charts": "^1.6.1",
    "@carbon/charts-react": "^1.6.1",
    "@carbon/react": "1.1.0",
    "react": "^18.2.0",
    "react-chartjs-2": "^4.3.1",
    "react-dom": "^18.2.0",

https://github.com/carbon-design-system/carbon-charts/issues/1455#tasklist-block-050b1b75-0ae4-43bb-8980-70162e24eb50

**Comment by wybieracz** [comment]
I have the same problem. Found this thread: https://github.com/carbon-design-system/carbon-charts/issues/1352 but solution with ```next.config.js``` is not working for me. (ps this is rather bug 🐛 than enhancement)

**Comment by theiliad** [comment]
Hi, I'm expecting this to be fixed now with the merge of #1501, but pls let us know if that's not the case and we can revisit 🙂
