### ISSUE TITLE
[Bug]: installation with pnpm is incomplete

### ISSUE THREAD

**Issue by ionutale** [carbon-design-system/carbon-charts#1457]
### What happened?

i like to use pnpm, and does not work

### Version

latest 
"@carbon/charts-svelte": "^1.6.1",

**Comment by theiliad** [comment]
Hi @ionutale 👋🏻 
Could you pls include some additional details in the issue? Such as your pnpm version, node version etc.

I will close for now, and feel free to comment with more info 🙂
