### ISSUE TITLE
Pie chart - breakpoints

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#146]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [X] Other

#### charts version:
0.8.3

### Issue description
What's the breakpoint for when legend collapses?

**Comment by theiliad** [comment]
https://github.com/carbon-design-system/carbon-charts/blob/edfe52fdf82b96f123d8ccef59d92a7ca798e149/packages/core/src/base-chart.ts#L597
https://github.com/carbon-design-system/carbon-charts/blob/edfe52fdf82b96f123d8ccef59d92a7ca798e149/packages/core/src/configuration.ts#L92
