### ISSUE TITLE
[Bug]: Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide 

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon-charts#1460]
### Contact Details

biagioparuolo@hotmail.it

### What happened?

Error: Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide

### Version

"@carbon/charts-react": "^1.6.1",
 "@carbon/react": "^1.15.0",
 "react": "^17.0.2",
"react-dom": "^17.0.2",

**Comment by biapar** [comment]
Strange. I've to install npm install -S @carbon/charts d3 too.

**Comment by theiliad** [comment]
Hi, styles come in from `@carbon/charts` so you probably did not have it installed, and your bundler couldn't make the connection through `@carbon/charts-react`
