### ISSUE TITLE
[Enhancement]: (v0.x) Loosen fixed dependency on `carbon-components@10.56.0`

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-charts#1461]
### Contact Details

Reply to this issue

### Summary

Please can you release a new version of `@carbon/charts@0` which unpins its fixed production dependency on `carbon-components@10.56.0` to something more flexible, like `carbon-components@^10.56.0`.

### Justification

We are using `@carbon/charts@0.58.2`, which is the latest **supported** version of Carbon Charts (`@carbon/charts@1` is in beta and requires Carbon 11, so we can't upgrade yet). This version of `@carbon/charts@0` has a fixed, exact dependency on `carbon-components@10.56.0`. We need to avoid having multiple versions of `carbon-components` in play simultaneously - this bloats our bundles and the two versions of Carbon interfere with one another. Because of this, we are having to pin our entire application to `carbon-components@10.56.0`. This prevents us from picking up the latest enhancements and bug fixes from Carbon 10.

Also, we use your sibling Carbon package, `@carbon/ibm-cloud-cognitive-cdai`. This package regularly upgrades its dependencies to always require the most recent version of Carbon. Right now, the latest version, `@carbon/ibm-cloud-cognitive-cdai@1.22.23`, [has a production dependency on `carbon-components@^10.58.4`](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/21bb950e99890e5d46512b9d47fa1112e5181669/packages/cdai/package.json#L40). Because these version ranges are incompatible, we are having to downgrade to an older version of CDAI, `1.22.9`, from about six months ago. This prevents us from picking up the latest enhancements and bug fixes from CDAI too. If you followed the lead of CDAI on this, that would be very helpful, and more consistent across all `@carbon`-scoped packages.

### Desired UX and success metrics

No UX changes - a simple peek at `@carbon/charts`'s `package.json` suffices to measure success here.

### "Must have" functionality

Again, no UX changes.

### Specific timeline issues / requests

We have a release on Friday 18 November 2022. We would appreciate it if this could be fixed at least a week before then, so we have time to incorporate the fixes.

### Available extra resources

I am happy to make this single-character change to your `package.json` - I just need to insert a `^`. However, I am not able to find a `v0.x` branch where work on the `@carbon/charts@0` release is tracked, so if you can direct me to that, I would appreciate it. Also, you would need to release the new version yourself.

Thank you!

**Comment by s100** [comment]
@theiliad Thank you for making this change as requested! However, it looks like the latest available version of `@carbon/charts@0` is still 0.58.2. When will you release a new version with this change in it?

**Comment by s100** [comment]
As I said, we are using `@carbon/charts@0`, not `@carbon/charts@1`. We didn't upgrade to `@carbon/charts@1` because it was in beta and it used Carbon 11, which we aren't using yet.

I see that as of `@carbon/charts@1.6.3` on 2022-12-23 it is out of beta, so congratulations on that. But we still aren't on Carbon 11 yet. Are you planning to backport this fix to `@carbon/charts@0`?

**Comment by theiliad** [comment]
> As I said, we are using `@carbon/charts@0`, not `@carbon/charts@1`. We didn't upgrade to `@carbon/charts@1` because it was in beta and it used Carbon 11, which we aren't using yet.
> 
> I see that as of `@carbon/charts@1.6.3` on 2022-12-23 it is out of beta, so congratulations on that. But we still aren't on Carbon 11 yet. Are you planning to backport this fix to `@carbon/charts@0`?

I currently don't have the bandwidth to generate a release for this in v0.x

I wonder if there are ways to override on your end. I'll do a search for this

**Comment by lkraav** [comment]
Did anything happen here for v0.x? We're in the exact same boat today, gradually upgrading our way to latest v10 and eventually to v11/v12, but `@carbon/charts` pin is creating a lot of uncertainty about what is supposed to be compatible, or not..

If https://github.com/carbon-design-system/carbon-charts/pull/1504 means there was never any compatibility issue with `carbon-components` up to final 10.65.2 version, easy consumer-side solution is `package.json:override` field.

Alternatively, it seems we could still bump to `@carbon/charts@^1.6` while on v10? Insights would be much appreciated 🙏
