### ISSUE TITLE
[Enhancement]: can we integrate grouped bar and stacked bar together as a new combo type

### ISSUE THREAD

**Issue by Chiayv** [carbon-design-system/carbon-charts#1465]
### Contact Details

chiayufan@cn.ibm.com

### Summary

Hi there, this request probably is for development only. So our team met a business need that seeks a "grouped and stacked" bar chart combo to visualize the data. 

### Justification

a "grouped and stacked" bar chart would visualize one of our data set in a better way.

### Desired UX and success metrics

A rough visualization looks like this:
<img width="855" alt="圖片" src="https://user-images.githubusercontent.com/117897304/201036767-bc03badc-586d-44ab-ad59-d4ab6cb918ab.png">

### "Must have" functionality

A "grouped and stacked" bar chart combo

### Specific timeline issues / requests

Not of high priority as we are using a compromised solution fulfilling the need

### Available extra resources

For additional reference, here's a grouped and stacked chart preview in highcharts: https://www.highcharts.com/demo/column-stacked-and-grouped

**Comment by theiliad** [comment]
Hi, unfortunately we have no plans currently to implement this chart type 🙂
