### ISSUE TITLE
[Bug]: should `@carbon/import-once` be a dependency?

### ISSUE THREAD

**Issue by neo** [carbon-design-system/carbon-charts#1467]
### Contact Details

@neo

### What happened?

Currently `@carbon/import-once` is part of the `devDependencies`: https://github.com/carbon-design-system/carbon-charts/blob/v1.6.1/packages/core/package.json#L67, and after installing from npm, and try to import `'@carbon/charts/styles/styles.scss'`, it complains about the stylesheet not existing (because the package is not installed).

So my questions are:
1. is this package necessary? it's used in three places throughout the code base, can it be replaced by something else such as `@use`?
2. if it ends up being necessary, can it be part of the `dependencies` rather than `devDependencies` so that when installing `@carbon/(react-)charts`, the package is installed automatically along with it?

### Version

latest: 1.6.1

### Relevant log output

```
SassError: Can't find stylesheet to import.
   ╷
16 │ @import '@carbon/import-once/scss/import-once';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@carbon/charts/styles/styles.scss 16:9  @import
```

**Comment by neo** [comment]
Also, it seems like it's a Carbon version 10 thing that's not even in the current carbon code base: https://github.com/carbon-design-system/carbon/tree/main/packages

So when this got into version 1 and migrated to Carbon 11, should we remove this dependency?

**Comment by theiliad** [comment]
Hi, unfortunately we still need `@carbon/import-once`. I'll double-check again with the team, but when we did the migration of Carbon Charts to v11, I was told to keep those imports.
