### ISSUE TITLE
Pie chart - size

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#147]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [X] Other

#### charts version:
0.8.3

### Issue description
**Expected:** Pie chart size can be adjusted to fit within a widget
**Observed:** According to OMSI developers height can't be adjusted  (no image attached)

**Comment by cal-smith** [comment]
It should scale to fit the container.

Big:
![image](https://user-images.githubusercontent.com/1744185/51329253-23f68400-1a43-11e9-9d3d-4051e91b6dfa.png)

Small:
![image](https://user-images.githubusercontent.com/1744185/51329271-2a84fb80-1a43-11e9-8586-c89671fee17d.png)

**Comment by assiroud** [comment]
@cal-smith Thanks for confirming Cal. This feature wasn't available in Neutrino, so we wanted to make sure we won't face the same issue in Carbon. Speaking of the small chart appearance - legends on top and bottom are overlapping the chart. Take a look at 16% - it's partially hidden behind the pie... is it something you can fix? Thanks!

**Comment by cal-smith** [comment]
They definitely shouldn't be doing that ... I'll close this and open an issue to look at the labels
