### ISSUE TITLE
Code of Conduct is 404

### ISSUE THREAD

**Issue by cwbriscoe** [carbon-design-system/carbon-charts#1476]
### Contact Details

dontcontactme@blah.com

### What happened?

Your readme.md has a link to a code of conduct (https://github.com/carbon-design-system/carbon-charts/blob/master/CODE_OF_CONDUCT.md) that gives a 404 error.  I don't really care about you having a CoC or not.  But don't false advertise please.

### Version

a

### Data & options used

```js
a
```

### Relevant log output

```js
a
```

**Comment by theiliad** [comment]
Fixed
