### ISSUE TITLE
[Feature Request]:  Ability to display column being grouped by in StackedBarChart tooltip

### ISSUE THREAD

**Issue by danielwaiforssell** [carbon-design-system/carbon-charts#1477]
### Contact Details

danielwai640@gmail.com

### Summary

Requesting the ability to show the column being grouped by in the StackedBarChart hover tooltip.

### Justification

Would improve the user experience by providing more specific information and clarity to the user.

### Desired UX and success metrics

Providing more clarity and specific information.

### "Must have" functionality

![image-2022-08-01-10-20-30-284](https://user-images.githubusercontent.com/51061073/205680528-35d21706-cb8c-4b6e-9c70-7d76679d55b6.jpeg)

Rather than "group", display the name of the column being grouped by in the tooltip.

### Specific timeline issues / requests

I don’t have a clear timeline.

### Available extra resources

I don't have.

**Comment by theiliad** [comment]
Hi @danielwaiforssell, could you pls expand on what it is that you're requesting here?

Unfortunately I wasn't able to understand 🙂

**Comment by theiliad** [comment]
@danielwaiforssell, I'm going to close this issue due to lack of activity. But feel free to post an update and we can reopen this and continue 🙂
