### ISSUE TITLE
Turning metrics on and off on a chart using chart legend

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#148]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3
### Issue description
**Expected:** On the chart component metrics can be turned off by clicking on an icon of a corresponding color on a legend. On the example below: blue has been turned off. Reference https://pages.github.ibm.com/peretz/charts/
**Observed:**  According to our developers the functionality is not supported
![image](https://media.github.ibm.com/user/45002/files/7fba06f8-1044-11e9-844c-5bce80d71f33)

**Comment by assiroud** [comment]
Looking good on the Demo site.

**Comment by EddieLi** [comment]
i will close, thanks!
