### ISSUE TITLE
[Bug]: Line chart is not working in  Combo chart ( "Line + Simple bar" chart )

### ISSUE THREAD

**Issue by Raviibmgithub** [carbon-design-system/carbon-charts#1488]
### Contact Details

ravishankar.p0507@gmail.com

### What happened?

Line chart is not working in Line + Simple bar chart. I used same code and exact version for carbon-chart, d3.js from the codesandbox: https://codesandbox.io/s/rijbih?file=/src/index.js:313-356

In _codesandbox it's working, but not in my local_ codebase with same code. I have attached all screenshot and source code of my local react code below.

**Finding: While inspecting the codesanbox output, the svg for line chart is created, but in my local the svg and class names are not added**

### Screenshot of local code output:
![image](https://user-images.githubusercontent.com/29069415/212812562-ead06398-12e1-4c52-be29-5a5e5d19fe67.png)

### Screenshot of codesandbox:
![image](https://user-images.githubusercontent.com/29069415/212813841-9eb04380-54e6-481f-9d6b-8e22d6556706.png)

### Screenshot of local:
![image](https://user-images.githubusercontent.com/29069415/212814242-efcd9d45-0631-458a-ab7e-b5596cb0bb84.png)

### Version

![image](https://user-images.githubusercontent.com/29069415/212813041-5672a113-d36a-4069-bced-6f7253f20bc5.png)

### Data & options used

```js
import React, { useState } from 'react'
import { ComboChart } from "@carbon/charts-react";
import "@carbon/charts/styles.css";

const mockData = [
	{
		"group": "School A",
		"date": "Monday",
		"value": 10000
	},
	{
		"group": "School A",
		"date": "Tuesday",
		"value": 65000
	},
	{
		"group": "School A",
		"date": "Wednesday",
		"value": 30000
	},
	{
		"group": "School A",
		"date": "Thursday",
		"value": 49213
	},
	{
		"group": "School A",
		"date": "Friday",
		"value": 49213
	},
	{
		"group": "Temperature",
		"date": "Monday",
		"temp": 70
	},
	{
		"group": "Temperature",
		"date": "Tuesday",
		"temp": 75
	},
	{
		"group": "Temperature",
		"date": "Wednesday",
		"temp": 31
	},
	{
		"group": "Temperature",
		"date": "Thursday",
		"temp": 31
	},
	{
		"group": "Temperature",
		"date": "Friday",
		"temp": 43
	}
];
const options = {
	"title": "Combo (Line + Simple bar) - custom configs",
	"axes": {
		"left": {
			"mapsTo": "value",
			"scaleType": "linear",
			"title": "USA Summer School Attendance"
		},
		"right": {
			"mapsTo": "temp",
			"scaleType": "linear",
			"title": "Temperature (°F)",
			"correspondingDatasets": [
				"Temperature"
			]
		},
		"bottom": {
			"title": "Day of the Week",
			"mapsTo": "date",
			"scaleType": "labels"
		}
	},
	"comboChartTypes": [
		{
			"type": "simple-bar",
			"correspondingDatasets": [
				"School A"
			]
		},
		{
			"type": "line",
			"options": {
				"points": {
					"radius": 5
				}
			},
			"correspondingDatasets": [
				"Temperature"
			]
		}
	],
	"height": "400px"
};

function ChartPage() {

  const [data,] = useState(mockData);
  return (<>
      <AppSideHeader />
      <Content className="chart-page">
        <Grid condensed fullWidth>          
          <Row>
            <Column>
              	{/* <StackedBarChart
                  data={data}
                  options={options}>
            	</StackedBarChart> */}
				<ComboChart
					data={data}
					options={options}>
				</ComboChart>
              </Column>
          </Row>
        </Grid>
	  </Content>
	  
    </>
  )
}

export default ChartPage;
```

### Codesandbox example

https://codesandbox.io/s/rijbih

**Comment by theiliad** [comment]
Hi, running the exact same code locally, I'm able to see the proper results generated (image below)
<img width="846" alt="image" src="https://user-images.githubusercontent.com/14989804/213242595-af1a3f1f-9404-4512-bd20-db9483db3c20.png">

I believe that this is related to an error in your application, could you pls try this in an empty project?

There could be a number of reasons for these kinds of errors in libraries... Are you seeing any errors in the console?

**Comment by theiliad** [comment]
1 thing I noticed @Raviibmgithub is that styles aren't properly being applied in your application (e.g. these buttons aren't properly styled)

<img width="96" alt="image" src="https://user-images.githubusercontent.com/14989804/213243699-6d98bae0-dd55-4413-a119-3ec31be9f5ae.png">

Not sure if that'd cause this issue

**Comment by Raviibmgithub** [comment]
@theiliad thank you. As you said, separately it works but when we try to implement in the existing project source code... only line part is missing in the graph... not sure why styles are not applying...still we are investigating. thanks

**Comment by Raviibmgithub** [comment]
No error in console @theiliad

**Comment by ManjuBelwal** [comment]
> @theiliad thank you. As you said, separately it works but when we try to implement in the existing project source code, only line part is missing in the graph... not sure why styles are not applying...still we are investigating. thanks



> 



> 1 thing I noticed @Raviibmgithub is that styles aren't properly being applied in your application (e.g. these buttons aren't properly styled)
> 
> <img alt="image" width="96" src="https://user-images.githubusercontent.com/14989804/213243699-6d98bae0-dd55-4413-a119-3ec31be9f5ae.png">
> 
> Not sure if that'd cause this issue

@theiliad : Tool buttons are not displaying properly as plex is not included.
And it not causing the issue in displaying of lines in graph.
Still debugging the code.

**Comment by theiliad** [comment]
@ManjuBelwal buttons not being styled shouldn't be related to Plex, and rather the Carbon styles missing

**Comment by Raviibmgithub** [comment]
@theiliad this is the error while building the app 
![image](https://user-images.githubusercontent.com/29069415/213610322-7abe6c12-0165-4d4d-94ea-8a445b174215.png)

**package.json**

`  "dependencies": {
    "@carbon/charts": "^1.6.3",
    "@carbon/charts-react": "^1.6.3",
    "d3": "^7.8.1",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.0.1",
    "@cloudant/cloudant": "^4.3.0",
    "body-parser": "^1.19.0",
    "carbon-components": "^10.15.0",
    "carbon-components-react": "^7.15.0",
    "carbon-icons": "^7.0.7",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.18.1",
    "express-session": "^1.17.1",
    "helmet": "^4.6.0",
    "html-react-parser": "^0.13.0",
    "i18next": "^19.7.0",
    "i18next-browser-languagedetector": "^6.0.1",
    "i18next-xhr-backend": "^3.2.2",
    "ibmcloud-appid": "^6.1.1",
    "lodash": "^4.17.19",
    "log4js": "^6.3.0",
    "moment": "^2.27.0",
    "multer": "^1.4.2",
    "passport": "^0.4.1",
    "passport-openidconnect": "0.0.2",
    "react-csv": "^2.0.3",
    "react-i18next": "^11.7.2",
    "react-idle-timer": "^4.3.7",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5",
    "request": "^2.88.2",
    "request-promise": "^4.2.6",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.4",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.11.5",
    "@babel/preset-env": "^7.10.4",
    "@babel/preset-react": "^7.18.6",
    "babel-loader": "^8.1.0",
    "babel-runtime": "^6.26.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.6.0",
    "file-loader": "^6.0.0",
    "html-webpack-plugin": "^4.3.0",
    "lodash-webpack-plugin": "^0.11.5",
    "node-forge": "^0.10.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.2",
    "style-loader": "^1.2.1",
    "url-loader": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^4.2.2"
  }`
@ManjuBelwal 


**code** 

`import React, { useState } from 'react'
import AppSideHeader from '../../components/AppSideHeader';
import { Content } from "carbon-components-react/lib/components/UIShell";
import { Column, Grid, Row } from 'carbon-components-react';
// import { StackedBarChart } from "@carbon/charts-react";
import { ComboChart } from "@carbon/charts-react";
import "@carbon/charts/styles.css";

const mockData = [
	{
		"group": "School A",
		"date": "Monday",
		"value": 10000
	},
	{
		"group": "School A",
		"date": "Tuesday",
		"value": 65000
	},
	{
		"group": "School A",
		"date": "Wednesday",
		"value": 30000
	},
	{
		"group": "School A",
		"date": "Thursday",
		"value": 49213
	},
	{
		"group": "School A",
		"date": "Friday",
		"value": 49213
	},
	{
		"group": "Temperature",
		"date": "Monday",
		"temp": 70
	},
	{
		"group": "Temperature",
		"date": "Tuesday",
		"temp": 75
	},
	{
		"group": "Temperature",
		"date": "Wednesday",
		"temp": 31
	},
	{
		"group": "Temperature",
		"date": "Thursday",
		"temp": 31
	},
	{
		"group": "Temperature",
		"date": "Friday",
		"temp": 43
	}
];
const options = {
	"title": "Combo (Line + Simple bar) - custom configs",
	"axes": {
		"left": {
			"mapsTo": "value",
			"scaleType": "linear",
			"title": "USA Summer School Attendance"
		},
		"right": {
			"mapsTo": "temp",
			"scaleType": "linear",
			"title": "Temperature (°F)",
			"correspondingDatasets": [
				"Temperature"
			]
		},
		"bottom": {
			"title": "Day of the Week",
			"mapsTo": "date",
			"scaleType": "labels"
		}
	},
	"comboChartTypes": [
		{
			"type": "simple-bar",
			"correspondingDatasets": [
				"School A"
			]
		},
		{
			"type": "line",
			"options": {
				"points": {
					"radius": 5
				}
			},
			"correspondingDatasets": [
				"Temperature"
			]
		}
	],
	"height": "400px"
};

function ChartPage() {

  const [data,] = useState(mockData);
  return (<>
      <AppSideHeader />
      <div className="chart-page">
        <Grid condensed fullWidth>          
          <Row>
            <Column>
              	{/* <StackedBarChart
                  data={data}
                  options={options}>
            	</StackedBarChart> */}
				<ComboChart
					data={data}
					options={options}>
				</ComboChart>
              </Column>
          </Row>
        </Grid>
	  </div>
	  
    </>
  )
}

export default ChartPage;`

**Comment by Gaya3G** [comment]
[chart-no-line.zip](https://github.com/carbon-design-system/carbon-charts/files/10466382/chart-no-line.zip)
@theiliad  This is a sample project created with webpack and babel configs which are in our project. There's only one chart module in it. Able to reproduce the issue. Line isn't getting rendered. Could you please let us know what needs to be changed in webpack.config.common.js where loaders are in or any other?
