### ISSUE TITLE
Tooltip font size

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#149]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3
### Issue description
**Expected:** Font size on tooltip can be adjusted to look the same on bar and pie charts. On the workspaces screen where bar and pie charts appear side by side font on legends expected to be of a same size.
**Observed:** Font size on chart tooltips doesn't match (font size is bigger on pie chart , smaller on bar chart)
![image](https://media.github.ibm.com/user/45002/files/9392aa4a-1044-11e9-892a-5349bb42e758)

**Comment by assiroud** [comment]
On the chart demo site Pie tooltip styling is different from Bar chart one. On our workspaces screen (screenshot above) these charts appear side by side and for that reason chart legends are expected to have identical styling. @cal-smith Can bar chart tooltip styling be applied to pie?

<img width="792" alt="image" src="https://user-images.githubusercontent.com/24441071/51335262-a38a5000-1a4f-11e9-91b7-d7aba8e3997f.png">

**Comment by cal-smith** [comment]
I'm not sure ... I'll defer to @theiliad, @nicoleroppel, and @dianatran18 for this one 👍

**Comment by theiliad** [comment]
This is a design choice. @dianatran18 @nicoleroppel We can release a mode that can make the Pie tooltip match the bar tooltip. Would that be ideal design wise?

**Comment by theiliad** [comment]
Yes we can do that. Great thanks 👍
