### ISSUE TITLE
[AreaChart]: How to set min axis value (to 0)?

### ISSUE THREAD

**Issue by AlexandrDobrovolskiy** [carbon-design-system/carbon-charts#1496]
### Question

I need not display negative values even if all values on the chart are 0. Is there a way to do it? 

![telegram-cloud-photo-size-2-5440835318006793030-y](https://user-images.githubusercontent.com/23122290/219653344-55753eb6-dfc9-4bde-9c1c-cf20c91ef254.jpg)

**Comment by AlexandrDobrovolskiy** [comment]
In other words, the line with all 0 values should always be at the bottom, not in the middle

**Comment by AlexandrDobrovolskiy** [comment]
The only way I found to do this is to set bounds and disable bound with CSS

**Comment by theiliad** [comment]
Hi,
Sorry for the delay. This can be achieved by doing

```js
"axes": {
    "left": {
      "domain": [0, 1],
      "ticks": {
          "values": [0, 1]
      }
    }
}
```

or if you'd like to hide the `1` as well

```js
"axes": {
    "left": {
      "domain": [0, 1],
      "ticks": {
          "values": [0]
      }
    }
}
```
