### ISSUE TITLE
Line chart - single continuous plot instead of points

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#150]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3
### Issue description
graph needs to have 30 plot points to indicate last 30 days (below does not indicate 30days, but hopefully illustrates the point). We need a single continuous plot instead of points.
![a](https://media.github.ibm.com/user/96977/files/7fd0a266-1a88-11e9-94e5-f3ab7a4331e3)

This is what is desired:
![b](https://media.github.ibm.com/user/96977/files/41307b8e-1a89-11e9-8d0c-95fde5d4fdb2)

**Comment by theiliad** [comment]
Can you please show some sample data you'd provide to that sort of chart? Thanks

**Comment by theiliad** [comment]
@EddieLi?

**Comment by EddieLi** [comment]
```javascript
{
  "labels": [
    "12 am",
    "1 am",
    "2 am",
    "3 am",
    "4 am",
    "5 am",
    "6 am",
    "7 am",
    "8 am",
    "9 am",
    "10 am",
    "11 am",
    "12 pm",
    "1 pm",
    "2 pm",
    "3 pm",
    "4 pm",
"12 am",
    "1 am",
    "2 am",
    "3 am",
    "4 am",
    "5 am",
    "6 am",
    "7 am",
    "8 am",
    "9 am",
    "10 am",
    "11 am",
    "12 pm",
    "1 pm",
    "2 pm",
    "3 pm",
    "4 pm"
  ],
  "datasets": [
    {
      "label": "Capacity",
      "backgroundColors": [
        "#81B532"
      ],
      "data": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    {
      "label": "Fulfilled",
      "backgroundColors": [
        "#FE8500"
      ],
      "data": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    {
      "label": "Sent to node",
      "backgroundColors": [
        "#4178BE"
      ],
      "data": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  ]
}```

**Comment by nicoleroppel** [comment]
@theiliad Design doesn't want to remove the nodes from this because we also have spark lines that aren't interactive that look like this. I'll post an updated spec tomorrow that will address this particular concern.

Thanks!

**Comment by nicoleroppel** [comment]
@theiliad Hi! We'd like to do something like this:

When you have a lot of data points on the chart, decrease the size of the nodes to 5px, 1px border. 

<img width="688" alt="screen shot 2019-01-29 at 10 54 45 am" src="https://user-images.githubusercontent.com/43546639/51920993-7ecd9b00-23b4-11e9-869e-46676c3ad19f.png">

When you hover over the node, it increases to the 10px default size, plus has the same glow-like hover state.

<img width="681" alt="screen shot 2019-01-29 at 10 54 50 am" src="https://user-images.githubusercontent.com/43546639/51921043-9d339680-23b4-11e9-88f2-8653d4c6529b.png">


To determine when you would switch down to the 5px nodes vs the 10px, we were wondering if we could use something similar to what Michelle wrote for the labels. I'm not saying it needs to be this exactly, I know that this is telling you when to drop labels, but is something like this doable for determining node size?

<img width="1066" alt="screen shot 2019-01-29 at 10 53 59 am" src="https://user-images.githubusercontent.com/43546639/51921091-be948280-23b4-11e9-9b2f-b3375cfb620a.png">

Thanks!

**Comment by theiliad** [comment]
This will be configurable through options, and for smaller sizes we will switch to filled circles
![image](https://user-images.githubusercontent.com/14989804/52429802-cb128c80-2ad2-11e9-93ca-1b43ffb04b73.png)
