### ISSUE TITLE
[Bug]: The chart is rendered twice on React 18 with StrictMode enabled

### ISSUE THREAD

**Issue by dhenneke** [carbon-design-system/carbon-charts#1500]
### What happened?

https://github.com/carbon-design-system/carbon-charts/pull/1364 added a fix for https://github.com/carbon-design-system/carbon-charts/issues/1357 so the charts are rendered correctly with React 18. However, I still get this rendering:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/720821/221658730-6ade015b-c7b6-4412-85d0-a2a5fcd3cae8.png">

---

This might be the issue:

https://github.com/carbon-design-system/carbon-charts/blob/0b41e0ec27709127788ba3ef3a3f45e0b9b53ba4/packages/react/src/utils.ts#L1

<img width="295" alt="image" src="https://user-images.githubusercontent.com/720821/221659050-2cbe031e-a86c-427d-aea9-077c86c7884d.png">

Doesn't this library use `cds` as a prefix?

### Version

`@carbon/charts-react@^1.6.3`

**Comment by theiliad** [comment]
> https://github.com/carbon-design-system/carbon-charts/blob/0b41e0ec27709127788ba3ef3a3f45e0b9b53ba4/packages/react/src/utils.ts#L1

ouu great catch!

just made a PR for it

**Comment by dhenneke** [comment]
Thanks for the quick fix 🥳
