### ISSUE TITLE
Make lodash includes tree-shaking friendly

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon-charts#1507]
### Summary

@carbon/charts ostensibly uses lodash-es to enable tree shaking.

However, it sabotages itself in tools.js, which pulls in all (or a lot) of lodash-es regardless of whether or not it's being used, via this code:

```js
export var Tools;
(function (Tools) {
    // Export these functions from lodash
    Tools.debounce = lodashDebounce;
    Tools.clone = lodashCloneDeep;
    Tools.merge = lodashMerge;
    Tools.unionBy = lodashUnionBy;
    Tools.removeArrayDuplicates = lodashUnique;
    Tools.clamp = lodashClamp;
    Tools.flatten = lodashFlatten;
    Tools.groupBy = lodashGroupBy;
    Tools.camelCase = lodashCamelCase;
    Tools.isEmpty = lodashIsEmpty;
    Tools.isEqual = lodashIsEqual;
    Tools.flatMapDeep = lodashFlatMapDeep;
    Tools.kebabCase = lodashKebabCase;
    Tools.fromPairs = lodashFromPairs;
    Tools.some = lodashSome;
```

That breaks tree shaking, at least in Rollup, even with the configuration `treeshake: "smallest"`.

I suggest you stop re-exporting lodash methods from the tools module and instead make the other modules directly import the lodash functions that they use.

Admittedly, your tools.ts file seems tree-shaking friendly:

```ts
// Functions
export namespace Tools {
	// Export these functions from lodash
	export const debounce = lodashDebounce;
	export const clone = lodashCloneDeep;
	export const merge = lodashMerge;
	export const unionBy = lodashUnionBy;
...
```

But the problem is that when you install from NPM, the above code has been transpiled into the tree-shaking *un*friendly:

```js
export var Tools;
(function (Tools) {
    // Export these functions from lodash
    Tools.debounce = lodashDebounce;
    Tools.clone = lodashCloneDeep;
    Tools.merge = lodashMerge;
    Tools.unionBy = lodashUnionBy;
...
```

And the situation is exacerbated when code like dom-utils.ts pulls in everything from Tools instead of just the functions it needs:

```js
import { Tools } from '../../tools';
...
const chartsprefix = Tools.getProperty(options, 'style', 'prefix');
```

So my other suggestion is to get rid of that

```js
export namespace Tools { ... }
```

wrapper around tools.ts' exports.   Can't it just export its methods directly?

### Justification

Big downloads make web apps sluggish.

### Desired UX and success metrics

Only include the parts of lodash that you are actually using.

### Available extra resources

I can certainly review the change, maybe could help with implementing it if you want.

**Comment by nstuyvesant** [comment]
Hi @wkeese - this was part of the 1.9.0 release. Can you please check the latest (currently 1.11.8) and close this issue if everything looks good to you.

**Comment by wkeese** [comment]
Thanks for merging my PR.  That made things better.  It's still weird (as I mentioned above) that Tools.ts re-exports the methods from lodash:

```
// lodash-es functions to export
export {
	debounce,
	merge,
	unionBy,
	clamp,
	flatten,
	groupBy,
	camelCase,
	isEmpty,
	isEqual,
	flatMapDeep,
	kebabCase,
	fromPairs,
	some
}
export const clone = cloneDeep
export const removeArrayDuplicates = uniq
```

So I made another PR #1617.
