### ISSUE TITLE
[Enhancement]: Support for Angular Ivy View Engine in Carbon Charts Angular

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1508]
### Contact Details

nstuyvesant@gmail.com

### Summary

Today, Carbon Charts Angular uses Renderer2 which was released with Angular 4. That rendering pipeline goes through 4 steps:
1. Template HTML
2. Template Data
3. Angular Interpreter
4. DOM

As of Angular 9 (we're now on 15.2.1), Ivy was introduced to speed up rendering. It now reduces one of the rendering steps to:
1. Template HTML
2. Template Instructions
3. DOM

Here's a helpful article on the change: https://browserperson.medium.com/from-view-engine-to-ivy-rendering-in-angular-a81d9eb8199b.

This would also suppress the warning when doing a build in Angular...

> Generating browser application bundles (phase: setup)...
> Processing legacy "View Engine" libraries:
> - @carbon/charts-angular [es2015/esm2015] (git@github.com:carbon-design-system/carbon-charts.git)
> Encourage the library authors to publish an Ivy distribution.

The caveat is that Carbon Charts Angular would need to upgrade from Angular 7.3.9 to at least 9 (there are benefits to moving up to 15.2) but it probably means dropping support for Angular 6, 7 and 8.

### Justification

1. Smaller bundle sizes: Ivy provides a more efficient and optimized template compiler, resulting in smaller bundle sizes and faster load times for your application.
2. Improved performance: Ivy generates more optimized and streamlined code, resulting in faster rendering and better overall performance of your application.
3. Improved debugging: Ivy provides better error messages and debugging support, making it easier to diagnose and fix issues in your code.
4. Better template type checking: Ivy provides improved type checking for templates, resulting in fewer runtime errors and improved code reliability.
5. Improved build times: Ivy supports incremental compilation, which means that it only recompiles the parts of your code that have changed, resulting in faster build times for your application.
6. Better tree shaking: Ivy is designed to be more compatible with tree shaking, resulting in smaller bundle sizes and faster load times for your application.

### Desired UX and success metrics

The UX would be unchanged other than faster loading through smaller bundles and faster rendering.

### "Must have" functionality

Support for Ivy.

### Specific timeline issues / requests

Carbon Charts Angular works well today even with the latest version of Angular. But there are load and performance benefits by upgrading to a newer version.

### Available extra resources

Can submit PRs but there would need to be a commitment to moving to a newer version of Angular first (and dropping support for Angular < 9).

**Comment by theiliad** [comment]
Hi @nstuyvesant, great topic for a discussion, thank you for starting this 🙂 

Couple of pointers:
1. I'm not sure that the type of the rendering engine we use would result in a significant improvement in our performance. The angular wrappers merely get the vanilla engine to start rendering a chart.
2. I've tried numerous times to update our angular process, however, due to my lack of recent experience with angular 4+ (which is about when I stopped using angular), it's always failed. I also believe that Lerna & Storybook have got something to do with the issues that I've been facing.

Having said that, I'm open to dropping support for outdated versions and moving on, specially since it seems like our `angular` package is the only reason that our build process still pulls in `node-sass`, which is not great...

**Comment by theiliad** [comment]
To add to the above, I think we should probably jump to v2.0 with this kind of a change. We could tally up a couple of PRs that involve breaking changes, and merge all at once.

**Comment by theiliad** [comment]
A HUGE bonus if this results in a storybook update as well 😄 Because of Lerna I haven't been able to update storybook due to the fact that things clash with the angular package once other packages are using a different version of it

**Comment by nstuyvesant** [comment]
Yeah, the old version of Lerna created challenges for me as well (because I use Python 3.11 and the old sub-dependency of node-gyp tries passing a parameter `-rU` and the `U` is deprecated in Python 3.11.

Also ran into build problems due to @vue/cli-plugin-babel relying on @achrinza/node-ipc@9.2.6 which only supported up to node 17.

I'll install an old version of node and Python to create a build then see what's what.

**Comment by nstuyvesant** [comment]
Just switched to Python 3.9 and Node 16.19.1. Was able to complete the `yarn install` but getting errors doing a `yarn build` in the react package after changing some versions in the angular package. So I bumped typescript in the react package to match what I put for angular and that seemed to resolve it. I'll submit a PR but we'll need to do a lot of testing.

**Comment by nstuyvesant** [comment]
Spent some time on this today. If it weren't for Storybook and Lerna, I could submit the PR for an updated charts-angular library.

In the course of looking at it, found similar limitations on @carbon/icons-angular. Submitted a PR for that to loosen the peer dependency versions so modern Angular is allowed. That might be a good, small library to start with to support Ivy.

**Comment by nstuyvesant** [comment]
Food for thought... to support Ivy, [per this article](https://angular.io/guide/creating-libraries#publishing-libraries), the oldest version with partial Ivy support is Angular 12.

And according to https://angular.io/guide/releases, Angular 13 LTS ends 2023-05-04 - pretty soon.

How OK would you be with the 2.x release of @carbon/charts-angular only supporting a minimum of Angular 14? Its LTS ends this November.

**Comment by theiliad** [comment]
We can speak to our carbon angular folks to see how they're supporting angular 12+
https://github.com/carbon-design-system/carbon-components-angular#support

Not sure if they're using Ivy or not

**Comment by nstuyvesant** [comment]
Looking at two of the most popular libraries for Angular - Angular Materials and ng-bootstrap, they appear to put out a release of their own package per major Angular release ([for example](https://github.com/ng-bootstrap/ng-bootstrap#dependencies) in order to keep the peer dependencies very narrow like this...
```json
  "peerDependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/localize": "^15.0.0",
    "@popperjs/core": "^2.11.6",
    "rxjs": "^6.5.3 || ^7.4.0"
  }
```

Might even make sense for Carbon Charts 2.x to target Angular 14.

**Comment by nstuyvesant** [comment]
BTW, looked over carbon-icons-angular. It is unusual for an Angular library in that it doesn't use the [project structure](https://angular.io/guide/file-structure#library-project-files) the Angular CLI normally sets up for generating bundles - very much a roll-your-own configuration. Would be time-consuming for an outside contributor to become familiar with this structure. The @carbon/charts-angular library is much closer to the standard though a little different.

**Comment by flomller** [comment]
Hi, a little heads up: 

As of Angular 16, the ngcc (Angular Compatibility Compiler) was removed. This results in View Engine Libraries no longer beeing usable in Angular 16+. 

https://angular.io/guide/update-to-version-16#angular-compatibility-compiler-ngcc-has-been-removed

This means for our usecase, we can no longer use any carbon-charts. Any plans on migrating to any version that would support compiling to Ivy?

**Comment by nstuyvesant** [comment]
Angular 16 is now supported in `@carbon/charts-angular@next`.
