### ISSUE TITLE
Line chart - threshold indication

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/carbon-charts#152]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description 
A line parallel to x-axis drawn from a y-axis value to indicate a threshold, its color should be the color provided by user. Green line on the screenshot below.

### Screenshot or recording
![image](https://user-images.githubusercontent.com/24441071/51341069-7beeb400-1a5e-11e9-8d95-0fb17ebcc06a.png)

**Comment by theiliad** [comment]
@dianatran18 @nicoleroppel?

**Comment by nicoleroppel** [comment]
@theiliad we do want this! Just working on a spec (plus getting a few details about the colour requirements). 

Thanks!

**Comment by theiliad** [comment]
Ok. Please post updates here @nicoleroppel once available.

**Comment by assiroud** [comment]
@nimit-chauhan How important is that the threshold color would be provided by a user? Can we set a default color for this?

**Comment by theiliad** [comment]
Just to give you some context @assiroud, thresholds are already working in charts (refer to demo site), but are in the form of blocks, rather than lines.

**Comment by nicoleroppel** [comment]
No need to work on this. The design team was unaware of the colour blocking version of thresholds that was already available. We will move forward with that version.

Thanks!

**Comment by trsiddiqui** [comment]
Can someone please provide an example for threasholdRegions. I was not able to get any examples from the documentation. Thanks.
