### ISSUE TITLE
[Bug]: Column mismatch in AlluvialChart

### ISSUE THREAD

**Issue by NoorHajDawood** [carbon-design-system/carbon-charts#1535]
### Name

Noor Haj Dawood

### Are you an IBM employee?

- [ ] Yes

### What happened?

When using AlluvialChart, if the number of nodes is large, the data gets disorganized, where a certain node from a certain category shows up in the wrong column. As well as a certain community can override the title of a different one:
for example in this picture, the categories are "Day 1" - "Day 4", but when the data is large enough, Day 3 overwrites Day 1, and Day 4 overwrote Days 2 + 3
also you can see where one of nodes shows up in the wrong column.
This does not happen when limiting the data and working with a smaller sample
![image](https://user-images.githubusercontent.com/57665132/227796715-85ad90b7-8513-4a76-ade7-3fafa3e3796a.png)

### Version

v1.6.14

### What priority level would this be in your opinion?

P3

**Comment by theiliad** [comment]
Hi, this doesn't look like our (carbon) alluvial chart component. Are you using `@carbon/charts`? I will close for now, but pls feel free to reply with additional details & we can reopen 🙂 

Also would massively help if you could reproduce in stackblitz
