### ISSUE TITLE
[Bug] Build Error: Module not found: Error: Can't resolve 'dom-to-image-more'

### ISSUE THREAD

**Issue by SanjayKumarBaraiya** [carbon-design-system/carbon-charts#1546]
Hi Team,

Recently, We started getting below error while build angular project (npm run build) with @carbon\charts v1.7.1
 ./node_modules/@carbon/charts/services/essentials/dom-utils.js:30:0-43 - Error: Module not found: Error: Can't resolve 'dom-to-image-more' in <ProjectPath>\node_modules\@carbon\charts\services\essentials'

Module : @carbon\Charts
Version : 1.7.1

Note : This was working fine till 20th April, 2023

**Comment by huineng** [comment]
same, reverted back to @carbon/charts@1.7.0 
not sure what the discussion is here in https://github.com/carbon-design-system/carbon-charts/pull/1540

I'm using webpack

so i tried with adding it to externals , but that didn't work, got this message on the ui

```
ReferenceError: dom is not defined\nReferenceError: dom is not defined
```

**Comment by theiliad** [comment]
@nstuyvesant shouldn't `dom-to-image-more` just be a dep rather than a dev dep? https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json#L90

**Comment by huineng** [comment]
i see your latest merge 1.7.3 fixed the issue.

**Comment by nstuyvesant** [comment]
dom-to-image-more@3.1.5 was also released (had my PR to fix the issue with Node undefined).

**Comment by theiliad** [comment]
Closing => #1547
