### ISSUE TITLE
[Enhancement]: When exporting data as CSV, filenames should be customizable as an option parameter

### ISSUE THREAD

**Issue by nemeseri-ibm** [carbon-design-system/carbon-charts#1550]
### Name

Andras Nemeseri

### Are you an IBM employee?

- [X] Yes

### Summary

When the user clicks any export options, the downloaded file name is a random id. It would be a great enhancement if we could add a filename or a filename pattern as an option to control the name of the downloaded file.

### Justification

This would provide a better user experience since it would be easier to find the downloaded data in a folder and would be easier to tell which file belongs to which chart.

### Desired UX and success metrics

When users click the "more" toolbar button, they are presented with file format options: i.e. "Export as CSV". When users click this menu item, a file is generated with a random filename and downloaded by the browser.

Downloading multiple data sets through the charts ends up with many files without a meaningful name in the user's download folder, making it hard to differentiate between them.

As carbon chart users, we should have the option to set the filename.

### "Must have" functionality

An optional filename property in the options JSON should work as a solution to the problem presented above.

### Specific timeline issues / requests

No timeline is requested.

### Available extra resources

We are looking into when we can provide assistance to create a pull request to implement this feature.

### What priority level would this issue be in your opinion?

P0

**Comment by theiliad** [comment]
This has already been added https://github.com/carbon-design-system/carbon-charts/pull/1536
