### ISSUE TITLE
[Bug]: meter chart min value disappears

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#1559]
### Name

Shixie

### Are you an IBM employee?

- [X] Yes

### What happened?

Hello team! Hope you are all doing well :) 

We found this issue where the minimum value disappears when the actual value and the max value match. When the actual value is above or below the max value then the min label shows up. 

<img width="1006" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/15144993/df17ad14-276a-49be-b421-c2f4ba393384">

### Version

Latest

### Codesandbox example

https://codesandbox.io/s/condescending-microservice-trjwsl?file=/src/index.js

### What priority level would this be in your opinion?

P2

**Comment by theiliad** [comment]
Hi @shixiedesign, we don’t really show a min/max value on the meter chart. That seems like a custom component on your end, could you pls confirm?
