### ISSUE TITLE
[Bug] AreaChartOptions: Gradient colors are not applied

### ISSUE THREAD

**Issue by guillaumegarcia13** [carbon-design-system/carbon-charts#1564]
### Name

Guillaume GARCIA

### Are you an IBM employee?

- [ ] Yes

### What happened?

Even if the documentation is stating that gradient colors can be specified:
https://charts.carbondesignsystem.com/documentation/interfaces/_interfaces_charts_.areachartoptions.html#color
![image](https://github.com/carbon-design-system/carbon-charts/assets/2786038/95bee609-3104-4b9d-ab27-3076c0342a1c)

it seems to have no effet on the rendering
![image](https://github.com/carbon-design-system/carbon-charts/assets/2786038/b742e517-60eb-4cc7-b97e-8eec56290cc2)

### Version

@carbon/charts@1.6.14

### Data & options used

```js
color: {
    gradient: {
      enabled: true,
      colors: ["#ff0000", "#0000ff"]
    }
  }
```

### Codesandbox example

https://codesandbox.io/s/relaxed-haze-ukf0fb

### What priority level would this be in your opinion?

P2

**Comment by theiliad** [comment]
Hi, unfortunately sparklines aren't supposed to have 2-color gradients and are monotone. This seems like a bug in the wrong flag being exposed for that component

**Comment by fmorency** [comment]
I just got bitten by this issue as well.
