### ISSUE TITLE
[Bug]: Carbon-Chart not minimising on Safari Web Browser 

### ISSUE THREAD

**Issue by mantvydasluksas** [carbon-design-system/carbon-charts#1565]
### Name

Mantvydas Luksas

### Are you an IBM employee?

- [X] Yes

### What happened?

A carbon-chart component was used on the UI, and upon enlarging it using expansion arrows, I was unable to minimise it when clicking on the expansion arrows again. I can only minimise the chart using the escape keyboard button. This behaviour was only evident on the Safari Web Browser. 

### Version

"@carbon/charts": "1.6.14"

### What priority level would this be in your opinion?

P2

**Comment by nstuyvesant** [comment]
Hi @mantvydasluksas - if you try to maximize and minimize this chart on Safari, https://charts.carbondesignsystem.com/?path=/story/simple-charts-bar-floating--horizontal-floating-bar-time-series, what happens?

I am using Safari 16.5.1 and was able to maximize and minimize using the buttons. This example is based on @carbon/charts 1.10.5.

**Comment by theiliad** [comment]
I've also tested on `16.4` and am able to properly maximize & minimize. @mantvydasluksas I'm going to close for now, but pls let us know if this issue is still there, and any additional details you could provide could help us debug the issue 🙂

**Comment by mantvydas-luksas** [comment]
@nstuyvesant @theiliad Thank you for looking into this, the issue is not present anymore.
