### ISSUE TITLE
Pie chart -center label

### ISSUE THREAD

**Issue by EddieLi** [carbon-design-system/carbon-charts#157]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.8.3
### Issue description
We need to display a label inside the donut chart.
<img width="203" alt="screen shot 2019-01-18 at 2 28 28 pm" src="https://user-images.githubusercontent.com/3457217/51408623-5f6d7d00-1b2d-11e9-8d3f-cfdefdc39c3b.png">

**Comment by theiliad** [comment]
Hi @EddieLi.

**This functionality exists in the library:** https://carbon-design-system.github.io/carbon-charts

**And here's how to use it:** https://github.com/carbon-design-system/carbon-charts/blob/6e3c16066a2a3b91275c75f564aabe04b733812a/packages/core/demo/demo-data/pie-donut.ts#L15

**Comment by EddieLi** [comment]
@theiliad this only enable us to change the label but not the number above the label right?

we need to change both the number and label below in the center of the donut chart. 

Is this supported?

**Comment by theiliad** [comment]
Currently the number shows the total value of your datapoints.

Please create an issue if you'd like support for custom center updates
