### ISSUE TITLE
[Bug]: CSS not being imported correctly

### ISSUE THREAD

**Issue by AlvinChacko** [carbon-design-system/carbon-charts#1572]
### Name

Alvin

### Are you an IBM employee?

- [X] Yes

### What happened?

Im seeing a lot of 'Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide.' in my production logs. This is for an angular app and I tried importing the css file and the scss file.

Importing the CSS file `@import "node_modules/@carbon/charts/styles.css"` give me the error above.

When I import the scss file here: `@import "node_modules/@carbon/charts/styles/styles";` it throws the following errors:
```
SassError: Undefined variable.
   ╷
32 │ $white: map.merge(themes.$white, compat.$white);
   │                   ^^^^^^^^^^^^^
   ╵
  node_modules/@carbon/styles/scss/compat/_themes.scss 32:19  @use
  node_modules/@carbon/styles/scss/theme/_theme.scss 12:1     @forward
  @carbon/styles/scss/_theme.scss 8:1                         @use
  node_modules/@carbon/charts/styles/styles.scss 10:1         @import
  src/styles.scss 17:9  
```

My full import in my scss file is:
@import 'node_modules/carbon-components/scss/globals/scss/styles';
@import 'node_modules/carbon-components/scss/globals/scss/vendor/@carbon/type/scss/font-family';
@import 'node_modules/carbon-components/scss/globals/scss/typography';
@import 'node_modules/@carbon/themes/scss/themes';
@import "node_modules/@carbon/charts/styles.css";

### Version

    "@carbon/charts": "^1.8.0",
    "@carbon/charts-angular": "^1.8.0",
    "@carbon/icons-angular": "^11.2.2",
    "@carbon/themes": "^10.50.0",
    "carbon-components": "^10.52.0",
    "d3": "^7.8.5",

### What priority level would this be in your opinion?

P0

**Comment by nstuyvesant** [comment]
Two separate items...
1. There is a known issue in 1.8.0 where an erroneous error was logged saying styles weren't properly loaded for Carbon Charts. This was fixed in later versions; however, the later versions require Angular 16. That said, the error message about the missing styles can be ignored.
2. Regarding the error you got loading the SCSS, can you try `@use '@carbon/styles/scss/themes';` before your import?

**Comment by theiliad** [comment]
Also, might be worth trying the CSS bundle instead of Sass

**Comment by AlvinChacko** [comment]
I tried the `@use '@carbon/styles/scss/themes';` it didnt help it throws the sassError described earlier. I did try to import the css thats when I get the error `Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide.'`

**Comment by theiliad** [comment]
are the styles showing up though when importing the css bundle?

**Comment by AlvinChacko** [comment]
Yes the charts seems to be working fine. Just little annoyed at the word error showing up on consoles.

**Comment by nstuyvesant** [comment]
OK - then the CSS is working for you. It's just the console error. That error was fixed in @carbon/charts and @carbon/charts-angular 1.9.0 (now 1.10.5); however, you would have to use Angular 16 and looks like you are on 14. So you have to stay with 1.8.0 or lower.

**Comment by nstuyvesant** [comment]
@AlvinChacko - as this issue has been resolved in newer versions (and was cosmetic pre-1.9.0), please close this ticket, if you would. Thanks!

**Comment by AlvinChacko** [comment]
Sure I can take a look at if I want to bump angular for the latest version. Thanks I'll close for now.
