### ISSUE TITLE
[Bug]: themes are not working when creating a bundle.js file for angular web component

### ISSUE THREAD

**Issue by AmirHussain93** [carbon-design-system/carbon-charts#1574]
### Name

Amir Hussain

### Are you an IBM employee?

- [ ] Yes

### What happened?

A bug happened!

I am creating a web component using angular along with carbon design system for UI components and carbon charts for visualisation. When I serve my application locally  themes are working fine. But when I created a bundle.js file to use this created app as a web component in some other app **import "@carbon/charts/styles.css"**  is not working. I have added this import statement in global styles.scss file. Could you please help me with this?

There is no error while creating a bundle file. But I don't see any theme classes related to charts in the bundle.js file as well. 

### Version

@carbon/charts@1.8.0

Angular version @14.2.0

@angular/elements": "^14.3.0",

### What priority level would this be in your opinion?

P1

**Comment by nstuyvesant** [comment]
I recommend doing View Encapsulation per https://angular.io/guide/view-encapsulation#:~:text=In%20Angular%2C%20a%20component%27s%20styles,on%20a%20per%20component%20basis.

You would import @carbon/charts/styles.css and @carbon/styles in the styles property for you component or in an associated stylesUrl css or scss file.

You need @carbon/styles but unless you're careful, it can pollute the global styles of your app. Encapsulation protects you from side effects.

**Comment by theiliad** [comment]
Hi @AmirHussain93, pls let us know if @nstuyvesant's response solved your issues 🙂 If not we can reopen anytime

**Comment by AmirHussain93** [comment]
Hi @theiliad @nstuyvesant I will try this and will let you know if this works 

Thank you for the response
