### ISSUE TITLE
[Bug]: generated source map for styles.css contains invalid paths

### ISSUE THREAD

**Issue by patricklx** [carbon-design-system/carbon-charts#1575]
### Name

Patrick 

### Are you an IBM employee?

- [X] Yes

### What happened?

the source map of @carbon/charts/styles.css contains sources file mappings to e.g "..src/styles/tokens.scss", which do not exist when installed.
it should probably be "./styles/tokens.scss

### Version

1.8.0

### What priority level would this be in your opinion?

P0

**Comment by nstuyvesant** [comment]
Can you try @carbon/charts@1.10.4 and let me know if this is resolved?

**Comment by patricklx** [comment]
No, 1.10.4 was missing the styles, 1.10.5 has them, but the source map is missing.

**Comment by nstuyvesant** [comment]
@patricklx - just adjusted the build script to add the CC source maps to the package root in a [PR that needs to be merged](https://github.com/carbon-design-system/carbon-charts/pull/1598).

Out of curiosity, what are you using for your project's bundler? In theory, it should use the exports in the package.json for `@carbon/charts` that map "./styles.min.css" to "./dist/styles.min.css". The maps are also in the dist directory.

**Comment by patricklx** [comment]
It's an ember project. It uses broccoli build pipeline mainly. 
I didn't test with the webpack version. 
I was importing the non-minifies file directly in my scss files. So the exports where just ignored... .

**Comment by nstuyvesant** [comment]
@patricklx - are you able to try out `@carbon/charts` 1.10.5? Would like to verify this works with your environment.

How does ember/broccoli process `@import '@carbon/charts/styles.css';` in an SCSS file? You mentioned webpack above. If so, which version of webpack (and style-loader) are you using?

Personally, I use vite because it's fast and handles all the file types I have (.ts, .js, .scss, etc.) and is great as a dev server with hot module reloading. This might be of interest to you... https://github.com/lifeart/demo-ember-vite.

Vite also respects the exports from the package.json.

**Comment by patricklx** [comment]
Probably ember-cli ignored the exports for the sass file.
It was importing it, but failed to process the source maps. 
ember cli process them all into one file with https://github.com/ef4/fast-sourcemap-concat
 Which failed because of the invalid paths it had before.

**Comment by patricklx** [comment]
I'll try it out tomorrow

**Comment by patricklx** [comment]
The import was okay also in 1.8.0. only processing source map failed. Because it contained invalid paths, which the source map concat used 
https://www.unpkg.com/browse/@carbon/charts@1.8.0/styles.css.map

**Comment by nstuyvesant** [comment]
The CSS and maps starting in `@carbon/charts` 1.90 (but use 1.10.5 or later) should not have the source map problem if you import from `node_modules/@carbon/charts/dist/styles.css`. The next release will also have the maps at the root level but if you want a quick fix, this should do it.

**Comment by nstuyvesant** [comment]
BTW, I would make sure you're using an up-to-date version of `sass` (latest is 1.63.6). There have been improvements regarding path resolution.
