### ISSUE TITLE
[Enhancement]:  ibm-simple-bar-chart modal translations

### ISSUE THREAD

**Issue by msolanon** [carbon-design-system/carbon-charts#1577]
## Detailed description

When we open the modal from ibm-simple-bar-chart component we are not able to translate this values (the ones that are in red).

We also checked the documentation and there is no way to send them as a parameter to the component 

https://charts.carbondesignsystem.com/angular/?path=/story/simple-charts-bar-simple--vertical-simple-bar-discrete

## Additional information

* <img width="744" alt="6079a311-869e-430f-b9ac-7b890b781d2f" src="https://github.com/carbon-design-system/carbon-components-angular/assets/76747996/bb9933ac-7045-483d-8e23-5d3b8ec18e3a">
* Notes

**Comment by nstuyvesant** [comment]
This is an enhancement request as it's not functionality that was ever implemented in the product. Only the dates are translated via date-fns.

@msolanon - could you please add "[Enhancement] " to the beginning of this issue's title?

**Comment by theiliad** [comment]
Yes I have these on my radar, and have added similar issues to the backlog, we should soon take care of this

**Comment by nstuyvesant** [comment]
@msolanon - does this issue (https://github.com/carbon-design-system/carbon-charts/issues/1635) address what you're running into? If so, perhaps consider closing this one so we can consolidate. Feel free to update the other issue if you'd like to see anything changed.

**Comment by msolanon** [comment]
@nstuyvesant  Looks like it does
