### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-charts#158]
We have typedoc right now, but it's a little light on details. Some of that can be addressed by better comments in the code, but a documentation solution like [readthedocs](https://readthedocs.org/) may be more useful.

Key requirements:
- must support regular API documentation
- guides/tutorials
- clear navigation and sectioning (guides should be separate from raw API docs)
- versioned automatically (a new tag should be a new docs version)

Bonus:
- embedded/interactive samples in guides (maybe we can compensate with codepen/codesandbox?)
- API docs generated from source

**Comment by theiliad** [comment]
**FYI:** we're keeping this issue around as a reminder
