### ISSUE TITLE
Support event handling on the elements of the charts in React wrapper

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#159]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
React variant of charts should support ability to event listeners.

Examples:
1. Clicking on one of the bars in Bar chart should invoke a callback method
2. Clicking on one of the slices in Donut chart should invoke a callback method

**Comment by theiliad** [comment]
**This is currently achievable using the code below:**
![image](https://user-images.githubusercontent.com/14989804/51573752-9c60a900-1e78-11e9-9976-ab0804ad3470.png)

We would in the future add support for eventListeners in the component props.

For more examples of eventListeners read this:
https://github.com/carbon-design-system/carbon-charts/blob/6e3c16066a2a3b91275c75f564aabe04b733812a/packages/core/demo/index.ts#L251-L274
