### ISSUE TITLE
Uncaught runtime errors: ERROR n is undefined

### ISSUE THREAD

**Issue by joselukeolivares** [carbon-design-system/carbon-charts#1613]
I got this error after mouse over on the legends of the charts, when I have only one group everything works right, however when I add another groups the app got this problem. The chart display all groups of data on the chart, and the mouseOver show the Tooltip with the data, the only problem is the legends of the charts.

![img1](https://github.com/carbon-design-system/carbon-charts/assets/1326667/f93aede8-760d-49e0-82cb-2a110dbf5815)

![imagen](https://github.com/carbon-design-system/carbon-charts/assets/1326667/f9719fc7-df98-4aba-9b25-caca746c6f08)
![imagen](https://github.com/carbon-design-system/carbon-charts/assets/1326667/8cf7e410-ab63-4608-b1de-d9b64d9899d0)
![imagen](https://github.com/carbon-design-system/carbon-charts/assets/1326667/2fad1806-fa7e-4a15-8dae-f42c5aac3f1b)

**Comment by nstuyvesant** [comment]
Can you create a minimal repro of your issue? In this [StackBlitz example](https://stackblitz.com/run?file=src%2Findex.js) of LineChart with `@carbon/charts-react`, I'm not seeing that issue. Perhaps you can fork it and make changes to match your environment?

**Comment by LeonardoBrandao** [comment]
I'm running into this issue as well, and from what I was able to debug it seems to be related to the label length. I can reproduce it 100% by using `small` as a label or anything that does not truncate the legend text, and it's fine, but as soon as try with `test big label that overflows` (or any big string) it throws the same error as soon as I hover over the truncated legend.

![image](https://github.com/carbon-design-system/carbon-charts/assets/15162580/0e1c3a59-d56a-4cd2-ad71-98ebebdfb9f2)

![image](https://github.com/carbon-design-system/carbon-charts/assets/15162580/0026c476-387d-4410-9107-76b05ccc5f8e)

Facing the error using the `StackedBar` component in React, btw.

npm versions:
`"@carbon/charts": "^1.11.13"`
`"@carbon/charts-react": "^1.11.13"`

**Comment by joselukeolivares** [comment]
@nstuyvesant can you check the url you share, it redirects only to the https://stackblitz.com/ page. @LeonardoBrandao  find the same issue as me.

**Comment by nstuyvesant** [comment]
Here ya go... https://stackblitz.com/edit/react-kb4tdn?file=src%2Findex.js

**Comment by joselukeolivares** [comment]
Here is another example where the error happens: [repository](https://github.com/joselukeolivares/bugcarbon)
![imagen](https://github.com/carbon-design-system/carbon-charts/assets/1326667/06b87daa-a776-4b4a-8b25-02c24aff4d09)
The application followed the tutorial steps in [Carbon Site Tutorial](https://charts.carbondesignsystem.com/?path=/docs/docs-tutorials-tabular-data-format--docs)
If the group have a large name like : "Restocking Restocking Restocking Restocking"
`const [stackedBarData, setStackedBarData] = React.useState([
    { group: "Qty", value: 65000 },
  { group: "More", value: 29123 },
  { group: "Sold", value: 35213 },
  { group: "Restocking Restocking Restocking Restocking", value: 51213 },
  { group: "Misc", value: 16932 }
  ])`

If the name is short, everything works fine:
` const [stackedBarData, setStackedBarData] = React.useState([
    { group: "Qty", value: 65000 },
  { group: "More", value: 29123 },
  { group: "Sold", value: 35213 },
  { group: "Restocking", value: 51213 },
  { group: "Misc", value: 16932 }
  ])`
![imagen](https://github.com/carbon-design-system/carbon-charts/assets/1326667/20ab0797-f6ed-42a2-90a1-e17441c941ff)

**Comment by nstuyvesant** [comment]
@joselukeolivares - My last post should be all that's needed to resolve the issue. I would even consider deleting your last post as it obscures the only needed steps to reproduce the issue and get the problem down to a particular line of code.
