### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by devlperry** [carbon-design-system/carbon-charts#1618]
### Name

failure to install via npm

### Are you an IBM employee?

- [ ] Yes

### What happened?

npm tries to run a script to install telemetry (spyware?). It fails.

![image](https://github.com/carbon-design-system/carbon-charts/assets/104520902/a2539b5a-3068-4154-9bee-3c48232201eb)

### Version

latest

### What priority level would this be in your opinion?

P0

**Comment by theiliad** [comment]
Closed by #1615
