### ISSUE TITLE
[Task]: Change latest version for @carbon/charts-vue to 1.11.0

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1625]
### Name

Nate Stuyvesant

### Are you an IBM employee?

- [ ] Yes

# Task

@theiliad - Please change the distribution tag `latest` for `@carbon/charts-vue` to 1.11.0. This is the last version with Vue 2.x support. The 1.8.0 version is missing the updated README but 1.11.0 has it.

- [x] `npm dist-tag rm @carbon/charts-vue@1.8.0 latest`
- [x] `npm dist-tag add @carbon/charts-vue@1.11.0 latest`

**Comment by theiliad** [comment]
Thanks @nstuyvesant
