### ISSUE TITLE
Bug: Overlapping Donut chart and Pie chart's values for different datasets.

### ISSUE THREAD

**Issue by inder18112000** [carbon-design-system/carbon-charts#1626]
Please resolve this issue
![image](https://github.com/carbon-design-system/carbon-charts/assets/66193782/422f8267-26d9-459d-87f6-db0433e12902)

```[tasklist]
### Tasks
```

**Comment by theiliad** [comment]
Hi, thank you for creating this issue. We usually don't recommend using pie/donut in cases where you could have too many neighbouring slices with very small values. The reasoning here is that positioning the labels in a way that fits together usually requires methods that clutter the chart.

What could be done instead is using a different chart type (e.g. a bar chart), or consolidating smaller slices into a `Other` slice

I will close the issue for now, but pls do let us know if you have further concerns, and we can re-open :)
