### ISSUE TITLE
Bar chart Legend 'expand' should be able to be hidden / disabled

### ISSUE THREAD

**Issue by asahlin** [carbon-design-system/carbon-charts#163]
I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

charts version:
0.8.6

Issue description
I have 2 bar charts side by side on a page, I only have one key in my legend, but it appears based on chart width (600px or under) the legend '+' expand is automatically shown.

Steps to produce the issue
Bar chart that is 600px or under

Current behavior
Legend expand '+' is being shown

Expected behavior
Ability to turn that feature off, or have it based on number of keys in legend & size

Screenshot or recording
![image](https://user-images.githubusercontent.com/13006634/51696526-523c0c80-1fcb-11e9-9648-b9f700b256a5.png)

**Comment by theiliad** [comment]
Good catch
