### ISSUE TITLE
[Task]: Create 1.8.0 branch so we can fix #1650

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1651]
# Task

- [x] Create a new branch called `1.8.0` based on git commit 62caeb1. This will be used for updates to `@carbon/charts-angular@1.8.0`

This is needed in order to address a 1.8.1 upgrade to charts-angular to fix https://github.com/carbon-design-system/carbon-charts/issues/1650

**Comment by theiliad** [comment]
https://github.com/carbon-design-system/carbon-charts/tree/1.8.0
