### ISSUE TITLE
[Bug]: Line Chart takes long time to render with massive data in Chrome

### ISSUE THREAD

**Issue by wangxy98** [carbon-design-system/carbon-charts#1657]
### Name

xinya

### Are you an IBM employee?

- [ ] Yes

### What happened?

When we render a line chart with 18000 records, it takes about 13s to render the chart in Chrome, and the zoom bar does not work properly, it gets stuck for several seconds. And if the records are about 130000, the browser will also get stuck. Is there any ways to make the line chart render faster and the zoom bar work normally? Thanks!
<img width="1225" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/50725856/6603b6e4-dbfe-434e-95fa-b2c10219950c">

### Version

    "@angular/animations": "15.2.8",
    "@angular/cdk": "15.2.8",
    "@angular/common": "15.2.8",
    "@angular/compiler": "15.2.8",
    "@angular/core": "15.2.8",
    "@angular/forms": "15.2.8",
    "@angular/material": "15.2.8",
    "@angular/platform-browser": "15.2.8",
    "@angular/platform-browser-dynamic": "15.2.8",
    "@angular/router": "15.2.8",
    "@carbon/colors": "^11.14.0",
    "@carbon/charts-angular": "1.8.0",
    "@carbon/charts": "1.8.0",

### Data & options used

```js
options:
export default {
  title: 'Line (time series) - Zoom bar enabled',
  axes: {
    bottom: {
      title: '2019 Annual Sales Figures',
      mapsTo: 'date',
      scaleType: 'time',
    },
    left: {
      mapsTo: 'value',
      title: 'Conversion rate',
      scaleType: 'linear',
    },
  },
  curve: 'curveMonotoneX',
  experimental: true,
  zoomBar: {
    top: {
      enabled: true,
    },
  },
  height: '400px',
  color: {
    pairing: {
      option: 2,
      numberOfVariants: 5,
    },
  },
  // timeScale: {
  //   timeIntervalFormats: {
  //     '15seconds': {
  //       primary: 'yyyy-mm-dd HH:mm:ss',
  //       secondary: 'HH:mm:ss'
  //     }
  //   }
  // },
  tooltip: {
    enabled: true,
    groupLabel: 'wwwww',
    showTotal: false,
  },
};

records are about 18000 like below, the interval of date is 10s:
export default [{"date":"2023-08-30T02:33:37.959Z","value":54,"group":"Group1"}, {"date":"2023-08-30T02:33:37.959Z","value":62,"group":"Group2"}, {"date":"2023-08-30T02:33:47.959Z","value":2,"group":"Group1"}, {"date":"2023-08-30T02:33:47.959Z","value":3,"group":"Group2"}, {"date":"2023-08-30T02:33:57.959Z","value":12,"group":"Group1"}, {"date":"2023-08-30T02:33:57.959Z","value":12,"group":"Group2"}
...]
```

### What priority level would this be in your opinion?

P0

**Comment by theiliad** [comment]
Hi, this library renders most of its charts using SVGs, which due have these kinds of limitations in comparison to canvas-based components. Unfortunately (as far as it goes in my experience) we won't be able to match that kind of performance without switching over to Canvas (which is also perceived to be less accessible in some ways)
