### ISSUE TITLE
Legend specs for appearing on right

### ISSUE THREAD

**Issue by nicoleroppel** [carbon-design-system/carbon-charts#166]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

Hi Eliad!

Just creating this issue following our conversation yesterday. We'd like to have a condensed version of the spec that allows teams to use the legend on the right when they have smaller charts in their widgets.

Attached is what we'd like to propose. Let me know if anything is unclear!

<img width="1076" alt="screen shot 2019-01-29 at 12 13 02 pm" src="https://user-images.githubusercontent.com/43546639/51926481-631bc200-23bf-11e9-801a-ca5b55e7d424.png">

<img width="1073" alt="screen shot 2019-01-29 at 12 14 27 pm" src="https://user-images.githubusercontent.com/43546639/51926505-70d14780-23bf-11e9-824c-e5eda322e686.png">

Thanks!

**Comment by theiliad** [comment]
this was added a while ago
