### ISSUE TITLE
Change chart area theme

### ISSUE THREAD

**Issue by aaaknot30** [carbon-design-system/carbon-charts#1663]
Hi - 

We are using svelte and carbon charts.  
Is there a way to change the color or theme of the chart area?  It is always white no matter the theme.

Thanks,
Kyle

**Comment by nstuyvesant** [comment]
See the options on this example: https://charts.carbondesignsystem.com/svelte/?path=/story/simple-charts-area-stacked--stacked-area-time-series

The g100 theme has a dark background (black)...
```json
{
  "title": "Stacked area (time series)",
  "axes": {
    "left": {
      "stacked": true,
      "scaleType": "linear",
      "mapsTo": "value"
    },
    "bottom": {
      "scaleType": "time",
      "mapsTo": "date"
    }
  },
  "curve": "curveMonotoneX",
  "height": "400px",
  "theme": "g100"
}
```

**Comment by aaaknot30** [comment]
Hi Nate - 
Could you double check why the StackBlitz version doesn't change chart area color? 
The StackBlitz version is what I deploy to local server. 
Thanks,
Kyle

**Comment by nstuyvesant** [comment]
The StackBlitz version doesn't have the theme property in its options so it defaults to white. Adding the theme 'g100' doesn't automatically set the chart box to black. It's just adjusted for dark colors but you still have to provide that dark color.

You can set the CSS custom property `--cds-grid-bg` to `black` or whatever you want, it will change.

See https://stackblitz.com/edit/t3e7yt?file=index.html

**Comment by aaaknot30** [comment]
Hi Nate - 
Yet, the theme automatically sets the chart area to dark or light in the first example you showed, (https://charts.carbondesignsystem.com/svelte/?path=/story/simple-charts-area-stacked--stacked-area-time-series).  
Can you show me where we would add or change the CSS class each time we changed the theme?
Thanks,
Kyle

**Comment by nstuyvesant** [comment]
First, it seems like an omission in the generated CSS for the component library. The simplest way to put this is that the Storybook demos use a different generated CSS file than what is exported by the component library.

The demo CSS includes these definitions (while the base does not):
```css
.cds--chart-holder {
  --cds-grid-bg: #ffffff;
}

.cds--chart-holder[data-carbon-theme=g10] {
  --cds-grid-bg: #ffffff;
}

.cds--chart-holder[data-carbon-theme=g90] {
  --cds-grid-bg: #161616;
}

.cds--chart-holder[data-carbon-theme=g100] {
  --cds-grid-bg: #161616;
}
```

The demo.scss file has...
```scss
@use '@carbon/styles';
html {
	@include styles.theme(styles.$g100);
}

html[data-carbon-theme='white'] {
	@include styles.theme(styles.$white);
}

html[data-carbon-theme='g10'] {
	@include styles.theme(styles.$g10);
}

html[data-carbon-theme='g90'] {
	@include styles.theme(styles.$g90);
}

html[data-carbon-theme='g100'] {
	@include styles.theme(styles.$g100);
}
```

while the SCSS for the component library's styles does...
```scss
@use '@carbon/styles/scss/theme';
@use '@carbon/styles/scss/themes';
@use 'globals';

.#{globals.$prefix}--chart-holder {
	@include theme.theme(themes.$white);
}

.#{globals.$prefix}--chart-holder[data-carbon-theme='g10'] {
	@include theme.theme(themes.$g10);
}

.#{globals.$prefix}--chart-holder[data-carbon-theme='g90'] {
	@include theme.theme(themes.$g90);
}

.#{globals.$prefix}--chart-holder[data-carbon-theme='g100'] {
	@include theme.theme(themes.$g100);
}
```

While both use `@carbon/styles`, the latter is more specific about the modules it uses. Perhaps something is happening by loading the top-level SCSS module that causes `--cds-grid-bg` to get defined for each theme?

**Comment by nstuyvesant** [comment]
The chart tokens (CSS custom properties) were being loaded too late in the SCSS as these are associated with the chart holder. After changing the order, `--cds-grid-bg` got defined for each theme just like the demo CSS. Submitted a PR that fixes this.
