### ISSUE TITLE
[Bug]: When charts styles are imported after carbon styles, some components break

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-charts#1669]
### Name

Jan Hassel

### Are you an IBM employee?

- [X] Yes

### What happened?

When the styles from carbon charts are imported after carbon, they have precedence over the core styles and break some components.

```scss
@use '@carbon/styles' with ($font-path: '@ibm/plex');

@use '@carbon/charts/styles.css' as charts;
```

For example, CodeSnippet (inline variant):
```jsx
<CodeSnippet type="inline">Hello world</CodeSnippet>
```

See reproduction link below.

<img width="143" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/28265588/43b61a5e-2d99-4790-a812-64fe2735e0ba">

<img width="169" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/28265588/069a5b3c-1368-4b8d-86b9-404864677b60">

### Version

`@carbon/charts-react@1.13.3`

Note: I've upgraded from `@carbon/charts-react@1.6.3` where this issue was not appearing.

### Codesandbox example

https://stackblitz.com/edit/github-skkfec?file=package.json,src%2FApp.jsx

### What priority level would this be in your opinion?

P3

**Comment by nstuyvesant** [comment]
@janhassel - This StackBlitz fork of your example uses Carbon Charts 1.0.1 https://stackblitz.com/edit/github-skkfec-q6ryuo?file=package.json and the problem appears to still be there. Please take a look.
