### ISSUE TITLE
Expose slice click event handling on Donut chart

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#167]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.9.0

### Issue description
The Donut chart doesn’t expose the slice click event handler to be used by the consuming application, unlike Pie chart that exposes `pie-slice-onClick`.

**Comment by kalai001** [comment]
`pie-slice-onClick` works on Donut chart too. Closing this issue.

**Comment by ckauth97** [comment]
Is there a good example on how to implement the pie-slick-onClick handler? I have been digging around and can't seem to find any way to get it working.
