### ISSUE TITLE
Legend display should be optional

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#173]
#### I am submitting a...

- [ ] Feature request

#### charts version:
0.8.6

### Issue description
The legend display should be made optional. The charts should have a property which can be passed by the user to display the legend

**Comment by theiliad** [comment]
@dianatran18 will wait on your feedback

**Comment by shixiedesign** [comment]
#arnajdas1992 Could you please provide context on why you'd need to hide the legends? In data visualization hiding legends is inaccessible and in general reduces the readability of the visualization. If you can provide some screenshots of your product, and data visualization in context, that would be really helpful. Thank you!

**Comment by shixiedesign** [comment]
Here is a possible solution. **Please note this is not approved yet.**

![image](https://user-images.githubusercontent.com/15144993/63200051-6158d980-c045-11e9-943f-79b260807563.png)
