### ISSUE TITLE
[Bug]: Broken style for "Download as CSV" button in tabular representation

### ISSUE THREAD

**Issue by lukasmalkmus** [carbon-design-system/carbon-charts#1730]
### Name

Lukas Malkmus

### Are you an IBM employee?

- [ ] Yes

### What happened?

I expected the following:

<img width="782" alt="Screenshot 2024-01-25 at 01 18 16" src="https://github.com/carbon-design-system/carbon-charts/assets/9931588/596acf99-c4dc-4fb4-91f7-cc9d35645f29">

But got this:

<img width="844" alt="Screenshot 2024-01-25 at 01 18 34" src="https://github.com/carbon-design-system/carbon-charts/assets/9931588/04e649e4-c437-45f8-89ba-99de0aa6cf51">

The first screenshot is from the Storybook: https://charts.carbondesignsystem.com/svelte/?path=/story/simple-charts-area-simple--area-time-series-natural-curve.

The second one is from the StackBlitz linked from the Storybook I mentioned above but I'm also seeing that locally.

### Version

carbon/charts-svelte@1.13.23

### What priority level would this be in your opinion?

P2

**Comment by markchou0225** [comment]
Hey @lukasmalkmus, @theiliad,

Sorry I just notice the https://github.com/carbon-design-system/carbon-charts/pull/1745 only fix the color, the padding-left seems not correct. I'll send another small PR later for this issue. 🙏 

<img width="626" alt="Screenshot 2024-02-08 at 9 01 22 PM" src="https://github.com/carbon-design-system/carbon-charts/assets/126788428/cfb86408-fed5-40d6-a930-717ad4acc71f">

**Comment by markchou0225** [comment]
Confirmed it's fixed in 1.13.33+ now 🎉
