### ISSUE TITLE
Tooltips in the charts are not customizable

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#174]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.9.0

### Issue description
There is no way to provide a custom content in the Tooptip. Users are forced to use see the default Tooltip, which just displays the legend. User should be able to at least pass a desired text that will be rendered in Tooltip

### Screenshot or recording
![image](https://user-images.githubusercontent.com/46040341/52143357-40203500-2681-11e9-8914-d2e1c436373a.png)

**Comment by theiliad** [comment]
@dianatran18 What do you think? Do we want to allow tooltip customizations? And if yes, to what level?

**Comment by theiliad** [comment]
@kalai001 in the meantime, there is support for formatting the number figure you see in the tooltips:
```js
tooltip: {
	formatter: tooltipValue => `${tooltipValue * 100}%`
}
```

**Comment by theiliad** [comment]
**Done in Q4:**

https://carbon-design-system.github.io/carbon-charts/documentation/interfaces/_interfaces_components_.tooltipoptions.html
