### ISSUE TITLE
how to manipulate locale for version "@carbon/charts-angular": "1.8.1"

### ISSUE THREAD

**Issue by mrtsrdm** [carbon-design-system/carbon-charts#1757]
### Application/Team

ı am not from IBM

### Question

ı am using "@carbon/charts-angular": "1.8.1" for my angular 8 application.
 I can format tick values by using ticks formatter in tr-TR localization ->
![image](https://github.com/carbon-design-system/carbon-charts/assets/65854951/c7bac7eb-3d45-457b-982b-68aebdb5d4d5)

Hovewer, it is not working for table view ->
![image](https://github.com/carbon-design-system/carbon-charts/assets/65854951/7b5ae5f9-b07a-4914-952b-abba04e5efe4)

I tried this -> " locale: { code: 'tr-TR' } ". But it is not working.

How can ı manipulate locale ?

**Comment by RiyaJethwa** [comment]
If possible could you provide a stackblitz link, also you can try using the date formatter given below:
[https://charts.carbondesignsystem.com/documentation/interfaces/interfaces.Locale.html#date](url)
Also additionally u can use tableCellFormatter option given below:
[https://charts.carbondesignsystem.com/documentation/interfaces/interfaces.TabularRepCustomizationOptions.html#tableCellFormatter](url)

**Comment by RiyaJethwa** [comment]
Just to clarify, I meant that you upgrade carbon-charts version. Since locale options and also tabularRepModal options are supported in it.

**Comment by theiliad** [comment]
AFAIK, Angular8 was end-of-life in 2020, unfortunately we won't be able to provide support for all of these versions
