### ISSUE TITLE
Zoom bar on plots with scaleType=linear

### ISSUE THREAD

**Issue by Gavaii** [carbon-design-system/carbon-charts#1774]
### Discussed in https://github.com/carbon-design-system/carbon-charts/discussions/1271

<div type='discussions-op-text'>

<sup>Originally posted by **diogorloureiro** January 16, 2022</sup>
Hello everyone,

I would like to use the Zoom Bar component in one of my plots with `"scaleType": "linear"`. However, whenever I try to add the Zoom Bar the plot just breaks. I also noticed that all the [Zoom Bar examples in Storybook](https://charts.carbondesignsystem.com/vue/?path=/story/utility-zoom-bar--line-time-series-time-interval-15seconds-zoom-bar-enabled) are using `"scaleType": "time"`, is there any reason for this?

Is it possible to use a Zoom Bar with scaleType=linear or will it be possible in a near future?

Thanks in advance,
Diogo</div>

**Comment by theiliad** [comment]
yes unfortunately we only support the zoombar with our time-scale axes
