### ISSUE TITLE
Tooltip hand icon should be only for Icon

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#178]
#### I am submitting a...

- [ ] Feature request

#### charts version:
0.8.6

### Issue description
If there is a tooltip icon present, then the hand icon should come only for the icon. If no icon is present, then the hand icon can come over the tooltip trigger text

**Comment by theiliad** [comment]
Sorry @arnajdas1992 I don't understand the description, could you describe the issue in more detail or using screenshots? Thank you 🙂

**Comment by arnajdas1992** [comment]
@theiliad - My bad, I raised a wrong issue. Closing it
