### ISSUE TITLE
[Bug]: Uncaught (in promise) rejection from DonutChart

### ISSUE THREAD

**Issue by AndersRobstad** [carbon-design-system/carbon-charts#1783]
### Application/Team

Kvist

### What happened?

When loading a page with one `DonutChart`-component we are getting two errors as such in the console: 

<img width="519" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/54552345/8db33855-8c1b-4843-8ffa-443c33650043">

### Version

@carbon/charts-svelte: ^1.15.3

### Data & options used

```js
options={{
				resizable: true,
				toolbar: { enabled: false },
				pie: { labels: { enabled: false }, valueMapsTo: 'percentagePoints' },
				donut: {
					alignment: Alignments.CENTER,
					center: {
						numberFontSize() {
							return 36;
						},
						label: classificationName,
						numberFormatter(value) {
							return `${value.toFixed(1)}%`;
						}
					}
				},
				tooltip: {
					valueFormatter(value) {
						return `${value.toFixed(1)}%`;
					},
					truncation: {
						numCharacter: 100
					}
				},
				legend: {
					truncation: {
						threshold: 1000
					}
				}
			}}

data= [
    {
        "group": "Ledelse",
        "percentagePoints": 7.428571428571428
    },
    {
        "group": "Helse og innemiljø",
        "percentagePoints": 2.526315789473684
    },
    {
        "group": "Energi",
        "percentagePoints": 2.9166666666666674
    },
    {
        "group": "Transport",
        "percentagePoints": 10
    },
    {
        "group": "Vann",
        "percentagePoints": 3.5555555555555554
    },
    {
        "group": "Materialer",
        "percentagePoints": 15.3
    },
    {
        "group": "Avfall",
        "percentagePoints": 7.000000000000001
    },
    {
        "group": "Arealbruk og økologi",
        "percentagePoints": 15
    },
    {
        "group": "Forurensing",
        "percentagePoints": 2.857142857142857
    },
    {
        "group": "Innovasjon",
        "percentagePoints": 1
    }
]
```

### What priority level would this be in your opinion?

P2

**Comment by markchou0225** [comment]
Thank you for reporting @AndersRobstad. I think it's caused by my change: https://github.com/carbon-design-system/carbon-charts/pull/1771 I'll look into this and deliver a fix asap.

**Comment by markchou0225** [comment]
PR submitted, confirmed it should impact `1.14.8~1.15.3(latest)`.

**Comment by justinschmidt-ventum** [comment]
I still seem to have the same bug on @carbon/charts-react@1.15.7 on both donut and pie charts.
![CleanShot 2024-04-25 at 09 29 22@2x](https://github.com/carbon-design-system/carbon-charts/assets/166023035/043cf786-5e01-4d83-a7b5-a56f04f2405a)
![CleanShot 2024-04-25 at 09 29 32@2x](https://github.com/carbon-design-system/carbon-charts/assets/166023035/e15e6c0d-4ab3-4f74-8c24-21935d370031)

**Comment by markchou0225** [comment]
Hi @justinschmidt-ventum,

Thanks for reporting this. Could you provide Options and sample data that could re-produce this issue via storybook like below? https://charts.carbondesignsystem.com/?path=/story/simple-charts-donut--donut&args=options.height:500px

It would help me for trouble-shoot, thanks.

**Comment by justinschmidt-ventum** [comment]
Hi @markchou0225,

        <DonutChart
          data={[
            { group: t('survey.step9.directemissions.title'), value: formState.calculatedEmissionsDirectPerTonne },
            { group: t('survey.step9.indirectemissions.title'), value: formState.calculatedEmissionsIndirectPerTonne },
          ]}
          options={{
            title: 'Total Emissions',
            resizable: true,
            donut: {
              center: {
                label: 't CO2e / tp'
              },
              alignment: 'center'
            },
            height: '300px'
          }}
        />
        
        The same error also happens when the value is set to something like 10 and 20 directly in the code instead of using formstate, same with the group name being set directly in the code. Interestingly, when my formstate was empty due to a bug and no data was passed to the chart, I didn't get any error messages.
