### ISSUE TITLE
[Bug]: The StackedBarChart doesn't display data when the first key it receives is a string of negative number

### ISSUE THREAD

**Issue by irinageorge** [carbon-design-system/carbon-charts#1795]
### Application/Team

IBM Support Insights

### What happened?

**Actual result:** The StackedBarChart doesn't display data when the first key it receives is a string of negative number, e.g. key: "-6". 
![Screenshot 1](https://github.com/carbon-design-system/carbon-charts/assets/114845971/5eb02b68-9eaa-4b70-b42f-5d7df3990125)

The chart works okay when:
-  the first key is NOT a string of negative number, e.g. key: "-6";
- the first key is a string of negative number + text, e.g. key: "-6M";
- the first key is "-Some Key". 

**Expectations:** The chart to display data when the first key that it receives is a string of negative number, e.g. key: "-6". 

### Version

"@carbon/charts-react": "^1.15.5"

### Data & options used

```js
//data
export default [
  {
    group: 'Dataset 1',
    key: '-6',
    value: 65000
  },
  {
    group: 'Dataset 2',
    key: '0',
    value: 29123
  },
  {
    group: 'Dataset 3',
    key: '6',
    value: 35213
  }
]

//options
export default {
  title: 'Vertical stacked bar (discrete)',
  axes: {
    left: {
      mapsTo: 'value',
      stacked: true
    },
    bottom: {
      mapsTo: 'key',
      scaleType: 'labels'
    }
  },
  height: '400px'
}
```

### What priority level would this be in your opinion?

P2

**Comment by theiliad** [comment]
Closed through #1821
