### ISSUE TITLE
Chart tooltip cannot be focused on via tab

### ISSUE THREAD

**Issue by danielwaiforssell** [carbon-design-system/carbon-charts#1796]
### Package
@carbon/react

### Operating System
MacOs

### Package version
1.50.0

### React version 
17.0.2

### Automated testing tool and ruleset
https://www.ibm.com/able/requirements/requirements/?version=v7_2$1_4_13

### Description
Expected: able to tab through chart tooltips

### Reproduction/example
not tabbable

### Steps to reproduce
Use tab to go through chart. Unable to focus on tooltip

**Comment by theiliad** [comment]
Hi 👋🏻 
Our tooltip was not designed to be tabbable, and only shows up onHover. I will close for now, and bring up with team just to make sure

**Comment by danielwaiforssell** [comment]
Hi @theiliad just confirming did the team confirm that it is not tabbable by design?
