### ISSUE TITLE
Keyboard opearability in HistogramChart

### ISSUE THREAD

**Issue by Vinodbs** [carbon-design-system/carbon-charts#1835]
### Application/Team

Vajra

### Environment

Browser

### What happened? What did you expect to happen instead?

We have added click functionality to histogram graph and it is working fine. Also , to make it keyboard operable, we have added tabIndex and onKeyPress. However, the <Path> is not getting focussed and hence not keyboard operable

### What WCAG 2.1 checkpoint does the issue violate?

AVT2 and AVT3

### Version

@carbon/charts-react": ^1.15.6

### What priority level would this issue be in your opinion?

P0

**Comment by RakshaFauzdar** [comment]
Any updates on this ?

**Comment by theiliad** [comment]
Hi, could you pls explain further what you've added and how you've added it?

During the numerous keyboard accessibility explorations with our team, we'd determined that it's not going to be feasible to add keyboard navigation for graph elements, as they do not convey the visualization in the same way through a screen-reader.

We instead added the tabular representation, but really we'd expect the users of the library (development team) to build an alternative text-based representation of the data that they're visualizing, and expose that to screen-reader users. The library would not be able to build that kind of alternative text description, as it's not aware of the purpose of each dataviz.

I'm looking forward to your respond, and we can reopen the ticket with more context 🙂
