### ISSUE TITLE
[Bug]: Cannot find module 'topojson-specification' or its corresponding type declarations

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon-charts#1854]
### Relevant package(s)

- [X] @carbon/charts
- [ ] @carbon/charts-svelte
- [ ] @carbon/charts-react
- [ ] @carbon/charts-angular
- [ ] @carbon/charts-vue
- [ ] Documentation website

### Carbon Charts Version

1.16.8

### Which bundler are you using?

Webpack

### What happened and what did you expect to happen?

I guess this is related to this change

https://github.com/carbon-design-system/carbon-charts/blob/a43f0eb3a9d09178ac613bc34de32816a4e0e4be/packages/core/src/interfaces/charts.ts#L1

the package dev dependencies are not install by npm (only the dependencies or unless i install them myself in my main package) (see this thread https://github.com/Microsoft/types-publisher/issues/81#issuecomment-459314973

Is it possible to move @types/topojson to dependencies or to explicitly mention we have to install them

thanks 

this was the error 
```
ERROR in node_modules/@carbon/charts/dist/interfaces/charts.d.ts:1:26 - error TS2307: Cannot find module 'topojson-specification' or its corresponding type declarations.

1 import { Topology } from 'topojson-specification';
                           ~~~~~~~~~~~~~~~~~~~~~~~~

webpack 5.92.0 compiled with 1 error and 2 warnings in 29953 ms
```

last working version was  @carbon/charts@1.16.6

**Comment by uniquejava** [comment]
Same issue here with `Angular 18` and  `@carbon/charts-angular": "^1.19.2`, I have to manually install the following dev dependencies:

```
  "devDependencies": {
    ...
    "@types/d3": "^7.4.3",
    "@types/topojson-specification": "^1.0.5",
}
```

**Comment by nstuyvesant** [comment]
@huineng and @uniquejava - do your tsconfig.json files have
```json
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

Wondering if your projects are unnecessarily checking types in your dependency on `@carbon/charts` or `@carbon/charts-angular`. The core package has its own devDependencies that include `@types/topojson` (which includes `@types/topojson-specification`) and `@types/d3`.

Your projects generally shouldn't need these type declarations unless you are directly using those types.

**Comment by huineng** [comment]
i have skipLibCheck set to false. And i have installed topojson-specification to avoid compilation issues.

My opinion is that dev dependencies are used during development. So you develop , build and publish and the dependencies should no longer be needed. But you publish the package with the dependency, and so for us doing further development on carbon charts, we do need to have that package installed. 

As npm does not install dev dependencies from 3th parties, we have to do it ourselves.

So whatever code you publish that contains a dependency on another package, should include that package as a dependency.

Thanks

**Comment by uniquejava** [comment]
Thanks for your help. `"skipLibCheck": true` fixed the issues.

No, I don't use these types in my hello world project.

When run `npm start` for the first time, I see the error originated from this file.

> node_modules/@carbon/charts/dist/components/axes/axis.d.ts:

Relevant logs:

```


Error: node_modules/@carbon/charts/dist/components/axes/axis.d.ts:1:53 - error TS7016: Could not find a declaration file for module 'd3'. '/Users/cyper/github/CarbonPoc/node_modules/d3/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/d3` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3';`

1 import { AxisScale, Selection as D3Selection } from 'd3';
                                                      ~~~~


Error: node_modules/@carbon/charts/dist/components/axes/axis.d.ts:20:47 - error TS7016: Could not find a declaration file for module 'd3-selection'. '/Users/cyper/github/CarbonPoc/node_modules/d3-selection/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/d3-selection` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3-selection';`

20     getInvisibleAxisRef(): D3Selection<import('d3-selection').BaseType, any, Element, any>;
                                                 ~~~~~~~~~~~~~~


```

**Comment by nstuyvesant** [comment]
Hi @huineng - since we publish the .d.ts files that reference some of those types, it's fair to say they should be dependencies. I have an open PR that I added them to.
