### ISSUE TITLE
[Question]: Versions not available on npm

### ISSUE THREAD

**Issue by max-jonas** [carbon-design-system/carbon-charts#1914]
### Question

Hi,
I just wanted to update my project to the latest version 1.22.2, but this version is not available on [npm](https://www.npmjs.com/package/@carbon/charts?activeTab=versions).
I checked the available versions and noticed that there are multiple releases that are not available there, for example 1.22.2, 1.22.1,  1.21.2, ...

Is that intended? Am I maybe missing something?

Thanks in advance for your help.
Kind Regards,
Max

**Comment by ddxv** [comment]
I've also been wondering about this. I am waiting for dependency bumps for `@carbon/charts-svelte` that are in 1.22.2 and are still not available on npm? 

v1.22.1 was 6 weeks ago, so not sure if they wait for a bigger set of changes or what?

**Comment by theiliad** [comment]
There was an issue with the release process, 1.22.3 is out now
