### ISSUE TITLE
[Bug]: npm warn deprecated carbon-components@10.59.0: This package is no longer supported. More info at https://carbondesignsystem.com/deprecations/

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon-charts#1918]
### Relevant package(s)

- [x] @carbon/charts
- [ ] @carbon/charts-svelte
- [ ] @carbon/charts-react
- [ ] @carbon/charts-angular
- [ ] @carbon/charts-vue
- [ ] Documentation website

### Carbon Charts Version

1.22.4

### Which bundler are you using?

None (UMD)

### What happened and what did you expect to happen?

https://github.com/carbon-design-system/carbon-charts/blob/6fea936edd126da37bdd164b7403c083ea6fe018/packages/core/package.json#L81

is it possible to handle this deprecation ?

### Chart data and options (automatically formatted so no need for backticks)

```js

```

### JavaScript console or build output (if relevant)

```shell

```

### What priority level would this be in your opinion?

P0 (Critical)

**Comment by theiliad** [comment]
This is now fixed in latest version, pls check

**Comment by huineng** [comment]
My charts are still working :). all good thanks
