### ISSUE TITLE
Tooltips get hidden when you're close to the edge of a screen

### ISSUE THREAD

**Issue by nicoleroppel** [carbon-design-system/carbon-charts#208]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
Whatever is on this site: https://carbon-design-system.github.io/carbon-charts/

### Issue description
Tooltips always point to the right, so when the chart is close to the edge of the container, the tooltip runs off the page.

#### Steps to produce the issue
Go to any chart, resize the container so the chart is sitting close to the edge, hover over any chart point.

#### Current behavior

<img width="1676" alt="screen shot 2019-03-06 at 12 17 30 pm" src="https://user-images.githubusercontent.com/43546639/54043736-526b2280-419b-11e9-8407-277044fd7400.png">

#### Expected behavior

The tooltip could point in a different direction that has more room when it's close to the right edge, or the bottom/top of a page.

<img width="342" alt="screen shot 2019-03-08 at 12 25 52 pm" src="https://user-images.githubusercontent.com/43546639/54044613-69ab0f80-419d-11e9-948f-88611db356cb.png">

**Comment by theiliad** [comment]
We had this discussion before with the team. We were thinking of using the peretz tooltip location service, but decided to investigate whether carbon has one or not.

I will look into that...

**Comment by nicoleroppel** [comment]
@theiliad Great, thank you!

Is there anything I need to/can do to get this prioritized? We have an upcoming release, and so many of our tooltips are falling outside of the screen.

Thanks!

**Comment by cal-smith** [comment]
You could probably just consume https://github.com/IBM/carbon-components-angular/blob/master/src/utils/position.ts directly for now ... I'd like to split that out into a separate package eventually

**Comment by theiliad** [comment]
Oh great!

**Comment by nicoleroppel** [comment]
@theiliad Hi Eliad! Just wanted to check in on the status of this one. Any updates on when this might be fixed?

Thanks!

**Comment by theiliad** [comment]
Hey Nicole, this had not been on our radar design wise... I will take a look soon

**Comment by nicoleroppel** [comment]
@theiliad hi! Great, sounds good. Is there anything I can do to assist or prioritize this issue? 

Thanks!

**Comment by nicoleroppel** [comment]
@theiliad hi! Just wanted to check in on the status of this. Any updates on when this update might be available?

Thank you!

**Comment by cal-smith** [comment]
We should have more time to look at this now that v3 of carbon-angular is out ... hopefully we'll get to it in the next few weeks

**Comment by theiliad** [comment]
@nicoleroppel `v0.11.15` solves this issue

**Demo:**
https://codesandbox.io/s/149vrzo62l
