### ISSUE TITLE
[React] Donut chart goes out of boundaries in Edge 16

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#209]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.10.1

### Issue description
Donut chart doesn't render fully within the boundaries in Edge v16
https://codesandbox.io/s/747p74jnk0

### Screenshot or recording
![image](https://user-images.githubusercontent.com/46040341/54116828-979a8900-4415-11e9-8b1c-4db4abb52e54.png)

**Comment by ninja511** [comment]
**slack conversation:**
Eliad Moosavi   [9 days ago]
Hi, we’ll need to look into this. What is the latest version of edge currently?

Kalaivanan Saravanan   [9 days ago]
Our product supports from EdgeHTML 16+

Eliad Moosavi   [9 days ago]
what is the latest version of edge?

Eliad Moosavi   [9 days ago]
Looks like edge is at 4% market share… Not sure if we can push that to high priority

Eliad Moosavi   [9 days ago]
I’ll discuss with the team

Kalaivanan Saravanan   [9 days ago]
Latest version 44.17763.1.0 comes with rendering engine EdgeHTML 17. But as I mentioned our product support is from EdgeHTML 16

Kalaivanan Saravanan   [3 days ago]
@iliadm, has this been discussed with your team? any updates ?

**Comment by cal-smith** [comment]
We support the latest version of each browser and IE11 (per https://www.carbondesignsystem.com/help/faq#which-browsers-are-supported)

I can't reproduce this issue on the latest version of Edge (44.17763.1.0) and EdgeHTML (17). If your team needs to support EdgeHTML 16 you will need to provide a fix.

**Comment by theiliad** [comment]
Yes. I did consider looking at Edge, however most of the information I found suggested <%5 market share in total. Either way we're currently compatible with EdgeHTML17
