### ISSUE TITLE
Scatter chart demo

### ISSUE THREAD

**Issue by darsi-an** [carbon-design-system/carbon-charts#215]
####
The demo in scatter chart currently uses the data defined in line.ts. Class line-chart inherits from scatter-chart. Area chart, line charts and possibly bubble can be generalized from scatter-chart, I think its best to keep the data separate in this case. It will provide better clarity for application developers.

I will push updates for this, if everyone agrees.  

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [X] Other

**Comment by theiliad** [comment]
Good idea 👍

**Comment by theiliad** [comment]
done a while ago
