### ISSUE TITLE
[React] negative values in stacked chart are not displaying properly

### ISSUE THREAD

**Issue by hah** [carbon-design-system/carbon-charts#222]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.11.0
### Issue description
Using negative values in **stacked** charts breaks the chart into a **grouped** chart

#### Steps to produce the issue
here is an example of the stacked chart:
https://codesandbox.io/s/2plrn2jp7r

if you change the values on line 19 for example to : 
` data: [-12312, 23232, 34232, 12312, 34234]`
the chart breaks down into a grouped chart

### Screenshot or recording
![image](https://user-images.githubusercontent.com/46223652/54923031-aa2ebb00-4f09-11e9-8997-7d13ef12aead.png)

**Comment by cal-smith** [comment]
From slack: What are you expecting here? An additional value on the y axis?

Generally it seems to be functioning correctly, so I'm curious what you see as broken?

**Comment by theiliad** [comment]
@hah We don't support negative values in a stacked bar chart (it is a design decision). If you have negative values, it's recommended that you use a grouped bar chart, and the codebase does automatically make that switch for you (check console logs)

Please let me know if you have any questions!
