### ISSUE TITLE
[Project] Explore yarn and it's workspaces feature

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-charts#228]
Carbon elements has been using yarn workspaces with a (checked in) offline cache for a while now ... from experience it simplifies a number of things when working with a monorepo (and the cache speeds up builds and improves reproducability)

https://github.com/IBM/carbon-elements/blob/master/.yarnrc

Also the remark tool is potentially handy: https://github.com/IBM/carbon-elements/blob/master/tasks/remark/remark-monorepo.js

**Comment by theiliad** [comment]
Yeah this is something I explored a while back, and at the time didn't find workspaces quite ready to be used in this repo. We can look at it again soon
