### ISSUE TITLE
Line chart - overlapping y-axis labels

### ISSUE THREAD

**Issue by eddieibm** [carbon-design-system/carbon-charts#238]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
latest

### Issue description
overlapping y-axis labels

### Screenshot or recording
![55a99a00-3e8d-11e9-9d8c-fd69294912af](https://user-images.githubusercontent.com/47797763/55185053-f1b38200-5169-11e9-8d17-94f32c54078a.png)

**Comment by eddieibm** [comment]
do we have updates on this defect?

**Comment by theiliad** [comment]
@eddieibm Specs are currently being updated. We will see design changes soon that'll account for issues like this one
