### ISSUE TITLE
Update layout & typography to follow new language

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#244]
## Layout, spacing, alignment

Spacing and alignment spec below 

![image](https://user-images.githubusercontent.com/15144993/56442143-2e7c2000-62b5-11e9-8762-74717b7cc0a8.png)

## Typography, grid, & color

Please note the addition of `Plex sans condensed` font. `12/16 px` refers to 12 px type size, and 16px line height. 

### Light UI

```css
Chart title: Plex sans semibold, 14/18 px, Gray 100
Legend name: Plex sans condensed, 12/16 px, Gray 60
background-color: White #ffffff
Grid lines: 1px Gray 10
Axis: 1px Gray 50 
Axis names: Plex sans regular, 12/16 px, Gray 100
Axis labels (string): Plex sans condensed, 12/16, Gray 60
Axis labels (num): Plex mono, 12/16, Gray 60

```

### Dark UI

```css
Chart title: Plex sans semibold, 14/18 px, Gray 100
Legend name: Plex sans condensed, 12/16 px, Gray 60
background-color: Black #000000
Grid lines: 1px Gray 90
Axis: 1px Gray 60 
Axis names: Plex sans regular, 12/16 px, Gray 10
Axis labels (string): Plex sans condensed, 12/16, Gray 50
Axis labels (num): Plex mono, 12/16, Gray 50
```

![image](https://user-images.githubusercontent.com/15144993/56442220-874bb880-62b5-11e9-8174-48f48c5fe209.png)

## Pie & Donut charts

![image](https://user-images.githubusercontent.com/15144993/60040603-00350b00-967f-11e9-96d9-9499ea3db057.png)

**Comment by natashadecoste** [comment]
@shixiedesign I just want to confirm that the Chart Title font is **semibold** for all charts. Under pie/donut chart specs it is listed as _Plex sans regular_ and in Light UI and Dark UI it is listed as _Plex sans semibold_

**Comment by shixiedesign** [comment]
@natashadecoste Yes! All Chart titles should be **semibold** Sorry about the mistake! I will corrected it for future sketchfiles.

**Comment by natashadecoste** [comment]
@shixiedesign it would take additional checking for the axis labels to have different fonts for numerical and for string labels (even though its a small difference). For example if their axis data was a mixed data set for time ("Morning", 11:00, 14:00, 16:00, "Evening") or other such custom case. Can we commit to Plex sans condensed or Plex sans mono for **Axis Labels**?

**Comment by shixiedesign** [comment]
@natashadecoste Oh in that case, let's use **Plex Sans Condensed** for all axis labels. Thanks! Numbers in plex sans are already mono so it doesn't disadvantage us!

**Comment by natashadecoste** [comment]
> 
> ### Light UI
> ```css
> Chart title: Plex sans semibold, 14/18 px, Gray 100
> Legend name: Plex sans condensed, 12/16 px, Gray 60
> background-color: White #ffffff
> Grid lines: 1px Gray 10
> Axis: 1px Gray 50 
> Axis names: Plex sans regular, 12/16 px, Gray 100
> Axis labels (string): Plex sans condensed, 12/16, Gray 60
> Axis labels (num): Plex mono, 12/16, Gray 60
> ```
> 
> ### Dark UI
> ```css
> Chart title: Plex sans semibold, 14/18 px, Gray 100
> Legend name: Plex sans condensed, 12/16 px, Gray 60
> background-color: Black #000000
> Grid lines: 1px Gray 90
> Axis: 1px Gray 60 
> Axis names: Plex sans regular, 12/16 px, Gray 10
> Axis labels (string): Plex sans condensed, 12/16, Gray 50
> Axis labels (num): Plex mono, 12/16, Gray 50
> ```
> 

@cameroncalder reposted the specs above for the Light and Dark UI.

I am almost done with the Dark UI, although it might need some more specs for different charts (such as donut) as well as the other themes.  Below is the current tokens used for **both dark and light ui**

### DARK UI
background-color: Black #000000
Grid lines: 1px Gray 90 // $ui-01
Axis: 1px Gray 60 // $ui-04
Axis names: Plex sans regular, 12/16 px, Gray 10 //$text-01
Axis labels (string): Plex sans condensed, 12/16, Gray 50 // unassigned
Axis labels (num): Plex mono, 12/16, Gray 50 // using the same as String

**Comment by shixiedesign** [comment]
Hi @natashadecoste please note there's a small change made to the type style used in axis labels and legend name - **line height of Sans Condensed should be 14px, not 16px!**
