### ISSUE TITLE
Restyle: line chart

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#252]
New style of Line chart is below. Reference text in `#D6316C` for measurements. Overall thinning the lines to 1.5px, reducing data point to 6x6px circle with white fill. For `step line` chart, dropping the data points on it so it's just line. 

- [ ] Standard line
- [ ] **Double Y axis (I'm unclear if this is considered a variation for line only, or if this is a variation on the grid.)
- [ ] Step line
- [ ] Curved line

![(1) Line charts](https://user-images.githubusercontent.com/15144993/56534269-ee1fda80-651e-11e9-8ac0-b413b257353c.png)

**Comment by theiliad** [comment]
Hi @shixiedesign, couple of points here:
1. For step charts, if we drop the circular points, what would trigger the tooltip?
2. Usually the 2nd y-axis has no linear relationship with the data. It is merely a scale shown where the user can visually make the connection. (e.g. we show a 2nd y-axis from 0-100%, however it is only a coincidence that the data falls in line with the axis, and there is no logic relating them. It is a dumb scale)
3. In what situation would we have black fills for the points? Currently if the point radius is smaller than 4px, we apply the same fill as the stroke color.
4. This is what the line & points strokes look like at 1.5px:
![image](https://user-images.githubusercontent.com/14989804/56938415-cbb63000-6acf-11e9-836c-c28b4a5232f5.png)
Is this a go?

**Comment by shixiedesign** [comment]
@theiliad Yep all great points:
1. [Step charts] Hover should apply to the entire horizontal section. Cameron will provide more specific spec, but here's the initial designs: 
![image](https://user-images.githubusercontent.com/15144993/57241294-40203000-6ff6-11e9-908a-fc9eeca200f2.png)
2. lemme come back to this
3. lemme come back to this
4. lemme come back to this!

**Comment by theiliad** [comment]
From what I can see the only remaining task here is this one:

![image](https://user-images.githubusercontent.com/14989804/72082227-d3b8a780-32cd-11ea-8c59-62af2aeb49e4.png)

Which isn't really possible when you think about how a step line is drawn in SVG. You'd draw the entire line using 1 SVG path:

![image](https://user-images.githubusercontent.com/14989804/72082392-15495280-32ce-11ea-99a5-9bd97da77efd.png)

@shixiedesign we can still detect a hover on the line, run some logic to determine whether it's a horizontal section of the line, then draw another line that thickens the original line. Not the most ideal piece of logic, but possible.

Another question, in this example it looks like we're also thickening the selected line when interacting with the legend:
![image](https://user-images.githubusercontent.com/14989804/72082645-78d38000-32ce-11ea-9146-3363c247ee50.png)

is that the case? If so, by how much?

**Comment by ninja511** [comment]
closing for now
