### ISSUE TITLE
Restyle: donut & pie 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#254]
Overall thinning the rings to `24px`, adding `1px` white divider line between sections, when label is short & few, display labels in chart instead of showing a legend. 

- [ ] Donut chart
- [ ] Pie chart

![(4) Donut   pie](https://user-images.githubusercontent.com/15144993/56553709-f2ff8100-6554-11e9-866f-2e537ff7bb5c.png)

**Comment by theiliad** [comment]
Hi @shixiedesign, couple of pointers here:
1. What defines "when possible" for slice labels?
2. Everything else completed

**Comment by shixiedesign** [comment]
> What defines "when possible" for slice labels?

For the sake of not keep checking and compromise performance, how about **when there are only 2 slices**? We know when there are 2 slices, there's no way labels would overlap / or be too close. When it gets up to 3 slices, there's a chance 1 slice is too small and there will be no room for label.

**Comment by theiliad** [comment]
@shixiedesign Seems somewhat inconsistent doesn't it? Also not sure how we'll handle longer labels

**Comment by shixiedesign** [comment]
I see your point. Let's tap into the larger community for some more takes.

**Comment by shixiedesign** [comment]
Structure spec for pie & donut charts
https://github.com/carbon-design-system/carbon-charts/issues/257

**Comment by shixiedesign** [comment]
## Additional spec for donut / pie chart states styles: 
- [ ] Hover state (tooltip spec in __issue # tbd__ )
- [ ] Small value
- [ ] Error state 1 & 2
- [ ] Empty state

FYI @theiliad. Nothing too controversial here I think, but I will go over these again during our Wednesday's call in case someone have issues with these. 

[(4) Donut & pie2.pdf](https://github.com/carbon-design-system/carbon-charts/files/3319102/4.Donut.pie2.pdf)

**Comment by theiliad** [comment]
Thanks @shixiedesign.

I don't see the strokes on hover for slices, should we remove those?
![image](https://user-images.githubusercontent.com/14989804/60030941-d6291c00-9671-11e9-8e86-184efe034979.png)

**Comment by shixiedesign** [comment]
Yes please! The width / thickness-growth alone would be the styling change for hover.

**Comment by natashadecoste** [comment]
![image](https://user-images.githubusercontent.com/14351335/60046635-d804d680-9695-11e9-8bb4-d3e0186f7a4a.png)

@shixiedesign for the requirements for 'small values', are there labels regardless of the size of the smallest values? for the attached photo, 5% and 8% are the smallest but are not visually too small for a label, would these smallest 2 values have a line to call out the label?

**Comment by shixiedesign** [comment]
Great point @natashadecoste I did some quick research and visual estimation, I think we can say any slice **≤ 2 degrees** can be considered a "small" slice.  

![image](https://user-images.githubusercontent.com/15144993/60064171-31d0c500-96c5-11e9-9770-97b682481dc6.png)

However, label overlapping is the driving reason for having a line for call out. So perhaps when there are more than 2 small slices together, it make sense to automatically lump them together to create the "others" category. Perhaps this can be a default we do, and users can turn it off if it does not suit their use case. 

https://superuser.com/questions/301655/excel-pie-chart-how-to-combine-smaller-values-in-a-single-other-slice

**Comment by theiliad** [comment]
Maybe we can try:
```js
if (datum.value <= (collectiveValue / 120)) {
 // add lines to 2 smallest labels
}
```

**Comment by natashadecoste** [comment]
@shixiedesign @theiliad 
the slices are sequenced from large to small, _however_ when grouped to create "Other" and maintain the current limit of 6 slices, the "Other" slice is **last** in the list. Without re-orderig it, the 2 call out labels (one going Left, one going Right) might not come from the top of the pie/donut chart (see attached image) they could likely both be on the left side of a larger "Other".

![image](https://user-images.githubusercontent.com/14351335/60114473-e4466d80-9741-11e9-8a9b-3c0de1913cf0.png)


At first thought, it seems like we could re-sequence it largest-smallest and then decide if the 2 smallest slices ≤ 3 degrees (and if call out label is needed at all) but the Legend is tied to the pie chart and Other would no longer be at the bottom of the legend as it is likely supposed to be. Can do it without re-ordering, but there is a scenario where both call out labels could be on the left (as in above photo if the 1% slices were to be call out labels).

**Comment by theiliad** [comment]
@natashadecoste The `other` label behavior might be something we'd like to call off.

It's confusing and automatic logic that happens without the developer realizing, and causes messy code internally as well.

@shixiedesign?

**Comment by shixiedesign** [comment]
Right. I agree let's skip the `Others` category behavior for now. Keeping the lines on top is kinda important to the design.

**Comment by theiliad** [comment]
@shixiedesign another thing we automatically do is sorting the pie slice values in a descending fashion. Do we want to continue doing that?

**Comment by shixiedesign** [comment]
I think so! Sorting/sequencing the slices definitely help users with comparisons.

**Comment by natashadecoste** [comment]
@shixiedesign Okay! So i **will** sort the slices (after "Other" is made) and keep everything descending making sure all call outs will be on top. Callouts will be 2 maximum (one left, one right) and only on <3 degree slices. Thanks!

**Comment by shixiedesign** [comment]
Mostly exactly what you said @natashadecoste ! Only skip making "Others" category.

**Comment by natashadecoste** [comment]
@shixiedesign this is a slice that is 3.08 Degs (just above 3 deg so it will not get a callout)
![image](https://user-images.githubusercontent.com/14351335/61152034-60b4ac80-a4b5-11e9-95aa-8e3a8c2716e6.png)

compared to a slice that is ~2.89 degrees and will get a callout
![image](https://user-images.githubusercontent.com/14351335/61152151-a70a0b80-a4b5-11e9-80ab-958c3da0d665.png)


let me know if you would want the thresholds adjusted or paddings for the callout (between line and text, between line and pie chart, etc).

**Comment by natashadecoste** [comment]
@shixiedesign 

currently the callouts are looking like this:
![image](https://user-images.githubusercontent.com/14351335/61895339-7330dc00-aee0-11e9-843c-3d0ea24b444a.png)

The height was changed to account for cases like these:
![image](https://user-images.githubusercontent.com/14351335/61895388-8fcd1400-aee0-11e9-8610-5e54b1c7bdca.png)

the current configuration for the offsetY is 15 and offsetX is 30

**Comment by natashadecoste** [comment]
and in dark theme the callouts match the text color for the percentage labels

![image](https://user-images.githubusercontent.com/14351335/61895848-a031be80-aee1-11e9-81cd-2d23a0eec165.png)

**Comment by shixiedesign** [comment]
Thanks!! Lemme review these and get you some feedback in the next few days.

**Comment by theiliad** [comment]
for items that say `0%`, can we do 1 more sig. fig? (e.g. `0.2%`)

**Comment by theiliad** [comment]
The restyles have all been implemented in Q3 2019, the only thing standing out is the empty state which has come up multiple times during discussions.

As discussed that portion doesn't seem to be ready for dev yet. We should create a separate issue and keep track of the work around empty states

**Comment by pre-ska** [comment]
hi @shixiedesign @theiliad 
what happened to slice labels?
I see discussion started, but without any conclusion in this thread
I it possible to create something like this? (notice slice labels)

![Screenshot from 2021-12-06 17-58-37](https://user-images.githubusercontent.com/18500014/144889098-0e730d86-c1da-43ab-a7df-097411633792.png)

**Comment by theiliad** [comment]
Hi, we've so far stayed away from those additional labels as they can clutter the charts, potentially cause accessibility/readability issues (specially when multiple small slices are closely positioned) and can also cause potential glitches in each render (e.g. when slices move around between renders, labels also need to reposition and this could change where the pie is placed)

**Comment by theiliad** [comment]
> what happened to slice labels?

Hi, we've so far stayed away from those additional labels as they can clutter the charts, potentially cause accessibility/readability issues (specially when multiple small slices are closely positioned) and can also cause potential glitches in each render (e.g. when slices move around between renders, labels also need to reposition and this could change where the pie is placed)

**Comment by pre-ska** [comment]
@theiliad ty for the answer
