### ISSUE TITLE
Restyle: scatter plot

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#255]
Overall, data points are `8px` circles and have an outline in color of legend, and fill with color of legend at `.3 opacity` .

Side note, while researching I found this data set. Curious if we can test out this design with data from https://stackoverflow.com/questions/19064772/visualization-of-scatter-plots-with-overlapping-points-in-matplotlib

![(5) Scatter and bubble](https://user-images.githubusercontent.com/15144993/56553950-b97b4580-6555-11e9-9383-fc6c59e191ab.png)

**Comment by theiliad** [comment]
Hi @shixiedesign. Regarding the fill & stroke grades. To be able to check those values we'd have to add too much logic. Are we able to agree on a certain ratio for fill & stroke (e.g. is 30% fill opacity good enough for us?)
