### ISSUE TITLE
Real time time-series line graph

### ISSUE THREAD

**Issue by Sandeep066** [carbon-design-system/carbon-charts#258]
### Issue description:

We have a requirement of mapping percentage of resource utilization like cpu,ram,hard disk,garbage collection against time [5 minutes apart or variable]   using line-graph however this feature is missing in react variant of carbon component for carbon charts. [It has bsic line grah but not time -series] 

Please find link below :

https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--label-based-legend

#### Steps to produce the issue

There is no time-series line graph for react variant of carbon charts as in below link -

https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--label-based-legend

However timeseries graph is available in c3.js library:

https://c3js.org/samples/timeseries.html

#### Current behavior

Currently there are Basic,Natural curve,Bundle curve,Monotone Y curve ,Monotone X curve  line graphs for carbon-charts 

#### Expected behavior

Time series line graph is required in carbon-charts to consume it

### Screenshot or recording
<img width="1106" alt="Screenshot 2019-04-23 at 12 01 53 PM" src="https://user-images.githubusercontent.com/12527032/56559724-ff6cf380-65bf-11e9-9ff1-0222f8f27ea0.png">

**Comment by Sandeep066** [comment]
@Cal Smith : We are looking for  this feature by May 10 ,2019 and we are part of "app connect professional [ aka cast iron]" team.

**Comment by theiliad** [comment]
@Sandeep066 Could you please provide me with sample data you would be using?

Given that your timeline is about 2 weeks away, we should be looking at interim solutions. What's stopping us currently from using a convenience function to create `labels` that the library would accept from a set of dates?

**Comment by Sandeep066** [comment]
We are  new to carbon components. Can you please explain the interrim solution in detail  [should have time [ex:03:45 pm 03:50 pm] along x-axis  continuously] ?

**Comment by theiliad** [comment]
Just realized that you have axis lines in there with no labels. That would be tougher to implement currently. Let me get back to you

**Comment by theiliad** [comment]
Hi @Sandeep066. Unfortunately, we are not able to deliver this within your timeline.

What are the options for you? Can we start with a more minimal version of the time-scale that a convenience function will be able to take care of?

**Comment by Sandeep066** [comment]
We are currently using c3js for time series for our requirement as workaround.Please let us know any progress on this issue or eta for same ?

**Comment by theiliad** [comment]
We're currently working on getting final specs on date/time scales, and timeline-wise are looking at Q3. @shixiedesign @cameroncalder

**Comment by PatrickDuncan** [comment]
My team is also seeking the same functionality #277
