### ISSUE TITLE
[React] Chart legends are compressed and appear distorted

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#265]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
At least from 0.11.11

### Issue description
The legends of Bar/Donut/Pie charts appear compressed, and appear distorted.

#### Steps to produce the issue
https://codesandbox.io/s/747p74jnk0
https://747p74jnk0.codesandbox.io/

### Screenshot or recording
![image](https://user-images.githubusercontent.com/46040341/57070816-321c9780-6cf6-11e9-961c-ae2cf456ae05.png)

**Comment by theiliad** [comment]
You're missing
```js
import "@carbon/charts/style.css";
```
