### ISSUE TITLE
Angular Sandbox has dependency issue

### ISSUE THREAD

**Issue by batje** [carbon-design-system/carbon-charts#269]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ x] Demo/documentation defect
- [ ] Other

#### charts version:
latest
### Issue description

The Angular example at https://codesandbox.io/s/k32kjy5qnr gives an error (in FF & Chromium):

`Error
Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency @carbon/charts-angular@0.11.15: Cannot find module 'tslib/package.json' from '/tmp/3020891293/node_modules/@carbon/charts-angular'`

#### Steps to produce the issue
open  https://codesandbox.io/s/k32kjy5qnr
#### Current behavior
error shown
#### Expected behavior
graph shown

**Comment by theiliad** [comment]
Hi @batje. We've been working on that issue, however it seems like CodeSandbox is to blame!

We can't reproduce the error locally or on other platforms, and will switch out of CodeSandbox for our angular demos. Here's a working stackblitz example:
https://stackblitz.com/edit/carbon-charts-angular
