### ISSUE TITLE
Link to Vue Sandbox is dead

### ISSUE THREAD

**Issue by batje** [carbon-design-system/carbon-charts#270]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x ] Demo/documentation defect
- [ ] Other

#### charts version:
latest
### Issue description
the link to the Vue sandbox gives a 404
#### Steps to produce the issue
Open https://codesandbox.io/s/040w2rqrxp
#### Current behavior
404
#### Expected behavior
nice graphs

**Comment by theiliad** [comment]
Yes, working on a new sandbox to point to. You can refer to our storybook demos for sample usage etc...

**Comment by moores2** [comment]
Try:  https://codesandbox.io/embed/pjkrw2omq0  this shows how to import all of the chart wrappers and register them globally as a Vue plugin. You can also import individual wrappers via:
```
import { CcvBarChart } from '@carbon/charts-vue';
...
components: {
     CcvBarChart
},
```
