### ISSUE TITLE
Export typescript types

### ISSUE THREAD

**Issue by testarossaaaaa** [carbon-design-system/carbon-charts#272]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### Current behavior
TS types are not exported, so I can't build own wrappers in ts project

**Comment by cal-smith** [comment]
Which types in particular are you missing? Also which version and package in charts is this?

For core, the definition files, and all the base types should be exported.

**Comment by theiliad** [comment]
I will close this for now since I can locate all the necessary types in the package:
![image](https://user-images.githubusercontent.com/14989804/58825636-e454c100-860c-11e9-8858-162f1456c517.png)

@testarossaaaaa if there are other specific issues you're having, feel free to reopen
