### ISSUE TITLE
white/G10/G90/G100 theme support

### ISSUE THREAD

**Issue by ninja511** [carbon-design-system/carbon-charts#273]

**Comment by theiliad** [comment]
Hi @ninja511. Theme support has been added in the new v0.12.0 release!

https://carbon-design-system.github.io/carbon-charts/

**Comment by cal-smith** [comment]
FYI @ninja511 is our Nina ... this is for the whole theme service stuff - for when we get the white/G10/G90/G100 themes specced out

**Comment by theiliad** [comment]
Yes. I'm going to let @cameroncalder respond.

**Comment by cameroncalder** [comment]
Here's an example for the theme mapping

[Carbon themes.pdf](https://github.com/carbon-design-system/carbon-charts/files/3375319/Carbon.themes.pdf)

**Comment by cameroncalder** [comment]
Here's an example for the theme mapping

![Carbon themes](https://user-images.githubusercontent.com/50155706/60932749-f9b0b100-a284-11e9-9a7d-6706deefd3b1.png)

**Comment by theiliad** [comment]
Duplicate of #244

@natashadecoste

**Comment by theiliad** [comment]
I think these specs have been implemented so far for our existing set of components, I will close for now
