### ISSUE TITLE
Custom tooltip with data in callback

### ISSUE THREAD

**Issue by cgirani** [carbon-design-system/carbon-charts#278]
#### I am submitting a...

- [x] Feature request

### Issue description
Hello, I'm part of the Monitoring IoTP team and we need a custom tooltip. Today the `customHTML` does not provide info about data, line color of the hovering one.

#### Feature Proposal
`customHTML` prop return a callback with data, line info.

**Comment by cgirani** [comment]
- Be able to have info on tooltip if the label is not shown x-axis
- Multiple lines with values for the same data point
![image](https://user-images.githubusercontent.com/22034430/59878091-cc579e00-937d-11e9-958e-0195b774d981.png)

**Comment by cgirani** [comment]
hey, @shixiedesign/ @theiliad  any updates on design/implementation for this issue?

**Comment by shixiedesign** [comment]
@cgirani I think the new tooltip designs meet your need here. Please see https://github.com/carbon-design-system/carbon-charts/issues/285

**Comment by theiliad** [comment]
and being implemented in #307
