### ISSUE TITLE
Legend position prop

### ISSUE THREAD

**Issue by cgirani** [carbon-design-system/carbon-charts#279]
#### I am submitting a...

- [x] Feature request

### Issue description
We have a requirement that the legend of the chart should be on top always. Today it's depending on parent size, to be on top or right.

#### Feature Proposal
- [ ] Provide a prop to the chart where we can set the position of the legend.

**Comment by cgirani** [comment]
hey, @shixiedesign any updates on design for this issue?

**Comment by shixiedesign** [comment]
@cgirani Sorry I was away on vacation last few weeks. Just back and will be looking at Legends as a whole soon.

**Comment by asahlin** [comment]
@shixiedesign @theiliad I am also interested in this.  
Charts look good at this browser size, but as soon as I make the window larger (2nd screen shot), the legend goes to the side and takes up way to much of the viewable area.

![image](https://user-images.githubusercontent.com/13006634/62977010-81895e00-bde3-11e9-887f-7d735b822a97.png)
![image](https://user-images.githubusercontent.com/13006634/62977030-8e0db680-bde3-11e9-8b3c-ec5490ebd37f.png)

**Comment by theiliad** [comment]
we have a refactor in the works for the legend component that'll fix tons of spacing issues

**Comment by shixiedesign** [comment]
Please refer to https://github.com/carbon-design-system/carbon-charts/issues/287 for details on the coming position options.
