### ISSUE TITLE
Displaying Gaps in a time-series line chart

### ISSUE THREAD

**Issue by kennethdnguyen** [carbon-design-system/carbon-charts#280]
#### I am submitting a...
-  Feature request

#### charts version:
v10

### Issue description
We are trying to display time-series data in a line chart, and it’s possible that we won’t have data for every point in time for a given dataset. Right now, the chart just handles null values as 0 and connects the dots, but we would like to have those gaps displayed visually as gaps instead. 

#### Steps to produce the issue
Change one of the values of data to have a null value, and then the line chart will continue to connect the dots using the value 0.

#### Current behavior
<img width="1256" alt="Screen Shot 2019-06-17 at 2 24 57 PM" src="https://user-images.githubusercontent.com/32250825/59627244-c0fd3c00-910b-11e9-8abf-dae4dd501e43.png">

#### Expected behavior
<img width="1285" alt="Screen Shot 2019-06-17 at 10 46 52 AM" src="https://user-images.githubusercontent.com/32250825/59627258-c78bb380-910b-11e9-9d7b-410f147c4bdf.png">

**Comment by theiliad** [comment]
Thanks @kennethdnguyen.

- You mentioned time-series but your x-axis labels are discrete labels. Just want to confirm that you're looking to do this in a time-series graph?
- This will no longer be a continuous scale. Could you elaborate on the cases where you'd want this sort of behavior?
- Do you already do this using another tool? Would like to see more examples of the functionality if you have any...

**Comment by theiliad** [comment]
I played around with this locally, is this what you're hoping to achieve?
![image](https://user-images.githubusercontent.com/14989804/59630809-4553bd00-9114-11e9-92c8-08cec912bdfa.png)

![image](https://user-images.githubusercontent.com/14989804/59630821-4dabf800-9114-11e9-869e-8bc79e713863.png)

**Comment by kennethdnguyen** [comment]
@theiliad Sorry for the very late response. To answer your questions, yes we want to do it in a time series graph. 

The latest screenshot you have attached is definitely what we want to achieve yes. It looks great. Thanks for attaching the screenshot of what you have worked on locally!

Another tool we used in the past to display the data was Kibana. This is what it looks like with the gap in the data. 
![kiban](https://user-images.githubusercontent.com/32250825/60988098-f5ca7080-a310-11e9-9d19-a232e0ef3c25.png)

**Comment by theiliad** [comment]
This has been addressed in #299, and will be implemented in Q1

**Comment by theiliad** [comment]
Closed #464
