### ISSUE TITLE
Legend labels are misaligned in Safari

### ISSUE THREAD

**Issue by feliseuy** [carbon-design-system/carbon-charts#282]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.9.7... and whatever version is being used in the demo

### Issue description
The text is not aligned properly in the legend.

#### Steps to produce the issue
See legends in demo https://carbon-design-system.github.io/carbon-charts/ on Safari

### Screenshot or recording

![image](https://user-images.githubusercontent.com/11200839/59792460-3d298800-92a2-11e9-8a72-dc8fbd035415.png)

**Comment by theiliad** [comment]
Thanks @feliseuy.
The legend component is currently built using HTML elements, but we're switching to SVG, that will fix this issue.

**Comment by theiliad** [comment]
This was fixed by #275. @feliseuy Feel free to reopen if you see the issue in a different version of Safari, I tested in v12.1.2
