### ISSUE TITLE
Change "main" file to "./bundle/bundle.js" in package.json

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#283]
Not exporting the bundle by default can cause build issues in environments not based on ES6

**Comment by bryancboyd** [comment]
Just so it's documented: the `@carbon/charts-react` bundle would also need to require `index.umd.js` from `@carbon/charts`.

The primary use case is to simplify support for testing frameworks like Jest, where the default configuration assumes that bundles in `node_modules/` are in ES5.
