### ISSUE TITLE
Resize chart full width if no legend is rendered

### ISSUE THREAD

**Issue by cgirani** [carbon-design-system/carbon-charts#286]
#### I am submitting a...

- [x] Feature request

### Issue description
If we have only one line, should have the possibility to not show legend. Today we hide our legend but the chart doesn't render the full width. 

### Screenshot or recording

![image](https://user-images.githubusercontent.com/22034430/60021317-2b603000-9668-11e9-80fa-8247175eba00.png)

**Comment by theiliad** [comment]
This is coming soon. Thanks for creating the issue 🙂

**Comment by cgirani** [comment]
hey, @shixiedesign any updates on design for this issue?

**Comment by CynZhang** [comment]
Just to add to that, this is also applicable when multiple data series are present on the chart. We want to be able to keep the legend above the chart as usual, and render the lines in full width.

**Comment by shixiedesign** [comment]
Hi @CynZhang here is the design and you can find layout options. We allow hiding legends but please keep in mind that is not encouraged for multiple data sets. 
https://github.com/carbon-design-system/carbon-charts/issues/287#issuecomment-522162125

**Comment by theiliad** [comment]
This was addressed in #275. Thanks!
