### ISSUE TITLE
Bubble Chart (Scatter + varying sizes for circles)

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#293]
@shixiedesign This is a component that the ADI team is requesting for currently.

Here are the contacts:
- @stanislavgeorgiev (Stanislav Georgiev - Dev)
- Tala El Hallak (Design)

**Comment by stanislavgeorgiev** [comment]
![image](https://user-images.githubusercontent.com/1253469/60294648-d9c9d680-98ef-11e9-9233-51865041c45c.png)

**Comment by shixiedesign** [comment]
Can certainly add to the up-coming chart types. This work might not get started until end of Q3 though I suspect. @stanislavgeorgiev would you be able to provide more product screens (full screens) where this chart is used so I can get the context. Thank you!

**Comment by stanislavgeorgiev** [comment]
@shixiedesign sure, here's a screenshot of the entire page. The idea here is that Marco, the development lead, can see all projects in his enterprise portfolio and plot different metrics about those projects to get a better understanding of their overall health and risks. Marco can see either all projects at once or filter to see only the selected ones (up to 5)

![image](https://user-images.githubusercontent.com/1253469/60346690-b0f61f80-9989-11e9-8668-6b8fc5c1a736.png)

There's also another option to show the tooltip for all projects:

![image](https://user-images.githubusercontent.com/1253469/60346910-2d88fe00-998a-11e9-8ee5-b4135ca6717f.png)

I hope that help a bit.

**Comment by stanislavgeorgiev** [comment]
This one you can assign to me @theiliad

**Comment by cjolif** [comment]
our use-case

![image](https://user-images.githubusercontent.com/623171/64541618-79f5a000-d322-11e9-9fb2-54365bb2ce6b.png)

**Comment by pcoccoli** [comment]
My use case would be plots like this:
https://elitedatascience.com/wp-content/uploads/2017/04/seaborn-scatterplot-example.png

All the examples above look good to me, though.

I need react wrappers, by the way.

**Comment by stanislavgeorgiev** [comment]
👍
