### ISSUE TITLE
Gauge Component

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#294]
Requested by ADI, HQS & SCI.

**ADI:**
![image](https://user-images.githubusercontent.com/14989804/60296780-d38a2900-98f4-11e9-811f-763c80c5a05c.png)

**HQS:**
![image](https://user-images.githubusercontent.com/14989804/60296832-f1f02480-98f4-11e9-9096-4ace51807b8e.png)

**SCI:**
![image](https://user-images.githubusercontent.com/14989804/60910258-4d53d800-a24e-11e9-95e3-70a42655caba.png)

@shixiedesign could you give me an estimation of when we'll be exploring/implementing these?

**Comment by caesarsol** [comment]
Semicircular Gauge:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1799710/78373123-73828a80-75ca-11ea-8bd1-166e8d00f51f.png">
