### ISSUE TITLE
Line chart space between y-axis label and y title

### ISSUE THREAD

**Issue by cgirani** [carbon-design-system/carbon-charts#295]
#### I am submitting a...
- [x] Design defect

#### charts version:
`0.12.4`

### Issue description
Y-axis label formatter not rendering enough space between labels and y title

#### Steps to produce the issue
LineChart card with options:
```
scales: {
    y: {
      title: "Temperature",
      formatter: axisValue => {
        return `${axisValue} ˚F`;
      }
    }
  }
```

#### Current behavior
![image](https://user-images.githubusercontent.com/22034430/60296710-10f2b480-98fd-11e9-9de4-675e6a9d6c66.png)

#### Expected behavior
Good space between y title text and Y-axis label text
![image](https://user-images.githubusercontent.com/22034430/60297063-c9b8f380-98fd-11e9-9592-c453d3c147f7.png)

**Comment by natashadecoste** [comment]
closing this in favour #244 (duplicate issue)
