### ISSUE TITLE
Angular module does not export base chart

### ISSUE THREAD

**Issue by sparikh1594** [carbon-design-system/carbon-charts#298]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.12.2

### Issue description
Can't import any components - charts-angular module doesn't export any components

### Screenshot or recording
![image](https://user-images.githubusercontent.com/43587264/60841853-a278e680-a187-11e9-9c8a-793e34f91787.png)

**Comment by theiliad** [comment]
@sparikh1594 Can I see your setup? The `main` file in `@carbon/charts-angular` is `./bundles/carbon-charts-angular.umd.js` which is a UMD bundle, so you shouldn't see anything about `base-chart.component`

You'll find a StackBlitz project here that uses `@carbon/charts-angular`
https://github.com/carbon-design-system/carbon-charts/tree/master/packages/angular

**Comment by stanislavgeorgiev** [comment]
@theiliad I think this issue could also be added to https://github.com/carbon-design-system/carbon-charts/projects/8

We found that `charts.module.ts` only declares but doesn't export the `BaseChart`.

**Comment by theiliad** [comment]
ok. Did you want to be assigned this too @stanislavgeorgiev?

**Comment by stanislavgeorgiev** [comment]
I think @sparikh1594 wanted to contribute that :)
