### ISSUE TITLE
Scatter chart missing in Angular package

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon-charts#300]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:

0.13.0

### Issue description

Scatter chart is missing from the Angular package and storybook.
Also Scatter chart doesn't show in the README.md.

#### Steps to produce the issue

Angular storybook: https://carbon-design-system.github.io/carbon-charts/angular/

https://github.com/carbon-design-system/carbon-charts/blob/master/README.md
![image](https://user-images.githubusercontent.com/1253469/60916493-7f6c3680-a25c-11e9-9883-f53e4bae46cc.png)

@theiliad You can assign this issue to me @theiliad as I'm starting it now.

**Comment by theiliad** [comment]
Good catch! Should be a fairly simple one in terms of creating the wrapper.

For all the sizing logic though, you should work in the `core` package and let your wrapper just mirror the component in core.

**Comment by stanislavgeorgiev** [comment]
Sizing should be handled in the other issue #293 you created. This one sort of straight forward after a few tips from @cal-smith :-)

**Comment by stanislavgeorgiev** [comment]
@theiliad I think this issue could also be added to https://github.com/carbon-design-system/carbon-charts/projects/8
