### ISSUE TITLE
<Feature Request> Reference Line(s) in Line Chart

### ISSUE THREAD

**Issue by trsiddiqui** [carbon-design-system/carbon-charts#303]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
latest

### Issue description
Unable to add a Reference Line in line charts

#### Expected behavior
Attached is a screenshot taken from a chart generated using Recharts library with a reference line labelled as "AL". It would be great if referenced lines could be added in the line charts.

### Screenshot or recording
![image](https://user-images.githubusercontent.com/4200469/61069260-7fda0e00-a3d1-11e9-8eda-6729f254b851.png)

**Comment by theiliad** [comment]
I would start off by diverting this to our design team.

@shixiedesign @cameroncalder

**Comment by trsiddiqui** [comment]
Ok, what are the next steps?

**Comment by cameroncalder** [comment]
> Ok, what are the next steps?

@trsiddiqui please set up a quick meeting with me to discuss your feature request/timeline.
my email: cecalder@us.ibm.com

**Comment by trsiddiqui** [comment]
Hello @cameroncalder thanks for responding. I dont think we need a meeting for this. I am looking for a similar feature as Rechart's Reference Line feature as shown here => [Recharts - Linechart with Reference Lines](http://recharts.org/en-US/examples/LineChartWithReferenceLines). In recharts, lines can be drawn along any axes by specifying a value on the axis. I saw the threshold feature on the Carbon Line Charts but, 1) I couldnt find any examples or documentation related to it, 2) Threshold feature in Carbon Line Charts looked like an area rather than a line.

**Comment by cameroncalder** [comment]
@trsiddiqui appreciate the live example reference. I'll work with the team to get this in the pipeline. Do you have a specific timeline you're working against for this request?

**Comment by trsiddiqui** [comment]
We have got a six week project that we start working on this Monday. We have only got a handful of charts which wont require much effort. If the feature can be provided in the next 3-4 weeks that would be really great. Thanks.
