### ISSUE TITLE
[Bug] Hide/show of data transitions inconsistent and confusing

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon-charts#305]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.14.1

### Issue description
Removing and adding legends back into charts has inconsistent and sometimes confusing 

#### Steps to produce the issue
1. In the demo page, go to the first line chart
2. Click the Dataset 3 legend to hide the line that corresponds to it
3. Notice that the line fades away
4. Click the Dataset 3 legend again to display the line
5. Click the Dataset 2 legend to hide the line that corresponds to it
6. Notice that the line for Dataset 2 transforms into the line for Dataset 3
7. Click the Dataset 2 legend again to display the line
8. Notice that the Dataset 3 line transforms into the line for Dataset 3

#### Current behavior
When there is an implied order in the legends when adding or removing their data from the chart results in two different animation behaviors:
- If the last legend is removed, the data in the chart fades away
- Otherwise existing data visualization are repurposed and transitioned (no fading away)

#### Expected behavior
I would expect that the data for any legend that is hidden would just fade away. It is the most intuitive way to display the filtering out of data and making it consistent regardless of the legend order would make the visualizations more easily interpretable. 

### Screenshot or recording
![Kapture 2019-07-15 at 13 14 49](https://user-images.githubusercontent.com/5973294/61238669-bcc04080-a702-11e9-96a0-c93c3c638081.gif)

**Comment by theiliad** [comment]
thanks @diego-codes. This is part of the inner workings of d3, which I think we'd be able to override

**Comment by theiliad** [comment]
**Update:** this can be fixed by adding 
```js
(...).data(this._model.getDisplayData().datasets, dataset => dataset.label);
```
