### ISSUE TITLE
IBM Sales Dashboard adoption blockers

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#308]
Getting some feedback forward originally from Saritha Koganti/India/IBM 

> This is regarding leveraging Carbon Angular components in our project IBM Sales Dashboard. Currently work is in progress for web application, will keep you posted on the progress.
> But in case of Mobile App, this seems to be challenging. We do not find few suitable components available or few components would require customization to suit the requirement. Please refer to the below eMail for more details.
> Considering the below listed challenges, for Mobile App we are proceeding with using Ionic components.

and from Swamy Putsala10/India/IBM :  

> Rahul and me have tried implementing the Executive summary default page of the ISD Mobile.
> Our observations upon implementing @carbon/components (version 10.3.2) in ionic application are as follows,
> 1. No component for the gauge chart in carbon-charts, although tried to implement a gauge chart out of a DonutChart from the Carbon-charts but could not customize it up to our requirements, (the component does not allow us to eliminate labels and tooltips).
> 2. Donut-chart does give an option to add two lines of text int he middle of the graph but not image or SVG or any other html  element which we require.
> 3. Bar thickness of the DonutChart cannot be manipulated which we require to make it look like a Gauge Chart.
> 4. Observed that the graph have a minimum width and height of 150px x 150px which makes it difficult to adjust in mobile devices.
> 5. We are able to achieve the required look and feel from the tiles and segments successfully form design prospective using carbon components.
![image](https://user-images.githubusercontent.com/15144993/61970587-b9e70a80-afa2-11e9-80e9-78c311e21fff.png)
> 6. Ionic components are built for mobile apps and they will have specific functionality related to mobile (like tabs, tabs will provide state retention). however, in carbon components we have to implement.
> To conclude customizing carbon components in ionic is too complex as per the requirement. 
> We used the following Carbon Components for development:
> "@carbon/charts": "^0.12.2", "@carbon/icons-angular": "^10.3.1", "carbon-components": "^10.3.2", "carbon-components-angular": "^3.11.3",

**Comment by theiliad** [comment]
Ok, so I see two points here that need to be addressed
1. Gauge component (should be super easy to implement, depending on design specs)
2. Min width & height of charts (we can stop limiting that)

**Comment by theiliad** [comment]
Partially related to #294
