### ISSUE TITLE
Firefox: LineChart isn't expanding to full available card height on firefox causing x-axis overlap

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#309]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.12.1

### Issue description
For some reason on Firefox even though our height is set to 100%, the LineChart isn't expanding to 100%, which is causing some x-axis overlaps:

#### Steps to produce the issue
If you visit this URL from both Chrome and Firefox you can see the difference:
https://carbon-addons-iot-react.com/?selectedKind=TimeSeriesCard%20%28Experimental%29&selectedStory=medium%20%2F%20single%20line%20-%20interval%20hour&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

#### Current behavior
Firefox and Chrome are behaving differently

#### Expected behavior
They both expand to 100%

### Screenshot or recording
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6663002/61984213-a8146000-afc0-11e9-9378-02690cd96b99.png">

**Comment by theiliad** [comment]
It's loading fine for me
![image](https://user-images.githubusercontent.com/14989804/62000730-42050700-b0ac-11e9-96b8-8ffebf66c8e0.png)

What version of Firefox is this?

**Comment by scottdickerson** [comment]
oh my apologies, as soon as I updated firefox it expanded!  Thanks!

**Comment by theiliad** [comment]
@scottdickerson That's good! We should still try to debug that specific Firefox version, can you post the info on that here please?
