### ISSUE TITLE
[React] Chart API not exposed to props.

### ISSUE THREAD

**Issue by kalbert312** [carbon-design-system/carbon-charts#313]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Only `data` and `options` props are available on the bar chart react component. It is not possible to add a bar click handler for example without extending the components to get access to the internal chart instance.

**Comment by theiliad** [comment]
Currently the chart instance can be accessed using `ref`:
```jsx
<BarChart
          data={this.state.data}
          options={stackedBarOptions}
          width="100%"
          height={400}
          ref={bC => (this.barChart = bC)}
        />
```

Then `this.barChart` would give you a reference to the `BarChart` react component, and `this.barChart.chart` will give you the internal chart instance.

Although, we could probably think of better ways to achieve this...

**Comment by theiliad** [comment]
Feel free to re-open if you have more questions/ideas
