### ISSUE TITLE
<Feature Request> Gridline Hover Label Indicator

### ISSUE THREAD

**Issue by natashadecoste** [carbon-design-system/carbon-charts#314]
#### I am submitting a...

- [  X ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.15.1

### Issue description
Need a tooltip or solution to expose the label of a gridline that has been hovered.

#### Current behavior
Gridline tooltips display the values of all points along that label

#### Expected behavior
Gridline tooltip (or other solution) for exposing the X domain label on the hovered gridline. 

### Screenshot or recording
![image](https://user-images.githubusercontent.com/14351335/62735737-d6029700-b9f9-11e9-8963-d005ac150b5e.png)

In above image, there are not labels on ALL gridlines, there should be a gridline hover option for exposing the missing label (s).

This feature is requested by the Watson IoT Platform team

**Comment by shixiedesign** [comment]
WIP does this serve the need of this feature? 

![image](https://user-images.githubusercontent.com/15144993/63625247-a7251d00-c5c4-11e9-89f6-cfe48fe140ec.png)
