### ISSUE TITLE
Doing a data change will change the chart's height

### ISSUE THREAD

**Issue by jdcai** [carbon-design-system/carbon-charts#323]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version: 

0.15.6

### Issue description

When you do a data change either by changing the data or unchecking a dataset in the legend the chart will look different than when it was initially loaded. 
This will only happen the first time you change the data after a refresh.

For my chart in my project I had the chart increase/decrease in height when I changed data.

#### Steps to produce the issue
I made an example that shows the chart changing size. 

https://stackblitz.com/edit/carbon-charts-angular-cgvrhw

Resize the preview on the right so that it's the same size as the border around the chart.
Refresh the page and click on any of the datasets in the legend.
The chart will increase in height.
Clicking on datasets afterwards will not change the height.

#### Current behavior

After changing data for the first time the height of the chart will change.

#### Expected behavior

Chart height should not change when changing data

**Comment by stanislavgeorgiev** [comment]
@theiliad Is there an ETA on this item?

**Comment by theiliad** [comment]
@stanislavgeorgiev Sorry about the confusion, this issue should've been closed by #275

**Comment by stanislavgeorgiev** [comment]
Thanks Eliad, I will test and let you know if I have any questions.
