### ISSUE TITLE
Item in legend disappears when resizing chart

### ISSUE THREAD

**Issue by jdcai** [carbon-design-system/carbon-charts#325]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:

0.15.7

### Issue description
Dataset in the legend will disappear if the window is resized so that the legend becomes horizontal and one of the datasets is hidden due to there not being space for it. Then when it's resized to be vertical legend again one of the datasets will disappear.

#### Steps to produce the issue
Go to https://carbon-design-system.github.io/carbon-charts/angular/?path=/story/bar--stacked and do the below steps

![image](https://user-images.githubusercontent.com/4312305/63607422-73d09700-c5a0-11e9-9034-b0734052b9ac.png)

Shrink browser window so that the legend becomes horizontal and Dataset 4 is hidden
![image](https://user-images.githubusercontent.com/4312305/63607557-c447f480-c5a0-11e9-916d-1829c4c9586d.png)

Expand the browser window again and Dataset 4 will not show up
![image](https://user-images.githubusercontent.com/4312305/63607610-e6417700-c5a0-11e9-8aee-f1b6652d56d0.png)

It will show up when clicking on the + when legend is horizontal but not when its vertical
![image](https://user-images.githubusercontent.com/4312305/63607636-f9ecdd80-c5a0-11e9-92ac-c57961b67d3c.png)

#### Current behavior

Dataset 4 disappears

#### Expected behavior

Dataset 4 should not disappear

**Comment by stanislavgeorgiev** [comment]
@theiliad Is there an ETA on this item?

**Comment by theiliad** [comment]
@stanislavgeorgiev Sorry about the confusion, this issue should've been closed by #275

**Comment by stanislavgeorgiev** [comment]
Thanks Eliad, I will test and let you know if I have any questions.
