### ISSUE TITLE
Stack Bar Chart Angular - Unable to provide conditional precision after decimal values in tooltip. 

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon-charts#331]
Hi,
I am implementing a stack bar chart in Angular.
But, I am not able to provide condition based precision after decimal value as we can only format view on the basis of value we received in formatter.

![image](https://user-images.githubusercontent.com/29912424/64147728-f0843080-ce3e-11e9-9d5c-e72e8449d4fe.png)

Expectation:
- If there are 5 values, then i can provide different precision for them on some condition.
tooltip: {
        formatter: (val) => {
          return `${this._currencyPipe.transform(
            val, this.currencyCode, 'symbol', '1.2'
          )} | ${this.getBreakdownPercentage(val)}`;
        }
for eg.,  3.5 => 3.540
3.2 => 3.20
4.2 => 4.2000
Right now i have to send '1.2' hard coded over there.

**Comment by theiliad** [comment]
@abhisheksinghrana This will be affected by #307 since we'll have different tooltip styles and also a custom HTML function that you can provide...

**Comment by abhisheksinghrana** [comment]
@theiliad , I tried the updated changes. But this issue is related to provide some custom config for calculation inside popover formatter.

**Comment by theiliad** [comment]
@abhisheksinghrana I'm still trying to understand what you're trying to do... The formatter function is just a callback to any function that you provide. You choose how the values will be formatted in your function... Am I missing something?
