### ISSUE TITLE
Legal use of the system

### ISSUE THREAD

**Issue by SokolSM** [carbon-design-system/carbon-charts#332]
Hi guys,
I like your design system very much. A question:
There is mentioned that this system is open source for anyone https://www.carbondesignsystem.com/contributions/governance#contributor-license-agreement.
Just to clarify, does that mean that I can use it in my project (which is not a part of IBM family)?
Sure thing I'll not use your visual style, but only some principles and general structure.
I want to know if that legal.

#### I am submitting a...

- [ ] Other

**Comment by cal-smith** [comment]
The CLA just covers contributions _to_ the design system. The system is open source under the Apache 2.0 license - You can (and should!) use our visual styling, components, principals, structure, etc, whatever you need to make your project successful 💯

**Comment by zvonimirfras** [comment]
If you need additional clarification, feel free to reopen.
