### ISSUE TITLE
[React] Donut chart doesn't honor the colors passed in the configuration

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#334]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.15.8

### Issue description
The colors of the Donut chart are not as per the specifications provided by the input.

#### Steps to produce the issue
1. Define custom color array for a Donut chart
2. Pass the color array to the `DonutChart` component

#### Current behavior
The sections in the chart doesn't render in corresponding colors.

#### Expected behavior
The sections should render in the same order as passed by the configuration color

### Screenshot or recording
https://codesandbox.io/s/xlkpxqw59p

**Comment by theiliad** [comment]
This is not really an unintentional bug...

We sort the slices based on value, however I think we should still respect your order of colors provided to us.

@shixiedesign?

**Comment by natashadecoste** [comment]
@kalai001 the values are sorted in descending orders to be displayed on the pie chart and the colors are applied in the same order **at that time.** The colors are not passed in and associated with the datasets the same way the labels are associated to them on initialization. if the datasets **are not** sorted into descending order (clockwise around the pie/donut) then the colors would be assigned as expected however there would be no support for callout labels (see picture below). 

![image](https://user-images.githubusercontent.com/14351335/64427940-6b885980-d080-11e9-9f2f-c2367347eb0b.png)

Sorting the pie chart slices is a common practice in data visualization. If it solves your problem to have a configuration for not sorting, we can move forward with that if the design team is in agreement.

Our ordering is option 2:
![image](https://user-images.githubusercontent.com/14351335/64428372-8dcea700-d081-11e9-9939-b39c68acd3fe.png)



reference: https://visage.co/data-visualization-101-pie-charts/

**Comment by danielnguyen** [comment]
I'd like to second this request. There are situations in which colors need to be associated to the specified labels (such as to represent severity or importance), and not having the ability to map colors to their labels is an unfortunate gap.

Are there any alternative approach we can try to temporarily overcome this issue?

**Comment by caiobozato** [comment]
I'm still having the same issue on Vue version

**Comment by theiliad** [comment]
I don't think we have a design decision on this topic yet. I'll bring up with design

**Comment by kalai001** [comment]
@theiliad , 
Digging deep into this issue, I found that the sorting of the slices aren't consistent. The values are sorted and the labels are ordered as per that. But the colors are left as is. It has to be consistent. Either sort and order all or none.

Need a confirmation from Carbon team if this is going to be addressed or not. We have a customer reported issues pending on this. If Carbon team isn't handling, we'll have to put in a work around.

**Comment by mjabbink** [comment]
Agree option 2 is a preferred way to go from my perspective. Confirming with some other folks as well.

<img width="203" alt="Screen Shot 2019-12-18 at 5 22 51 PM" src="https://user-images.githubusercontent.com/32881239/71131792-4ea10d80-21bb-11ea-874c-6ce7deb8495b.png">

**Comment by theiliad** [comment]
> Agree option 2 is a preferred way to go from my perspective. Confirming with some other folks as well.
> 
> <img alt="Screen Shot 2019-12-18 at 5 22 51 PM" width="203" src="https://user-images.githubusercontent.com/32881239/71131792-4ea10d80-21bb-11ea-874c-6ce7deb8495b.png">

So we do apply the option 2 approach currently. The issue here is that because we sort the slices based on value, the set of colors the user specified for those slices don't get applied in the same order they provided, rather in the order of the sorted slices.

**Comment by kalai001** [comment]
Ok, what is the conclusion from dev on the ordering of colors? Will the chart component take care of it, or the consumer has to explicitly order as per the values? 
Refer: https://github.com/carbon-design-system/carbon-charts/issues/334#issuecomment-562830973

**Comment by theiliad** [comment]
> Ok, what is the conclusion from dev on the ordering of colors? Will the chart component take care of it, or the consumer has to explicitly order as per the values?
> Refer: [#334 (comment)](https://github.com/carbon-design-system/carbon-charts/issues/334#issuecomment-562830973)

The issue with ordering the colors would be accessibility. Still looking to design to solve the issue

**Comment by kalai001** [comment]
Any updates? Can we have an ETA on this ?

This is not an accessibility issue btw. In our service, the colors in the chart represents severity (like red for failure, green for success etc). If the are not rendered right, the whole meaning changes.

**Comment by anne-stevens** [comment]
Responding to slack request from @theiliad here's my opinion of Pie and donut chart best practices:

1. as per majority opinion above, slices should be sorted from biggest to smallest going clockwise from noon
2. slice order could change as a result of filtering or some other interaction.  In this case, assuming slices are always sorted biggest to smallest, the relative position of a particular slice might change.  In this case, to minimize cognitive load and help the user understand the transition, colour assignment should not change.  In other words, if member-slices/colours were originally sorted and rendered this way: Cars/purple, then Trucks/blue, then Bicycles/green, then Trains/orange, and I filtered out, say, last year's sales and the sort order changed so that there were more Trucks sold, then the new chart would be rendered Trucks/blue, then Cars/purple, then Trains/orange and then Bicycles/green.  In other words, the member-segments are always sorted biggest to smallest but the colour assignment is consistent so that I can easily follow the one I'm interested in. 
3.  colour order in the legend should be consistent before and after the interaction.  If a colour is removed from the chart as a result of the interaction, it should be removed from the legend as well to avoid confusion about why there are more colours in the legend than in the chart.

If I understand the comments above correctly, I believe these requirements would mean that both label and colour would have to be assigned on the initial rendering and that the colour assignment would have to persist.

**Comment by anne-stevens** [comment]
An example of a pie chart (ignore the fact that it sorts counterclockwise from noon).  Initial rendering:
![image](https://user-images.githubusercontent.com/59665153/72010403-c7790f80-3225-11ea-9ea7-3cb7f6a562ef.png)

After filter interaction, relative order of Spanish, Japanese and Chinese has changed, but colour assignment is the same.  This is important b/c if the slices were similar in size, it would be very difficult to notice that the order changed if the colour order was always the same:
![image](https://user-images.githubusercontent.com/59665153/72010538-06a76080-3226-11ea-852b-935e18b876ea.png)

Legend order does not change between the two.

**Comment by theiliad** [comment]
Thanks @anne-stevens. That is what we've needed a decision on basically.

So everything you mentioned above happens already except for re-ordering the assigned colors to the sorted labels, which I think is good practice and we should implement

**Comment by kalai001** [comment]
@theiliad , Can this be expedited ? We have a long pending customer issue on this. It has been close to 5 months since it was reported.

**Comment by theiliad** [comment]
@kalai001 yes, working on releasing it soon

**Comment by kalai001** [comment]
@theiliad , Is color configuration supported by Donut chart now or not? It was before (around 0.10.x versions). The colors passed in this example are not being applied at all (https://codesandbox.io/s/xlkpxqw59p). The primary issue reported in this defect that colors passed in the configuration hasn't been honored. But, looks like other surrounding issues have been addressed, but not the core issue.

**Comment by theiliad** [comment]
@kalai001 `backgroundColors` were renamed to `fillColors` for readability purposes
