### ISSUE TITLE
[React]: LineCharts allow us to disable tooltips with a property

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#336]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.12.0
### Issue description
is there an prop option to hide the tooltip in the LineChart react?  Our line chart is in "preview" mode so it's not real data and we don't want tooltips to show

**Comment by natashadecoste** [comment]
👍 Closing this, it will be supported to toggle tooltips (single and gridline) on and off with new configs + new tooltips after merge: https://github.com/carbon-design-system/carbon-charts/pull/307
