### ISSUE TITLE
ADDI Immediate Needs

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#345]
- Bubble chart
![image](https://user-images.githubusercontent.com/14989804/64797529-8ad72900-d54f-11e9-9828-823dce19180b.png)

- Gauge
![image](https://user-images.githubusercontent.com/14989804/64797555-91fe3700-d54f-11e9-9aa5-17862fae3541.png)

- Horizontal bar
![image](https://user-images.githubusercontent.com/14989804/64797580-99254500-d54f-11e9-9d06-98804dc00aa8.png)

**Comment by jagdishkumar1** [comment]
@theiliad when can we expect guages/meter to be part of carbon charts

**Comment by theiliad** [comment]
@jagdishkumar1 very soon! #425
