### ISSUE TITLE
docs(contribution): Refine topology chart from the Design System Adoption Guild

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-charts#346]
### Context

This is an open issue in the Design Systen Adoption Guild repo. Following feedback from @shixiedesign, the following must happen before the chart is ready for experimental release.

Link: https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/79

#### Next steps (re: Shixie)

There is some additional information required before this would be ready for posting.

- [ ] What’s the data model? Is there going to be data in the edges? We can’t determine what we’re looking at.
- [ ] We would need to know what kind of data goes in, why is it visualized in this way, how do people interact with it, how do they dig in, is there a progressive data disclosure.
- [ ] The definition is also needed. Define what is going to be mapped out here.
- [ ] Name, relationship, category description — these would give me the understanding of what data is being mapped out.

**Comment by theiliad** [comment]
@connor-leech is there an action item here we can move forward on?
