### ISSUE TITLE
Inbuilt support to download chart as Pdf/Png. 

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon-charts#357]
Need a support to download chart as pdf/png.

**Our requirement :** 
We have to download chart with some data table as pdf.
So, in that case we require some api to get it as image. By which we can download entire view as pdf.

**Timeline :**
We require this by end of November, 2019

@theiliad

**Comment by theiliad** [comment]
I'll investigate this a bit.

Usually, PDF generation requires some backend processing...

Saving to SVG wouldn't be too bad since you'd just save the DOM SVG + couple of styling additions...

**Comment by scottdickerson** [comment]
@theiliad we had png saving requirements and went with this library but it only supported Firefox and Chrome and I'm not sure you can get away with that..https://github.com/tsayen/dom-to-image

**Comment by theiliad** [comment]
These libraries usually don't do well with a full SVG chart. There are always some `<rect>` elements or `<path>`s taking on the wrong fills etc.

Also the addition of that library to the bundle wouldn't be ideal.

This is a complex piece of functionality. I'd like to keep the discussion going for a while before we actually execute

**Comment by theiliad** [comment]
Looking into this issue it seems like there isn't currently an efficient way to export a chart in the browser to PDF or PNG. Going to hold off for now.

You can easily achieve that result on the backend though, running a headless browser such as `puppeteer` and just rendering saving the resulting chart onto a PNG would be my first guess.
