### ISSUE TITLE
Usecase input on Heatmap

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon-charts#359]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [X] Other

#### Description (sorry, original headers did not fit with the role of this issue):

Spotting the heat-map example in the [newly released visualisation documentation](https://www.carbondesignsystem.com/data-visualization/advanced-charts) on the site.
![image](https://user-images.githubusercontent.com/30671949/66200354-c66d9a80-e698-11e9-8f8c-f3de04f8b935.png)

I noticed with glee, that in the example the X-Axis is time buckets, and Y-Axis being value buckets. I'm also aware that this isn't always the most common usage of heatmaps.

This issue to chip in a use case from one of my projects around heatmaps with some examples, rationale etc. And of course to offer what help I can from a design side of edging it towards reality.

----

**Usecase:**

- IoT 👋 
- We are familiar with the most common case of IoT with charting, numeric time series usually using a line chart base to tell you something about a single device (eg: temperature over the last day):
![image](https://user-images.githubusercontent.com/30671949/66216965-5b36bf00-e6be-11e9-8683-6385b89a97e3.png)

- Now, zoom out and look at a large group of devices, and try to get an understanding of the lay of the land in terms of how they are performing in terms of temperature. Typically we go with 3 lines now - Min, Max and Mean to provide that overview:

![image](https://user-images.githubusercontent.com/30671949/66216979-5f62dc80-e6be-11e9-9c65-ff8f4ab4c5d4.png)

- The purpose of these kinds of views is manyfold, but one example would be when calibrating threshold rules against that data item. Getting an idea of how the group usually behaves is a great way to start and understand where the thresholds should be placed.

- **The downfall** is that, without some more complex things going on behind the scenes, the above concept is very open to being skewed by outliers in the group, and even worse - you can't see what the outlier is exactly.

- **The proposal** is a time-series heatmap capability, which would bucket by a given time grain, and value groups, so now the user would be able to see how many devices in the group were which temperatures over the course of the day, [such as this example from Graphana](https://grafana.com/docs/features/panels/heatmap/):

![image](https://user-images.githubusercontent.com/30671949/66215959-7b657e80-e6bc-11e9-875c-635c745bf5d7.png)

As an aside, in our IoT world, we'd probably want to go even further and allow the tooltip to tell you the count, but also have an interaction to fetch the list of devices that were members of that block. 

-----

**Conclusion:**
- Not quite a feature request, as the design for heatmaps may already cover the case.
- Happy to pitch in to help with no-code elements if and where necessary 😄

**Comment by theiliad** [comment]
I'm going to loop in @cameroncalder here to comment from a design perspective
