### ISSUE TITLE
Update styles to work with the Carbon Design System

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-charts#360]
Hi there! 👋 Was going through the latest release and noticed a regression on the website due to a class name conflict (related PR on website: https://github.com/carbon-design-system/carbon-website/pull/441)

After looking into the styles for carbon-charts, it would be great if we could update them to be fall in line with how we do styles at the system level and also help prevent regressions in the future. 

Some quick notes that would be great to see changed:

- [x] All selectors use the `$prefix` variable from Carbon styles in the form: `.#{$prefix}--my-selector`
  - This helps to prevent collisions and namespaces selectors for the design system
- [x] Update how themes are being brought in
  - Currently they are brought in under a selector such as `.carbon--theme--g90`
  - Theme-related styles should be opt-in instead of included by default. Authoring styles such that they use color tokens should allow this to work by default
- [x] Update styles imports to not include paths to `node_modules` and instead inline dependencies or specify a configuration for `includePaths` on `node-sass`
- [x] All type should derive from the carbon type package or associated behavior loaded in `carbon-components`, namely `carbon--type-style` for applying type tokens. If the type tokens don't exist, can definitely add them in!
  - This also includes things like font-family and loading in IBM Plex
    - https://github.com/carbon-design-system/carbon/tree/master/packages/type#font-family
- [x] Use color tokens instead of specific color values from the IDL, if colors from the IDL are needed please load from carbon styles
- From a style guide perspective:
  - We tend to prefer not nesting styles from a maintenance perspective
  - We tend to prefer class name selectors over element selectors (for example relying on a `span` element)
  - For spacing, we tend to use either our spacing tokens or specify them in `rem` values
  - We never use `!important` in property values
- Icons should always be loaded from `@carbon/icons` or an associated library instead of inlined in CSS

Let us know if it'd be helpful to hop on a call and chat about this stuff! Just wanted to leave some quick notes to make sure everything works together well 😄

**Comment by theiliad** [comment]
Hi @joshblack 👋This is great feedback, thanks 🙂 

Many of these points have been addressed in the refactor PR, but I'll comment on some specific ones as well.

> Hi there! 👋 Was going through the latest release and noticed a regression on the website due to a class name conflict (related PR on website: [carbon-design-system/carbon-website#441](https://github.com/carbon-design-system/carbon-website/pull/441))
> 
> After looking into the styles for carbon-charts, it would be great if we could update them to be fall in line with how we do styles at the system level and also help prevent regressions in the future.
> 
> Some quick notes that would be great to see changed:
> 
> * All selectors use the `$prefix` variable from Carbon styles in the form: `.#{$prefix}--my-selector`
>   
>   * This helps to prevent collisions and namespaces selectors for the design system
> * Update how themes are being brought in
>   
>   * Currently they are brought in under a selector such as `.carbon--theme--g90`
>   * Theme-related styles should be opt-in instead of included by default. Authoring styles such that they use color tokens should allow this to work by default
This is great, let's do it. Also we need to add some new colors onto the `@carbon/colors` package to include some colors needed for the new color palette.
> * Update styles imports to not include paths to `node_modules` and instead inline dependencies or specify a configuration for `includePaths` on `node-sass`
> * All type should derive from the carbon type package or associated behavior loaded in `carbon-components`, namely `carbon--type-style` for applying type tokens. If the type tokens don't exist, can definitely add them in!
>   
>   * This also includes things like font-family and loading in IBM Plex
>     
>     * https://github.com/carbon-design-system/carbon/tree/master/packages/type#font-family
This is great!
> * Use color tokens instead of specific color values from the IDL, if colors from the IDL are needed please load from carbon styles
We do use color tokens, however some are missing, so we'll need to make PRs there to add them in, then update...
> * From a style guide perspective:
>   
>   * We tend to prefer not nesting styles from a maintenance perspective
>   * We tend to prefer class name selectors over element selectors (for example relying on a `span` element)
>   * For spacing, we tend to use either our spacing tokens or specify them in `rem` values
>   * We never use `!important` in property values
Yes. This is all removed in the refactor.
> * Icons should always be loaded from `@carbon/icons` or an associated library instead of inlined in CSS
Yes, refactor...
> Let us know if it'd be helpful to hop on a call and chat about this stuff! Just wanted to leave some quick notes to make sure everything works together well 😄

**Comment by alisonjoseph** [comment]
@theiliad what is the ETA on the refactor being published?

**Comment by theiliad** [comment]
@alisonjoseph PR has been in review for about a week now. I'd say another week probably?

**Comment by theiliad** [comment]
Going to move a few of these points to the next PRs:
> Icons should always be loaded from @carbon/icons or an associated library instead of inlined in CSS
Icons are only used in the vanilla demo site. I'll investigate using `@carbon/icons` there, however I think this is a lower priority item since it's the demo site.

Also:

> - We tend to prefer class name selectors over element selectors (for example relying on a `span` element)
> - For spacing, we tend to use either our spacing tokens or specify them in `rem` values

We'll address soon
