### ISSUE TITLE
Please provide onClick -  (Output) event on the x-axis data set of line graph and bar graph angular charts.

### ISSUE THREAD

**Issue by nethravikram** [carbon-design-system/carbon-charts#373]
#### I am submitting a...

-  Feature request

#### charts version:
v0.16.17
### Issue description
We need onClick event on line graph and Bar Graph data set. Example: On clicking on the data point of the line/bar graph, an event to be passed to the consuming app with the corresponding data set so that, we get to display more information on the table related to that. same feature for the bar graph as well.

### Screenshot or recording
<img width="348" alt="image" src="https://user-images.githubusercontent.com/16252150/66772441-6073e500-eeda-11e9-84e1-298745b24439.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/16252150/66772714-00317300-eedb-11e9-86fb-f6307167469c.png">

**Comment by theiliad** [comment]
This is already available: https://github.com/carbon-design-system/carbon-charts/blob/e3f60f19bb706c066e45913906ea73c7c4373896/packages/core/demo/index.ts#L152-L174 (That example is for bar, in the case of line, you can also use `"line-onClick"`)

However in the refactor, I'm going to do a pass through all the graphs and components, and as a result event names might change with that release. In the current version you can go ahead with those values

**Comment by LuDre** [comment]
How do I add an event listener to a chart in Angular, if I only have this line in my html file?

`<ibm-circle-pack-chart [data]="circlePackData" [options]="circlePackOptions"></ibm-circle-pack-chart>` 

Is there a handy way to do so? E.g. `(circle-leaf-click)="myEventFunction()"` 

Or is there any tutorial how to add event listeners in Angular? I just found one for vanilla and react.
