### ISSUE TITLE
Where is the documentation for the React <LineChart>?

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-charts#375]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:

0.16.17

### Issue description

I am trying to find the documentation for your React `<LineChart>` component and I can't...

#### Steps to produce the issue

* Start at [https://www.carbondesignsystem.com/data-visualization/getting-started/vanilla](https://www.carbondesignsystem.com/data-visualization/getting-started/vanilla).
* Go to the React tab ([https://www.carbondesignsystem.com/data-visualization/getting-started/react](https://www.carbondesignsystem.com/data-visualization/getting-started/react)). Scrolling down to "Getting started" shows example usage for `<BarChart>` but nothing for any other kind of chart.
* Look for a "Documentation" link... nothing...
* Under "Resources", click "Try Carbon Charts React components with CodeSandbox"  ([https://codesandbox.io/s/pppmo3ollx](https://codesandbox.io/s/pppmo3ollx)). Another `<BarChart>`, no help.
* Go back and under "Resources" try "Carbon Charts React", bringing me to [https://github.com/carbon-design-system/carbon-charts/tree/master/packages/react](https://github.com/carbon-design-system/carbon-charts/tree/master/packages/react).
* Still no documentation and very short README.
* Click "Storybook Demos", end up at [https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--label-based-legend](https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--label-based-legend)...
* Aha, a `<LineChart>` demo! [https://carbon-design-system.github.io/carbon-charts/react/?path=/story/line--basic](https://carbon-design-system.github.io/carbon-charts/react/?path=/story/line--basic)
* No help... but I click "Show info" in the top right to see sample code... this gives me a section "Story Source" with a very brief (incomplete, unexplained) example `<LineChart>`, and a "Prop Types" section which says "No propTypes defined!"
* Try going back to the main page again. This time, in the left panel, select "Chart types" ([https://www.carbondesignsystem.com/data-visualization/chart-types](https://www.carbondesignsystem.com/data-visualization/chart-types)). Here we see a line chart under "Trends", great...
* Click the line chart to go to [https://www.carbondesignsystem.com/data-visualization/basic-charts#line-chart](https://www.carbondesignsystem.com/data-visualization/basic-charts#line-chart). Just an example `<LineChart>`, no way to find out how it works, no link to additional information.

#### Current behavior

I would expect your documentation to be easy to find...

#### Expected behavior

I can't find it, after a fairly thorough search.

### Screenshot or recording

![image](https://user-images.githubusercontent.com/9932290/67023185-487aac00-f0fa-11e9-8c79-2c5ce3acd470.png)

![image](https://user-images.githubusercontent.com/9932290/67023484-c8087b00-f0fa-11e9-936d-fa24d9458a9e.png)

![image](https://user-images.githubusercontent.com/9932290/67023979-8fb56c80-f0fb-11e9-9ea9-334f671d9d61.png)

**Comment by s100** [comment]
To give a specific example of what I'm trying to do, I'm trying to create an XY line plot which shows a metric changing over time. The X axis is time and the Y axis is the value of the metric (throughput in messages per second, say). Currently there seems to be no way to treat the X axis as a continuous axis - instead, the best I can do is provide the specific string names of points on the X axis, which then get rendered at equal distances apart from one another. So if I have a data point for 12:00:00, and another for 12:30:00, and another for 17:00:00, the three points get rendered equal distances apart, which is clearly not what I want. We see this in your example [here](https://www.carbondesignsystem.com/data-visualization/basic-charts/#default-1), where the X axis has labels "Qty", "More", "Sold" and so on, and clearly isn't serving as a continuous axis, it's just a disguised bar chart.

Can `@carbon/charts` do this?

**Comment by theiliad** [comment]
Hi, yes the refactor PR (#275) includes the time-series functionality, which is being merged next week.

In terms of documentations, currently we have the API reference (https://carbon-design-system.github.io/carbon-charts/documentation/interfaces/_configuration_.linechartoptions.html).

More elaborate documentations are in the works including PropTypes, examples and more code samples

**Comment by s100** [comment]
That PR will be very useful to me if it gets merged next week! It's been open since June though so I hope it doesn't get delayed too much longer.

**Comment by theiliad** [comment]
Hi, please refer to:

https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--simple-bar-time-series-turkish

Here are the data & options used for the demo above:
https://github.com/carbon-design-system/carbon-charts/blob/4a3727d13796030866e1416effdc48b274bdb401/packages/core/demo/demo-data/bar.ts#L104-L150
