### ISSUE TITLE
tooltip: Add the x-axis value into the tooltip

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#376]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.16.17 with the refactor
We'd like an option to show the x-axis current value at the top of the new tooltips.  We have lots of data points and there aren't enough ticks in the axis to be able to tell which datapoint corresponds to what date/time.

![image](https://user-images.githubusercontent.com/6663002/67052534-12dac080-f104-11e9-8617-6abd4f1dfad6.png)

#### Expected behavior
This is using the new refactored tooltip code, the idea is to have the x-axis value at the top of the tooltip somehow identified.

**Comment by theiliad** [comment]
So the only todo here is to pass in the x-axis value into the custom HTML formatter you can use. The formatter will also provide you the HTML we generate that's showing up in your screenshot, so you'd prepend your title to that

**Comment by theiliad** [comment]
@scottdickerson I think #389 should get you going with that functionality. Let me know if anything is missing in there, thanks.
