### ISSUE TITLE
Legend color swatch radius should match check box

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-charts#383]
The current legend color swatch is too round on the corners. @shixie or @cameroncalder to supply specification.

Current (Too round):
<img width="247" alt="Screen Shot 2019-10-24 at 8 50 44 PM" src="https://user-images.githubusercontent.com/32881239/67537217-fe686c00-f69f-11e9-9f8a-58bc5b8fbc7a.png">

**Comment by cameroncalder** [comment]
**1px border radius**

![image](https://user-images.githubusercontent.com/50155706/67579263-b847f280-f709-11e9-83e6-1a7b31e6c9c6.png)

**Comment by theiliad** [comment]
This is already been addressed!

The refactor (which we merged in yesterday) updated those styles.

That demo is the old version of charts on the Carbon Website, which I've updated in this PR, pending merge: https://github.com/carbon-design-system/carbon-website/pull/530
