### ISSUE TITLE
[LineChart]: Need localization support for the axis of time series

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#388]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.16.24
### Issue description
Set your language to French and view a LineChart graph instead of seeing the French months you see them in English

![image](https://user-images.githubusercontent.com/6663002/67636172-d9404d00-f89b-11e9-9a09-e3c8d01e75d6.png)

**Comment by scottdickerson** [comment]
@theiliad can you also do the tickFormatter function callback as part of this.  I believe our designers want to have custom tick axis labels instead of the default format you're providing (regardless of language)

**Comment by theiliad** [comment]
> @theiliad can you also do the tickFormatter function callback as part of this. I believe our designers want to have custom tick axis labels instead of the default format you're providing (regardless of language)

Yes, both already done in #390, pending merge
