### ISSUE TITLE
[LineChart]: Need ability to customize a particular point color on the line

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#398]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.16.25

### Issue description
I have a usecase where we need to markup a particular datapoint of a line differently than the others to indicate an alert

#### Current behavior
All points for a line chart have the same basic radius or filled/unfilled rendering, would like to pass an array of css classes to add to the points

#### Expected behavior
![image](https://user-images.githubusercontent.com/6663002/67806159-5b796e80-fa60-11e9-9fde-23da2c8fb7c0.png)

**Comment by scottdickerson** [comment]
I think I can accomplish almost all of this with some minor changes to getFillColor and getStrokeColor of scatter.ts, will put in a PR suggesting this..

**Comment by theiliad** [comment]
@scottdickerson Did you need help setting up that PR? Let me know 🙂

**Comment by theiliad** [comment]
Closed by #422
