### ISSUE TITLE
Vallina version seems not working

### ISSUE THREAD

**Issue by linzhaoken** [carbon-design-system/carbon-charts#399]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
Vallina Version

### Issue description
I tried both bundled version and browser env, both are not working. I followed the steps here https://www.carbondesignsystem.com/data-visualization/getting-started/vanilla#install

![image](https://user-images.githubusercontent.com/4997989/68144287-3fc40b80-ff2b-11e9-8144-cb0f990fcbe0.png)

![image](https://user-images.githubusercontent.com/4997989/68144322-566a6280-ff2b-11e9-958d-7ff11b1298d6.png)

**Comment by theiliad** [comment]
Hi,
In all versions > `0.16.9` please use `bundle.js` instead of `index.umd.js`

And `styles.css` instead of `style.css`
