### ISSUE TITLE
[Legend]: Would like to right-align the Top and Bottom positioned legends

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#400]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.16.25

### Issue description
I'm using the latest charting and putting my Legend in the TOP position, but my designers don't like the fact that it's left aligned.  Can I somehow have it be right-aligned when the legend is on TOP or BOTTOM?

### Screenshot or recording
![image](https://user-images.githubusercontent.com/6663002/68243940-4b6e0b80-ffd9-11e9-8c7d-6b53d4fd3f34.png)

**Comment by theiliad** [comment]
Hi,
I haven't seen anything about this in the design specs or the design discussions that have happened.

Here are the current legend guidelines:
https://www.carbondesignsystem.com/data-visualization/legends

I can bring up the suggestion to the design team.

**Comment by theiliad** [comment]
closing this as I haven't seen any conversations happening around it. Not sure if enabling this would really be beneficial. Feel free to reopen
