### ISSUE TITLE
[LineChart]: the default date range for one days worth of data is too wide

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#403]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.16.25

### Issue description
If I create a timeseries chart and give it 24 hours of data (one per hour), the x-axis crosses 3 day boundaries so there's lots of wasted space to the left and the right.

### Screenshot or recording
![image](https://user-images.githubusercontent.com/6663002/68352332-b992fb00-00cb-11ea-95c6-5ac9b59e77ff.png)

**Comment by scottdickerson** [comment]
I tried disabling the timeScale options with addSpaceOnEdges to false, but then I get much worse looking axis ticks with overlapping axis ticks:

![image](https://user-images.githubusercontent.com/6663002/68627862-81613300-04a4-11ea-9278-cf1a8312d0e2.png)

**Comment by theiliad** [comment]
This is due to `addSpaceOnEdges` adding a day on each side.

I'm going to think of a way to detect a smarter amount of time added on both sides rather than a full days regardless of the distribution of your data.
