### ISSUE TITLE
Could you please remove the dependency on `bash` to install this package

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-charts#404]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
All

### Issue description
`yarn install @carbon/charts` on some windows will result in `command not found` as the post install has to run `bash`.

https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json#L12

#### Steps to produce the issue
Try installing on a version of windows where WSL is not installed and `bash` is not installed.

#### Current behavior
It fails

#### Expected behavior
We should not be adding more friction to the install process by forcing a user to install extra tools just to satisfy some post install process.

If you require a post install script, then write it in JavaScript since, you absolutely know that it will be installed.

You should ban any script that is a .sh and simply use portable commands OR install dev dependencies such as `shx` that can be used to emulate most of the command commands that you'd run in a script.

In looking at the post install script this is simply doing a bunch of cp commands which means it all could have been put into the pacakge.json directly (yes, not as pretty, but would have workded at least).

As a project guideline you shoudl forbid any checkins of .sh files especially if htey are used as a post install.

### Screenshot or recording
https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json#L12

I'm a linux developer and I get that using bash can be handy... but unfortunately not everyone uses bash as their goto shell, especially on windows.   The sad part for us, is that we are not using carbon charts, but depend on something else that just pulled it in between versions.  So upgrading our dependency slipped us a cabon charts and then nuked many of our windows developers and qa people as they now had to decipher why they were getting a `command not found` error.

**Comment by theiliad** [comment]
Hi, there is no dependency on bash

As you mentioned that you are using v0.16.25, I'll post the package.json file for that version here:
https://unpkg.com/@carbon/charts@0.16.25/package.json

There is no postinstall script to be ran, therefore you're definitely not running v0.16.25. You might have a cache of an older version (we had 2 version that shipped mistakenly with the postinstall script, however all the latest version exclude that script at deploy time)

To conclude, to use the library I do not see any dependencies on bash (unless you're developing the library, which can be removed but also considering the bash support in Windows should be fine). (edited)

**Comment by stuckless** [comment]
Are the multiple versions of carbon charts... since the package.json that I linked to from the master... clearly shows a post install script that is a .sh file... and that is on the master??

**Comment by theiliad** [comment]
@stuckless As I mentioned the `postinstall` script exists internally within the library. Therefore if you're looking to fork the repo and contribute some code it'll run for you.

However when you consume the library off of NPM, the `postinstall` script will not exist on there because it isn't necessary. We remove that script right before deploying to NPM.

https://unpkg.com/browse/@carbon/charts@0.19.0/package.json

> (we had 2 version that shipped mistakenly with the postinstall script, however all the latest version exclude that script at deploy time)

**Comment by stuckless** [comment]
I'm not even using carbon charts... something I depended on brought it in... and it was joyful (not) see several sqauds of windows developers fail because of "bash not found" as the postinstall script got invoked.   I guess if you are saying "It's not you", then I guess it's not you.

**Comment by theiliad** [comment]
No as I mentioned this was a mistake on our part.

In 2 versions we shipped out the `postinstall` script, and immediately removed it in a newer version once we realized that that is happening.

So the package you depended on unfortunately was using 1 of those 2 versions. Sorry about the inconvenience 🙂

**Comment by theiliad** [comment]
Btw the fix in v0.16.22 was pushed less than 24 hours after the bug was introduced.

It is really unlucky that the package you depend on pushed a new version within that timeframe using the broken 0.16.21 version.

**Comment by stuckless** [comment]
Thx for the update... I'll wait for newer library update (not from you) but from the dependency that I'm using, and hopefully that resolves my issues.  But as of now, all windows developers has "bash" installed and as such it's less of an issue.  But, yeah, I guess bad timing :(  thx again for the update.
