### ISSUE TITLE
Histograms

### ISSUE THREAD

**Issue by pcoccoli** [carbon-design-system/carbon-charts#406]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

I need a histogram.  Preferably with a way to input pre-computed bin edges (which is done already in my back-end code).  I have both integer and floating point data, and need to show the distribution of that data.

I'm using the react wrappers, by the way.

D3 histograms: https://www.d3-graph-gallery.com/graph/histogram_basic.html
See https://datavizcatalogue.com/methods/histogram.html

**Comment by theiliad** [comment]
Hi, time-series is supported in `SimpleBarChart` and `StackedBarChart`, although **the examples you posted match up closely with `SimpleBarChart`.**

https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--simple-bar-time-series-turkish

**And here are the underlying data & options:**
https://github.com/carbon-design-system/carbon-charts/blob/4a3727d13796030866e1416effdc48b274bdb401/packages/core/demo/demo-data/bar.ts#L104-L150
