### ISSUE TITLE
Skeleton charts & empty states

### ISSUE THREAD

**Issue by pcoccoli** [carbon-design-system/carbon-charts#407]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

0.16.24

### Issue description

My project requires UI "skeletons" while data is loading.

**Comment by theiliad** [comment]
There have been explorations on empty states and skeletons.

Nothing that's been approved so far, I will bring up with design, thanks 🙂

**Comment by theiliad** [comment]
Minor explorations by Shixie
![image](https://user-images.githubusercontent.com/14989804/73885438-c394d900-4835-11ea-9d88-50789aac72a3.png)

**Comment by gvnmagni** [comment]
Hello! We are working on the empty states for the different typologies of charts. Attached you can find a preview (sorry for the quite long image), we'd love to get a feedback on a detail.

As you can see for each chart we made two option and the difference is just in the color, second option include a light red for chart structure/grid.

This two states could become one, or they could be 2 option for 2 specific cases:
- Grey option / When data is loading
- Red option / When data are not available or there are issues

Using a light red could be interesting to point out errors or issues, what do you think @theiliad?

![empty_states](https://user-images.githubusercontent.com/18484576/75025071-d0066c00-549a-11ea-8a11-683746deb6a6.jpg)

**Comment by theiliad** [comment]
LGTM @gvnmagni. I like the red versions as well although I don't see a necessity for that, the lack of a chart being rendered should be alarming enough to the user/developer.

**Comment by gvnmagni** [comment]
Thanks Iliad, @mjabbink any preference on this? We are totally ok with both options, just wanted to understand if we like the idea of using a bit of red to give a little alarm when there are issues or if we prefer to just use the grey which might be more neutral

**Comment by mjabbink** [comment]
agree no red as I think that over emphasizes the issue. Belt and suspenders.

**Comment by stegue88** [comment]
Hi all, please find attached the Sketch file with the design specs. 
Let me know if you prefer to receive directly svgs or something else instead.
[200306_skeleton_emptystates.zip](https://github.com/carbon-design-system/carbon-charts/files/4297821/200306_skeleton_emptystates.zip)

**Comment by theiliad** [comment]
> Hi all, please find attached the Sketch file with the design specs.
> Let me know if you prefer to receive directly svgs or something else instead.
> [200306_skeleton_emptystates.zip](https://github.com/carbon-design-system/carbon-charts/files/4297821/200306_skeleton_emptystates.zip)

LGTM

**Comment by ilariaventurini** [comment]
Hello everyone! We did two simple tests with missing data (ie `data = { datasets: [], labels: [] }`) for scatterplot and stackedbar. 

Attached you can find two gifs that show the animation between missing data and correct data (the idea is simulate the data loading).

![scatterplot](https://user-images.githubusercontent.com/44204353/76787642-c205eb80-67b9-11ea-8a08-e22df5669e3f.gif)
![stackedbar](https://user-images.githubusercontent.com/44204353/76787645-c4684580-67b9-11ea-8488-c0ebbf6ac570.gif)


Do you think they can be fine?

**Comment by theiliad** [comment]
> Do you think they can be fine?

looks great to me 💯

**Comment by theiliad** [comment]
One comment I have is that if the legend disappears then the chart should probably take the rest of the height of the container

**Comment by gvnmagni** [comment]
Russ, this image includes all the empty states from the design side. Development is almost done (we are evaluating what to do with skeleton, if it's worth to put some effort on it, but this is now a different issue)

![empty states](https://user-images.githubusercontent.com/18484576/76979091-cce68a80-6937-11ea-9265-b4d9b164647f.png)

**Comment by anne-stevens** [comment]
Here are some examples of empty state placeholders, loader states (the shimmer) and entry animation patterns from Cognos Analytics.  (Note that the first couple of example take a long time to load b/c they are from a slow test environment.)

[Cognos - empty state and shimmer 1.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350490/Cognos.-.empty.state.and.shimmer.1.mov.zip)
[Cognos - empty state and shimmer 2b.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350491/Cognos.-.empty.state.and.shimmer.2b.mov.zip)
[Cognos - entry animation 3.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350492/Cognos.-.entry.animation.3.mov.zip)
[Cognos - empty state and entry animation 4.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350495/Cognos.-.empty.state.and.entry.animation.4.mov.zip)

**Comment by theiliad** [comment]
> Here are some examples of empty state placeholders, loader states (the shimmer) and entry animation patterns from Cognos Analytics. (Note that the first couple of example take a long time to load b/c they are from a slow test environment.)
> 
> [Cognos - empty state and shimmer 1.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350490/Cognos.-.empty.state.and.shimmer.1.mov.zip)
> [Cognos - empty state and shimmer 2b.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350491/Cognos.-.empty.state.and.shimmer.2b.mov.zip)
> [Cognos - entry animation 3.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350492/Cognos.-.entry.animation.3.mov.zip)
> [Cognos - empty state and entry animation 4.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/4350495/Cognos.-.empty.state.and.entry.animation.4.mov.zip)

@anne-stevens have you done user testing for any of these skeleton components?

They seem highly inconsistent with the real chart that's rendered afterwards.

Overall I think it's a bit loud on the screen

**Comment by caesarsol** [comment]
Just created https://github.com/carbon-design-system/carbon-charts/issues/568 to track the error states. They are considered external to this task.
