### ISSUE TITLE
Line chart space between graph and legend

### ISSUE THREAD

**Issue by JehanX** [carbon-design-system/carbon-charts#408]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Need space between line chart and legend when the position of legend is right

#### Steps to produce the issue
Set option to:
```
lineOptions: {
      legend: {
            orientation: "vertical",
            position: "right"  
      } 
}
```

#### Current behavior
There is no space between graph and legend

### Screenshot or recording
![image](https://user-images.githubusercontent.com/10249186/69179774-16ce7980-0ada-11ea-8ce9-28f99936c701.png)

**Comment by theiliad** [comment]
Yes, this is coming this week with the addition of spacer components

**Comment by theiliad** [comment]
This's been addressed for all charts & for all legend positions in #350
