### ISSUE TITLE
Adding an angular sandbox

### ISSUE THREAD

**Issue by agostinocinelli** [carbon-design-system/carbon-charts#417]
#### I am submitting a **installation issue**

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
    "@carbon/charts": "^0.15.6", //same with "0.20.0"
    "@carbon/charts-angular": "latest",

### Issue description
**Can't bind to 'data' since it isn't a known property of 'n-bar-chart'**

#### Steps to produce the issue
cloning the repo, npm install, npm start

#### Current behavior
No graph is shown, error in console

N.W.
The Angular demo in README is not working
https://codesandbox.io/s/k32kjy5qnr

The only working demos are:
https://stackblitz.com/edit/carbon-charts-angular-cgvrhw
but it fails when running locally :(

and
https://carbon-design-system.github.io/carbon-charts/angular/?path=/story/bar--simple-bar-discrete
but there is no code to download and try

Thank you for your help

**Comment by theiliad** [comment]
Hi. I'm unable to find a cloud sandbox solution that can handle Angular properly.

We tried codesandbox for a while, and it broke in a few different ways, and there seems to always be a `zone.js` issue with stackblitz.

I'll need to explore some other tools to host our angular code samples & demos.

For now we will have to work with Storybook and Github.

**For this demo:**
https://carbon-design-system.github.io/carbon-charts/angular/?path=/story/bar--simple-bar-discrete

**You can find the data & options used over here:**
https://github.com/carbon-design-system/carbon-charts/blob/d7860afd91433e40b3945ddd5d816a0bfa16574c/packages/core/demo/demo-data/bar.ts#L68-L96

Overall this directory includes all the demo data & options used in storybook https://github.com/carbon-design-system/carbon-charts/tree/master/packages/core/demo/demo-data

**Comment by agostinocinelli** [comment]
Hi @theiliad, thanks for your answer.
The problem here is that no example explains how to use the library in angular.
I installed libraries (charts, charts-angular, d3, colors) and imported the necessary ChartModule in my module.ts

And then?
How do I use the options and data that you posted?

**1**
I have to create a (for example) GroupedBarChart in my-component.ts and add it to a div?
if so, how can i pass the options and data?
```
new GroupedBarChart(this.chartContainer.nativeElement, {
    data: {
      labels: ["Qty", "More", "Sold", "Restocking", "Misc"],
```
doesn't work, it accepts a ChartData object

**2**
instantiated in the html file:
`<ibm-grouped-bar-chart ></ibm-grouped-bar-chart>`
doesn't work: 
_ERROR TypeError: Cannot read property 'datasets' of undefined
    at ChartModel.push../node_modules/@carbon/charts/model.js.ChartModel.generateDataLabels_

**3**
instantiated in the html file:
`<n-bar-chart  class="n-chart"  [data]="stackedBarData"  [options]="stackedBarOptions"  width="100%"  height="400"  #stackedBarChart></n-bar-chart>`
doesn't work: 
_Uncaught (in promise): Error: Template parse errors:
Can't bind to 'data' since it isn't a known property of 'n-bar-chart'.
1. If 'n-bar-chart' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'n-bar-chart' is a Web Component_

Thank you very much for your help and work.
Agostino

**Comment by theiliad** [comment]
**I would use the instructions on this page for now to get started:**
https://www.carbondesignsystem.com/data-visualization/getting-started/angular

I'm looking for a tool that can reliably hold a sample angular project with a basic usage example of charts.

**Comment by agostinocinelli** [comment]
Hi again,
i made it in the end! i think the docs you linked are outdated.
The working tag is
`<ibm-grouped-bar-chart />`
not
`<n-bar-chart />`

 Thank you very much for addressing.

**Comment by theiliad** [comment]
Great @agostinocinelli. I'm in the process of updating the website content. I will close this issue once I've setup a working sandbox again 🙂

**Comment by theiliad** [comment]
I don't think that there currently is a stable & reliable angular sandbox tool around, unfortunately!
