### ISSUE TITLE
Visual fix: increase margin bottom of all Chart Titles to 24px

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#426]
## Increase margin bottom of all Chart Titles to 24px

This is a comment only on visual design and made to me somewhere in November. Only got to make an issue now. This is per Mike's comment below. Hopefully an easy fix?

> curren sample title too tight to chart:
<img width="898" alt="Screen Shot 2019-12-04 at 3 45 49 PM" src="https://user-images.githubusercontent.com/32881239/70184316-360a0100-16ad-11ea-8d8b-bd926968808c.png">

_Originally posted by @mjabbink in https://github.com/carbon-design-system/carbon-charts/issues/421#issuecomment-561853681_

**Comment by theiliad** [comment]
yeap, coming with #350
