### ISSUE TITLE
Line chart values do not perfectly align with x-axis in smaller dimensions

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#43]
![image](https://user-images.githubusercontent.com/14989804/45329075-a66ab680-b52c-11e8-9f28-eec4c8c8feef.png)

**Comment by t-mullen** [comment]
It looks like the way D3 calculates the positions for the axis ticks and the way we calculate the cx,cy offsets for the dot svg elements are slightly different.

cx and cy are rounded to integers, but that's not enough to explain the mismatch. Still looking.

**Comment by theiliad** [comment]
Is D3 rounding values or are we? @t-mullen

**Comment by t-mullen** [comment]
I think cx and cy only accept integer values. So us.

https://github.com/IBM/carbon-charts/blob/master/packages/core/src/line-chart.ts#L77
vs
https://github.com/IBM/carbon-charts/blob/master/packages/core/src/base-axis-chart.ts#L391

**Comment by t-mullen** [comment]
It should be noted that the y position is also off by a integer values.
