### ISSUE TITLE
Node outline size — line chart

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/carbon-charts#433]
- [ ] Line charts: node outlines should match the same weight as the connecting lines (1.5)

**Current**
![Artboard](https://user-images.githubusercontent.com/50155706/70643458-a90ffc00-1c06-11ea-8bef-a0d0570aacc0.png)

**Expected**
![image](https://user-images.githubusercontent.com/50155706/70643566-d2c92300-1c06-11ea-9a11-18b659ddc24b.png)

**Comment by natashadecoste** [comment]
@cameroncalder the stroke of the line is currently 1.75.  Im pushing code to adjust it to 1.5 and the node outline size to also be 1.5

![image](https://user-images.githubusercontent.com/14351335/70928949-07225200-2000-11ea-9dd7-3f4add89a711.png)
