### ISSUE TITLE
Undocumented dependency on @carbon/colors

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon-charts#436]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:

0.22.0

### Issue description

I updated from 0.16.8 to 0.22.0, I did go through the upgrade instructions but I was always getting compile errors which turned out to be caused by my project not having `@carbon/colors` as a dependency. 

### Screenshot or recording

```
ERROR in ./node_modules/@carbon/charts/services/colors.js
Module not found: Error: Can't resolve '@carbon/colors' in '/my-project/node_modules/@carbon/charts/services'
resolve '@carbon/colors' in '/my-project/node_modules/@carbon/charts/services'
  Parsed request is a module
  using description file: /my-project/node_modules/@carbon/charts/package.json (relative path: ./services)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /my-project/src
        using description file: /my-project/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /my-project/package.json (relative path: ./src/@carbon/colors)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/src/@carbon/colors doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/src/@carbon/colors.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/src/@carbon/colors.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/src/@carbon/colors.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/src/@carbon/colors.js doesn't exist
            as directory
              /my-project/src/@carbon/colors doesn't exist
      /my-project/node_modules/@carbon/charts/services/node_modules doesn't exist or is not a directory
      /my-project/node_modules/@carbon/node_modules doesn't exist or is not a directory
      /my-project/node_modules/node_modules doesn't exist or is not a directory
      /Users/sgeorgiev@ca.ibm.com/addi/510/node_modules doesn't exist or is not a directory
      /Users/sgeorgiev@ca.ibm.com/addi/node_modules doesn't exist or is not a directory
      /Users/sgeorgiev@ca.ibm.com/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /my-project/node_modules/@carbon/charts/node_modules
        using description file: /my-project/node_modules/@carbon/charts/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /my-project/node_modules
        using description file: /my-project/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /my-project/node_modules/@carbon/charts/package.json (relative path: ./node_modules/@carbon/colors)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /my-project/package.json (relative path: ./node_modules/@carbon/colors)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/charts/node_modules/@carbon/colors doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/colors doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/colors.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/colors.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/colors.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.js doesn't exist
            as directory
              /my-project/node_modules/@carbon/charts/node_modules/@carbon/colors doesn't exist
              /my-project/node_modules/@carbon/colors.js doesn't exist
            as directory
              /my-project/node_modules/@carbon/colors doesn't exist
[/my-project/src/@carbon/colors]
[/my-project/src/@carbon/colors.ts]
[/my-project/src/@carbon/colors.tsx]
[/my-project/src/@carbon/colors.mjs]
[/my-project/src/@carbon/colors.js]
[/my-project/node_modules/@carbon/charts/services/node_modules]
[/my-project/node_modules/@carbon/node_modules]
[/my-project/node_modules/node_modules]
[/Users/sgeorgiev@ca.ibm.com/addi/510/node_modules]
[/Users/sgeorgiev@ca.ibm.com/addi/node_modules]
[/Users/sgeorgiev@ca.ibm.com/node_modules]
[/Users/node_modules]
[/node_modules]
[/my-project/node_modules/@carbon/charts/node_modules/@carbon/colors]
[/my-project/node_modules/@carbon/colors]
[/my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.ts]
[/my-project/node_modules/@carbon/colors.ts]
[/my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.tsx]
[/my-project/node_modules/@carbon/colors.tsx]
[/my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.mjs]
[/my-project/node_modules/@carbon/colors.mjs]
[/my-project/node_modules/@carbon/charts/node_modules/@carbon/colors.js]
[/my-project/node_modules/@carbon/colors.js]
 @ ./node_modules/@carbon/charts/services/colors.js 1:0-79 4:45-49 5:45-49 6:46-51 7:48-55 8:47-53 9:44-47 10:45-49
 @ ./node_modules/@carbon/charts/services/colorPalettes.js
 @ ./node_modules/@carbon/charts/index.js
 @ ./node_modules/@carbon/charts-angular/fesm5/carbon-charts-angular.js
 @ ./src/app/charts/charts.module.ts
 @ ./src/app/apa-drilldown/apa-drilldown.module.ts
 @ ./src/app/workbook/workbook.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?https://0.0.0.0:0/sockjs-node ./src/main.ts
ℹ ｢wdm｣: Failed to compile.
```

**Comment by natashadecoste** [comment]
closing as stale/outdated

**Comment by theiliad** [comment]
`@carbon/colors` should be installed automatically by your package manager when installing `@carbon/charts`

![image](https://user-images.githubusercontent.com/14989804/110141604-57233b00-7da3-11eb-96b1-8d2d7ba32172.png)

**Comment by akshay27395** [comment]
Getting this error while performing ng build --prod not able to understand the soln


ERROR in ./node_modules/@carbon/charts/services/essentials/dom-utils.js
Module not found: Error: Can't resolve 'dom-to-image' in '/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials'
resolve 'dom-to-image' in '/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials'
  Parsed request is a module
  using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/package.json (relative path: ./services/essentials)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/
        using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: ./dom-to-image)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.js doesn't exist
            as directory
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image doesn't exist
      /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials/node_modules doesn't exist or is not a directory
      /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/node_modules doesn't exist or is not a directory
      /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/node_modules doesn't exist or is not a directory
      /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/node_modules doesn't exist or is not a directory
      /Users/sanchitaraut/Cateina/mainBranchCode/node_modules doesn't exist or is not a directory
      /Users/sanchitaraut/Cateina/node_modules doesn't exist or is not a directory
      /Users/sanchitaraut/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules
        using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules
        using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/package.json (relative path: ./node_modules/dom-to-image)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: ./node_modules/dom-to-image)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.js doesn't exist
            as directory
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image doesn't exist
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.js doesn't exist
            as directory
              /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image doesn't exist
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.ts]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.tsx]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.mjs]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.js]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials/node_modules]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/node_modules]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/node_modules]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/node_modules]
[/Users/sanchitaraut/Cateina/mainBranchCode/node_modules]
[/Users/sanchitaraut/Cateina/node_modules]
[/Users/sanchitaraut/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.ts]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.ts]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.tsx]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.tsx]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.mjs]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.mjs]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.js]
[/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.js]
 @ ./node_modules/@carbon/charts/services/essentials/dom-utils.js 24:0-38 204:8-18 222:8-18
 @ ./node_modules/@carbon/charts/services/index.js
 @ ./node_modules/@carbon/charts/chart.js
 @ ./node_modules/@carbon/charts/charts/wordcloud.js
 @ ./node_modules/@carbon/charts/charts/index.js
 @ ./node_modules/@carbon/charts/index.js
 @ ./node_modules/@carbon/charts-angular/fesm2015/carbon-charts-angular.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by theiliad** [comment]
> Getting this error while performing ng build --prod not able to understand the soln
> 
> ERROR in ./node_modules/@carbon/charts/services/essentials/dom-utils.js
> Module not found: Error: Can't resolve 'dom-to-image' in '/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials'
> resolve 'dom-to-image' in '/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials'
> Parsed request is a module
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/package.json (relative path: ./services/essentials)
> Field 'browser' doesn't contain a valid alias configuration
> resolve as module
> looking for modules in /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: .)
> Field 'browser' doesn't contain a valid alias configuration
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: ./dom-to-image)
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image doesn't exist
> .ts
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.ts doesn't exist
> .tsx
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.tsx doesn't exist
> .mjs
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.mjs doesn't exist
> .js
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.js doesn't exist
> as directory
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image doesn't exist
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials/node_modules doesn't exist or is not a directory
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/node_modules doesn't exist or is not a directory
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/node_modules doesn't exist or is not a directory
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/node_modules doesn't exist or is not a directory
> /Users/sanchitaraut/Cateina/mainBranchCode/node_modules doesn't exist or is not a directory
> /Users/sanchitaraut/Cateina/node_modules doesn't exist or is not a directory
> /Users/sanchitaraut/node_modules doesn't exist or is not a directory
> /Users/node_modules doesn't exist or is not a directory
> /node_modules doesn't exist or is not a directory
> looking for modules in /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/package.json (relative path: ./node_modules)
> Field 'browser' doesn't contain a valid alias configuration
> looking for modules in /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: ./node_modules)
> Field 'browser' doesn't contain a valid alias configuration
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/package.json (relative path: ./node_modules/dom-to-image)
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> using description file: /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/package.json (relative path: ./node_modules/dom-to-image)
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image doesn't exist
> .ts
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image doesn't exist
> .ts
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.ts doesn't exist
> .tsx
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.ts doesn't exist
> .tsx
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.tsx doesn't exist
> .mjs
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.tsx doesn't exist
> .mjs
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.mjs doesn't exist
> .js
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.mjs doesn't exist
> .js
> Field 'browser' doesn't contain a valid alias configuration
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.js doesn't exist
> as directory
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image doesn't exist
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.js doesn't exist
> as directory
> /Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image doesn't exist
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.ts]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.tsx]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.mjs]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/dom-to-image.js]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/essentials/node_modules]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/services/node_modules]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/node_modules]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/node_modules]
> [/Users/sanchitaraut/Cateina/mainBranchCode/node_modules]
> [/Users/sanchitaraut/Cateina/node_modules]
> [/Users/sanchitaraut/node_modules]
> [/Users/node_modules]
> [/node_modules]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.ts]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.ts]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.tsx]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.tsx]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.mjs]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.mjs]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/@carbon/charts/node_modules/dom-to-image.js]
> [/Users/sanchitaraut/Cateina/mainBranchCode/starfish_UI/node_modules/dom-to-image.js]
> @ ./node_modules/@carbon/charts/services/essentials/dom-utils.js 24:0-38 204:8-18 222:8-18
> @ ./node_modules/@carbon/charts/services/index.js
> @ ./node_modules/@carbon/charts/chart.js
> @ ./node_modules/@carbon/charts/charts/wordcloud.js
> @ ./node_modules/@carbon/charts/charts/index.js
> @ ./node_modules/@carbon/charts/index.js
> @ ./node_modules/@carbon/charts-angular/fesm2015/carbon-charts-angular.js
> @ ./src/app/app.module.ngfactory.js
> @ ./src/main.ts
> @ multi ./src/main.ts

Installing the latest version should resolve your issue
