### ISSUE TITLE
Compound Chart containing both line chart and bar chart

### ISSUE THREAD

**Issue by tulasigudibanda** [carbon-design-system/carbon-charts#454]
Thia is a  new design/functionality request

charts version: "@carbon/charts-angular": "^0.16.25",

We need a single compound chart component which has both line chart and bar chart for this functionality:

<img width="494" alt="Screen Shot 2019-12-19 at 3 31 55 PM" src="https://user-images.githubusercontent.com/47306803/71213096-5b376b80-2278-11ea-9915-65c0c3f7d939.png">

**Comment by mjabbink** [comment]
@theiliad Assign to Accurat

**Comment by jorgetorreso** [comment]
@theiliad is there a task  to follow up?

**Comment by theiliad** [comment]
This has already been communicated to Accurat. I just added the label as well, this should be coming in fairly soon.

**Effort involved:**
Any Carbon Charts chart is currently a combo chart (you can add as many graphs within the graph frame to any chart)

**All we need implemented** is a layer within charting data where you can assign a dataset (or multiple) to the bars, and one (or multiple) to the line graphs
