### ISSUE TITLE
[LineChart]: How to set line color from stacked Options and remove bottom labels?

### ISSUE THREAD

**Issue by penzhan8451** [carbon-design-system/carbon-charts#455]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [- ] Other

#### charts version:
0.24.3

### Issue description
How to set Line color  from stacked Options?
=====use example options =====
"title": "TOP Title",
  "axes": {
    "bottom": {
      "title": "2018 Annual Sales Figures",
          "scaleType": "labels",
          "secondary": true
    },
    "left": {
      "primary": true
    }
  },
  "height": "160px",
  "width": "30%"

#### Steps to produce the issue
please see screenshot.

#### Current behavior
It seems to assign default color, but not  customized color
 
#### Expected behavior
It can set customized color,  and remove bottom labels 'traffic in' and 'traffic out'
please see screenshot.

### Screenshot or recording
![carbon-charts](https://user-images.githubusercontent.com/10585564/71557427-00282480-2a81-11ea-849e-363dd6573b15.png)

**Comment by theiliad** [comment]
Hi, please refer to the `Color Scale` section of this tutorial https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--tabular-data-format
