### ISSUE TITLE
axis type and legend in Helvetica 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-charts#456]
In Safari the font is defaulting to Helvetica rather than IBM Plex.

https://carbon-design-system.github.io/carbon-charts/

<img width="743" alt="Screen Shot 2019-12-30 at 12 33 57 PM" src="https://user-images.githubusercontent.com/32881239/71595328-b2eb9780-2b00-11ea-8fba-075086dcd83a.png">

**Comment by theiliad** [comment]
Good catch @mjabbink thanks! This issue is seen because the `IBM Plex Sans Condensed` font wasn't imported on the core demo site.

Thankfully the `react`, `angular` & `vue` demo sites already had the font imported and were working fine.
