### ISSUE TITLE
Line [Time series]: The time labels does not show the date and time

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon-charts#468]
I am facing a issue on the time series line chart when there is only one dataset with one value.
When value of date is 
1. 2020-01-06T19:43:16Z , I get a chart with time axis having one value and the value being ( :16)
2. 2020-01-06T19:43:00Z , I get a chart with time axis having one value and the value being ( 19:43)
 in first case, I am sure we cannot understand what that 16 means (its 16 sec)
in second case though it shows the proper time, we do not know which day or month or year it belongs to.

#### charts version:
"@carbon/charts": "^0.24.3",
"d3": "^5.15.0",

### Issue description
Time value is not clear when there is only one value.

#### Steps to produce the issue
have single dataset with one time value 

#### Current behavior
it should show the date and time

### Screenshot or recording
![image](https://user-images.githubusercontent.com/44162180/72718632-52e68f00-3b9c-11ea-9abf-8d6b9a24a56c.png)

![image](https://user-images.githubusercontent.com/44162180/72718658-60037e00-3b9c-11ea-964d-9c8b7c3fae84.png)

**Comment by theiliad** [comment]
Related to #299

**Comment by caesarsol** [comment]
Hi, Accurat here.

We created a simple repro case for this issue: https://codesandbox.io/s/carbon-charts-issue-468-repro-xtvnt

You can see from the `Multiple Every-Second Data` chart that the case is not limited to single-datum charts.

We will solve it within #299, which is in progress on our side.

**Comment by theiliad** [comment]
Thanks Accurat 👍

**Comment by gvnmagni** [comment]
Russel, here's the image

![74938406-3bdecb00-53ee-11ea-9dc8-1911994b3400](https://user-images.githubusercontent.com/18484576/76979585-6ca41880-6938-11ea-9e4c-3b6dc44c3afe.png)
