### ISSUE TITLE
Hand icon on the Donut charts when mouse pointer is hovered over them

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#475]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

Mouse pointer on the Donut chart doesn't change to hand cursor on hovering. In some of the graphs, they have a drill down capability. Having hand cursor on hover would be appropriate.
Having the hand icon gives the user a feeling that there might be some functionality associated with it.

#### Current behavior
No hand icon

**Comment by theiliad** [comment]
I wouldn't think that you'd want that as the default behavior.

Currently clicking on the slices won't result in an action, therefore the `pointer` cursor would be pointless.

Feel free to re-open but I would say if you catch the click event and attach more interactions to the slice click, then you should add the `pointer` cursor through your CSS styles.
