### ISSUE TITLE
Legends shouldn't be displayed for simple bar/line chart

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#476]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Legends in bar chart of line chart would be useful, if there are multiple entities plotted.
Example: https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--grouped-bar-discrete

But, for a single bar (or line) chart, the legend is redundant and useless. It simply renders the same information as in the x/y axis. Refer: https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar--simple-bar-discrete

#### Current behavior
Redundant legends are rendered

#### Expected behavior
Don't render legends for simple bar/line charts

**Comment by theiliad** [comment]
Addressed in #423
