### ISSUE TITLE
Option to set custom/fixed colours for bars in SimpleBarChart

### ISSUE THREAD

**Issue by reeteshsingh93** [carbon-design-system/carbon-charts#486]
#### I am submitting a...

Feature request:
Need an option to set the colours for bars in carbon SimpleBarChart?

#### charts version:
"@carbon/charts": "^0.24.3",
"@carbon/charts-react": "^0.24.3"

### Issue description
Currently bar charts uses colour of it own choice however we have a requirement to fixed the colour options to choose from.

**Comment by theiliad** [comment]
Hi, this is already achieveable by passing in a `fillColors` array within each dataset
