### ISSUE TITLE
Click Event needed on x-axis labels of Bar charts (Vertical and horizontal) 

### ISSUE THREAD

**Issue by yvswamy** [carbon-design-system/carbon-charts#487]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description 
Currently, we are using D3 charts. In one of our existing charts, we have click events on the x-axis labels. As we are migrating to carbon charts, it would be good if you can prioritize this issue. 

#### Current behavior
There is no click event present on the x-axis labels of bar charts (vertical & horizontal)

#### Expected behavior
Need to enable click event on x-axis labels of bar charts (vertical & horizontal)

**Comment by theiliad** [comment]
Thanks for bringing up this issue, should be coming in within the next week!
