### ISSUE TITLE
Stacked bar chart stacks from bottom, but tooltip and legend goes from top

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#488]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.29.1

### Issue description
If I make a stacked bar chart even though the legend and the tooltip read from the top to bottom of the data set order, the stacking is actually happening from bottom up.

#### Steps to produce the issue
Reproducible even in the demo chart provided by Carbon Charts

### Screenshot or recording
Notice the legend goes 1, 2 as well as the tooltip 
![image](https://user-images.githubusercontent.com/6663002/74194014-0da70180-4c1e-11ea-9dc2-6c6262212d9b.png)

![image](https://user-images.githubusercontent.com/6663002/74194024-13044c00-4c1e-11ea-84e7-ec9fe60115d3.png)

But that the bar is actually reversed visually

**Comment by theiliad** [comment]
@scottdickerson great catch!

**Comment by deandwill** [comment]
... in support of this issue:   see  https://jazzycat.ca/covid_ontario.html?opt:Z,theme:3  ... it's "disconcerting" to have the stacked-bar colours opposite to the colour sequence in the legend.
<img width="332" alt="Screen Shot 2020-07-15 at 4 21 31 PM" src="https://user-images.githubusercontent.com/446838/87592097-4b212680-c6b7-11ea-99ce-a03de34e26dc.png">

**Comment by scottdickerson** [comment]
this is important for us in the next sprint, I'll take it @theiliad

**Comment by theiliad** [comment]
I want to confirm that @natashadecoste has already addressed this in the #734 PR. I think she has

@natashadecoste?

**Comment by natashadecoste** [comment]
![image](https://user-images.githubusercontent.com/14351335/106761143-8444c800-6602-11eb-8535-93bb328cf125.png)
yes. this is included in the most recent carbon-charts. closing this issue.
