### ISSUE TITLE
Stacked bar chart throws exception if a datasets doesn't have data

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#494]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.29.1

### Issue description
Bar chart throws an exception and fails to render if a dataset doesn't have data.  In a real world case, our datasets may or may not have data.

Here's the exception:
axis.ts:100 Uncaught TypeError: Cannot read property 'value' of undefined
    at axis.ts:100
    at Array.map (<anonymous>)
    at axis.ts:99
    at Array.reduce (<anonymous>)
    at Axis../src/components/axes/axis.ts.Axis.getScaleDomain (axis.ts:98)
    at Axis../src/components/axes/axis.ts.Axis.render (axis.ts:169)
    at two-dimensional-axes.ts:82
    at Array.forEach (<anonymous>)
    at TwoDimensionalAxes../src/components/axes/two-dimensional-axes.ts.TwoDimensionalAxes.render (two-dimensional-axes.ts:80)
    at layout.ts:192

#### Steps to produce the issue
Easy to reproduce in the demo cases if you change the stackedBarTimeSeriesData to be this
```
export const stackedBarTimeSeriesData = {
	labels: ["Qty", "More", "Sold", "Restocking", "Misc"],
	datasets: [
		{
			label: "Dataset 1",
			data: [
			]
		},
		{
			label: "Dataset 2",
			data: [
```

### Screenshot or recording
![image](https://user-images.githubusercontent.com/6663002/74447618-483bb480-4e3f-11ea-8ee5-8bcd6a587813.png)

**Comment by theiliad** [comment]
This should be addressed by #534
