### ISSUE TITLE
Donu chart: When all the values of the data are 0, we get as NAN% on the chart

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon-charts#500]
I am facing an issue in Donut charts.
When the data is all 0 the chart is displayed with NaN%

#### charts version:
"@carbon/charts": "^0.29.1",
"d3": "^5.15.0"

### Issue description
NaN% is not a valid value to be shown

#### Steps to produce the issue
Have a dataset with all 0 as values, if there is any one non-zero value it all works well. 
"datasets": [   {
      "label": "Dataset 1",
      "data": [  0,  0, 0, 0 ]
    }]

#### Current behavior
![image](https://user-images.githubusercontent.com/44162180/74736793-85f27000-5279-11ea-8789-49a81c235b97.png)

**Comment by Chris221** [comment]
The same bug occurs for any 0, they don't all have to be 0, just one needs to be a 0 for it to display NaN% when that one is clicked
