### ISSUE TITLE
Line chart: “customHTML” function in TooltipOptions doesn't work as expected

### ISSUE THREAD

**Issue by navjeets** [carbon-design-system/carbon-charts#502]
#### “customHTML” function in TooltipOptions doesn't pass x-axis label value in "data" object in mouse-over tick event.

- [ ] Source code defect

#### charts version:
0.29.1

### Issue description
I’m facing an issue with “customHTML” function in TooltipOptions. This fuction has 2 parameters “data” and “defaultHTML”.
When I hover over a data point in line chart the data object is as follows:
[“{”label”:“70”,“datasetLabel”:“Sub class 2 “,”value”:40}“]
Here the “label” is x-axis value and “value” is y-axis value for that data point.
However, when I hover over the tick, I get the following data object:
[“[{“datasetLabel”:“Sub class 2 “,”value”:40},{“datasetLabel”:“Sub class 3 “,”value”:30},{“datasetLabel”:“Sub class 1 “,”value”:20}]“]
The 3 objects in the above array contain the y-axis values for each of the 3 data points on the tick. You can see that the “label” value is missing. This prevents us from creating a custom tooltip which includes the x-axis value as well

#### Current behavior
“customHTML” function in TooltipOptions doesn't pass x-axis label value in "data" object in mouse-over tick event.

#### Expected behavior
“customHTML” function in TooltipOptions should pass x-axis label value in "data" object in mouse-over tick event. The data object passed when mouse-over data point in chart does contain the x-axis label value.

### Screenshot or recording
Desired output:
<img width="622" alt="Screen Shot 2020-02-18 at 12 45 21 PM" src="https://user-images.githubusercontent.com/18363183/74771619-76186300-525c-11ea-9d50-d6dbe7a9cdc2.png">

**Comment by navjeets** [comment]
@scottdickerson @theiliad

**Comment by natashadecoste** [comment]
With the new Tabular Data format introduced in this PR https://github.com/carbon-design-system/carbon-charts/pull/529 **all** dimensions associated with each data item are provided to the customHTML function.
