### ISSUE TITLE
Line [Time series]: Is there a way to get only integers ( not decimals) on y-axis

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon-charts#505]
Our Line charts has data which contains always round integer number.
But when we have data whose values are small ( 1, 2, 3,4, 5), we get the y-axis in decimals.
Is there a way to say not to show decimals.

![image](https://user-images.githubusercontent.com/44162180/74819166-fc4cac00-5325-11ea-8745-be416ca4f8bc.png)

**Comment by theiliad** [comment]
Hi, you can use axis formatters:

```js
{
  axes: {
     left: {
       ticks: {
          formatter: val => val // You'd change this function
       }
     }
  }
}
```
