### ISSUE TITLE
Threshold in Line charts.

### ISSUE THREAD

**Issue by changshunwang** [carbon-design-system/carbon-charts#506]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.29.1
### Issue description
Line chart can set threshold.

#### Current behavior
No threshold parameter in the interfaces.

#### Expected behavior
1. Set one or more dotted line as threshold.
2. Set different color to highlight threshold line. 
3. When hovering on the threshold line, more detailed pop up is displayed that shows more information about the line.

### Screenshot or recording
![image](https://user-images.githubusercontent.com/17962664/74911693-1951af80-53f8-11ea-9a19-c28048adc833.png)
Link to design: https://ibm.invisionapp.com/share/9XNZ96CSJVQ#/screens/319291108

**Comment by changshunwang** [comment]
Hi,  @theiliad Could you please help me solve this issue. I am very happy to do if there is something I can. Thanks. :)

**Comment by theiliad** [comment]
Hi, I've added the `specs-needed` label and passed on the issue to design. Before any development we'd need design to solidify the logic here

**Comment by mjabbink** [comment]
@theiliad Let’s ask Accurat to look at this as well.

**Comment by theiliad** [comment]
Added accurat @gvnmagni @caesarsol

**Comment by gvnmagni** [comment]
> Added accurat @gvnmagni @caesarsol

👍
