### ISSUE TITLE
TimeSeries, Line chart/StackedBarChart fails when used with Node V13.9.0 

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon-charts#510]
#### I am submitting a bug

We have to migrate to latest version of Node because of certain vulnerabilities with older versions of Node and have to move to Node v 13.8.0 or above.
And we planned to move to the latest version which is Node 13.9.0.
And we observe that Timeseries charts (Line and StackedBar Charts), fails with javascript error in console

#### charts version:
"@carbon/charts": "^0.29.1",

#### Current behavior
It throws following error on browser console with a blank chart with complete gray background

![image](https://user-images.githubusercontent.com/44162180/75029759-ad8b4780-54c8-11ea-9b2f-63879b23a471.png)

![image](https://user-images.githubusercontent.com/44162180/75029726-9fd5c200-54c8-11ea-8fd2-6d676d15300a.png)

**Comment by theiliad** [comment]
I don't see how Node versions can affect this.

Could you please share your setup and how you're bundling your project, it most likely has to do with that.

**Comment by PAnilReddy** [comment]
Closing it as it works
