### ISSUE TITLE
Gray 100 background has wrong hex value

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-charts#518]
I see #171717 as fill in `.bx--cc--grid rect.chart-grid-backdrop`. It should be $161616 per https://www.carbondesignsystem.com/guidelines/color/usage.

Updating to a newer `@carbon/themes` should fix this?

https://github.com/carbon-design-system/carbon/blob/master/packages/colors/src/colors.js#L213

**Comment by theiliad** [comment]
Hey @mattrosno  👋 

The tokens were thoroughly checked with design at the time
https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/src/styles/components/_grid.scss

> Updating to a newer `@carbon/themes` should fix this?
Have some of the colors changed within `@carbon/themes`? If that's the case then we might indeed be using an older color.

**Comment by mattrosno** [comment]
@theiliad yes, it looks like v2 colors from the IDL were merged in ~6 months ago. https://github.com/carbon-design-system/carbon/pull/3957

**Comment by theiliad** [comment]
Should be addressed by #520
