### ISSUE TITLE
Stacked bar chart timeseries missing labels cause the bars to go off the grid

### ISSUE THREAD

**Issue by enricoberti** [carbon-design-system/carbon-charts#521]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
0.29.8

### Issue description
When setting the `options` for a stacked bar time series, it's not clear what `labels` does. If you leave a quantity of labels that is less than the number of any datasets data points, it renders bars outside the grid.

It might be related to a possible bug I noticed here: https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/src/components/graphs/bar-stacked.ts#L147

`yScale.scaleType` is always `undefined` because is not a valid property of `d3.scale()`  (while it's used correctly [here](https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/src/components/graphs/bar-stacked.ts#L49))

#### Steps to produce the issue
- change [this line](https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/demo/demo-data/bar.ts#L281) on the demo data to `labels: ["Qty"],`
- press 'Update data' as many times as needed to reproduce the problem

### Screenshot or recording
![image](https://user-images.githubusercontent.com/751894/76001163-f7caea80-5f04-11ea-978a-79da1e9b5d34.png)

**Comment by theiliad** [comment]
Hi @enricoberti, you're missing the `stacked: true` field for your left axis. Please let me know if adding that will fix your issue, thanks.

**Comment by enricoberti** [comment]
hi @theiliad, unfortunately that's not the problem - we do have `stacked: true` in the axis options. 
we fixed it in our case with adding as many labels as the dataset points, but I think there might really be a problem here for example https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/src/components/graphs/bar-stacked.ts#L147

**Comment by theiliad** [comment]
That's fair! Sorry about closing the issue initially, I'll take a look

**Comment by enricoberti** [comment]
no worries, i would have done the same @theiliad  :)

**Comment by theiliad** [comment]
Will be addressed by #529
