### ISSUE TITLE
Support for having both axes being based on a linear scale in a scatter chart

### ISSUE THREAD

**Issue by matheenpasha** [carbon-design-system/carbon-charts#523]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version: 
0.29.8

### Issue description
We working on the next generation of cloud-based Master Data Management which requires to show the results of a Probabilistic Matching Engine (PME) on a chart based dashboard. We employ the carbon design system & use the carbon 10 react library for our components. We have decided to go with a scatter chart that has log/linear axes on both x & y-axis. After going through the source code & talking to @theiliad we found out that the required scatter chart is not supported yet in the current version of the carbon-charts package. Could you prioritize this for the next release as we have expected to deliver this by end of this month?

#### Current behavior
Only a discrete & time-series based scatter chart is supported currently.

#### Expected behavior
Should be able to render scatter chart having both axes on a linear/log scale.

### Screenshot or recording
We would like the scatter chart to look like this -

![Screenshot 2020-03-05 at 6 11 56 PM](https://user-images.githubusercontent.com/3271882/76197356-ff92d380-6211-11ea-9ff9-ffcd15f95daf.jpg)

**Comment by matheenpasha** [comment]
Hello,

@theiliad  Thanks for picking this up. May I know when can I expect this to be available for use?

Thanks,
Mat

**Comment by theiliad** [comment]
@matheenpasha Hi Matheen sorry for missing this! This functionality was added a long time ago, please take a look here: https://carbon-design-system.github.io/carbon-charts/?path=/story/scatter--scatter-linear-x-y

**Comment by matheenpasha** [comment]
@theiliad We took it a long time ago & it's working perfectly in our application :) We can close this issue now. Thanks!
