### ISSUE TITLE
Combo Chart

### ISSUE THREAD

**Issue by dgyates** [carbon-design-system/carbon-charts#527]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

Looking to produce a combo-chart (i.e. a single chart that displays data series in 2 different formats within the same single chart)

The secondary Y-axis independence would be an important feature to maintain ratios amongst the series.

Ideally too our use case allows a stacked bar chart as a percentage

### Screenshot or recording

![image](https://user-images.githubusercontent.com/58667537/76352468-19e5b380-62dd-11ea-893c-07b9d57e974b.png)

**Comment by theiliad** [comment]
Great thank you @dgyates for letting us know. Please provide us with a timeline of when your team will be looking to start using a combo chart component.

Also I'm tagging @deandwill @mjabbink & @gvnmagni

**Comment by dgyates** [comment]
Our plan would be to have this going in 2Q2020

**Comment by theiliad** [comment]
Thanks @dgyates. Combo is on our roadmap already for Q2 and seeing your request we should be able to prioritize it
