### ISSUE TITLE
Need gradient support for Carbon bar graph

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-charts#531]
@vsnichols commented on [Wed Mar 11 2020](https://github.com/carbon-design-system/carbon/issues/5599)

## Description
Several prominent page designs in IBM Cloud use bar graphs with gradient, including the dashboard and the new billing overview page. Currently however the code does not support use of gradients. These pages are set to be released before THINK.
 
Use of gradients with bar graphs fits the Carbon accessibility guides. We would like to add gradient support to this specific type of graph. 

The turnaround for this is fairly tight - please let us know what we can do to move the issue forward.

## Example

<img width="618" alt="Screen Shot 2020-03-11 at 10 55 23 AM" src="https://user-images.githubusercontent.com/39408106/76436943-d6478400-6386-11ea-8b9d-932b583d1c7b.png">

**Comment by theiliad** [comment]
Thanks TJ for communicating the message.

I'll need to get design to review these specs, are there more screenshots/guidelines you've created @vsnichols?

I'm sending this issue over to design right now. I personally don't see the gradients being a viable option accessibility wise for anything other than the simple bar graph where you've got datapoints from only 1 category being shown.

**Comment by vsnichols** [comment]
@theiliad I agree, I think single category bar charts are a chart type where gradients make sense. I can try to post more specs here.

**Comment by vsnichols** [comment]
This is an updated mockup:

<img width="976" alt="Screen Shot 2020-03-11 at 6 30 31 PM" src="https://user-images.githubusercontent.com/39408106/76473464-8a1c3400-63c6-11ea-9dd0-88da4a2f0d32.png">

<img width="1035" alt="Screen Shot 2020-03-11 at 6 30 42 PM" src="https://user-images.githubusercontent.com/39408106/76473467-8c7e8e00-63c6-11ea-9dfa-52f832a03494.png">

**Comment by theiliad** [comment]
@vsnichols what do the grey bars in the background represent?

**Comment by lissali** [comment]
We have the similar requirement in our usage such as to show baseline as following image:
![image](https://user-images.githubusercontent.com/22383754/77025777-f4d3fd80-69cc-11ea-859a-2d89848ad4ff.png)
![image](https://user-images.githubusercontent.com/22383754/77025794-fef5fc00-69cc-11ea-959b-7bf82ebb170e.png)

**Comment by loganmccaul** [comment]
@theiliad An alternative approach to you having to add in gradient support is to enable attaching custom css classes to different data, maybe something like

```
{
      key: 'month',
      value: '$100,
      group: 'usage',
      className: 'custom-css-usage'
 }
```

and then consumers can add any visual design specifics they need.

I'd be happy to contribute this if it makes sense to you and you don't mind pointing me in the right direction 😄

**Comment by theiliad** [comment]
This was discussed multiple times within the design team.

Bottom line is, we're not sure if gradients add a ton of value to the visualization.

One of the main concerns is that a gradient fill on a bar for instance could create the deception of a scale within the bar itself that doesn't exist necessarily in the visualization...

My personal opinion is we should stay away from creating incorrect perceptions or causing unintentional dishonesty in the data.

Feel free to re-open the issue if you've got any other ideas, research or examples but for now I'm going to close the issue. Thanks!
