### ISSUE TITLE
SimpleBarChart has accessibility issues 

### ISSUE THREAD

**Issue by reeteshsingh93** [carbon-design-system/carbon-charts#535]
#### I am submitting a...

Accessibility defect

#### charts version:

"@carbon/charts": "^0.29.6",
"@carbon/charts-react": "^0.29.6",

### Issue description

Issue with SimpleBarChart:

Elements that use 'role' should reference a valid WAI-ARIA role
Element 'role' is not a valid WAI-ARIA role.
DAP rule set: IBM Accessibility January 2020

#### Steps to produce the issue

Go to https://dev.console.test.cloud.ibm.com/security-advisor#/configadvisor

Screenshots:

![image](https://user-images.githubusercontent.com/46310374/76707623-c4fbd000-6716-11ea-9644-f25d12c5cff4.png)
![image](https://user-images.githubusercontent.com/46310374/76707627-d04efb80-6716-11ea-9825-49d0b73fe46b.png)
![image](https://user-images.githubusercontent.com/46310374/76707629-d644dc80-6716-11ea-8909-009a76e9f19f.png)
![image](https://user-images.githubusercontent.com/46310374/76707634-de048100-6716-11ea-9609-3814c9ee9e49.png)
![image](https://user-images.githubusercontent.com/46310374/76707636-e2c93500-6716-11ea-82da-35292aa9c88f.png)

#### Current behavior

Accessibility issues being reported by DAP

#### Expected behavior

No voilation should be reported by DAP plugin

**Comment by reeteshsingh93** [comment]
Can we have any update on this?

**Comment by theiliad** [comment]
@reeteshsingh93 those warnings are invalid
https://www.w3.org/TR/graphics-aria-1.0/#graphics-symbol
https://www.w3.org/TR/graphics-aria-1.0/#graphics-object

Now something that should be done is to remove `role` from `<g>` elements, however the `rect` roles are valid

**Comment by theiliad** [comment]
Closed by #707
