### ISSUE TITLE
Accessibility issue with bars in Simplebarcharts

### ISSUE THREAD

**Issue by reeteshsingh93** [carbon-design-system/carbon-charts#537]
#### I am submitting a...

Accessibility defect

#### charts version:

"@carbon/charts": "^0.29.6",
"@carbon/charts-react": "^0.29.6",

### Issue description

Issue with SimpleBarChart Bars:
Elements that use WAI-ARIA properties must reference valid IDs

Refers creenshot for the defect:

The id 2020-02-10 specified for WAI-ARIA property aria-labelledby on element g is not valid. See rule help for remediation guidance.

DAP rule set: IBM Accessibility January 2020

#### Steps to produce the issue

Go to https://dev.console.test.cloud.ibm.com/security-advisor#/configadvisor
Screenshots:

![image](https://user-images.githubusercontent.com/46310374/76708176-dba42600-671a-11ea-9f37-41335682a1d7.png)

#### Current behavior
Accessibility issues being reported by DAP

#### Expected behavior

No voilation should be reported by DAP plugin

**Comment by reeteshsingh93** [comment]
Can we have any update on this?

**Comment by reeteshsingh93** [comment]
As per the carbon chart's team response in slack channel, most of the errors shown here are invalid, so  we’d need DAP to correct those false negative.
https://ibm-cloudplatform.slack.com/archives/CCA7L4MS9/p1585793294036600

**Comment by sophiiae** [comment]
Closed by #707
