### ISSUE TITLE
Invalid Link of "Charting Data & Options"

### ISSUE THREAD

**Issue by ssiang1627** [carbon-design-system/carbon-charts#538]
#### I am submitting a...
- [ ] Demo/documentation defect

#### charts version:
v0.30
### Issue description
The link of "Charting Data & Options" is invalid.
It would get a 404 response.
Is there any other document of data and options?

**Comment by theiliad** [comment]
Hi @ssiang1627, which page are you referring to?

**Comment by ssiang1627** [comment]
Hi @theiliad, the link of the text" for more examples please see here" is in the paragraph "Charting Data & Options", which is in the README.md of angular package
![image](https://user-images.githubusercontent.com/11325761/77272992-7a1d2200-6ced-11ea-8241-28029a3e9c1e.png)

**Comment by ssiang1627** [comment]
Hi @theiliad the link I mention above is still invalid, which page can I access for the document of Data & Option? I can't find a accessible page for the document. Is there any other document of data and options?

**Comment by theiliad** [comment]
> Hi @theiliad the link I mention above is still invalid, which page can I access for the document of Data & Option? I can't find a accessible page for the document. Is there any other document of data and options?

Hi, just updated the links in all the package READMEs. The one you're looking for is https://github.com/carbon-design-system/carbon-charts/tree/master/packages/core/demo/data
