### ISSUE TITLE
Advanced Charts in carbon

### ISSUE THREAD

**Issue by manaspandey45** [carbon-design-system/carbon-charts#539]
#### I am submitting a...

- [x] Feature request

for advanced charts , specifically charts with Geography , as we have to use it for a feature.

**Comment by theiliad** [comment]
Hi, please be more specific, the following info in general can be useful to us:
- What chart types exactly you have a need for
- Posting timelines within which your team is committed to start developing using said chart types
- Whether you have any explorations/mockups/screenshots of your use cases
- What sort of data you're looking to visualize
