### ISSUE TITLE
Min option is not working in simple bar charts

### ISSUE THREAD

**Issue by reeteshsingh93** [carbon-design-system/carbon-charts#540]
#### I am submitting a...
-  Source code defect

#### charts version:
"@carbon/charts": "^0.24.3",
"@carbon/charts-react": "^0.24.3"

### Issue description

Unable to define min tick value in simple bar charts.

We are trying to avoid decimal values in Y axis ticks:
![image](https://user-images.githubusercontent.com/46310374/77279328-90c07a80-6ce7-11ea-9f81-d590412f48dc.png)

We have tried using formatter with math.floor or ceil   however since we have restricted the number of ticks to 5 it looks something like this which is not correct, so if we have any option where we can define domains if the calculated max range is less than 5 it might work

![image](https://user-images.githubusercontent.com/46310374/77279472-d8df9d00-6ce7-11ea-89b0-67cf882d40d3.png)

#### Current behavior

Round of the ticks value which repeats the value if the ticks decimal value  is  in same range.

#### Expected behavior

Value should not be repeated and it should be a whole number intead of decimal

**Comment by reeteshsingh93** [comment]
Is there any update on this?

**Comment by lruffing** [comment]
I need this functionality as well to avoid what's happening below.
![decimal ticks not desired](https://user-images.githubusercontent.com/8334304/79392774-ccd2ae00-7f28-11ea-9b7e-e8180980acab.JPG)

Using formatter results in: 
![too many ticks](https://user-images.githubusercontent.com/8334304/79392865-f12e8a80-7f28-11ea-96fa-082407826502.JPG)

**Comment by reeteshsingh93** [comment]
Is there any update on this?
