### ISSUE TITLE
Funnel Chart

### ISSUE THREAD

**Issue by trummerfeld** [carbon-design-system/carbon-charts#551]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Looking for a funnel-chart that can be used horizontally and vertically and with different forms (neck, no neck, pyramid, etc.).

### Screenshot or recording
<img width="719" alt="Bildschirmfoto 2020-04-01 um 18 58 33" src="https://user-images.githubusercontent.com/7021599/78164964-e6fd8e00-744a-11ea-898b-55b7d5994733.png">

**Comment by theiliad** [comment]
I haven't really seen any other requests for this chart. We're not going to move forward with it at this time
