### ISSUE TITLE
Request for gauge, meter and treemap charts

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/carbon-charts#554]
#### I am submitting a...

- [ ] Feature request

Our team needs to implement the mentioned chart types in our project. Is there any possibility of rolling out support for these?

**Comment by theiliad** [comment]
Hi, gauge and meter will be coming soon. Unfortunately I don't have an estimation of a release on treemaps, it's currently not on our roadmap

**Comment by natashadecoste** [comment]
gauge added in #623 
meter added in #425 
treemap added in #719
