### ISSUE TITLE
G100 theme for React Charts

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/carbon-charts#557]
#### I am submitting a...
- [ ] Demo/documentation defect

Hi, I am trying to implement this example line chart in my react project. However, the documentation seems to be poor. Or maybe I am not looking at it correctly. Please let me know how to apply G100 them on any chart.
https://carbon-design-system.github.io/carbon-charts/?path=/story/line--line-time-series
https://codesandbox.io/s/ydknh?file=/src/index.js

**Comment by theiliad** [comment]
Hi, themes can be switched by importing any of the themed style files.

e.g.
`import "@carbon/charts/styles.css";`
`import "@carbon/charts/styles-g10.css";`
`import "@carbon/charts/styles-g90.css";`
`import "@carbon/charts/styles-g100.css";`

**Comment by lordsfantasy** [comment]
Awesome, thanks for this. I didn't find this anywhere in the documentation. 
Is there any way, I can contribute to building the documentation?

**Comment by theiliad** [comment]
Yes for sure! We're adding more pages to the Tutorials story group very soon.

https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/stories/tutorials.stories.ts

You're more than welcome to contribute
