### ISSUE TITLE
Radar Chart Type

### ISSUE THREAD

**Issue by nigellima** [carbon-design-system/carbon-charts#562]
#### I am submitting a...

- [x] Feature request

#### charts version:
Latest

### Issue description
I've just came across the Carbon library ecosystem and noticed this Chart library built on D3, which is really cool. However, in the chart types page I noticed that Radar chart type is disabled and in fact it's not present in the library and I couldn't find any further explanation. Was it present before and then removed or is it an ongoing work?

#### Current behavior
No Radar Chart

#### Expected behavior
Radar Chart included

### Screenshot or recording
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/14295280/78856395-0ffac180-79fd-11ea-8d80-0364f3d6b682.png">

**Comment by natashadecoste** [comment]
@nigellima radar chart is currently being developed, there is a PR here https://github.com/carbon-design-system/carbon-charts/pull/581 that you can subscribe to

**Comment by natashadecoste** [comment]
@nigellima radar chart is currently being developed, there is a PR here https://github.com/carbon-design-system/carbon-charts/pull/581 that you can subscribe to
