### ISSUE TITLE
landmark tick of axis and non-hidden tooltip for all bars

### ISSUE THREAD

**Issue by ssiang1627** [carbon-design-system/carbon-charts#570]
#### I am submitting a...

- [ ] Feature request

#### charts version:
0.30.8
### Issue description
I want to add landmark labels in y axis, let 30 as Low, 60 as High. How can I add these labels?
Besides, the original behavior is that tooltip would show when hover.
But can I make many tooltips of bars keep showing at the same time just like below?
Please take a look the expected image:
<img width="556" alt="螢幕快照 2020-04-13 下午3 36 17" src="https://user-images.githubusercontent.com/11325761/79102891-3c686200-7d9e-11ea-8945-de4544072381.png">

**Comment by theiliad** [comment]
Hi, unfortunately showing values above the bars isn't part of the Carbon charting specs.

In terms of annotations, we've got #564 covering that functionality.
