### ISSUE TITLE
The sum of donut chart slices is not equal to 100%.

### ISSUE THREAD

**Issue by amoldeshpande05** [carbon-design-system/carbon-charts#571]
### Issue description:
When the values are passed in the donut chart, the sum of each slices when added up is not equal to 100%

#### Steps to produce the issue
You can follow the example here:
https://codesandbox.io/s/1q22n?file=/src/index.js

Where it sums up to 99% or less every time.

**Comment by theiliad** [comment]
Hi, this was covered by #560. Please update to a recent version of the library
