### ISSUE TITLE
[LineChart]: If I specify only one custom fill color but multiple lines, the chart blows up

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#580]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.30.5

### Issue description
Exception is thrown when only one fillColor is passed to a LineChart with multiple lines on it
![image](https://user-images.githubusercontent.com/6663002/79576143-6ebcdc80-8088-11ea-8863-00614d34a3a3.png)

#### Steps to produce the issue
Here's the configuration I passed to the LineChart
```
{"data":{"labels":[1586149200000],"datasets":[{"label":"Average Speed","fillColors":["#F00"],"data":[{"date":"2020-04-06T05:00:00.000Z","value":2.9406917567}]},{"label":"Maximum Speed","data":[{"date":"2020-04-06T05:00:00.000Z","value":4.3205206977}]},{"label":"Minimum Speed","data":[{"date":"2020-04-06T05:00:00.000Z","value":2.0571602988}]}]},"options":{"animations":false,"accessibility":false,"axes":{"bottom":{"scaleType":"time","primary":true,"ticks":{"max":14},"includeZero":false},"left":{"secondary":true,"stacked":false,"includeZero":false}},"legend":{"position":"top","clickable":true,"enabled":true},"containerResizable":true,"tooltip":{"gridline":{"enabled":false}}}}
```

#### Expected behavior
No exception

### Screenshot or recording
![image](https://user-images.githubusercontent.com/6663002/79576493-fdc9f480-8088-11ea-88f2-53612b66d507.png)

**Comment by sstone2423** [comment]
Looks like this is fixed with the new tabular format
