### ISSUE TITLE
TypeError: t.getAttribute is not a function when displaying Line Chart in jest testcase

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#594]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.30.5

### Issue description
If you try and render a LineChart in a jest testcase, it will fail with this issue

#### Steps to produce the issue
urn function(){this.removeAttribute(t)}}function Fs(t){return function(){this.removeAttributeNS(t.space,t.local)}}function Hs(t,e){return function(){this.setAttribute(t,e)}}function Vs(t,e){return function(){this.setAttributeNS(t.space,t.local,e)}}function Bs(t,e){return function(){var n=e.apply(this,arguments);null==n?this.removeAttribute(t):this.setAttribute(t,n)}}function zs(t,e){return function(){var n=e.apply(this,arguments);null==n?this.removeAttributeNS(t.space,t.local):this.setAttributeNS(t.space,t.local,n)}}function Gs(t){return t.ownerDocument&&t.ownerDocument.defaultView||t.document&&t||t.defaultView}function Ws(t){return function(){this.style.removeProperty(t)}}function Ys(t,e,n){return function(){this.style.setProperty(t,e,n)}}function qs(t,e,n){return function(){var r=e.apply(this,arguments);null==r?this.style.removeProperty(t):this.style.setProperty(t,r,n)}}function Xs(t,e){return t.style.getPropertyValue(e)||Gs(t).getComputedStyle(t,null).getPropertyValue(e)}function $s(t){return function(){delete this[t]}}function Qs(t,e){return function(){this[t]=e}}function Zs(t,e){return function(){var n=e.apply(this,arguments);null==n?delete this[t]:this[t]=n}}function Js(t){return t.trim().split(/^|\s+/)}function Ks(t){return t.classList||new tu(t)}function tu(t){this._node=t,this._names=Js(t.getAttribute("class")||"")}

#### Current behavior
![image](https://user-images.githubusercontent.com/6663002/80138612-a89b5080-856a-11ea-83f1-320704564b9a.png)

**Comment by theiliad** [comment]
@scottdickerson these must be d3 related issues. Could you try a non-bundle version of the library and see whether you get a better stack trace?

**Comment by scottdickerson** [comment]
Sure is there a branch I can pull into my package.json? @theiliad

**Comment by theiliad** [comment]
@scottdickerson just for debugging purposes I recommend switching out the import in your `node_modules` for `@carbon/charts-react` to import an ESM version rather than bundles from `@carbon/charts`
