### ISSUE TITLE
Y-axis scaling needs tuning for line charts

### ISSUE THREAD

**Issue by deandwill** [carbon-design-system/carbon-charts#596]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

As you click items in the legend to select & deselect datasets, the y axis scale dynamically adjusts.  The current algorithm works well for "stacked" datasets ... but not so well for line charts containing many datasets.
<img width="767" alt="Screen Shot 2020-04-24 at 2 39 07 AM" src="https://user-images.githubusercontent.com/446838/80182485-02d0fb80-85d5-11ea-8913-4c1a39ddbaf5.png">
<img width="763" alt="Screen Shot 2020-04-24 at 2 39 51 AM" src="https://user-images.githubusercontent.com/446838/80182491-0795af80-85d5-11ea-89cc-19f1ffb79104.png">

#### Steps to produce the issue

Take any linechart with multiple datasets ... if all datasets are being displayed note that the default y scale causes the lines to be needlessly compressed to the bottom of the chart.

Select only one dataset and the default y scale is good.

As you add more datasets the y scale it gets worse.

It looks like the algorithm being used to adjust the Y scale is assuming 'stacked' datasets.

**Comment by theiliad** [comment]
Hi, this should be happening because of the `stacked: true` flag you've got in your options

```js
{
 axes: {
   left: {
      stacked: true
   }
 }
}
```
