### ISSUE TITLE
Proposed design: Metering

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon-charts#601]
#### I am submitting a...

- [x ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ x] Other (proposed design)

### Issue description
Meter is still in the works for the Carbon design team. The DB2 went ahead and created our own gauges to show proportion of resource consumption. 
Knowing how the system is doing at all time is one of the critical responsibilities of our key target persona. Our users demanded the detailed information to better understand what is taking up the  memory. If they are running out of the memory, they must scale up the core to prevent the system failure due to the lack of memory. 

Below is an example of the order of the mental processing: 
What is it (title)?
What does it mean (title definition)?
What is the total amount? 
How much was being used?
How much was available?
What was taking up the memory?

The current CX lacks component to support our use cases.

Old design:
![gauge](https://user-images.githubusercontent.com/63752979/80737929-185c8e80-8ac9-11ea-9ea8-df6e8ff1167b.png)

New design:
<img width="993" alt="multi-color-gauge" src="https://user-images.githubusercontent.com/63752979/80737855-f82ccf80-8ac8-11ea-8350-dc7c28128945.png">

**Comment by jeanservaas** [comment]
![image](https://user-images.githubusercontent.com/43144260/86064487-df8e5680-ba32-11ea-8f0b-9998d7a6ffec.png)
