### ISSUE TITLE
Fix documentation links & add style imports.

### ISSUE THREAD

**Issue by martijnmelchers** [carbon-design-system/carbon-charts#618]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
Latest

### Issue description
Hi, recently we ran into an issue with your documentation. We were using your library and we couldn't find why all our charts were looking unstyled and they had a black background. In the Angular docs it states nowhere that you have to import the styles manually, were had to find it by trying every possible solution there is and it made us annoyed. You should add a line to your documentation that you should import these styles and where to find them.

We had to add the following line to our `styles.scss`:

`@import "~@carbon/charts/styles/styles";`

**Comment by theiliad** [comment]
Natasha's PR should add the missing import instruction.

It's pretty typical for libraries to have a separate `style.css`, and finding should be as easy as browsing https://unpkg.com/browse/@carbon/charts@0.30.24/ for a developer

we should have added the line in there nonetheless, seems like angular was the only one missing this info
