### ISSUE TITLE
Changelog files do not list changes

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-charts#619]
#### I am submitting a...

- [x] Demo/documentation defect

### Issue description

I’m reviewing a PR on my project (https://github.com/IBM/carbon-addons-iot-react/pull/1200) that is updating carbon charts from `0.30.18` to `0.30.24`.

I’d like to get a sense of what’s changed between these versions, but [the various package changelogs state "version bump only"](https://github.com/carbon-design-system/carbon-charts/search?l=Markdown&q=30.24).

https://github.com/carbon-design-system/carbon-charts/blob/0cea6d2fd7af19b13ee92ae21c55e0a0fffd1103/CHANGELOG.md#L6-L56

[The compare view shows changes](https://github.com/carbon-design-system/carbon-charts/compare/v0.30.18...v0.30.24) - why aren’t these outlined in the changelog files?

**Comment by theiliad** [comment]
CHANGELOG is functioning again
