### ISSUE TITLE
LineChart Slow performance rendering graph with thousands of data points

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#620]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.30.18

### Issue description
If I render a LineChart with 9000 datapoints and 5 lines, it takes many 20-30 seconds before it returns in Firefox

#### Steps to produce the issue
Generate a timeseries LineChart with 9000 datapoints and 5 lines a piece, notice the render time is slow. 

I attached the devTools performance monitor to it and it seems that lots of time is spent in the garbage collector cleaning up abandoned addEventListeners styleCircles

![image](https://user-images.githubusercontent.com/6663002/82263835-5bbc5700-9929-11ea-83de-0950a1508017.png)

#### Current behavior
10-15 seconds to render

#### Expected behavior
Faster initial render for these large data loads

### Screenshot or recording

![image](https://user-images.githubusercontent.com/6663002/82264343-5c092200-992a-11ea-9a46-98b8f64cbace.png)

**Comment by leeoniya** [comment]
@scottdickerson 

it looks like carbon-charts uses SVG, which will always run into performance issues with large datasets. you might want to evaluate some Canvas-based libs for this use-case: https://github.com/leeoniya/uPlot#performance

(maintainers, sorry for the shameless plug, but from my testing i don't believe the large-dataset problem is solvable in svg-based libs, the perf gap is simply too large).

**Comment by theiliad** [comment]
we can take a look @scottdickerson, would you be able to pass your data & options to me somehow? Through slack maybe.

In terms of rendering 9000 points, canvas definitely will do a better job than SVG, but it'll come with it's own set of downsides (almost total lack of accessibility, text rasterizations etc.)

Also, I can't think of a reasonable UX where a user would be shown 9000 points within 1 graph view.

You'd either:
- Be doing this in line charts, where you're really showing the trend so not all 9000 points need to be plotted, correct me if I'm wrong
- Be showing bars, in which case you should really start out with a zoomed view that can pan around

And other chart types such as pie also have really small data limits beyond which the chart is really unreadable.

There definitely wouldn't be a reason UX-wise to show that many points within 1 graph view.

Eitherway I'll look through the eventListener issue

**Comment by scottdickerson** [comment]
@theiliad was there a proposed (or delivered) solution or workaround?  Is it the pan-and-zoom feature to show the trend for the larger data set, and the line chart only shows some smaller subset of the data?

**Comment by theiliad** [comment]
yes zoom & pan is probably the best bet for a larger collection of data

**Comment by ShongSu** [comment]
@theiliad It seems that zoom bars only can be used in time-series charts, how about generic charts?
I have a `<StackedBarChart />` with only 200 records but it takes more than 3s to rerender every time.

**Comment by theiliad** [comment]
> @theiliad It seems that zoom bars only can be used in time-series charts, how about generic charts?
> I have a `<StackedBarChart />` with only 200 records but it takes more than 3s to rerender every time.

Hi, please create a separate issue with actual data & options that we can look at.
