### ISSUE TITLE
Need a Life-cycle hook for when chart rendering has completed.

### ISSUE THREAD

**Issue by deandwill** [carbon-design-system/carbon-charts#628]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Need a way to know when all Chart DOM updates have completed, so developers can trigger their own DOM updates
For example: "Sparse" x-axis labels is not supported within Carbon Charts ... but with the above life-cycle hook this could easily be done after-the-fact.

**Comment by theiliad** [comment]
looking through the currently dispatched event types you'll find `render_finished`
