### ISSUE TITLE
Line Chart - Allow to remove extra padding from start and stop of data

### ISSUE THREAD

**Issue by JeffBaumgardt** [carbon-design-system/carbon-charts#630]
#### I am submitting a...

- [x] Feature request
- [x] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
0.30.24

### Issue description
In every usage of the line chart, and I assume others, there is extra white space at the start and end of the data. I would like to display a chart that starts at the axis and ends at the axis.

#### Steps to produce the issue
I created a code sandbox (https://codesandbox.io/s/recursing-merkle-wn2oe?file=/src/index.js) but any line chart from the storybook works as well.

#### Current behavior
Extra white space before and after data

#### Expected behavior
I would like an option to remove this extra space. Or ability to specify min, max on each axis.

### Screenshot or recording
![Screen Shot 2020-05-21 at 12 39 18 PM](https://user-images.githubusercontent.com/777527/82593677-1b92e980-9b60-11ea-89bf-d24eca4c3018.png)

**Comment by theiliad** [comment]
Hi, please set this flag in your charting options
![image](https://user-images.githubusercontent.com/14989804/82635750-eec9eb00-9bce-11ea-86a0-52fc135572d2.png)
