### ISSUE TITLE
Line Chart - Thresholds line appearing off chart

### ISSUE THREAD

**Issue by JeffBaumgardt** [carbon-design-system/carbon-charts#631]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [x] Other

#### charts version:
0.30.24

### Issue description
I have a time series data line chart and on that chart I want to denote events using the thresholds array. My chart (https://codesandbox.io/s/recursing-merkle-wn2oe?file=/src/index.js) is of just a few hours of data and I've set a threshold to be inside of that data set, but it is appearing to the left of the entire chart, not where it is intended to be.

#### Steps to produce the issue
Please see https://codesandbox.io/s/recursing-merkle-wn2oe?file=/src/index.js for reproduction. 

#### Current behavior
The threshold line is rendered outside of the chart

#### Expected behavior
Threshold line should render within the given scale of data format.

### Screenshot or recording
![Screen Shot 2020-05-21 at 2 49 36 PM](https://user-images.githubusercontent.com/777527/82604934-4ede7400-9b72-11ea-8d81-8fadf62c6802.png)
In this example I attempted to put a red threshold at 12:30 `(2020-05-20T18:30:00.000Z)` but you can see it is off to the left.

**Comment by theiliad** [comment]
Thanks @JeffBaumgardt, got a PR that'll resolve the issue
