### ISSUE TITLE
[AVT], StackedBarChart/ DonutChart/ LineChart, Elements that use 'role' must reference a valid WAI-ARIA role

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon-charts#634]
Charts version
"@carbon/charts": "^0.30.10",

Elements that use 'role' must reference a valid WAI-ARIA role violations are seen in the 3 charts we use StackedBarChart/ DonutChart/ LineChart
23 violations in DonutChart( both empty state and with data)
26 violations in StackedBarChart( both empty state and with data)
8 violations in LineChart( both empty state and with data)

![image](https://user-images.githubusercontent.com/44162180/82658304-61c17900-9c44-11ea-8138-e5f2b5a34a9a.png)

![image](https://user-images.githubusercontent.com/44162180/82658411-903f5400-9c44-11ea-97d9-1c1b3412de59.png)

![image](https://user-images.githubusercontent.com/44162180/82659922-12307c80-9c47-11ea-816c-cbba8b0a4e51.png)

**Comment by theiliad** [comment]
`graphics-documents` is a valid role https://www.w3.org/TR/graphics-aria-1.0/#:~:text=graphics%2Ddocument%20(role),layout%20of%20content%20conveys%20meaning.

**Comment by PAnilReddy** [comment]
@theiliad,
Well but the DAP shows it as error. Can you keep this open until we get the confirmation from accessibility team on the same and until we revert back.

**Comment by yinting-github** [comment]
@theiliad  I retested it using DAP and IBM Accessibility Checker, it both report this error.
Would you mind to check the details under https://www.w3.org/TR/graphics-aria-1.0/#graphics-symbol, to see if any fixing can be implemented? Thanks.
Can we reopen this defect for tracking purpose?

**Comment by theiliad** [comment]
@yinting-github as far as I can read into [this](https://www.w3.org/TR/graphics-aria-1.0/#graphics-symbol) page, the way we're using `graphics-symbol` is completely acceptable

![image](https://user-images.githubusercontent.com/14989804/84617671-c1a2ec80-ae9d-11ea-87ba-1703d1a00dbd.png)

If this is still an issue in DAP I'd suggest creating an issue in their repo or creating a support ticket etc.

**Comment by yinting-github** [comment]
@theiliad we advised this specific issue to #accessibility-at-ibm team, and below are the comments:
_You may need to post your code so we can review specifically what is the problem.
You probably need to add img to the role to support older user agents per the documentation in the green box note box.
Also add aria-label="Description of overall graphic"  to provide a text description of the graphic as well.
I would generally follow the IBM Accessibility Checklist, as it is a slightly different (usually more conservative) set of standards than the w3 standards.
https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html_
![image](https://user-images.githubusercontent.com/63330745/84999338-9b25cf80-b183-11ea-86a1-a17bdc30e3c9.png)

**Comment by yinting-github** [comment]
![image](https://user-images.githubusercontent.com/63330745/84999823-420a6b80-b184-11ea-894b-db93ce0ac336.png)

**Comment by yinting-github** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/63330745/85000100-8bf35180-b184-11ea-8498-167ed8aa53f3.png">

**Comment by yinting-github** [comment]
@theiliad  Would you please reopen this defect so we can continue to track it? Thanks.

**Comment by theiliad** [comment]
not sure if this is still relevant to us. yes looks like we might want to add an `img` role as fallback, but what's really broken here?

**Comment by pankaj-kumar34** [comment]
We are still facing this issue and should be reopened

**Comment by theiliad** [comment]
> We are still facing this issue and should be reopened

Hi 👋
As mentioned in the previous issue created, this is a DAP bug that we've reported to them and they've fixed.

#634

IBMa/equal-access#194

This isn't really a `Carbon Charts` issue, it'll happen with any SVGs with the DAP version you're using.
For further assistance I would:
- update the DAP version you're using
- reach out to DAP

I am not able to help at this point as those are valid WAI-ARIA roles that we're using 🙂
