### ISSUE TITLE
TimeSeries Axis - ShowDayName still showing day name on first axis tick

### ISSUE THREAD

**Issue by JeffBaumgardt** [carbon-design-system/carbon-charts#637]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [x] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
0.30.24

### Issue description
Using the `showDayName: false` still shows the first tick with the day name
https://codesandbox.io/s/recursing-merkle-wn2oe?file=/src/index.js:1141-1217

#### Steps to produce the issue
In a line chart, with time data on x axis, set `timeScale: { showDayName: false},` in the options.

#### Current behavior
The first tick still shows the day name as the first tick

#### Expected behavior
With the provided option I expect to only show the time

### Screenshot or recording
![Screen Shot 2020-05-22 at 1 15 21 PM](https://user-images.githubusercontent.com/777527/82701954-51060880-9c2e-11ea-912d-131bf1d0aa7f.png)
![Screen Shot 2020-05-22 at 1 15 11 PM](https://user-images.githubusercontent.com/777527/82701963-5400f900-9c2e-11ea-82a6-79418ac1e5d7.png)

I used the following data & options.
```
const data = [
  {
    count: 115,
    ts: "2020-05-20T18:00:00.000Z",
    group: "Detections"
  },
  {
    count: 120,
    ts: "2020-05-20T19:00:00.000Z",
    group: "Detections"
  },
  {
    count: 119,
    ts: "2020-05-20T20:00:00.000Z",
    group: "Detections"
  },
  {
    count: 15,
    ts: "2020-05-20T21:00:00.000Z",
    group: "Detections"
  }
];
```
```
options: {
      axes: {
        bottom: {
          mapsTo: "ts",
          scaleType: "time",
          includeZero: false,
          thresholds: [
            {
              value: "2020-05-20T18:30:00.000Z",
              label: "Deployment",
              fillColor: "red"
            }
          ]
        },
        left: {
          mapsTo: "count",
          scaleType: "linear",
          includeZero: true
        }
      },
      height: "400px",
      legend: {
        position: "top"
      },
      timeScale: {
        addSpaceOnEdges: 0,
        showDayName: false
      },
      color: {
        scale: {
          Detections: "#6929c4"
        }
      }
    }
```

**Comment by theiliad** [comment]
that's how the specs are designed, first label is always going to have full context, regardless of the configs
