### ISSUE TITLE
Ability to highlight grid lines/values 

### ISSUE THREAD

**Issue by carmiele** [carbon-design-system/carbon-charts#640]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
I am proposing the (optional) ability to **highlight a value/line on the grid itself**, external to the data set.  There are some cases where a grid line/value has to be highlighted in order to showcase it as a valuable reference related a certain data set (e.g. lower and/or upper thresholds).  These are different from lower/upper ranges of the data, in that the value is not necessarily within the data itself, but rather part of the area/chart the data is a part of. (See screenshot of proposed design below).

For the new feature, I am proposing the following options:
- ability to add custom colors to the threshold lines
- ability to specific which axis the highlighted lines (values) are on
- upon hover of the line, show tooltip for the value the line represents (in alignment with the existing Carbon Charts behavior), in additional to any additional label information for what that threshold indicates (see text "Exceeded by 100 temp mins")
- (OPTIONAL if time permits): ability to specify not only min/max values (2 lines), but also any other custom values a user might want to display (any number of highlighted grid values)

### Screenshot or recording
![ThresholdLines](https://user-images.githubusercontent.com/3290221/82930774-c4638f00-9f3a-11ea-8c93-3fca5ce25760.png)

**Comment by theiliad** [comment]
This is already available
https://carbon-design-system.github.io/carbon-charts/?path=/story/line--line-with-thresholds-time-series

**Comment by carmiele** [comment]
I see this is for the Vanilla charts only. Is there support for threshold options in the Angular Charts?

**Comment by theiliad** [comment]
Yes it's available, we should add the demos to all wrappers but essentially you'll pass in the same data/options as vanilla to all wrappers.

**Comment by carmiele** [comment]
ok thanks! I'll look into that.
