### ISSUE TITLE
[Donut Chart] Add Support for horizontal (row) alignment of left/right legend

### ISSUE THREAD

**Issue by carmiele** [carbon-design-system/carbon-charts#641]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### Current behavior
Currently the legend of the donut chart, when positioned either to the left or right of the donut chart, can only be displayed in a column format.
![DonutChartLegend](https://user-images.githubusercontent.com/3290221/82932031-a7c85680-9f3c-11ea-84b0-0f129b800e67.png)

#### Proposed behavior
I would like to be able to specify a horizontal alignment of the legend, where they are organized on a row and overflows downwards.
![DonutChartLegend](https://user-images.githubusercontent.com/3290221/82932982-1f4ab580-9f3e-11ea-8506-9037308e44d9.png)

**Comment by theiliad** [comment]
Hi, that unfortunately is not part of the specs

Feel free to re-open if you'd like design to review this

**Comment by carmiele** [comment]
Can I get this re-opened for design review?

**Comment by theiliad** [comment]
@designertyler please chime in here

**Comment by designertyler** [comment]
Hi @carmiele, could you give more info on why this layout change would help your use case? 

The benefit of the column layout is that it should be quicker to scan compared to the horizontal layout. The horizontal layout relies on subtle proximity differences of the label and color where the vertical column layout's grid groups color and title without much work from the user.

In this example, there is only a few pixel difference between the magenta representing "Distribution Center" vs "In-transit to restaurant"

![image](https://user-images.githubusercontent.com/19270502/83032864-fdb00380-9ffb-11ea-95a7-29ea79ab7231.png)

Having this vertical alignment for the legend is one of the main pros for having the legend on the left or right. I worry that having horizontal alignment on the left or right might not utilize the space as well and we would have legend items moving further away from the visual just to fill horizontal space.

**Comment by carmiele** [comment]
@designertyler this would be mainly for larger screens or larger dashboards, where the space allocated to the legend is disproportionately larger than the actual chart itself. This isn't a problem on chart containers smaller than~600/700px, but the bigger the container, the large amount of space in between the legend and the chart becomes more of an eyesore. It would be more ideal if the contents of the legend take up the remaining space allocated to the whole chart container. See screenshot:
<img width="719" alt="Screen Shot 2020-05-27 at 8 03 46 AM" src="https://user-images.githubusercontent.com/3290221/83037931-3a2a3200-9ff1-11ea-9c84-61afb67abc40.png">

**Comment by theiliad** [comment]
I think a better solution would be to bring the legend closer to the donut.

Donut/pies are circles, which means similar to a square the width and height of the actual pie/donut will be of equal sizes.

Therefore if your charting container width is a lot larger than your height, you'll end of with spare space, that's just how it'll physically work.

**Comment by carmiele** [comment]
ok, thanks for the guidance. I'll get back to our designers and see if that would be an acceptable solution.
