### ISSUE TITLE
Modification of Axis label Alignment and Placement

### ISSUE THREAD

**Issue by carmiele** [carbon-design-system/carbon-charts#642]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Is there a way to specify a horizontal alignment for the y-axis label? The vertical alignment can be hard to read sometimes with longer labels.
I would also like to move the labels to the edges of the axis, instead of centering.

### Screenshot or recording
<img width="457" alt="labels" src="https://user-images.githubusercontent.com/3290221/82937463-098cbe80-9f45-11ea-8b11-ac7e8c6c52a7.png">

**Comment by theiliad** [comment]
unfortunately none of these have been explored or are currently supported. Feel free to contribute the work to the library if you have the bandwidth

**Comment by carmiele** [comment]
Sounds good! If the design is approved for the Carbon spec, I can provide the development effort.

**Comment by theiliad** [comment]
@designertyler can chime in on the design

**Comment by carmiele** [comment]
Any update regarding the design approval?

**Comment by theiliad** [comment]
Haven't heard back from Tyler. I personally see no reason to add this piece, the library should be able to automatically rotate based off of whether all ticks fit fine and are readable, which I believe it does currently unless there are edge cases or bugs. Wrt the `today` mark I've seen many teams use our threshold component for that

**Comment by designertyler** [comment]
I'm having trouble understanding the request based on the description and image.

The image seems like it's a request to remove the legend and add labels to the end of the data line on the chart. IMO that seems reasonable with some adjustments to the alignment of the labels and the axis titles. You do lose the ability to select and focus on one data set like the current legend offers.

It's almost like a persistent tooltip positioned on the end. Am I interpreting the request correctly?

**Comment by carmiele** [comment]
@designertyler it's just the movement of the labels from the center of the data line to the edges/end of the data line. The legend would remain as is, wherever it is currently placed. I edited the chart to illustrate what I mean:
<img width="457" alt="labels" src="https://user-images.githubusercontent.com/3290221/84444330-63081500-abf6-11ea-9b2d-3c5147ea0507.png">

**Comment by carmiele** [comment]
The label of the lines themselves (tooltip) can remain as a hovered behavior, instead of being persisted on to the page. That behavior as is is fine.
