### ISSUE TITLE
Support for External Legends on a Group of Charts

### ISSUE THREAD

**Issue by carmiele** [carbon-design-system/carbon-charts#643]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
I sometimes have a group of charts that have the same exact legends.
In order to keep the design consistency, I would like the ability to specify an external legend to control multiple charts, instead having to click the individual chart's legend to view each of the data.

### Screenshot or recording
<img width="626" alt="shared legends" src="https://user-images.githubusercontent.com/3290221/82937808-a2bbd500-9f45-11ea-8821-f2600013dd44.png">

**Comment by theiliad** [comment]
we currently don't support rendering multiple charts through one component. this seems like something that either:
- you'd build on your end (render 2 charts using the library and render a custom legend at the top)
- you'd have to add as a core functionality to the library and contribute back if you have the bandwidth

**Comment by carmiele** [comment]
Sounds good! If the design is approved for the Carbon spec, I can provide the development effort.

**Comment by theiliad** [comment]
@designertyler can chime in on the design. Please note that in order to get this functionality 2 different pieces need to be added to the library:
1. Support for the rendering of multiple charts/graphs within 1 component
2. The external legend + any other utilities/layout components that need to go with the multi-graph functionality

**Comment by carmiele** [comment]
Any update regarding the design approval?

**Comment by designertyler** [comment]
Hi @carmiele

Do you have a larger view of how these external legends would appear on the page? I'm not sure if the "unit of measure - case" is meant as a title or something else.

How many charts will be grouped with the same legend? Is it possible the legend would ever be off-screen in a dashboard situation with several charts in a group?

How would the legend be visually grouped with the multiple charts? In that mockup the legend is on the grey 10 background with each chart getting its own white tile. Can we use the same white background behind the legend and all grouped charts? It would help organize the screen if there were several different chart groups.

**Comment by carmiele** [comment]
@designertyler here are the charts with the external legend in the context of the page:
<img width="1037" alt="Screen Shot 2020-06-11 at 3 04 45 PM" src="https://user-images.githubusercontent.com/3290221/84443811-3e5f6d80-abf5-11ea-84be-f10be8a91c79.png">
The idea is to fit 3 in the same row/group with and controlled by the same legend.
I don't think we could use the same background for the legend as the tile, as long as all components were in the same parent tile container.

Also, the "unit of measure - case" is meant to be a side note, not as a label. I think we can ignore that part of the mockup for now, since they're not quite finalized.

**Comment by jeanservaas** [comment]
Hi @carmiele Carbon certainly wouldn't block this behavior if you're willing to do the implementation. I would just make sure to match your donut chart and legend to the Carbon Donut. 

1. Your legend squares look larger than carbon legend squares.

2. You wouldn't need to repeat the legend squares, for the donut, the appropriate legend would be the one at the top, where it says "In good condition" and "out of code;" the other percentages would be labels on the actual donut. Also, not sure I understand what this means "81% - 230" Does that show both the percentage and the number of cases at the same time? I would arrange the type differently (see below) so people don't think that dash is a minus. You can also include your unit in the title of chart too, like Cases per week etc.

3. Use Carbon approved color pairings... looks like you have a 2-color donut, so these would be your choices

![image](https://user-images.githubusercontent.com/43144260/85746174-42e75400-b6d4-11ea-8e67-b5aeea97308d.png)

4. You need a 1px white stroke between the colors for accessibility (see below)

![image](https://user-images.githubusercontent.com/43144260/85745475-b89ef000-b6d3-11ea-834f-ade8dd5c5487.png)

5. Without the large central number... you might also consider just using a pie here — also, I don't really mind the repeated legends, but it's up to you if you want to implement it with the legend outside the tile, I would actually make sure not to separate the tiles though in that case, so you're aware that they all belong to the same legend.

![image](https://user-images.githubusercontent.com/43144260/85748304-f69d1380-b6d5-11ea-93d6-06ef9dc869a0.png)

With all of this you should be good to go. Here are also the structural specs for the donut below. When the donut's in the tile, you can center it in your square and the legend and the title should be equidistant from the edge of your tile... so you don't need to worry so much about the distances between things.

![image](https://user-images.githubusercontent.com/43144260/85748983-74f9b580-b6d6-11ea-9680-82cb44b5ac31.png)

**Comment by carmiele** [comment]
@jeanservaas sounds good, thanks for the feedback! I'll use this design as part of my implementation.
