### ISSUE TITLE
Export types for charts-react

### ISSUE THREAD

**Issue by JeffBaumgardt** [carbon-design-system/carbon-charts#644]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version
0.32.0

### Issue description
TypeScript types are not exported in `charts-react`

#### Steps to produce the issue
Use codesandbox or CreateReactApp with typescript template.
`import { LineChart } from '@carbon/charts-react'`

#### Current behavior
Typescript error
```
Could not find a declaration file for module '@carbon/charts-react'. '/Users/jb/Projects/app/node_modules/@carbon/charts-react/bundle.js' implicitly has an 'any' type.
  Try `npm install @types/carbon__charts-react` if it exists or add a new declaration (.d.ts) file containing `declare module '@carbon/charts-react';`ts(7016)
```

#### Expected behavior
Could possibly export types in package.json or add types to definitelytyped.

**Comment by theiliad** [comment]
Hi, there are no types defined for the react wrappers, unless we bind the vanilla types to the react components. Feel free to contribute this if you have the bandwidth 🙂

**Comment by metonym** [comment]
@theiliad Could I work on this?

**Comment by theiliad** [comment]
PR #867 addressed this, thanks @metonym
