### ISSUE TITLE
Line Chart - addSpaceOnEdges not being respected

### ISSUE THREAD

**Issue by JeffBaumgardt** [carbon-design-system/carbon-charts#645]
#### I am submitting a...
Ref #630
- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [x] Other

#### charts version:
0.32.0

### Issue description
I have a line chart with an option to set the `addSpaceOnEdges` to 0 as to remove the extra white space at the start and end of the chart. This seems to have stopped working.

#### Steps to produce the issue
See https://codesandbox.io/s/affectionate-bush-mxzy5?file=/chart.js:2649-2719
```
timeScale: {
  addSpaceOnEdges: 0,
  showDayName: false
},
```

#### Current behavior
Extra white space at start and end of chart

#### Expected behavior
With the requested option to not have any extra spacing.

### Screenshot or recording
![Screen Shot 2020-06-01 at 10 34 05 AM](https://user-images.githubusercontent.com/777527/83430755-709ded80-a3f3-11ea-9d90-7b1b252ac787.png)

#### Bonus issue
Also if you see on that code sandbox an error will shortly appear 
```
TypeError
Cannot read property 'type' of null
    at SVGCircleElement.eval (https://mxzy5.csb.app/node_modules/
```

This appears to be coming from d3 but I'm not sure.

#### Extra question
Since I updated from 0.30.25 to 0.32.0 the `carbon-components` package is now also required. Not sure if this has been documented.

**Comment by JeffBaumgardt** [comment]
Also,
Not represented on the codesandbox but in my actual app the axis are invisible by being set to an opacity of 0, not sure how to fix that.

![Screen Shot 2020-06-01 at 10 38 11 AM](https://user-images.githubusercontent.com/777527/83431081-020d5f80-a3f4-11ea-849b-ef93b043083d.png)

![Screen Shot 2020-06-01 at 10 38 42 AM](https://user-images.githubusercontent.com/777527/83431128-13566c00-a3f4-11ea-91c4-a4a27e01fb5a.png)

**Comment by JeffBaumgardt** [comment]
Note: To see the error as described in the bonus issue, attempt to hover a data point.

**Comment by theiliad** [comment]
@JeffBaumgardt `carbon-components` isn't a hard dependency for `@carbon/charts`.

Seems like codesandbox has made some changes and is using es modules for default module resolution... every codesandbox we link to now seems to be broken because of that

**Comment by JeffBaumgardt** [comment]
My vs code also complained about that import as well

**Comment by theiliad** [comment]
vscode shouldn't do that also, we'll add it as a dependency

**Comment by JeffBaumgardt** [comment]
Link to #651 for the dependency question.

**Comment by theiliad** [comment]
**UPDATE:** we've got someone reaching out to codesandbox to find out what they've really changed which is causing this override in module resolution behaviour.

The tooltip error seems to be coming from d3 which when manually switching to the specified `main` bundle in our package.json it's fixed.

Pretty sure no bundler should override the `main` field with something else, even if it's `module`, I'll research some more

**Comment by theiliad** [comment]
Closing because `addSpaceOnEdges` seems to be working fine, and codesandbox examples have been fixed 
![image](https://user-images.githubusercontent.com/14989804/84416782-ae182d00-abe2-11ea-878b-29d3cb6ee15b.png)

`carbon-components` dependency has also been addressed [here](https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--vanilla)
