### ISSUE TITLE
Line Chart - Empty state is not respecting height constraint

### ISSUE THREAD

**Issue by JeffBaumgardt** [carbon-design-system/carbon-charts#648]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
0.32.0

### Issue description
If you generate a chart with 0 data then you get a blank grid, however the rendered chart is larger than that of the same chart but with data

#### Steps to produce the issue
See codesandbox - https://codesandbox.io/s/hopeful-mayer-m6xkr?file=/src/App.js

Set height in options `height: "240px",`

In the sandbox I have a chart that optionally displays data. First render is empty data. Clicking on toggle data will re-render the line chart with a few points of data.

#### Current behavior
The chart size jumps from empty state to filled state.

#### Expected behavior
Since I am passing a height in the options I would expect that height to always be respected, regardless of data.

### Screenshot or recording
![Screen Shot 2020-06-01 at 2 33 47 PM](https://user-images.githubusercontent.com/777527/83451905-f4b49d00-a414-11ea-9350-e18758b58ac8.png)
![Screen Shot 2020-06-01 at 2 33 56 PM](https://user-images.githubusercontent.com/777527/83451910-f716f700-a414-11ea-816f-fa7e9bdb1158.png)

**Comment by theiliad** [comment]
Hi, the current behaviour matches the specs. Feel free to make a PR if you have the bandwidth for implementing this, thanks
