### ISSUE TITLE
Scatter chart - multi-tooltip doesn't show on hover over data points

### ISSUE THREAD

**Issue by navjeets** [carbon-design-system/carbon-charts#650]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.30.24
### Issue description
If there are multiple data points, with same x and y values, the multi-point tooltip only shows on hover over grid and not the actual point. This may lead to user not knowing that there are multiple data points especially when AxisTooltipOptions.gridline.enabled is set to false.
#### Steps to produce the issue
Create new Scatter chart with dataset containing multiple records with same x and y values. Observe that the multi-tooltip shows on hover over grid but not the point.
#### Current behavior
If there are multiple points with same x and y values, multi-point tooltip doesn't show on hover over data point.
#### Expected behavior
Multi-point tooltip should show on hover over data points with same x and y values.

**Comment by theiliad** [comment]
According to the specs, the multidata tooltip should only show when hovering on a point if there are other points behind that hovered point which cannot be seen properly.

If you're hovering over just 1 point you should always be seeing the singular tooltip.

**Comment by navjeets** [comment]
Yes. This issue is about the scenario where there are multiple points with same x and y values (i.e. overlapping points) and multidata tooltip doesn't show on hover.

**Comment by theiliad** [comment]
yes, just leaving that piece as an FYI for everyone else that might get to this issue
