### ISSUE TITLE
Feature: Support time-based Grouped bar charts

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-charts#655]
#### I am submitting a...

- [x] Feature request

### Issue description

In Maximo Asset Monitor, we have a customer use-case for grouped, time-based bar charts. This seems to be the only type of bar chart that is missing the time-series support.

### Screenshot Example

This is only a general example of what the chart would look like. The labels would stay the same as a regular grouped bar chart

![Screen Shot 2020-06-05 at 9 15 10 AM](https://user-images.githubusercontent.com/25177649/83886720-15c70780-a70d-11ea-832e-690e5b6a144c.png)

**Comment by theiliad** [comment]
Hi @sstone2423, do you have the bandwidth for contributing this piece?

**Comment by sstone2423** [comment]
I haven't contributed to this library before. Could you send me a link to the general area where this would be and I can try and estimate the work?

**Comment by theiliad** [comment]
@sstone2423 I'd start with the contribution guidelines https://github.com/carbon-design-system/carbon-charts/blob/master/CONTRIBUTING.md

and the grouped bar chart class https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/src/charts/bar-grouped.ts

**Comment by scottdickerson** [comment]
@theiliad this is important for us in the next sprint, I'll take it

**Comment by theiliad** [comment]
> @theiliad this is important for us in the next sprint, I'll take it

👍

**Comment by vgb1993** [comment]
We also need this to display year over year comparisons

**Comment by SteffenBaumann** [comment]
I just encountered this isn't working and considered it as a bug. Searching for existing issues, revealed this is actually still pending? Using time series on a GroupedBarChart are failing with an error on DomainScale.step().

@scottdickerson @theiliad Anything specific blocking this request? :)
