### ISSUE TITLE
[LineChart] domain range is rendering invalid values

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-charts#658]
#### I am submitting a...

- [x] Source code defect

### Issue description

When attempting to use domain range in line time series charts, no error appears and the x-axis shrinks correctly, but points outside of the domain still get painted

#### Steps to produce the issue

On a line time series chart, add a domainRange using timestamp values smaller than the actual values given to the chart

#### Current behavior

Points are painted / rendered outside of the domain range and axes

#### Expected behavior

Only the valid values within the domain range are rendered

### Screenshot or recording

![image](https://user-images.githubusercontent.com/25177649/83915773-85eb8280-a739-11ea-96dc-8dba5ee4eba3.png)

**Comment by theiliad** [comment]
this is a bug in the code. either model, axes or graphs should take into account the domain

**Comment by sstone2423** [comment]
Thanks for the fix. Looks good!
