### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#66]
We essentially should be testing at the very least:
- [ ] Data processing & Render
- [ ] Tooltips
- [ ] Legend filters
- [ ] Data updates

**Comment by t-mullen** [comment]
Spent some time assessing our test effort today.

Adding code coverage would be a good place to start with this. I wasn't able to get it working with istanbul-coverage, karma-coverage or karma-typescript's coverage though. Those modules really dislike the inclusion of non-code files like SVG. Maybe someone more adept with webpack could take a look.

There are several commented-out unit tests already. They fail with a cryptic "Script Error" that I wasn't able to debug (it has no trace at all).

The existing tests are fragile and fail intermittently. They're all wrapped in timeouts, which could be part of the problem (is this normal for Jasmine tests?).

**Comment by theiliad** [comment]
We will potentially replace webpack with Rollup. What are the possibilities there?

The tests that use setTimeouts are testing functionality that the library needs to run and update DOM.

**Comment by t-mullen** [comment]
I'm not sure about Rollup. I noticed some incompatibilities with how webpack does module loading (`nyc` for example relies on overriding "require"), so it might help.

Apparently ES6+TypeScript+Karma+Webpack is just not a usecase that any of the code coverage tools account for.

**Comment by theiliad** [comment]
**UPDATE**: @t-mullen & I are putting together a full test plan (WIP currently), and will start with unit-tests, but will also implement code-coverage analysis down the road:
https://github.com/IBM/carbon-charts/wiki/Test-Plan-for-v1.0
