### ISSUE TITLE
timeScale option missing for AxisOptions interface

### ISSUE THREAD

**Issue by carmiele** [carbon-design-system/carbon-charts#668]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
`AxisOptions` is missing the `timeScale` option.

#### Steps to produce the issue
found in latest commit: https://github.com/carbon-design-system/carbon-charts/blob/0402e2a2c3c99b780ebfe6dc9fe1238c3106b002/packages/core/src/axis-chart.ts

#### Current behavior
Missing option to use `timeScale` when typecasting options objects to `AxisOptions` and its inherited interfaces/classes.

#### Expected behavior
Have option to use `timeScale` when typecasting options objects to `AxisOptions` and its inherited interfaces/classes.

**Comment by theiliad** [comment]
@sophiiae could you please take a look?

**Comment by sophiiae** [comment]
> @sophiiae could you please take a look?

Sure.
