### ISSUE TITLE
Charts in Angular not showing in it's real size

### ISSUE THREAD

**Issue by OmarSherif96** [carbon-design-system/carbon-charts#670]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
**- [ ] Source code defect**
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
"@carbon/charts": "^0.32.6",
"@carbon/charts-angular": "^0.32.6",
### Issue description
Charts in angular not working properly I tried the Donut and Bubble chart 

#### Steps to produce the issue
Followed this guide https://carbon-design-system.github.io/carbon-charts/?path=/story/intro--welcome
### Screenshot or recording
![image](https://user-images.githubusercontent.com/46057697/84730707-3e65c180-af97-11ea-8750-57424c13d800.png)

**Comment by theiliad** [comment]
Hi, have you set width & height in your charting options?

If not, have you set a a width & height for the chart holder?

Also you're missing the CSS import listed [here](https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--angular)
![image](https://user-images.githubusercontent.com/14989804/84730993-8966e100-af65-11ea-9a68-3d1ca4e3a22c.png)

**Comment by OmarSherif96** [comment]
Hello I have that file imported, 

Also I am using this options for the donut chart 

`options = {
		title: "Donut",
		resizable: true,
		donut: {
			center: {
				label: "Browsers",
			},
		},
		height: "4000px",
		width: "4000px",
	};`

**Comment by theiliad** [comment]
Just checked, everything seems to be working well. Something must be going on in your application. Could you share a sandbox please?

**Comment by OmarSherif96** [comment]
https://github.com/OmarSherif96/health-planner-frontend
This is the source code

**Comment by theiliad** [comment]
Please be more specific, which files to look at, which lines to look at etc.

**Comment by OmarSherif96** [comment]
You can find the chart component inside this 
https://github.com/OmarSherif96/health-planner-frontend/tree/master/src/app/pages/catalog

**Comment by nstuyvesant** [comment]
@OmarSherif96 - Is this still an issue in @carbon/charts-angular@1.8.0? BTW, there is a version for Angular 16 now @carbon/charts-angular@next.

**Comment by nstuyvesant** [comment]
@OmarSherif96 - The link provided above gave me a 404.

**Comment by theiliad** [comment]
I'll close for now, pls let us know @OmarSherif96
