### ISSUE TITLE
Hidden Axes Text and Tick Text

### ISSUE THREAD

**Issue by rrTong** [carbon-design-system/carbon-charts#673]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
    "@carbon/charts": "^0.30.25",
    "@carbon/charts-react": "^0.30.25",

### Issue description
Axes and tick text does not show.
`g axis` is set to `opacity: 0`. 
Text is still on display, hidden by `opacity` styling.

#### Steps to produce the issue
`data` is initialized and populated through for-loop logic (used useEffect)
`options` is initialized and populated immediately, O(1)

#### Current behavior
Axes text and tick text is hidden.

##### Screenshot or recording

![image](https://user-images.githubusercontent.com/15644119/84920236-bc00fe80-b077-11ea-8d1e-b33c81e20d7f.png)

#### Expected behavior
Axes text and tick text should be visible.

##### Screenshot or recording

![image](https://user-images.githubusercontent.com/15644119/84920260-c7ecc080-b077-11ea-8e66-45570547cc28.png)

### Current workaround
Wrapping the chart's `data.length` around the chart component.

      {graphData.length && (
        <SimpleBarChart data={graphData} options={options} />
      )}

**Comment by theiliad** [comment]
@sophiiae would you be able to look into this issue?

**Comment by sophiiae** [comment]
> @sophiiae would you be able to look into this issue?

OK.
