### ISSUE TITLE
How to add an event listener?

### ISSUE THREAD

**Issue by jordanoverbye** [carbon-design-system/carbon-charts#683]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:
0.32.13

### Issue description

How do you actually add event listeners? I can't find any docs anywhere. I am looking specifically for Vue but I don't know how you would do it for anything really.

I could only find this documentation which seems incomplete:
`https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--event-listeners`

What is the `barChart` variable in that instance?

#### Steps to produce the issue
N/A

#### Current behavior
N/A

#### Expected behavior
N/A

### Screenshot or recording
N/A

**Comment by theiliad** [comment]
Hi, `barChart` is just an arbitrary name that's used in that guide, it points to the chart object reference.

Here's a small piece of code I wrote using React `refs` to obtain the reference
![image](https://user-images.githubusercontent.com/14989804/86178072-ba165100-baf5-11ea-9bbb-94178548a4e8.png)

**Comment by DakotaWray2** [comment]
For anyone looking at this issue, I found the correct path to add an event listener with Vue at least. 
`const chart = this.$refs.chartRef;`
`chart.coreChart.services.events.addEventListener("scatter-click", e => {
      console.log(e);
    });`
I would agree that the docs could use some work with respect to events.

**Comment by bo0m3r31337** [comment]
@DakotaWray2 
Hey does this add function to every part of lets say a donutChart? I notice I can click the check boxes, and i'd also like to add events for each of those clicks separate functions from lets say clicking directly on a slice in the actual chart.

**Comment by gi4no** [comment]
here all events 
https://github.com/carbon-design-system/carbon-charts/blob/fe4d592991e9cbf68c4b9efab0be4aa46dfcd416/packages/core/src/interfaces/events.ts
