### ISSUE TITLE
Feature request for Bullet Charts

### ISSUE THREAD

**Issue by pjrdata** [carbon-design-system/carbon-charts#684]
#### I am submitting a...

- [ X ] Feature request

#### charts version:
n/a

### Issue description
A Bullet Chart is a good way to show KPIs with thresholds.
One of Stephen Few's original write-ups is here:  https://www.perceptualedge.com/blog/?p=217
and his original specification is here:  http://www.perceptualedge.com/articles/misc/Bullet_Graph_Design_Spec.pdf
Carbon Charts has a horizontal bar version of the meter chart but that doesn't show the thresholds and seeing the thresholds along with the value indicator is really useful. Please include adding a bullet chart style to Carbon Charts.

#### Steps to produce the issue
n/a

#### Current behavior
n/a

#### Expected behavior
n/a

### Screenshot or recording
n/a

**Comment by ninja511** [comment]
tracked in https://github.com/carbon-design-system/carbon-charts/issues/841. Closing this as duplicate.
