### ISSUE TITLE
Problem about options and chart appearances

### ISSUE THREAD

**Issue by etuna** [carbon-design-system/carbon-charts#685]
Hi,

I have integrated the lib into my project. But I havent yet got the working example on my project, I just copied your code for a sample. Why do I encounter such a problem, could u please help me out?
I also tried to set width and height, background color like styling options, but these did not work as well.
Thanks 

![image](https://user-images.githubusercontent.com/13668716/86147640-4dee1a00-bb02-11ea-835f-39229a13eff1.png)

**Comment by theiliad** [comment]
Hi, you're missing the style import

![image](https://user-images.githubusercontent.com/14989804/86149692-53c80900-baca-11ea-8468-0dc597997596.png)

The line is included in all storybooks and our [getting started guides](https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--vanilla)

**Comment by etuna** [comment]
Thanks for the reply.

Yes, actually it was not the exact case. But after you reply, I have seen that it did not apply to css styles and I changed the encapsulation as ViewEncapsulation.None from default settings. (angular)

Thank you, have a good day
