### ISSUE TITLE
a11y: Donut charts aria-label

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/carbon-charts#693]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [X] Other

#### charts version:
0.30.18
### Issue description
Elements having any WAI-ARIA roles must have a label specified with aria-label or aria-labelledby so as not to confuse users while navigating a page.

#### Steps to produce the issue
- Open: https://carbon-design-system.github.io/carbon-charts/react/?path=/story/donut--donut
- Inspect a slice of the donut and search for the parent `g` html tag 

#### Current behavior
The `g` html tg does not provide any aria-label or aria-labelledby property.

#### Expected behavior
Elements having any WAI-ARIA roles must have a label specified with aria-label or aria-labelledby so as not to confuse users while navigating a page.

### Screenshot or recording
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/20518828/86908634-c3637700-c10e-11ea-9330-38296b513ed8.png">

**Comment by theiliad** [comment]
Closed by #707
