### ISSUE TITLE
Allow zone.js dependency as 0.10.x

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon-charts#696]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

Upgrading to Angular 9 also updates the `zone.js` module to `0.10.3` which ends up showing the following warning:
```
npm WARN @carbon/charts-angular@0.33.0 requires a peer of zone.js@^0.8.29 || ^0.9.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by stanislavgeorgiev** [comment]
Thanks for fixing this @theiliad. Is it included in a release already?

**Comment by theiliad** [comment]
> Thanks for fixing this @theiliad. Is it included in a release already?

yes, I'd just install the latest version

**Comment by stanislavgeorgiev** [comment]
thanks @theiliad, the warning is gone now :)
