### ISSUE TITLE
Design for simple zoom bar

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-charts#698]
This issue tracks the requirements and design specs for a simple version of the zoom bar.

The simple zoom allows the user to scope the start and endpoints of the chart from a larger range of data. This simple zoom bar is intended to be used for area, bubble charts, and an alternative to the zoom bar with thumbnail shown here https://github.com/carbon-design-system/carbon-charts/issues/380

## Final specs

![Simple_zoom_20200722](https://user-images.githubusercontent.com/19270502/88218816-36e4a880-cc26-11ea-9125-cdb65cb36be1.png)

**Comment by designertyler** [comment]
@jeanservaas 

Here are a few explorations for a simplified zoom control. 1 & 2 following closely to the original style of the specs found in https://github.com/carbon-design-system/carbon-charts/issues/380 and 3 & 4 follow closely to Carbon's slider component. I'm not sure either is a stand-out but would like your feedback on any new directions to pursue. I'll be looking at more data viz zoom control examples next and adding those explorations here


![(1) Zoom bar styles](https://user-images.githubusercontent.com/19270502/87351013-59880a80-c51e-11ea-8517-001cca7514cd.png)

**Comment by designertyler** [comment]
Proposed behavior and states


![(2) Zoom pan interactions](https://user-images.githubusercontent.com/19270502/87455527-36676480-c5cb-11ea-8693-933b03e8aff6.png)

**Comment by jeanservaas** [comment]
@designertyler 

I actually like sticking closer to Shixie's design... but just removing the second chart since it's causing rendering issues/implementation problems and is not functional for certain charts or for the y-axis. 

So I prefer these explorations below:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/43144260/87457344-d0c8a780-c5cd-11ea-93b1-c0fdbb99cf7d.png">

To me the default range view. in the option that looks like the Carbon slider is just not intuitive at all for a chart zoom and the balls feel a little clunky to me.

**Comment by theiliad** [comment]
> @designertyler
> 
> I actually like sticking closer to Shixie's design... but just removing the second chart since it's causing rendering issues/implementation problems and is not functional for certain charts or for the y-axis.
> 
> So I prefer these explorations below:
> 
> <img alt="image" width="836" src="https://user-images.githubusercontent.com/43144260/87457344-d0c8a780-c5cd-11ea-93b1-c0fdbb99cf7d.png">
> 
> To me the default range view. in the option that looks like the Carbon slider is just not intuitive at all for a chart zoom and the balls feel a little clunky to me.

the circular handles seem like a closer match to me to the Carbon slider
https://www.carbondesignsystem.com/components/slider/usage/
![image](https://user-images.githubusercontent.com/14989804/87458011-4d13b880-c5d7-11ea-90e1-02943d50ecea.png)

if we go with the rectangular handles, are we able to try having them not stick out of the zoombar rectangle?

**Comment by theiliad** [comment]
and @designertyler could you also highlight use cases where the zoombar would show up on the left axis? would like to see how we'll fit it in with the axis title and labels

**Comment by jeanservaas** [comment]
1. Are we ever going to be able to implement a version of the zoom that functions like this? For situations where is is appropiate? This is the one that @mjabbink prefers. 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/43144260/87461007-6155b680-c5d3-11ea-8989-16ae0fc9b104.png">

I notice Material has two Chart Range filters, a simple one and a more complex one. If we are, we'd definitely want the two to have the same rectangular geometry.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/43144260/87461251-c5787a80-c5d3-11ea-89e2-28e123c428e9.png">

<img width="899" alt="image" src="https://user-images.githubusercontent.com/43144260/87461197-aaa60600-c5d3-11ea-8eba-74083e71c207.png">

2. Most all sliders have those round handles... that doesn't mean it's a convention in charting for zoom and pan. To use Material as an example again... their slider looks like ours, but they do not use it for their Chart Range filter. I also don't think that a slight protrusion from the zoom bar will interfere with anything.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/43144260/87461489-286a1180-c5d4-11ea-9990-9bc091fd399e.png">

**Comment by designertyler** [comment]
Final specs have been added to this issue's original comment at the top

**Comment by theiliad** [comment]
Thanks Tyler, great work!

**Comment by mjabbink** [comment]
@designertyler That last sample your found is a nice one. How does a user get the magnafying icon to zoom?
