### ISSUE TITLE
Line chart: Custom domain doesn't use entire x-axis

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-charts#708]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

When using the custom domain option on line time-based graphs, the whole x-axis is not used. There's a small blank gap on both sides of the graph.

#### Steps to produce the issue

1. Go to https://carbon-design-system.github.io/carbon-charts/react/?path=/story/line--line-time-series-with-customized-domain
2. Change the domain to 
```
"domain": [
        "2019-01-05T06:00:00.000Z",
        "2019-01-14T06:00:00.000Z"
      ],
```
3. See the gap on both sides

#### Current behavior

Line graph has blank gap on both sides of the x-axis

#### Expected behavior

Line graph uses the entire x-axis

### Screenshot or recording

These screenshots are from the same chart with the same data

![Screen Shot 2020-07-16 at 9 04 15 AM](https://user-images.githubusercontent.com/25177649/87680689-59b51f80-c743-11ea-945a-7eafb9762f3f.png)

![Screen Shot 2020-07-16 at 9 04 08 AM](https://user-images.githubusercontent.com/25177649/87680692-5a4db600-c743-11ea-8b69-4d61731de2d1.png)

**Comment by theiliad** [comment]
`addSpaceOnEdges` just needs to be overlooked when custom domain is passed in
