### ISSUE TITLE
Line thresholds

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#72]
Currently we're working on region thresholds with background colors:
![image](https://user-images.githubusercontent.com/14989804/47441085-6dee0780-d77d-11e8-8ceb-6ba0424c10b8.png)

Are we looking to implement a lined version as well?

**Comment by theiliad** [comment]
@nicoleroppel @dianatran18 Is this still relevant?

**Comment by nmalyschkin** [comment]
Hi @theiliad 
Could you show me how you configured the above area thresholds?

**Comment by theiliad** [comment]
> Hi @theiliad
> Could you show me how you configured the above area thresholds?

Hi, this design was dropped in favor of some newer specs.

![image](https://user-images.githubusercontent.com/14989804/114731391-b7e15400-9d0f-11eb-92c4-dfc5aebca5ad.png)

You can find the demo here https://carbon-design-system.github.io/carbon-charts/?path=/story/utility-thresholds--thresholds-line
