### ISSUE TITLE
[Zoombar] single data point doesn't display

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-charts#740]
#### I am submitting a...

- [x] Source code defect

### Issue description

If there is only 1 data point with zoomBar enabled, it sometimes fails to render the point. The center threshold line is still there and you can hover over it to see the data, but the actual point is missing

#### Steps to produce the issue

1. Go to https://carbon-design-system.github.io/carbon-charts/?path=/story/zoom-bar-alpha--line-time-series-time-interval-15seconds-zoom-bar-enabled
2. Remove all data except for 1 data point
3. See that the point doesn't show

#### Current behavior

Single data point doesn't display

#### Expected behavior

Should show single data point

### Screenshot or recording

![Screen Shot 2020-08-06 at 1 12 21 PM](https://user-images.githubusercontent.com/25177649/89566926-7b577300-d7e6-11ea-9ebd-f20a1f5c6094.png)

**Comment by nstuyvesant** [comment]
@sstone2423 - is this still an issue with @carbon/charts@latest?

**Comment by theiliad** [comment]
I will close for now, pls let us know @sstone2423
