### ISSUE TITLE
AreaChart tooltips broken on Firefox when graph is translated

### ISSUE THREAD

**Issue by obambrough** [carbon-design-system/carbon-charts#743]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.34.9

### Issue description
Firefox doesn't display a tooltip when hovering over the body of an AreaChart (but the tooltip does display with Chrome and Safari.) 

#### Steps to produce the issue
The AreaChart must be within a div that has an x-axis translation applied. 

#### Current behavior
On both Chrome and Safari when I hover over the body underneath any point (not on a point) it will show a tooltip describing all points on that line (and draw a vertical line/ruler at the mouse position.) On Firefox it does not draw the tooltip nor vertical line/ruler at the mouse position (it will draw a tooltip when hovering over a point though.)

#### Expected behavior
Firefox should draw the tooltip when hovering over the body of the area graph just like Chrome and Safari do.

### Screenshot or recording
codesandbox demonstrating the issue: https://codesandbox.io/s/firefox-tooltip-broken-forked-xq1o9?file=/index.html

I'm not able to debug the codesandbox but in my application's dev environment I'm able to debug into Carbon Charts. The issue appears to be due to the showRuler function (of ruler.js) receiving an incorrect mouseCoordinate. 

NOTE: In my dev env the graph has over 100 elements so it goes through the deboubceWithD3MousePosition - the example sandbox has less than 100 elements and exhibits the same behaviour but may not have debounceWithD3MousePosition in the stack. I assume point.js is broken either way.

When I debug with Chrome the mouseCoordinate is correctly generated here:

@carbon/charts/tools.j-> debounceWithD3MousePosition, line 25
|
--->d3-selection/src/mouse.js, line 7
    |
    --->d3-selection/src/point.js, line 7

When I debug with Firefox and step into point.js it seems to step to line 7 then mysteriously jumps to line 12 when it should have stepped to line 8 and returned. This jump leads to the wrong coordinate being returned.

**Comment by obambrough** [comment]
I debugged the behaviour from the Carbon Charts storybook, Firefox diverges from Chrome while calling `getScreenCTM` (called by `d3-selection/src/point/js` during the ruler.ts' event handler.) Firefox returns a different value than Chrome.

![image](https://user-images.githubusercontent.com/1922249/98558568-987f6000-2273-11eb-8b8b-2e94e3edb326.png)

This seems to be a known and possibly intentional interpretation in Firefox as there have have been a few bug reports filed related to the issue. This one in particular is most relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=1610093. Functionality does appear to work properly in Chrome and Safari.

**Comment by theiliad** [comment]
> I debugged the behaviour from the Carbon Charts storybook, Firefox diverges from Chrome while calling `getScreenCTM` (called by `d3-selection/src/point/js` during the ruler.ts' event handler.) Firefox returns a different value than Chrome.
> 
> ![image](https://user-images.githubusercontent.com/1922249/98558568-987f6000-2273-11eb-8b8b-2e94e3edb326.png)
> 
> This seems to be a known and possibly intentional interpretation in Firefox as there have have been a few bug reports filed related to the issue. This one in particular is most relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=1610093. Functionality does appear to work properly in Chrome and Safari.

Hi, so is this a d3 issue? Or are we shipping out buggy code?

**Comment by obambrough** [comment]
I don't think its a Carbon Charts issue. I think its a Firefox issue (based on the bugzilla issue linked in the previous comment.)

**Comment by theiliad** [comment]
ok, I'll close for now then. Feel free to re-open if you the issue persists
