### ISSUE TITLE
Missing legend on SimpleBarChart, LineChart, StackedBarChart when loading option is set

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/carbon-charts#748]
#### I am submitting a...

- [ ] Feature request
- [X] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
"@carbon/charts": "0.35.0",
"@carbon/charts-react": "0.35.0",
"d3": "5.16.0"

### Issue description
When setting the option:
```
"data": {
    "loading": true
  },
```
as in https://carbon-design-system.github.io/carbon-charts/react/?path=/story/bar-vertical--stacked-bar-skeleton once the data get loaded the chart legend is missing

#### Steps to produce the issue
Add the option:
```
"data": {
    "loading": true
  },
```
to any of these chart objects [SimpleBarChart, LineChart, StackedBarChart.

#### Current behavior
Chart legend is not displayed

#### Expected behavior
Chart legend should be displayed

**Comment by kimbaz** [comment]
@sophiiae I tested it with
```
"@carbon/charts": "0.36.2",
"@carbon/charts-react": "0.36.2"
```
but I'm still able to reproduce it. Has the fix already been included in the latest release?
Thank you.

**Comment by sophiiae** [comment]
> @sophiiae I tested it with
> 
> ```
> "@carbon/charts": "0.36.2",
> "@carbon/charts-react": "0.36.2"
> ```
> 
> but I'm still able to reproduce it. Has the fix already been included in the latest release?
> Thank you.

The PR is not merged yet. Once it merges, this issue should be closed.

**Comment by kimbaz** [comment]
Looks good. Thank you

**Comment by WilliamHolmes** [comment]
I'm still seeing this issue.
**Component**: `SimpleBarChart`
**Package Versions**:
```
"@carbon/charts": "0.36.2",
"@carbon/charts-react": "0.36.2",
"d3": "6.1.1",
```
![image](https://user-images.githubusercontent.com/5538260/92919723-e705af00-f428-11ea-8030-05705bfd5361.png)

**Comment by sophiiae** [comment]
> I'm still seeing this issue.
> **Component**: `SimpleBarChart`
> **Package Versions**:
> 
> ```
> "@carbon/charts": "0.36.2",
> "@carbon/charts-react": "0.36.2",
> "d3": "6.1.1",
> ```
> 
> ### Loading = true
> ![image](https://user-images.githubusercontent.com/5538260/92919723-e705af00-f428-11ea-8030-05705bfd5361.png)
> 
> ### Loading = false
> ![image](https://user-images.githubusercontent.com/5538260/92919787-069cd780-f429-11ea-82b9-bdcfe0badb06.png)

Could you update the Charts to "0.36.4" and try it again. Thanks.

**Comment by WilliamHolmes** [comment]
testing with `0.36.4`

So the described issue is resolved, **HOWEVER** im seeing the same issue when .. `options.legend.enabled` is originally false.

**Comment by sophiiae** [comment]
> testing with `0.36.4`
> 
> So the described issue is resolved, **HOWEVER** im seeing the same issue when .. `options.legend.enabled` is originally false.

Yes, the default value for `options.legend.enabled` is `true`. If you set it to `false`, legend won't show no matter the data is loading or not.

**Comment by WilliamHolmes** [comment]
What i meant was we were toggling the `enabled` value. but it didn't make an difference.
Lets assuming loading is false in the use case...

If `enabled`is initially false, the legend will not show on mount.
if `enabled` is changed to true during a react render, the legend still will not show.

**Comment by sophiiae** [comment]
> What i meant was, we were toggling the `enabled` value. but it didn't make an difference.
> Let's assume `loading` is `false` in the use case...
> 
> If `enabled`is initially `false`, the legend will not show on mount.
> if `enabled` is changed to `true` during a react render, the legend still will not show.

Do you mind create an issue and provide a codesandbox that we can use to debug?
Thank you.

**Comment by WilliamHolmes** [comment]
Issue Created: https://github.com/carbon-design-system/carbon-charts/issues/802
