### ISSUE TITLE
Consuming in a browser environment (e.g. CDNs) - Not working

### ISSUE THREAD

**Issue by wilsonwong13** [carbon-design-system/carbon-charts#755]
Currently getting an error with the CDN example 
Link: https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--vanilla
Error: 
![Screen Shot 2020-08-20 at 12 46 00 PM](https://user-images.githubusercontent.com/23243527/90800773-1a01ca80-e2e3-11ea-9fa9-864ddd15b124.png)

**Comment by theiliad** [comment]
> Currently getting an error with the CDN example
> Link: https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--vanilla
> Error:
> ![Screen Shot 2020-08-20 at 12 46 00 PM](https://user-images.githubusercontent.com/23243527/90800773-1a01ca80-e2e3-11ea-9fa9-864ddd15b124.png)

Hi, please provide your full code sample, thanks

**Comment by wilsonwong13** [comment]
Using this code 
![Screen Shot 2020-08-24 at 10 11 18 AM](https://user-images.githubusercontent.com/23243527/91055067-27c09400-e5f2-11ea-9c83-2ca233cc0a34.png)

**Comment by theiliad** [comment]
> Using this code
> ![Screen Shot 2020-08-24 at 10 11 18 AM](https://user-images.githubusercontent.com/23243527/91055067-27c09400-e5f2-11ea-9c83-2ca233cc0a34.png)

@wilsonwong13 did you fill in `stackedBarData` & `stackedBarOptions` with your own data & options?
If not, then please use any of the `codesandbox` examples in our storybook https://carbon-design-system.github.io/carbon-charts/?path=/story/bar-vertical--simple-bar-discrete

**Comment by wilsonwong13** [comment]
Omg, yup your right. Will close the issue. Thanks
