### ISSUE TITLE
Tooltips missing for points on StackedAreaChart

### ISSUE THREAD

**Issue by obambrough** [carbon-design-system/carbon-charts#758]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
charts: 0.34.9

### Issue description
StackedAreaChart doesn't show tooltip for point on any dataset other than the first dataset (e.g. only the datapoint lowest on the y-axis has a tooltip shown when the mouse is hovering over the point.)

#### Steps to produce the issue
This is present on any StackedAreaChart

#### Current behavior
When you hover over a graph point it only shows the tooltip for the bottom most point on the y-axis.

#### Expected behavior
The individual tooltip should appear when hovering over any graph point.

### Screenshot or recording
The behaviour can be seen on the Carbon Charts storybook: https://carbon-design-system.github.io/carbon-charts/?path=/story/area--stacked-area-time-series

Short recording showing only the lowest datapoint shows a tooltip
[Missing tooltips.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/5110085/Missing.tooltips.mov.zip)

**Comment by hlyang397** [comment]
I think #764 may fix this problem.
