### ISSUE TITLE
[AVT1] <Notifications> Multiple elements with the WAI-ARIA role 'group' must not use the same label. 

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon-charts#762]
Charts version
"@carbon/charts": "^0.34.5",

Each element with "group" role must have a unique label that describes its purpose.
This issue happens when we have multiple Donut charts on the page. As we have multiple charts, the same aria-lable is repeated for all the donuts and hence the issue.

Soln could be, there should be a way to set the aria_label from the user.
![image](https://user-images.githubusercontent.com/44162180/91153619-1359c580-e6de-11ea-9e68-34d9bb221a7a.png)

![image](https://user-images.githubusercontent.com/44162180/91153653-1fde1e00-e6de-11ea-8fac-97c1ebe63716.png)

**Comment by pankaj-kumar34** [comment]
Chart type: StackedBarChart

![image](https://user-images.githubusercontent.com/18532515/94390482-7375d880-0170-11eb-871b-5586625215a0.png)

**Comment by theiliad** [comment]
> @theiliad Chart type: StackedBarChart
> 
> ![image](https://user-images.githubusercontent.com/18532515/94390482-7375d880-0170-11eb-871b-5586625215a0.png)

Hi, your original post only pointed out this issue for pie & donut. Please specify every chart type that you're running into this issue with and create a separate issue since this one is closed
