### ISSUE TITLE
[LineChart] addSpaceOnEdges: 0 breaks when zoomBar is enabled

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-charts#763]
#### I am submitting a...

- [x] Source code defect

### Issue description

If zoomBar is enabled and `addSpaceOnEdges: 0` is enabled, the left and right-most points are no longer displayed

#### Steps to produce the issue

1. Go to https://carbon-design-system.github.io/carbon-charts/react/?path=/story/zoom-bar-alpha--line-time-series-zoom-bar-enabled
2. Add `"timeScale": {"addSpaceOnEdges": 0}` to the options
3. See that the points are no longer displayed

#### Current behavior

First and last point are not displayed when zoomBar and addSpaceOnEdges: 0 is enabled

#### Expected behavior

Both points should be displayed as it normally acts

### Screenshot or recording

![Screen Shot 2020-08-25 at 2 44 30 PM](https://user-images.githubusercontent.com/25177649/91220250-81ec5280-e6e1-11ea-98d0-1e454bf535fe.png)

**Comment by Akshat55** [comment]
@sstone2423 The PR will allow you to see first and last scatter elements, but they will not be overlapping the axes (like when zoom is disabled). Enabling zooming adds a clipPath svg element to prevent the data (scatter points) from being drawn outside of the chart area.
