### ISSUE TITLE
area-* events not emitted for AreaChart or StackedAreaChart

### ISSUE THREAD

**Issue by obambrough** [carbon-design-system/carbon-charts#771]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.34.9

### Issue description
None of the [documented area events](https://carbon-design-system.github.io/carbon-charts/documentation/enums/_interfaces_events_.area.html) (area-click, area-mousemove, area-mouseover, area-mouseout) are being emitted for AreaChart or StackedAreaChart

#### Steps to produce the issue
Register event listeners for any area-* event on either an AreaChart or StackedAreaChart then move the mouse around the chart

#### Current behavior
No events are emitted when the mouse is moved around the charts or clicked

#### Expected behavior
Events should be emitted for the mouse moving and being clicked

### Screenshot or recording
Here's a sandbox demonstrating it for StackedAreaChart: https://codesandbox.io/s/still-river-x6zvh
Here's a sandbox demonstrating it for AreaChart: https://codesandbox.io/s/inspiring-https-tm18c

**Comment by theiliad** [comment]
@Akshat55 pls reference `bar-simple.ts`'s `addEventListeners()`

**Comment by Akshat55** [comment]
Area events documentation will be updated with PR #1066 - should be `scatter-*` instead of `area-*`.

For example:
```js
  componentDidMount() {
    this.state.chartRef.current.chart.services.events.addEventListener(
      "scatter-click",
      (e) => {
        console.log(`clicked on area: `, e.detail);
      }
    );
```
