### ISSUE TITLE
Issue with Charts v0.36 and D3 v6.0

### ISSUE THREAD

**Issue by nikhilkomakula** [carbon-design-system/carbon-charts#775]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Current D3 version i.e. 6.0 is not working with Charts 0.36

#### Steps to produce the issue
Install Charts using 'npm install -S @carbon/charts @carbon/charts-react d3' and it fails to compile with an error "Attempted import error: 'event' is not exported from 'd3-selection'."

#### Current behavior
The Charts code fails to compile

#### Expected behavior
The Charts code should compile without errors.

**Comment by LucasKeiti28** [comment]
same error, someone solved it?

**Comment by theiliad** [comment]
Hi 👋 
Our `peerDependecies` describes the recommended range of d3 versions to use.

https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json#L58

We'll need to time to explore compatibility with v6, however looking at the CHANGELOG in d3 I don't really see a benefit to adding that piece, but it would definitely be good for us to support d3 v6 as well.
