### ISSUE TITLE
[BarCharts] Need to add ChartClip to bar charts

### ISSUE THREAD

**Issue by manigurusankar10** [carbon-design-system/carbon-charts#783]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
When you add ```{
  timeScale: {
    addSpaceOnEdges: 0
  }
}``` to bar charts, the first bar appears on the y-axis.

I was told you need to `ChartClip` to the library.

#### Steps to produce the issue
https://codesandbox.io/s/jolly-diffie-n1obf?file=/src/index.js

**Comment by natashadecoste** [comment]
Looking into this again, it's a bit confusing and would be better if you provided the end result you are looking for. 
Currently (in most recent carbon-charts) with the configs `{ timeScale: { addSpaceOnEdges: 0 } }`, the domain doesn't have padding outside the datapoints' values, and so it makes sense that the middle of the bars in a bar chart would line up to x-axis values (and produce overhang on the axis and right axes). That being said, using  `{ timeScale: { addSpaceOnEdges: 1 } }` is for padding the domain and there would be no overhang - and all bars/data are visible. 

**add spaces on edges : 0**
🚫 bars overlap axes  
![image](https://user-images.githubusercontent.com/14351335/97903916-c31a6780-1d0d-11eb-8a49-1b1c6fd1073a.png)

**add spaces on edges : 1**
bars all visible within the chart axes
![image](https://user-images.githubusercontent.com/14351335/97903831-9cf4c780-1d0d-11eb-8f7f-b92bc8893efc.png)

Adding in a chartclip (without zoombar) would essentially just "clip" off the overhang - resulting in inconsistent bar sizes and not spec chart.

**add spaces on edges : 0 with ChartClip**
🚫 bars are not consistent widths
![image](https://user-images.githubusercontent.com/14351335/97904075-fbba4100-1d0d-11eb-8652-f058176f24ca.png)
