### ISSUE TITLE
[StackedBarChart] Setting width property does not do anything

### ISSUE THREAD

**Issue by manigurusankar10** [carbon-design-system/carbon-charts#784]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Setting `width` or `max-width` to stacked bar chart does not do anything

#### Steps to produce the issue
https://codesandbox.io/s/crazy-germain-zeme1?file=/src/index.js

#### Expected behavior
The width of the bar should be set when applied.

**Comment by theiliad** [comment]
This should be resolved now #825
