### ISSUE TITLE
[StackedAreaChart] No fill color below curves (normal AreaChart works fine)

### ISSUE THREAD

**Issue by BTOdell** [carbon-design-system/carbon-charts#786]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

0.36.0

### Issue description

I was using `AreaChart` to display a single group of data and the chart was properly filled below with color.

![AreaChart](https://i.gyazo.com/d09307f217def4cb21d246a0a61e3f5d.png)

But then I needed to display two groups of data in a stacked format, so I changed to `StackedAreaChart`.

![StackedAreaChart](https://i.gyazo.com/e481daedb875080edc8f65fd60b0f8e1.png)

But without changing the chart options, the fill color is suddenly not showing:
```js
const chartOptions = {
    "axes": {
        "left": {
            "stacked": true,
            "title": "Violations",
            "mapsTo": "value",
            "scaleType": "linear"
        },
        "bottom": {
            "title": "Frame",
            "mapsTo": "frame",
            "scaleType": "linear"
        }
    },
    "color": {
        "scale": {
            "Non-violations": "#007398",
            "Violations": "#87212e"
        }
    },
    "curve": "curveMonotoneX"
};
```

#### Steps to produce the issue

(See above)

#### Current behavior

Area under curve is not filled with color for `StackedAreaChart`.

#### Expected behavior

Area under curve should be filled with color just like it is done for normal `AreaChart`.

**Comment by theiliad** [comment]
Hi, we have multiple demo examples for the stacked area chart. Please look at this link https://carbon-design-system.github.io/carbon-charts/?path=/story/area--stacked-area-time-series

and clicking this button on each demo will give you an isolated project with all of the charting data & options used
![image](https://user-images.githubusercontent.com/14989804/93930656-b4db3380-fceb-11ea-82f4-65e0e28ef9e9.png)
