### ISSUE TITLE
requires a peer of d3@>=5.0.0 <=5.14.2 but none is installed

### ISSUE THREAD

**Issue by ankitbaid11326** [carbon-design-system/carbon-charts#792]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description: Getting warning in our production build for this chart version:

> npm WARN @carbon/charts@0.34.11 requires a peer of d3@>=5.0.0 <=5.14.2 but none is installed. You must install peer dependencies yourself.
> npm WARN @carbon/charts@0.34.11 requires a peer of d3@>=5.0.0 <=5.14.2 but none is installed. You must install peer dependencies yourself.

**Comment by theiliad** [comment]
Hi, this is acceptable behaviour. Carbon Charts is a data-visualization framework that uses d3. We've specified `d3` as a peerDependency and also in our getting started guides https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--vanilla
