### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon-charts#803]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

0.34.2

**Comment by theiliad** [comment]
@cal-smith do you know what's currently missing that stops us from supporting Angular 10 users?

**Comment by cal-smith** [comment]
Nothing specific that _stops_ us, we just need to do up a test environment and make sure that:

- `ng serve` works
- `ng build` works
- `ng build --prod` works
- `ngcc` and imports work as expected

**Comment by stanislavgeorgiev** [comment]
Thanks for the quick resolution Eliad!

Cheers,
Stan
