### ISSUE TITLE
[PieChart] tooltip functions not working properly

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-charts#808]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.38

### Issue description
The tooltip function `customHTML` will receive an undefined value as the first parameter and the `valueFormatter` is not called at all.

#### Steps to produce the issue

Define the valueFormatter and the customHTML functions and send them in as props under options.tooltip.

#### Expected behavior
1. The `valueFormatter` should be called and with the value
2. `customHTML` should be called with an array or object with the data as the first parameter like the docs describe

**Comment by theiliad** [comment]
Hi,
`customHTML` is returning content as expected for me (I'm using a sandbox I created through storybook, using v`0.38.2`)
https://codesandbox.io/s/optimistic-austin-hicju?file=/src/index.js

Regarding the issue with `valueFormatter`, yes that looks like a bug which I've fixed in #809.

**Comment by bjornalm** [comment]
> Hi,
> `customHTML` is returning content as expected for me (I'm using a sandbox I created through storybook, using v`0.38.2`)
> https://codesandbox.io/s/optimistic-austin-hicju?file=/src/index.js
> 
> Regarding the issue with `valueFormatter`, yes that looks like a bug which I've fixed in #809.

Thanks, I upgraded both @carbon/charts and @carbon/charts-react to version 0.38.2 now and I can't reproduce the problem with the customHtml anymore.
