### ISSUE TITLE
[Zoom] Emit event after zoom change on chart

### ISSUE THREAD

**Issue by nestarz** [carbon-design-system/carbon-charts#810]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.38.2

### Issue description
When using the Zoom feature on LineChart it would be awesome to have an event after any use so we can get the range the user selected. I don't really know in vanilla but in react it would be something like:

`<LineChart onZoomChange={([x1, x2]) => setRange([x1, x2])} {...props} />`

And thank you for your awesome work.

**Comment by theiliad** [comment]
Hi, these events are already available. You'd need to use react `refs` to get access to the charting object instance, then you can follow this doc to attach event listeners:
https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--event-listeners

Additionally, this is a list of all the events that we dispatch https://carbon-design-system.github.io/carbon-charts/documentation/modules/_interfaces_events_.html

**Comment by nestarz** [comment]
I have another question, I need to react to change but only on mouseup event, not always, but I can't have this event, there is some stopPropagation somewhere that prevent the bubbling... What should I do ?
Thanks

**Comment by theiliad** [comment]
@nestarz I'm unable to find an instance of `stopPropogation()` anywhere in the Carbon Charts codebase. On a separate note, we can certainly dispatch a `mouseUp` event through the library if you'd need to catch that on your end.

Would you be able to create a separate issue for this? thanks
