### ISSUE TITLE
[AVT], StackedBarChart/ DonutChart/ LineChart, Elements that use 'role' must reference a valid WAI-ARIA role

### ISSUE THREAD

**Issue by pankaj-kumar34** [carbon-design-system/carbon-charts#814]
We are using latest version of carbon/charts and still we are facing this issue
Previous issue: https://github.com/carbon-design-system/carbon-charts/issues/634
Charts version
"@carbon/charts": "^0.38.2",

Elements that use 'role' must reference a valid WAI-ARIA role violations are seen in the 3 charts we use StackedBarChart/ DonutChart/ LineChart
23 violations in DonutChart( both empty state and with data)
26 violations in StackedBarChart( both empty state and with data)
8 violations in LineChart( both empty state and with data)

![image](https://user-images.githubusercontent.com/18532515/93769702-d202fa00-fc38-11ea-9bea-936e3cf51c4f.png)
![image](https://user-images.githubusercontent.com/18532515/93769718-d7f8db00-fc38-11ea-815d-0be4adac93ee.png)
![image](https://user-images.githubusercontent.com/18532515/93769733-dc24f880-fc38-11ea-9f56-f803f2b600a4.png)

**Comment by theiliad** [comment]
Hi 👋 
As mentioned in the previous issue created, this is a DAP bug that we've reported to them and they've fixed.

https://github.com/carbon-design-system/carbon-charts/issues/634

For further assistance I would:
- update the DAP version you're using
- reach out to DAP

I am not able to help at this point as those are valid `WAI-ARIA` roles that we're using 🙂
