### ISSUE TITLE
[zoomBar]: need a callback to tell us the current domain

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#818]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version
0.36

### Issue description
We would like to change the behavior of our graph based on the desired zoom range that a user is trying to interact with.  For instance, if they drag the zoomBar all the way over to the left, we'd like to load additional data.

If they grow/shrink the zoomBar, we'd like to receive a callback that allows us to determine and decide on a x-axis formatting strategy (i.e. give me more details in the x-axis formatting points the closer they zoom in).

#### Expected behavior
Would like an additional feature so that we can change our graph behavior based on the current zoom range.

**Comment by theiliad** [comment]
Hey Scott, this should already be available through the `Events.ZoomDomain.CHANGE` event type.

https://carbon-design-system.github.io/carbon-charts/documentation/enums/_interfaces_events_.zoomdomain.html

https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--event-listeners
