### ISSUE TITLE
Design specs for Lollipop chart

### ISSUE THREAD

**Issue by DanaPaslaru** [carbon-design-system/carbon-charts#827]
I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x] Other

Issue description: 
Doing design specs explorations (dot, line treatment, color) for lollipop chart.

**Comment by DanaPaslaru** [comment]
@jeanservaas Hi, these are the initial explorations for Lollipop chart:
https://ibm.box.com/s/69sy9u3c1a81dvzxlut89flgq1h2uwq5

Thanks!

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad Hi, I refined v1 file and now we have v2, here it is: https://ibm.box.com/s/b5t5yv9gjsevvqk480ch08ld1f6qfb4b

It has a version for a stacked lollipop, also, please let me know what you think of it. Thanks!

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad Hi, I've refined the file after yesterday's data vis playback, and we have v3 here:
https://ibm.ent.box.com/folder/123652327316?s=69sy9u3c1a81dvzxlut89flgq1h2uwq5

It includes dot size variations (as Mike suggested) using increments of 2px and some useful documentation resource.

Thanks!

FYI @mjabbink

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad Hi, I've refined the file and, after talking with Jeannie also, we though to remove the 16px dot option and move forward with 8px dot for default size and, for presentation purposes, to have an option with 14px dot. Thanks!
box folder here, with latest file (v4): https://ibm.ent.box.com/folder/123652327316?s=69sy9u3c1a81dvzxlut89flgq1h2uwq5 

@mjabbink FYI

**Comment by mjabbink** [comment]
@DanaPaslaru Excellent work!

**Comment by mjabbink** [comment]
@DanaPaslaru Can you double check the Sketch file I think the box around the tooltip dropped off?

**Comment by DanaPaslaru** [comment]
> @DanaPaslaru Can you double check the Sketch file I think the box around the tooltip dropped off?

@mjabbink thanks for the heads up, I'll fix and upload again, got lost that box. Many thanks!:)

**Comment by mjabbink** [comment]
@DanaPaslaru Is the final uploaded in above link?

**Comment by mjabbink** [comment]
@theiliad I think this is ready for development.

**Comment by DanaPaslaru** [comment]
@mjabbink @theiliad Hi, the final one is uploaded in the above url, file "Carbon_DataViz_design explorations_Lollipop_dp_v4ok". Thanks!

**Comment by natashadecoste** [comment]
closing since #936 is merged
