### ISSUE TITLE
Add in confidence interval chart 

### ISSUE THREAD

**Issue by shaziajk** [carbon-design-system/carbon-charts#835]
### Issue description
Add in a confidence interval chart (screenshot below of an example confidence interval graph). When given the confidence interval range for a point be able to plot this onto a chart. This will look similar to what is already available for a line chart in terms of design but would have an included filled area around the line indicating the confidence interval 

The input data would match that of other charts but with the additional fields for the confidence interval e.g. [
  {
    "group": "Dataset 1",
    "date": "2019-01-01T00:00:00.000Z",
    "value": 10,
    "CI-Min": 5,
    "CI-Max": 10
  },.....

### Screenshot or recording
![image (5)](https://user-images.githubusercontent.com/44590418/95228680-8c792c00-07f7-11eb-8370-3d78d7dbd1d4.png)

![image](https://user-images.githubusercontent.com/44590418/95225501-c6e0ca00-07f3-11eb-999a-4cfa6ca1022b.png)

**Comment by ptlm500** [comment]
Regarding rendering confidence interval for discrete data with some form of interpolation function for "smoothing", as in:

![image](https://user-images.githubusercontent.com/16822085/95229044-027d9300-07f8-11eb-8515-f9078687bba2.png)

I would propose that the same interpolation function is applied to the upper and lower bounds of the confidence interval, so the filled background displaying the confidence interval is "smoothed" in the same way.
