### ISSUE TITLE
Looking for Grouped Stacked Bar Chart

### ISSUE THREAD

**Issue by nikhilkomakula** [carbon-design-system/carbon-charts#838]
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
Interested to know if Carbon Charts offer a Grouped Stacked Bar Chart?

**Comment by theiliad** [comment]
Hi, apologies as I seem to have missed responding to this 🙂 

Unfortunately we're not supporting that right now.
