### ISSUE TITLE
Network diagram - Explorations

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/carbon-charts#839]

**Comment by theiliad** [comment]
🎉

**Comment by cameroncalder** [comment]
Diagram audit: [Mural](https://app.mural.co/invitation/mural/carboncharts6255/1602613883345?sender=cecalder&key=30859176-13a1-477a-b7b9-a2c7c5386801)

**Comment by cameroncalder** [comment]
Box folder: https://ibm.box.com/s/p4oo2qxad1m8r0yilsc2wh416pi9v7kz

**Comment by cameroncalder** [comment]
Design WIP: https://ibm.box.com/s/samrrgyzhkazeq0r8uh5zgzjea2cnmkd

**Comment by cameroncalder** [comment]
Usage guidance WIP: https://ibm.box.com/s/tor7r4nxrims1lg329kagdyksr4rto5q

**Comment by cameroncalder** [comment]
Latest design files:
https://ibm.box.com/s/cd4zcinov6l8m2jkxd4q7fipu45scmju

https://ibm.box.com/s/owjz5sr4m8pcdnv4o5k0uvh88amoygjb

https://ibm.box.com/s/um2c18svdyut9mn9bf30w8bkldire26e
