### ISSUE TITLE
Design specs for Bullet graph

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/carbon-charts#841]
Design explorations for the bullet graph.

**Comment by DianaStanciulescu** [comment]
V1, discussed in the guild meeting on October 15. 

[Bullet graph_ds_ v1.zip](https://github.com/carbon-design-system/carbon-charts/files/5383026/Bullet.graph_ds_.v1.zip)

to consider:
- percentage based instead of value based
- vertically aligned goals
- explore behaviour for > 100% bars
- a single value axis instead of multiple
- adding value labels
- red / green for below target / above target.

**Comment by DianaStanciulescu** [comment]
@jeanservaas @theiliad  FYI

**Comment by DianaStanciulescu** [comment]
@jeanservaas @theiliad I made an invision file with the percentage-focused bullet graphs, I thought it might be easier to comment on specific stuff: https://ibm.invisionapp.com/share/JCO0LS74THS

I did not include the skinny bars anymore; for the performance colors, I think a range can be specified (eg: use from color 20 to 40). 

thanks!!

**Comment by DianaStanciulescu** [comment]
@jeanservaas  this is the latest sketch file:

[Bullet graph_ds_v3.zip](https://github.com/carbon-design-system/carbon-charts/files/5458807/Bullet.graph_ds_v3.zip)

still to decide:
Jeannie: 

"Does a single bullet have axes or not? (hmm)
Whether or not to turn off the background grid for bullets as a default? (yes)
Deciding how best to present the values (this one verges on a functionality vs. style question maybe)
Whether the circular legend swatch works to indicate that there’s no interaction on that category? (hmm)
Should the quartile markers extend 100 through the line or 50% though the line like a tick? (after what Michael said, I think the latter, and you can extend the white quartile mark 100% when it overlaps with a threshold)"

Others:
divider lines only vs full borders for the performance areas, colors for those areas, target line treatment for the misaligned targets (i had a few options here i did not get into); colors for bars (one color/ black/different colors based on relation to target)

**Comment by DianaStanciulescu** [comment]
@jeanservaas @theiliad 
I received feedback from KL, from a questionnaire filled by data scientists :
[bullet feedback.pdf](https://github.com/carbon-design-system/carbon-charts/files/5537030/bullet.feedback.pdf)

no definite conclusions but: 
- most people prefer the clarity of the lined up target lines
- few people use quartiles
- quite a few comments finding the performance areas confusing (though they are an integral part of what a bullet chart is supposed to be) some confusion comes from the use of outlines; 
- a few people had a hard time identifying the target line as target and wanted to see it in the legend

**Comment by DianaStanciulescu** [comment]
latest sketch file: 

missing piece: how to treat the non-interactive legend

[Bullet graph_ds_v6.zip](https://github.com/carbon-design-system/carbon-charts/files/5573337/Bullet.graph_ds_v6.zip)

**Comment by DianaStanciulescu** [comment]
hi, I attach the final (?) sketch file; @theiliad please tell me if there is anything I missed. thanks!

[Bullet graph_ds_v7.zip](https://github.com/carbon-design-system/carbon-charts/files/5702746/Bullet.graph_ds_v7.zip)

**Comment by natashadecoste** [comment]
closes #684

**Comment by theiliad** [comment]
Thank you @DianaStanciulescu. Sorry for missing your msg as I was on vacation.

**Comment by DianaStanciulescu** [comment]
@theiliad no problem! as I was saying, if you find any gaps please tell me!
