### ISSUE TITLE
Proposed Carbon map base enhancements

### ISSUE THREAD

**Issue by anne-stevens** [carbon-design-system/carbon-charts#842]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x] Other - proposed contribution to Carbon Charts

### Issue description
As previously discussed in the weekly Carbon Charts Guild call, I propose a number of enhancements to the original four carbon-themed base maps, in order to optimize them for data visualization and use in carbon-themed dashboards:

- (a) Revise water colour from cool grays to grays for colour consistency in Carbon themed dashboards (which do not otherwise use cool gray).
- (b) Adopt the zoom behaviour work previously invested in Cognos Analytics base maps.  This behaviour ensures that the appropriate detail and labelling surfaces at different zoom scales.  The settings have been battle tested in the CA product.  
- (c) Support inverse figure/ground relationships (eg. one theme with white ocean and grey land and one theme with grey ocean and white land) for both the light and dark theme-pairs.  This offers maximum mapping flexibility for use for either choropleth or bubble maps.  See more detail below.

#### Steps to produce the issue
1.  Create a Mapbox Studio account if you don't already have one.
2.  Manually load the IBM Plex fonts, if they aren't already loaded: IBM Plex Sans Regular, IBM Plex Sans Bold, IBM Plex Sans Italic, IBM Plex Sans Medium, IBM Plex Sans Condensed Regular, IBM Plex Sans Condensed Bold.  Note this step is a bit of a Mapbox idiosyncracy, but is necessary for maps to render and zoom properly.  If the fonts are missing, things won't work properly.
3.  Use these public mapbox style links to compare live current to proposed new.  (Note the names I'm using for the time being refer to the land colour.  They are not final).  If these links don't work, let me know and I will share json packages instead. 

**Light themes:**
mapbox://styles/annestevens/ckg0v9p852mhv18pg6d0guba0
mapbox://styles/annestevens/ckfmxkmk02mk019muetlsxyqa

**Dark themes:**
mapbox://styles/annestevens/ckfoa55fb1ht819p9iz46kccw
mapbox://styles/annestevens/ckfocmwme02b419mr5lp8whkk

#### Current behavior
![Screen Shot 2020-10-14 at 11 50 41 AM](https://user-images.githubusercontent.com/59665153/96147443-56156e00-0ed5-11eb-8354-0b0aa81777be.png)
^ Four current Carbon base maps

#### Proposed behavior
![Screen Shot 2020-10-15 at 12 28 06 PM](https://user-images.githubusercontent.com/59665153/96158834-eeb1eb00-0ee1-11eb-9597-2dd7eccc6985.png)
^ Top row: white ocean suits choropleth maps, especially when all regions have data mapped to them.  White lands is best suited for bubble charts where data is land-based. I.e the data is more accessible on white background, than grey.  
^ Bottom row: Similarly, bubbles are most accessible on dark land.  Chroropleth data pops off the dark ocean, especially when regions border on ocean.

Note, for choropleth maps, depending on the extent of data and the part of the world in question, white land might be better suited than white ocean.  Having both white land and grey land options means more flexibility.

____
EXAMPLES OF BASE MAPS AT DIFFERENT SCALES WITH NO DATA PROJECTED ON TOP
![Screen Shot 2020-10-15 at 1 24 16 PM](https://user-images.githubusercontent.com/59665153/96165024-1311c580-0eea-11eb-8a09-a0f6557849f3.png)

![Screen Shot 2020-10-15 at 1 24 32 PM](https://user-images.githubusercontent.com/59665153/96165045-186f1000-0eea-11eb-9aad-596924725075.png)

![Screen Shot 2020-10-15 at 1 24 59 PM](https://user-images.githubusercontent.com/59665153/96165068-1efd8780-0eea-11eb-9e98-7d6986029a40.png)

**Comment by anne-stevens** [comment]
@jeanservaas,  @peter-garvin, @theiliad, 

It is my intention to submit these bases to CD&AI's PAL group as a pattern.
Would appreciate your comments in the mean time.  You've all seen my previous presentations at the guild calls, but I'd be happy to discuss further or do a live demo.  LMK if you need the style json packages instead of the links.

**Comment by anne-stevens** [comment]
@theiliad since this is my first Carbon github item, I didn't know who to assign or what labels to add.  Please feel free to fill in the blanks as required. Thx

**Comment by jeanservaas** [comment]
I am fine with the changes that Anne Stevens proposed though we don't have resources on the Carbon team to do any work on this currently.

I'm also not quite sure what specs are need since Anne's directions seemed pretty straightforward above. Could we get some more clarity on what further design direction might be needed from the Carbon change to proceed with this enhancement?

If nothing else is needed other than to implement the changes, can a resource on the Cognos team help with this?

**Comment by fvanham** [comment]
I can help if needed. Changes needed would be:
- upload these basemaps to Carbon design systems mapbox account (better not immediately delete the old styles).
- update the documentation on https://www.carbondesignsystem.com/data-visualization/advanced-charts#mapbox or even better, break it out into a separate "Basemap" component so it's easier to locate.

**Comment by fvanham** [comment]
@theiliad Any chance we can get these enhanced basemaps uploaded to the carbon charts mapbox page and get the links on the main page updated? I'd be happy to help, but I'd need access..

**Comment by theiliad** [comment]
@fvanham it's been a while, but I believe we followed this up privately together. Pls lmk if there's anything else you'd like me to do 🙂
