### ISSUE TITLE
Colors are missing when importing charts/styles/styles.scss

### ISSUE THREAD

**Issue by kgibb** [carbon-design-system/carbon-charts#866]
- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

`0.40.11` Vanilla

### Issue description
Colors are missing when importing `charts/styles/styles.scss` SCSS file directly.

Using `node-sass@4.14.1`.

### Screenshot or recording

![image](https://user-images.githubusercontent.com/12196391/98389634-38f33b80-204c-11eb-8adf-cf98c2d2fa68.png)

https://github.com/carbon-design-system/carbon-charts/blob/27e1725e6989796a3066ba73321ff77755b5187e/packages/core/src/styles/colors.scss#L275-L280

The above block should use the `!global` flag to update the global scope `$color-map`.

https://github.com/carbon-design-system/carbon-charts/blob/27e1725e6989796a3066ba73321ff77755b5187e/packages/core/src/styles/colors.scss#L250

```
$color-map: map-merge(
    $color-map,
    (
        "#{$name}-#{$category}": $value
    )
) !global;
```

Example: https://codesandbox.io/s/carbon-chart-missing-colors-2jgh2

**Comment by sophiiae** [comment]
@kgibb can you provide more details about how to produce this issue? Thank you.

**Comment by kgibb** [comment]
I've just forked a codepen sample. Updated description with the link.

**Comment by sophiiae** [comment]
> I've just forked a codepen sample. Updated description with the link.
Here's the link for sass: JavaScript API:
https://sass-lang.com/documentation/js-api

Sass files cannot be imported directly in JS, you need a compiler like `node-sass` to compile it to `css`. 
or you can use: 
`import "@carbon/charts/styles.css";`  in your codepen. 

https://codesandbox.io/s/carbon-chart-missing-colors-forked-xoqd6?file=/src/index.js

**Comment by kgibb** [comment]
I am aware it's working when pulling in the built out CSS. I am using `node-sass` as the description notes. 

Fixing the `$color-map` [variable shadowing](https://sass-lang.com/documentation/variables#example-7-scss) will resolve the issue, see description.

**Comment by theiliad** [comment]
I've just downloaded the sandbox and got it working. Seems like your imports are the issue here

**Here's what worked for me:**
```scss
@import "~@carbon/themes/scss/themes";
$carbon--theme: $carbon--theme--g10;

@import "~@carbon/charts/styles/styles.scss";
```

1. You're using `@carbon/themes` off of the carbon charts vendor libraries, not recommended although it wouldn't break the code.
2. Without the `~` the compiler doesn't seem to be able to resolve the libraries (not sure why codesandbox doesn't report this but downloading the sandbox and running locally will).

Fixing those I get this:
![image](https://user-images.githubusercontent.com/14989804/98568756-74298080-227f-11eb-890a-8c0673ef74a2.png)

**Comment by kgibb** [comment]
The chart styles are resolved in the remote sandbox without the tilde, it's just the `"./colors.scss"` import is essentially empty due to the aforementioned scope issue.

![image](https://user-images.githubusercontent.com/12196391/98655703-adbdc280-2337-11eb-944d-7abe23def1de.png)

I've created a Storybook sample using `node-sass`: https://ibm.box.com/s/4sm5t0oiboktmr64u8ns4guq7vfn0wh8

**Comment by theiliad** [comment]
Storybook is a bit weird. When importing the colors module manually everything works... Eitherway, I've added the global flag
