### ISSUE TITLE
What is the new way of using getFillColor in Chart options

### ISSUE THREAD

**Issue by bertrandmartel** [carbon-design-system/carbon-charts#868]
- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

I'm using `@carbon/charts-react`. There is a breaking change between 0.40.2 and 0.40.3 about the behaviour of [`getFillColor`](https://carbon-design-system.github.io/carbon-charts/documentation/interfaces/_interfaces_charts_.basechartoptions.html#getfillcolor)

## v0.40.2 

In version 0.40.2 and below, the following code works to set the colors in a Donut Chart 

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { DonutChart } from "@carbon/charts-react";
import "@carbon/charts/styles.css";

const colors = {
  java: "#FF0000",
  javascript: "#00FF00",
  "c++": "#0000FF"
};

const chartData = [
  {
    group: "java",
    value: 300
  },
  {
    group: "javascript",
    value: 600
  },
  {
    group: "c++",
    value: 200
  }
];

const demoDonutOptions = {
  getFillColor: (field) => {
    return colors[field];
  },
  height: "300px"
};

function App() {
  return (
    <div className="App">
      <h3>React Donut chart with label</h3>
      <div>
        <DonutChart data={chartData} options={demoDonutOptions} />
      </div>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
See [this sandbox](https://codesandbox.io/s/carbon-react-donut-color-0402-0u03z?file=/src/index.js)

It renders the colors correctly (calling getFillColor) :

![chart-color](https://user-images.githubusercontent.com/5183022/98454578-4dc3f200-2166-11eb-8aae-be4db0132afc.png)

## v0.40.3 and above

It doesn't work anymore, see [this sandbox](https://codesandbox.io/s/carbon-react-donut-color-04013-1lq2v?file=/src/index.js) which uses the latest version at this time (0.40.13)

It doesn't set the color anymore, the `getFillColor` function is not called, the default colors are rendered :

![chart-color2](https://user-images.githubusercontent.com/5183022/98454613-cb87fd80-2166-11eb-8c82-cf8808a43944.png)

Maybe there are some option fields missing in order for it to work in 0.40.3 and above ? When I look at [the history](https://github.com/carbon-design-system/carbon-charts/commit/8e32712652a4726da5a978313e01c1139d8baf77) I've noticed some conditional change when `getFillColor` is called related to `color.scale` field. Maybe @sophiiae or @theiliad have more insights about the changes in 0.40.3

Thanks a lot for your help

**Comment by bertrandmartel** [comment]
Ok I've found out that I need to set `color.scale` with all the groups present in data :

```javascript
color: {
    scale: {
        "java": "#FF0000",
        "javascript": "#00FF00",
        "c++": "#0000FF"
    }
}
```
In my case I don't need `getFillColor` and the config above is sufficient but if someone wants to control the color using `getFillColor`, the `color.scale` is still necessary which I think is a bug.

[Here is the working sandbox v0.40.13](https://codesandbox.io/s/carbon-react-donut-color-04013-working-p30ol?file=/src/index.js)

It would be nice to include an example in the documentation about setting the color

**Comment by theiliad** [comment]
@sophiiae could you please take a look here

**Comment by sophiiae** [comment]
Sorry for the late reply. You can use the `getFillColor` in the same way as you posted after we merge the PR #896.
