### ISSUE TITLE
AVT1: 4.1.2 Name, Role,Value-The 'id' downshift-1-label specified for the WAI-ARIA property 'aria-labelledby' value is not valid

### ISSUE THREAD

**Issue by pankaj-kumar34** [carbon-design-system/carbon-charts#902]
=====ENVIRONMENT=====
Browser: Chrome
DAP: with "12 May 2020 deployment"and "IBM Accessibility & IBM Accessibility Experimental" supported rulesets.

=====DEFECT DESCRIPTION=====
![image](https://user-images.githubusercontent.com/18532515/100984179-5d213a00-3570-11eb-87b5-34d8d0179d68.png)
Check point: https://www.ibm.com/able/guidelines/ci162/name_role_value.html

**Comment by theiliad** [comment]
Hi, could you please point me to where the id `downshift-1-label` is being applied to that div?

I don't think that Carbon Charts is producing that div since I cannot find it in the demos or the codebase.

Feel free to re-open, but this looks like it's an issue from some other library or your application code

**Comment by pankaj-kumar34** [comment]
@theiliad, it's dropdown component.
![image](https://user-images.githubusercontent.com/18532515/103739991-75c3ba80-501c-11eb-895b-49a6911c4346.png)

**Comment by theiliad** [comment]
> @theiliad, it's dropdown component.
> ![image](https://user-images.githubusercontent.com/18532515/103739991-75c3ba80-501c-11eb-895b-49a6911c4346.png)

Yes, dropdown isn't part of Carbon Charts.

If you're using a library that renders a chart with the dropdown out of the box, then that library should be fixing this issue for you. If not, then you're probably just using `carbon-components`'s dropdown and need to correct your `aria-labelledby` attribute
