### ISSUE TITLE
Request: Standalone Legend component

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon-charts#903]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
There are times when we need to build visualizations that are unique to our offering and do not exist in the Carbon Charts ecosystem. For example, a global map visualizing network connections.

Even though the visualization might be custom for the application, it would be great to follow the conventions provided by these charting libraries. One of those conventions is the Legend and its interactions. 

#### Current behavior
As a producer of custom visualizations, I cannot leverage any of the underlying conventions offered by Carbon Charts without duplicating code that already exists in this project.

#### Expected behavior
As a producer of custom visualizations, I want a way to leverage the Legend as a standalone component to use in my visualization. Having access to this building block, I can ensure that the charts that I produce adhere to and follow the same UX principles as all other charts.

**Comment by theiliad** [comment]
> #### I am submitting a...
> * [x]  Feature request
> * [ ]  Design defect
> * [ ]  Source code defect
> * [ ]  Demo/documentation defect
> * [ ]  Other
> 
> ### Issue description
> There are times when we need to build visualizations that are unique to our offering and do not exist in the Carbon Charts ecosystem. For example, a global map visualizing network connections.
> 
> Even though the visualization might be custom for the application, it would be great to follow the conventions provided by these charting libraries. One of those conventions is the Legend and its interactions.
> 
> #### Current behavior
> As a producer of custom visualizations, I cannot leverage any of the underlying conventions offered by Carbon Charts without duplicating code that already exists in this project.
> 
> #### Expected behavior
> As a producer of custom visualizations, I want a way to leverage the Legend as a standalone component to use in my visualization. Having access to this building block, I can ensure that the charts that I produce adhere to and follow the same UX principles as all other charts.

Hi, I've thought of a quick workaround for now which may be able to address this situation. I'll test it a bit and see whether we can put this out soon, stay tuned

**Comment by theiliad** [comment]
Unfortunately not much demand around this feature, and for something like the legend component, you could probably use the carbon checkbox component https://carbondesignsystem.com/components/checkbox/usage/#live-demo
