### ISSUE TITLE
Request: Consumable color patterns

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon-charts#904]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
The Carbon Design System provides useful guidance on appropriate color palettes for data visualizations [here](https://www.carbondesignsystem.com/data-visualization/color-palettes). I would like to be able to programmatically access these palettes in my UI.

#### Current behavior
As a producer of custom visualizations, I cannot consume the color palette guidelines through code, which results in duplicating the color palette lists in my project.

#### Expected behavior
As a producer of custom visualizations, I want to consume the color palettes as a module so I can always stay up to date with the latest color palettes to stay consistent with Carbon Charts.

**Comment by theiliad** [comment]
Hi, color palettes should be accessible via this file https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/src/styles/color-palatte.scss

@sophiiae could you please help out here in terms of accessing these colors, thanks!

**Comment by diego-codes** [comment]
Is it accessible via JS as well?
