### ISSUE TITLE
Line chart with left axis scale type 'log' and bottom axis scale type 'time' fails to render

### ISSUE THREAD

**Issue by amilligan** [carbon-design-system/carbon-charts#905]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.12

### Issue description
We have rendered a line chart with dates on the bottom axis (`scaleType: time`), and calculated values on the left axis.  When we set the left axis scale type to `linear` this works as expected and looks fine.  However, we need a logarithmic scale on the vertical axis; when we change the left axis scale type to `log` the chart fails to render and we see the following errors in the browser console:
```
Error: <path attribute d: Expected number, "<gibberish>...".
Error: <circle> attribute cy: Expected length, "NaN".
```

Based on tracing through the browser console debugger, this appears to happen during the animation step.  Strangely, although I can't be certain, it appears to happen during the animation of the *bottom* axis.

#### Steps to produce the issue

Here are the options we're passing to the chart:
```js
{
  title: '...',
  axes: {
    bottom: {
      mapsTo: 'date',
      scaleType: 'time',
      title: 'Date',
    },
    left: {
      mapsTo: 'value',
      scaleType: 'linear',
      title: 'Values',
    },
  },
  timeScale: {
    addSpaceOnEdges: 0,
  },
});
```

These options work fine.  Changing the left axis `scaleType` from `linear` to `log` causes the error.

#### Current behavior
With the `log` scale option, the left axis renders with no value labels, and the data points render along the top edge of the chart (presumably where they start their animation, which is interrupted by the error).

#### Expected behavior
Value labels appear, and data points appear in the appropriate locations on the chart.

### Screenshot or recording
Linear:
![Screen Shot 2020-12-08 at 11 47 38 AM](https://user-images.githubusercontent.com/23890/101521271-39cd0500-394b-11eb-8904-ca4b6050cb19.png)
Log:
![Screen Shot 2020-12-08 at 11 47 16 AM](https://user-images.githubusercontent.com/23890/101521289-43566d00-394b-11eb-8f89-95ce9420df72.png)
Errors:
![Screen Shot 2020-12-08 at 11 49 39 AM](https://user-images.githubusercontent.com/23890/101521460-7f89cd80-394b-11eb-8f95-0ed399617db6.png)

**Comment by amilligan** [comment]
Should it matter, this behavior is the same with d3 versions 5.16.0 and 5.14.2.

**Comment by matias-quezada** [comment]
It also happens on a area chart, here is it:

https://codesandbox.io/s/friendly-chatterjee-u5rd3?file=/src/index.js

**Comment by Akshat55** [comment]
One thing to keep in mind is that setting scaleType to log requires the data values to be greater than 0, since it isn't possible to find the log of 0 or any negative numbers. PR #1065 will update the storybook to include a log scale example under axes.
