### ISSUE TITLE
X-axis labels for ~2-3 month time series are missing month name

### ISSUE THREAD

**Issue by nertzy** [carbon-design-system/carbon-charts#907]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
X-axis labels for ~2-3 month time series are missing month name as the month changes.

#### Steps to produce the issue
- Build a time series data set that covers about 2-3 months
- Render a LineGraph with default options

#### Current behavior
Labels are generated that look like this:
* __Jan 6__
* 13
* 20
* 27
* 3
* 10
* 17

#### Expected behavior
Labels should contain the month name (and be bold) as the month changes:
* __Jan 6__
* 13
* 20
* 27
* __Feb 3__
* 10
* 17

### Screenshot or recording
https://codesandbox.io/s/funny-leftpad-6lpeq?file=/src/index.js

![Screen Shot 2020-12-09 at 2 41 58 PM](https://user-images.githubusercontent.com/2488/101685057-ee8b2300-3a2c-11eb-99d6-9a57d2cd8b2c.png)

**Comment by theiliad** [comment]
This seems to be fixed now, feel free to re-open if issue still exists 🙂
