### ISSUE TITLE
Design specs for Circle Pack charts

### ISSUE THREAD

**Issue by DanaPaslaru** [carbon-design-system/carbon-charts#908]
design explorations around circlepack charts for Carbon.

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad Hi, here is the first round of design explorations for circlepack charts: 
https://ibm.ent.box.com/folder/127755502152

Thanks!
@mjabbink

**Comment by theiliad** [comment]
> @jeanservaas @theiliad Hi, here is the first round of design explorations for circlepack charts:
> https://ibm.ent.box.com/folder/127755502152
> 
> Thanks!
> @mjabbink

Hey... Thank you Dana 🎉

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad Hi, here is the v2update for circle pack design explorations: https://ibm.ent.box.com/folder/127755502152
 Thanks!

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad @natashadecoste Hi, v3 for circle pack, with explorations around contrast and accessibility, zoom in to reveal level three and options for all three levels visible from start. Thanks!

box url: https://ibm.ent.box.com/folder/127755502152

**Comment by DanaPaslaru** [comment]
@jeanservaas @theiliad @natashadecoste Hi, this is the v3update for circle pack, with options for contrast, accessibility and zoom in. 
box folder (file Carbon_DataViz_design explorations_circlepack_dp_v3update): https://ibm.ent.box.com/folder/127755502152
Thanks!

**Comment by theiliad** [comment]
Closed by #944
