### ISSUE TITLE
Donut chart tooltip does not appear/broken with d3 version 6

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/carbon-charts#912]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version: 
0.41.14

### Issue description
`d3 version 6` does not play nicely with `@carbon/charts-react`, specifically with Tooltips on Donut Charts (I imagine it is on other charts too, but this is where I specifically see the error). It appears as though d3 has changed the way in which they handle events.

Downgrading the `d3` version on an application to 5 helps, but if we're using other `d3` abilities that don't include carbon-charts, it breaks. 

Take for example, an app I'm working on -- one of the other engineers on the project decided to create some custom d3 charting using version 6. As soon as I try to implement `carbon-charts` using `d3` version 5, all of his logic breaks.

#### Steps to produce the issue
The easiest way to reproduce is to:

- Fork this codesandbox example: https://codesandbox.io/s/2z0ch
- Change the `d3` dependency to version 6
- Hover over a piece of the chart which should show a tooltip
- Check the console for errors

#### Current behavior
When you hover over a portion of a donut chart, you do not see a tooltip, and the animation is delayed. 

#### Expected behavior
A tooltip should appear with more information about the particular data you've hovered over.

### Screenshot or recording
<img width="389" alt="Screen Shot 2020-12-14 at 11 30 36 AM" src="https://user-images.githubusercontent.com/47571589/102237033-d0ed0c00-3eb9-11eb-96d8-2e32bcb0aeba.png">
<img width="356" alt="Screen Shot 2020-12-14 at 11 30 47 AM" src="https://user-images.githubusercontent.com/47571589/102237046-d4809300-3eb9-11eb-89cf-cf42c67981e1.png">

Hope this helps :D

**Comment by milahu** [comment]
d3@6 is not yet supported ..

https://github.com/carbon-design-system/carbon-charts/blob/3663b2aaa972e7df0707847d4ff24c0ff99f59db/packages/core/package.json#L57-L59

.. and will throw all kinds of errors, cos of API change

**Comment by theiliad** [comment]
Hi, yes as @milahu has mentioned, d3@6 introduces some really large breaking changes and isn't currently supported. We're taking a look at supporting v6 but unfortunately I don't have a timeline right now

**Comment by theiliad** [comment]
Closing, we now support d3 7.x
