### ISSUE TITLE
How to install @ibm/plex and use it in my project, Instead of referencing online fonts

### ISSUE THREAD

**Issue by liuxuanhe** [carbon-design-system/carbon-charts#914]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ 1 ] Other

#### charts version:
latest
### Issue description
How to install @ibm/plex and use it in my project, Instead of referencing online fonts.
So as to solve the problem of cross-domain access.
![image](https://user-images.githubusercontent.com/38306051/103404574-0dde2180-4b8f-11eb-81f7-e8484dcd272d.png)

**Comment by theiliad** [comment]
Hi, I'd suggest taking a look at the IBM Plex github repo as your question isn't directly relevant to Carbon Charts.

https://github.com/IBM/plex

You should be able to find instructions here, and ask questions/open issues
