### ISSUE TITLE
How to change area chart fill color

### ISSUE THREAD

**Issue by maxjowett** [carbon-design-system/carbon-charts#915]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

### Issue description

It is unclear how to change the fill color for area chart datasets.

https://codesandbox.io/s/mutable-resonance-d1cst

The following code seems to only change the color of the stroke/edge of the dataset.
```
color: { scale: { "Dataset 1": "orange" } }
```

I'm hitting a brick wall trying to navigate through the options/docs, but I suspect `getFillColor` is relevant. How do I use this function?

**Comment by sophiiae** [comment]
user can define the `getFillColor` function to change the way how charts get fill color based on dataset label or data. 
you can change area chart color by use `color: { scale: { "Dataset 1": "orange" } }`, but the stroke color of area chart is auto-generated based on its fill color. We don't have the option that can change the stroke color of area chart.
