### ISSUE TITLE
options.data.selectedGroups: Resetting via props in React isn't possible?

### ISSUE THREAD

**Issue by tony** [carbon-design-system/carbon-charts#916]
Hi there, thank you very much for this project! I love that it's TypeScript is and framework agnostic!

When using charts w/ React, I update via passing props:

```typescript
<DonutChart options={{data: { selectedGroups: [] }}) />

<DonutChart options={{data: { selectedGroups: stateOrReactiveVariableOfSomeSort }}) />
```

When I pass empty values: `[]`, `null`, `undefined` I would expect all items to be selected again

Minimal recreation: https://codesandbox.io/s/carbon-components-selectgroups-with-hooks-forked-2s6j2

`window` variables for access in console: `chart` instance of `DonutChart`, `setSelectedGroups`, `selectedGroups`

Aside: In [the sandbox](https://codesandbox.io/s/carbon-components-selectgroups-with-hooks-forked-f2hij) it takes two calls to `setSelectedGroup`'s for the chart to update, I'm not sure if this is a chart issue yet!

#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### Steps to produce the issue

https://codesandbox.io/s/carbon-components-selectgroups-with-hooks-forked-2s6j2

Note: You may have to run these twice in the console (May be an issue with how I wired it in?)

`window.setSelectedGroups(["Shine", "Lemon"])`
`window.setSelectedGroups(["Shine"])`
`window.setSelectedGroups(["Lemon"])`

Assuming 2 or more items are selected, passing less selected groups won't remove the unselected ones, it only seems to append / union them.

So if its `["Shine", "Lemon"]`

`window.setSelectedGroups(["Lemon"])`  won't change it to `["Lemon"]` (no matter how many times it passed in as a prop)

`window.setSelectedGroups([])` won't clear the list

For some reason `setSelectedGroups` needs to be invoked twice

For that matter, `setOptions` doesn't work:

`window.chart`
`window.chart.model.setOptions({data: {selectedGroups: ["Chart"]}})`

#### Current behavior

DonutChart's legend doesn't update when `[]` is passed

Same goes for `[]`, `null`, `undefined` I would expect all items to be selected again

#### Expected behavior

The selected legend items should all be selected

`window.setSelectedGroups([])` should behave the same as `<DonutChart options={{data: { selectedGroups: [] }}) />` would act on initial render (all groups selected)

### Screenshot or recording

From [Sandbox](https://codesandbox.io/s/carbon-components-selectgroups-with-hooks-forked-2s6j2):

https://user-images.githubusercontent.com/26336/103426724-17608d00-4b81-11eb-9636-0f3bd1fdc059.mp4

From a non-MVP project (too much going on to rule out it's not me)

https://user-images.githubusercontent.com/26336/103426539-da47cb00-4b7f-11eb-8551-58dcb02013b9.mp4

**Comment by sophiiae** [comment]
`selectGroups` can be reset via props, but you may need to wrap the chart. 
Normally, all props are default settings for the chart that won't be changed with user interaction. 
`selectedGroups` changes if user select or unselect a dataset so we need to save the changes in chart self-rerendering. 
It only backs to the default options (props) with chart resetting. 

@tony  can you try to put the chart in a wrapper and let me know if you still have the same issue. 
Thanks.

```
const Chart = ({ data, options }) => (
      <DonutChart data={data} options={options} />
    );
};
...
return <Chart data={state.data} options={state.options} />;

```
