### ISSUE TITLE
[typescript] MeterChartOptions missing peak, status types

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-charts#920]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description

The `MeterChartOptions` interface is missing types for `peak`, `status` values.

#### Steps to produce the issue

See the [demo meter chart options](https://github.com/carbon-design-system/carbon-charts/blob/070f9e38481362e1ad55f036915deb66d8a16648/packages/core/demo/data/meter.ts#L11).

See the [`MeterChartOptions` interface](https://github.com/carbon-design-system/carbon-charts/blob/aceafe264e387949470c7ebe042583dff0f819b7/packages/core/src/interfaces/charts.ts#L303).

#### Current behavior

TypeScript throws an error when attempting to define `peak`, `status` values.

#### Expected behavior

```diff
export interface MeterChartOptions extends BaseChartOptions {
    meter?: {
+       peak?: number;
+       status?: {
+           ranges: { range: [number, number], status: Statuses }[];
+       };
        height?: number;
        title?: {
            percentageIndicator?: {
                /**
                 * rendering of the percentage value relative to the dataset within title
                 */
                enabled?: boolean;
            };
        };
    };
}
```

**Comment by theiliad** [comment]
> #### I am submitting a...
> * [ ]  Feature request
> * [ ]  Design defect
> * [x]  Source code defect
> * [ ]  Demo/documentation defect
> * [ ]  Other
> 
> #### charts version: 0.41.14
> ### Issue description
> The `MeterChartOptions` interface is missing types for `peak`, `status` values.
> 
> #### Steps to produce the issue
> See the [demo meter chart options](https://github.com/carbon-design-system/carbon-charts/blob/070f9e38481362e1ad55f036915deb66d8a16648/packages/core/demo/data/meter.ts#L11).
> 
> See the [`MeterChartOptions` interface](https://github.com/carbon-design-system/carbon-charts/blob/aceafe264e387949470c7ebe042583dff0f819b7/packages/core/src/interfaces/charts.ts#L303).
> 
> #### Current behavior
> TypeScript throws an error when attempting to define `peak`, `status` values.
> 
> #### Expected behavior
> ```diff
> export interface MeterChartOptions extends BaseChartOptions {
>     meter?: {
> +       peak?: number;
> +       status?: {
> +           ranges: { range: [number, number], status: Statuses }[];
> +       };
>         height?: number;
>         title?: {
>             percentageIndicator?: {
>                 /**
>                  * rendering of the percentage value relative to the dataset within title
>                  */
>                 enabled?: boolean;
>             };
>         };
>     };
> }
> ```
> 
> ### Screenshot or recording

Hi @metonym, could you please make that a PR?
