### ISSUE TITLE
Gauge chart should have option to hide percent symbol

### ISSUE THREAD

**Issue by theoshu** [carbon-design-system/carbon-charts#941]
#### I am submitting a...

- [x ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
We are using the gauge semi chart to signify risk on a scale of 1-150. The gauge only seems to allow 1-100 and always displays the percent symbol. It is possible to override the scale via the numberFormatter option, but it is not possible to disable the symbol from displaying. Hiding the .gauge-value-symbol via CSS leaves the 10px shift for the value.

I am creating a PR to address this.

### Screenshot or recording
![image](https://user-images.githubusercontent.com/4643524/106195600-fbe3a480-6175-11eb-89ec-263583841388.png)

**Comment by natashadecoste** [comment]
after discussions with the dataviz guild, 
the configuration to enable/disable the percentage should also enable/disable the percentage icon on the delta that is supplied to the gauge component (if present)
