### ISSUE TITLE
Metadata Visualization Using Graphs 

### ISSUE THREAD

**Issue by rafaelamascaro-star** [carbon-design-system/carbon-charts#945]
### Summary

Metadata needs a graph called a tree view, and for that it needs a specific design that is adaptable to each new type of data included in the platform.

I'm creating some components and I would like to review and guidance from the data visualization team. 

### Justification

This request is related to the IBM Enterprise Reference Data Manager (ERDM) project.

What resources do you have to assist this effort?

I already have some components, I can make all of them and submit it for approval and guidance. :)

**Comment by theiliad** [comment]
Seems like there isn't a response for now from the author of the issue.

We have released some diagram components in react & angular, lmk if you have any additional comments

https://carbon-design-system.github.io/carbon-charts/react/?path=/story/diagrams--start-here
