### ISSUE TITLE
With more data groups, check boxes ticks are not appearing.

### ISSUE THREAD

**Issue by kavyanekkalapu** [carbon-design-system/carbon-charts#947]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

Latest

### Issue description

When selecting checkboxes for legends/data groups, check boxes ticks are not appearing .

#### Steps to produce the issue

- Open any chart with more data groups so that data groups will be in more than a line.
- Try to select checkboxes in second row.
- check box ticks are not appearing

Example: https://codesandbox.io/s/broken-bash-fyn6c?file=/src/index.js

#### Current behavior

<img width="1621" alt="Screen Shot 2021-01-28 at 9 15 05 AM" src="https://user-images.githubusercontent.com/37085529/106791127-8454c000-6622-11eb-9f36-14be5e52c621.png">

#### Expected behavior

Ticks need to appear on checkboxes.

**Comment by kavyanekkalapu** [comment]
This code is not getting added for second row data groups.

<img width="278" alt="Screen Shot 2021-01-28 at 9 19 42 AM" src="https://user-images.githubusercontent.com/37085529/106791326-c54cd480-6622-11eb-9cb6-da5b8ca90c93.png">

**Comment by theiliad** [comment]
Should be addressed in #1013
