### ISSUE TITLE
Feedback Form

### ISSUE THREAD

**Issue by rafaelamascaro-star** [carbon-design-system/carbon-charts#948]
### Issue description

Create a modal for feedbacks forms inside platforms. 

#### Current behavior

Right now we have this behavior, but we would like to make a more consistent and carbon-aligned flow. We currently have the design attached, and we would like your guidance to improve it.  

### Screenshot or recording

<img width="1675" alt="Screen_1" src="https://user-images.githubusercontent.com/64613838/106805819-ed99fa80-6645-11eb-891c-34ca1d5a2428.png"><img width="1679" alt="Screen_2" src="https://user-images.githubusercontent.com/64613838/106805830-f12d8180-6645-11eb-9ad7-48011d563729.png">a design
<img width="939" alt="Screen_3" src="https://user-images.githubusercontent.com/64613838/106805836-f25eae80-6645-11eb-958d-1189b9ad61a0.png">

**Comment by rafaelamascaro-star** [comment]
@ruchika-verma

**Comment by theiliad** [comment]
Hi, this might be related to carbon-components and not carbon-charts. Have you considered posting on https://github.com/carbon-design-system/carbon?

**Comment by rafaelamascaro-star** [comment]
Hello! Yes, I've changed to https://github.com/carbon-design-system/carbon

Sorry!
