### ISSUE TITLE
Avoid data sorting in Donut chart

### ISSUE THREAD

**Issue by matias-quezada** [carbon-design-system/carbon-charts#949]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

```json
    "@carbon/charts": "^0.41.30",
    "@carbon/charts-react": "^0.41.30",
    "carbon-components": "^10.22.0",
    "carbon-components-react": "^7.22.0",
```

### Issue description
Donut chart is sorting my data, I want to avoid that

#### Steps to produce the issue
Create a Donut chart where options have a specific order.
Click [here](https://codesandbox.io/s/wonderful-robinson-d3tx2?file=/src/index.js) to see an example.

#### Current behavior
It sorts the data by decreasing order.

#### Expected behavior
It should render the data in the order I give them to it. Or at least provide an option to behave like that.

### Screenshot or recording
![Screenshot 2021-02-04 at 12 48 22](https://user-images.githubusercontent.com/44360321/106889328-25f21500-66e8-11eb-9e9d-0e548f86a21f.png)

**Comment by matias-quezada** [comment]
Related but not duplicate of https://github.com/carbon-design-system/carbon-charts/issues/449

**Comment by theiliad** [comment]
I think that this was a design choice at the time of the donut implementation. @jeanservaas could you please chime in?

**Comment by vgb1993** [comment]
Hy, I have the same problem.

I'm showing multiple Donuts that have the same groups. It's very misleading to have the order altered.

I tried using:

```
"legend": {
 "order": ["JQAI 2M4L1", "YEL48 Q6XK YEL48"]
}
```

But it doesn't work.

Also having to specify the order of the items would make it harder to use in our use case. It would be nice to have a On/Off flag to disable sort.

**Comment by joan-pascual** [comment]
I think I'm facing the same issue. Starting from 12 o'clock the the size of the pieces should be specified, or at least implement a coherent default order, for exemple, descending in size, as i show in the picture
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11899282/111813916-1fa3ab00-88da-11eb-927a-3d2b06934c05.png)

**Comment by theiliad** [comment]
> I think I'm facing the same issue. Starting from 12 o'clock the the order of the pieces should be specifiable, or at least implement a coherent default order, for exemple, in the picture case I always want to see the same order in every Donut to keep it coherent

I'll make sure that design responds to this soon

**Comment by jeanservaas** [comment]
Like I said to @theiliad — there's no reason why design would block specifying the order of these categories.

As far as I can see, it doesn't affect the design of the chart in any way, just changes the sequencing of the categories and I'm fine with that.

**Comment by vgb1993** [comment]
Hy we still have the need to mantain the order of the categories. Now that we know design is not blocking this, could we implement it?

**Comment by ntsd** [comment]
I made a PR to add sortFunction option for the pie chart (also work on Donut chart)

this can fix this issue by replacing the sort function

https://github.com/carbon-design-system/carbon-charts/pull/1043

**Comment by theiliad** [comment]
PR #1043 addressed this issue
