### ISSUE TITLE
Heatmap specs

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#961]

**Comment by mjabbink** [comment]
https://deploy-preview-720--carbon-charts-core.netlify.app/?path=/story/heatmap--heatmap

**Comment by DianaStanciulescu** [comment]
@theiliad @jeanservaas 

hi, these are the current specs for the discrete heatmap. some small things are still in exploration: "empty" states for cells, the static legend, hover states. 

[Heatmap_discrete_ds_v8.zip](https://github.com/carbon-design-system/carbon-charts/files/7143587/Heatmap_discrete_ds_v8.zip)

**Comment by theiliad** [comment]
Great, thank you @DianaStanciulescu 🎉

**Comment by DianaStanciulescu** [comment]
also, akshat pointed out a few unsolved issues:

1. the legend  - which one should we choose ?
![image (6)](https://user-images.githubusercontent.com/51086727/138314538-6de74529-1ae8-4e9f-b00b-6f36b5527346.png)

2. legend width - I was thinking that it should be the same width as the chart, up to a certain max point after which one can decide if to cap it or keep it the same width. not sure what that max point should be - 25% on desktop? and always full on mobile? 

@jeanservaas @theiliad please let me know what you think

**Comment by DianaStanciulescu** [comment]
@jeanservaas @theiliad @Akshat55 I think I solved it, I attach the file. basically white only appears in the gradient legend and not in the stepped legend

<img width="1065" alt="Screenshot 2021-11-17 at 19 34 05" src="https://user-images.githubusercontent.com/51086727/142252303-423a4e5d-6bc4-4165-a258-aeb74d172bef.png">

And I also think we can have excentric diverging legends for non-symmetrical data sets, but zero=white no matter what.

<img width="586" alt="Screenshot 2021-11-17 at 19 35 48" src="https://user-images.githubusercontent.com/51086727/142252658-0dac5211-7dfb-42eb-b8fe-7feefdea94af.png">

The sketch file:
[Heatmap_legend_ds_v9.zip](https://github.com/carbon-design-system/carbon-charts/files/7556710/Heatmap_legend_ds_v9.zip)

**Comment by DianaStanciulescu** [comment]
still to be solved: how wide is the legend.

**Comment by DianaStanciulescu** [comment]
regarding keyboard navigation to show axes tooltips, m gower had a comment : 

"we’d need to add 2 more tab stops, one for each axis. Focus goes around the whole thing, then the user arrows between the labels to expose the value (equivalent to the hover)"

**Comment by Akshat55** [comment]
@DianaStanciulescu 

`Left` and `Right` arrow key for horizontal axes and `Up` and `Down` for vertical?

**Comment by DianaStanciulescu** [comment]
@Akshat55 makes sense!
