### ISSUE TITLE
[Question] Changing themes on the fly

### ISSUE THREAD

**Issue by cupcakearmy** [carbon-design-system/carbon-charts#966]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x] Other

#### charts version: 

@carbon/charts: ^0.41.40
@carbon/charts-svelte: ^0.41.40

### Issue description

How can I change styles dynamically without custom building the styles again? I'm aware of #892, however with carbon components there is a prebuilt css file that changes depending on `<html theme="g100">` which makes it really handy to switch on the fly. Any ideas/suggestion?

**Comment by theiliad** [comment]
> #### I am submitting a...
> * [ ]  Feature request
> * [ ]  Design defect
> * [ ]  Source code defect
> * [ ]  Demo/documentation defect
> * [x]  Other
> 
> #### charts version:
> @carbon/charts: ^0.41.40
> @carbon/charts-svelte: ^0.41.40
> 
> ### Issue description
> How can I change styles dynamically without custom building the styles again? I'm aware of #892, however with carbon components there is a prebuilt css file that changes depending on `<html theme="g100">` which makes it really handy to switch on the fly. Any ideas/suggestion?

Hi,
We have these css files available in the package which you can dynamically switch between:
- `@carbon/charts/styles.css`
- `@carbon/charts/styles-g10.css`
- `@carbon/charts/styles-g90.css`
- `@carbon/charts/styles-g100.css`

**Comment by cupcakearmy** [comment]
@theiliad  Thanks for the quick answer! Is there an example on how to do that?

**Comment by theiliad** [comment]
> @theiliad Thanks for the quick answer! Is there an example on how to do that?

Unfortunately not at this time. This isn't something that's specific to Carbon Charts, switching out css files dynamically through JS is something that is arbitrary and you should be able to find tons of examples online

**Comment by cupcakearmy** [comment]
I'll leave a working example here for anyone interested. Feel free to include it in the docs if you think it could be useful.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://unpkg.com/@carbon/charts@0.41.40/styles.min.css" id="chart-css" />
  </head>
</html>
```

```typescript
function setTheme(theme: 'white' | 'g10' | 'g90' | 'g100') {
  const chart = window.document.getElementById('chart-css') as HTMLLinkElement
  chart.href = `https://unpkg.com/@carbon/charts@0.41.40/styles${theme === 'white' ? '' : '-' + theme}.min.css`
}

setTheme('white')
```

It's not optimal as the version served by unpkg would need to be pinned manually to the same as in the actual package. But it could be easily modified to serve a local file and add a build step to copy the 4 css files to your assets folder.

**Comment by vgb1993** [comment]
this doesen't work for newer versions
https://unpkg.com/@carbon/charts@1.6.14/styles-g90.min.css

but does for old ones
https://unpkg.com/@carbon/charts@0.41.40/styles-g90.min.css

**Comment by theiliad** [comment]
Hi @vgb1993, yes this is done a lot more smoothly now.

Pls look at this line 302 here https://unpkg.com/browse/@carbon/charts@1.6.14/styles.css

All you need to do is set `theme` in your charting options to `g100 | g90 | g10 | white`
