### ISSUE TITLE
Update lodash version due to vulnerability with v4.17.15

### ISSUE THREAD

**Issue by tonydiaz** [carbon-design-system/carbon-charts#967]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x] Other

Vulnerability in the lodash package 4.17.15
https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json

#### charts version:
Latest version

### Issue description
During the vulnerability scan for Watson assistant, it was noticed that a version of lodash was being used with a vulnerability. Watson assistant has since updated the lodash version but it was noticed that Carbon charts uses this version also. 

#### Steps to produce the issue
Run a vulnerability scan on carbon-charts. Notice the vulnerability for lodash

#### Expected behavior
Should update lodash to version 4.17.21

**Comment by theiliad** [comment]
Recently updated some packages and dependabot seems to be happy
