### ISSUE TITLE
[Bug] [Angular] "Missing CSS styles for Carbon Charts.."-error after rerendering

### ISSUE THREAD

**Issue by code-asylum** [carbon-design-system/carbon-charts#968]
#### I am submitting a...
- [ ] Design defect
 or
- [ ] Source code defect
 not sure.

#### charts version:
**@carbon/charts:** 0.41.41
**@carbon/charts-angular:** 0.41.41

if relevant:
**Angular**: ^10.0.0
**carbon-components:** ^10.30.0
**carbon-components-angular**: ^4.41.0"

### Issue description
We use carbon charts for a statistic dashboard where we load the full dashboard information on startup as a JSON from our API and build the components based on that JSON (rows, cols, charts). _When the dashboard is initially loading, everything works fine._

But we have simple functionality to refresh the dashboard, where the hole dashboard is loaded again from our API and the dashboard property of our main component is then updated with the new value. In **Angular 8**, everything worked fine and everything got rerendered correctly, but since updating to **Angular 10** when the dashboard is rerendered due to the change of the main components property, the charts are broken and we get the **"Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide."**-error.

Did something change in the rerendering behavior of angular from 8 to 10 or carbon-charts after a property changes?

I tried a lot to fix this issue, even trying to add the checked CSS-properties to the `<g>`-Tag in the svg (I know i shouldn't) which produces the missing-styles-error. But I can't figure out where things go wrong.

Any idea or help would be much appreciated!

#### Steps to produce the issue
short version of the current code, don`t know what else I could share:

**(Main Component)**
**dashboard-shell.html**
```
<div ibmGrid>
  <app-block-row-view
	ibmRow
	*ngFor="let blockRow of dashboard.rows; index as currentBlockRowIdx"
	[blockRow]=blockRow
	[currentBlockRowIdx]=currentBlockRowIdx
	[parentDashboardComponent]=this>
  </app-block-row-view>
</div>
```

**dashboard-shell.ts**
```
export class DashboardShellComponent implements OnInit, AfterViewInit {
  @Input() dashboard: Dashboard;

  ...

  loadDashboard(): void {
    // http-request to our API to get JSON converted to Dashboard-Type
    this.dashboard = response.json;
  }
```

---

**app-block-row-view.html**
```
<app-block-view ibmCol [columnNumbers]="{'sm': block.smallGridColumns, 'md': block.mediumGridColumns, 'lg': block.largeGridColumns}"
	*ngFor="let block of blockRow.blocks; index as currentBlockIdx"
	[ngStyle]="{
		'padding-bottom': '16px',
		'padding-top': '16px'
	}"
	[block]=block
	[currentBlockIdx]=currentBlockIdx>
</app-block-view>
```
_(nothing interesting in .ts)_

---

**app-block-view.html**
```
<app-diagram-view
	*ngFor="let diagram of block.charts; index as currentDiagramIdx"
	[ngStyle]="{}"
	[diagram]=diagram
	[currentDiagramIdx]=currentDiagramIdx
	[parentBlock]=block>
</app-diagram-view>
```
_(nothing interesting in .ts)_

---

**app-diagram-view.html**
```
<ibm-tile>
  <div id="diagram-{{ this.diagram.$hash }}"></div>
</ibm-tile>
```

**app-diagram-view-ts**
```
export class DiagramViewComponent implements OnInit, AfterViewInit {
  @Input() diagram: Diagram;
  private chart: any;

  ...

  ngAfterViewInit() {
    ...
    const chartHolder = document.getElementById(
      `diagram-${this.diagram.$hash}`
    );

   // ommited the other charts
   switch (this.diagram.type) {
      case DiagramType.Line: // Custom Enum
        this.chart = new LineChart(chartHolder, {
          data: this.diagram.data,
          options: this.diagram.options,
        });
        
        break;
        ...
    }
```

#### Current behavior
On rerendering the charts, we get the "Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide." error.

#### Expected behavior
All charts should be rerendered without an error after the main property is changed

**Comment by theiliad** [comment]
Hi @code-asylum, as the getting started outlines, charting CSS styles need to be imported https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--angular

![image](https://user-images.githubusercontent.com/14989804/113891620-3760a780-9793-11eb-9519-89474e220966.png)

the error you have in there is from a validator we have in place that checks whether the styles are applied, and it also is telling you that the getting started guide would have the piece of code needed.

Please lmk if your issue is resolved

**Comment by code-asylum** [comment]
> Hi @code-asylum, as the getting started outlines, charting CSS styles need to be imported https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials-getting-started--angular
> 
> ![image](https://user-images.githubusercontent.com/14989804/113891620-3760a780-9793-11eb-9519-89474e220966.png)
> 
> the error you have in there is from a validator we have in place that checks whether the styles are applied, and it also is telling you that the getting started guide would have the piece of code needed.
> 
> Please lmk if your issue is resolved

This should not be the Problem, because the site renders an first, only on rerendering it is not and the styles are imported, I checked this multipletimes with multiple different versions how they are imported.

this is the main style.scss:
`
@import "@carbon/themes/scss/themes";
$carbon--theme: $carbon--theme--g100;
@include carbon--theme();

@import "~carbon-components/scss/globals/scss/styles";
@import "~@carbon/charts/styles/styles.scss";
@import "./assets/scss/carbon-override.scss";
`

**Comment by theiliad** [comment]
> @theiliad
> This should not be the Problem, because the site renders at first, only on rerendering it is not and the styles are imported, I checked this multipletimes with multiple different versions how they are imported.

Could you please post a screenshot of what your chart looks like? The library adds an element in the chart that then it checks to make sure has the correct styling applied.

I can only assume that however your styles are imported, they aren't being applied properly to the elements

**Comment by code-asylum** [comment]
How they look on first loading where everything works:
![image](https://user-images.githubusercontent.com/5221060/114180207-315bf980-9940-11eb-94ec-ddcfedbe0cfb.png)

How it looks after:
![image](https://user-images.githubusercontent.com/5221060/114180345-60726b00-9940-11eb-840b-7526fd4690bd.png)

**Comment by code-asylum** [comment]
@theiliad could we reopen this issue since it's not yet resolved or invalid?

**Comment by theiliad** [comment]
> @theiliad could we reopen this issue since it's not yet resolved or invalid?

Hi, could you please provide an online sandbox where I can verify the issue?

**Comment by number-00** [comment]
Hi, Is there any way to disable the validator? I am also facing same issue intermittently in react. I have also tried manually adding the min css file, but the error still comes and the complete page goes blank.

**Comment by theiliad** [comment]
> Hi, Is there any way to disable the validator? I am also facing same issue intermittently in react. I have also tried manually adding the min css file, but the error still comes and the complete page goes blank. 

Hi, I'm still having trouble understanding how to reproduce the issue. Could you pls provide a sandbox?

**Comment by number-00** [comment]
> > Hi, Is there any way to disable the validator? I am also facing same issue intermittently in react. I have also tried manually adding the min css file, but the error still comes and the complete page goes blank.
> 
> Hi, I'm still having trouble understanding how to reproduce the issue. Could you pls provide a sandbox?

I am unable to reproduce the issue on sandbox, strangely it happens only in production and not on localhost/codesandbox.
I was able to temporarily resolve this by manually adding the minified css file containing the required css.

**Comment by code-asylum** [comment]
I'm sorry that I wasn't responsive for so long.
With the latest carbon-charts(-angular) Version and litte changes to the refresh logic we managed to solve this bug and charts are getting refreshed/repainted properly.

Thanks very much!

**Comment by theiliad** [comment]
> I'm sorry that I wasn't responsive for so long.
> With the latest carbon-charts(-angular) Version and litte changes to the refresh logic we managed to solve this bug and charts are getting refreshed/repainted properly.
> 
> Thanks very much!

Hi, it'd be great if you could post your solution as a reference here. Thanks.

**Comment by dancras** [comment]
FWIW I have just reproduced something similar to this with React. In my case a route with the graph is accessed, but then a redirect happens immediately. The current timeout solution doesn't consider the situation where the component is unmounted immediately. It's quite an edge case.
