### ISSUE TITLE
Does vertical bar chart support scrolling when there's huge amount of data? If not, is it there in the roadmap?

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/carbon-charts#973]

**Comment by theiliad** [comment]
Hi, not sure exactly what you mean, please re-open with more details. Thank you

**Comment by lordsfantasy** [comment]
Hi, I am looking for scrollable chart feature like this one.
https://www.fusioncharts.com/dev/chart-guide/standard-charts/scroll-charts

**Comment by marghidanu** [comment]
Yep, that would be great
