### ISSUE TITLE
Wrong display of lower or upper bound in bounded area charts

### ISSUE THREAD

**Issue by FlorianBoe** [carbon-design-system/carbon-charts#978]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.41.44

### Issue description
When setting the min and max values, a typecheck does not seem to work, since 0 values are treated as null.

#### Steps to produce the issue
Set the min or max value in https://carbon-design-system.github.io/carbon-charts/?path=/story/area--bounded-area-time-series-natural-curve to zero.

#### Current behavior
The min and max line is drawn on the position of the value.

#### Expected behavior
The upper or lower bound should correctly be set to the value zero.

### Screenshot or recording
<img width="757" alt="bounded-area-chart" src="https://user-images.githubusercontent.com/663702/112477122-ef915780-8d72-11eb-9608-acca20b30d05.png">

**Comment by FlorianBoe** [comment]
Furthermore, null values are drawn for the bounds (min and max), while these are ignored for the value.
<img width="196" alt="bounded-area-chart-null" src="https://user-images.githubusercontent.com/663702/112499645-f70f2b80-8d87-11eb-8425-26a455d2a69b.png">

**Comment by theiliad** [comment]
> Furthermore, null values are drawn for the bounds (min and max), while these are ignored for the value.
> <img alt="bounded-area-chart-null" width="196" src="https://user-images.githubusercontent.com/663702/112499645-f70f2b80-8d87-11eb-8425-26a455d2a69b.png">

Please create a separate issue for this. I'll communicate to the person that contributed this

**Comment by FlorianBoe** [comment]
[With pleasure](https://github.com/carbon-design-system/carbon-charts/issues/980). Thanks for your quick reply!
