### ISSUE TITLE
Visualization elements awkwardly flash as visualizations on the Carbon Charts demo page render and re-render

### ISSUE THREAD

**Issue by brnnnfx** [carbon-design-system/carbon-charts#986]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [x] Demo/documentation defect
- [ ] Other

#### charts version:

Latest (on demo page https://carbon-design-system.github.io/carbon-charts/)

### Issue description

Visualization elements awkwardly flash as visualizations on the Carbon Charts demo page render and re-render

#### Steps to produce the issue

_browsing on Edge (Chromium) or Chrome_

1. Navigate to https://carbon-design-system.github.io/carbon-charts/
2. Expand the section for `Bubble`
3. Select `Bubble (linear)` to render the visualization, watching how it renders
4. Select `Bubble (time series)` to render the visualization, watching how it renders
5. Click back & forth between the two to really notice the issue

#### Current behavior

Visualization elements awkwardly flash as visualizations on the Carbon Charts demo page render and re-render

"Elements" appears to be the visualization's axis labels, and legend labels.

#### Expected behavior

Visualizations should smoothly and elegantly render / re-render

### Screenshot or recording

![strangeRedraw](https://user-images.githubusercontent.com/12024098/113032846-54c3bf00-915e-11eb-8fc4-5fcab9d38284.jpg)

https://user-images.githubusercontent.com/12024098/113032849-55f4ec00-915e-11eb-88c1-495fbdae6e9d.mov

**Comment by nstuyvesant** [comment]
This appears to be the same as https://github.com/carbon-design-system/carbon-charts/issues/1599.
@brnnnfx - if it looks the same, let's go ahead and close this issue since the other one is against a newer version than when you submitted this.
