### ISSUE TITLE
OnClick event for pie chart segments

### ISSUE THREAD

**Issue by pfaiola** [carbon-design-system/carbon-charts#99]
#### I am submitting an enhancement request for the Pie / Donut charts.

- [ ] onSegmentClick event for pie segments. 

#### charts version: 
Any

### Issue description
I have a chart that is populated with just the amount of inventory being used in a given segment.  I would like to be able to link the number to the associated orders that make up the number.  Right now, there is no onClick event for the pie chart for me to be able to raise the event.  I had implemented a work around in a previous release, but would like something provided with the module if possible.

#### Current behavior
There is no segment click event to do anything from the chart.

### Screenshot or recording, would like something like this to be made available
![image](https://user-images.githubusercontent.com/45182629/48734364-3c008180-ec13-11e8-898d-87f42bf4c9b8.png)

**Comment by theiliad** [comment]
Hi @pfaiola, this was done in October in #55.

**Refer to this line for sample code:**
https://github.com/carbon-design-system/carbon-charts/pull/55/files#diff-3882ec94f948948bfff156d33479f283R299
